import { CSSProperties, FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Modal } from 'react-bootstrap';
import { DndContext, DragEndEvent, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from '@dnd-kit/core';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import Inline from '../../../components/Shared/Inline';
import Stack from '../../../components/Shared/Stack';
import SelectControl from '../../../components/Shared/SelectControl';
import SearchInput from '../../../components/Shared/SearchInput';
import TablePagination from '../../../components/Shared/TablePagination';
import PrimaryButton from '../../../components/Shared/PrimaryButton';
import { Toast } from '../../../components/Toast';
import PbiCategoryField, { PbiCategory } from './PbiCategoryField';

type Status = 'por_hacer' | 'en_progreso' | 'en_revision' | 'completada';
type Area = { id: string; name: string; description?: string; color: string };
type Member = { uid: string; displayName?: string; email: string; smartPlannerRole?: string };
export type Pbi = { id: string; displayId?: string; title: string; description?: string; areaId: string; assignedTo: string; categoryId?: string; status: Status; priority: 'baja' | 'media' | 'alta'; startDate?: string; dueDate?: string; cost?: number; createdAt?: string; createdBy?: string };
type Draft = Omit<Pbi, 'id' | 'displayId' | 'createdAt' | 'createdBy'>;
const columns: Status[] = ['por_hacer', 'en_progreso', 'en_revision', 'completada'];
const statusLabels: Record<Status, string> = { por_hacer: 'Por hacer', en_progreso: 'En progreso', en_revision: 'En revisión', completada: 'Completada' };
const canonical = ['estrategia', 'comunicacion', 'avanzada y logistica', 'finanzas', 'juridico'];
const normalize = (name: string) => name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const sortAreas = (areas: Area[]) => [...areas].sort((left, right) => (canonical.indexOf(normalize(left.name)) < 0 ? 99 : canonical.indexOf(normalize(left.name))) - (canonical.indexOf(normalize(right.name)) < 0 ? 99 : canonical.indexOf(normalize(right.name))) || left.name.localeCompare(right.name));
const draft = (areaId = '', assignedTo = ''): Draft => ({ title: '', description: '', areaId, assignedTo, categoryId: '', status: 'por_hacer', priority: 'media', startDate: new Date().toISOString().slice(0, 10), dueDate: new Date().toISOString().slice(0, 10), cost: 0 });
const formatDate = (value?: string) => value ? new Date(value).toLocaleDateString('es-AR') : '—';

function KanbanCard({ pbi, onMove }: { pbi: Pbi; onMove: (pbi: Pbi, status: Status) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: pbi.id, data: { pbi } }); const style = transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : undefined;
  return <article ref={setNodeRef} style={style} className={`sp-task${isDragging ? ' is-dragging' : ''}`} data-kanban-task={pbi.id} {...attributes} {...listeners}><span className={`sp-task__priority ${pbi.priority}`} /><Link to={`/smartplanner/pbi/${pbi.id}`}><strong>{pbi.displayId ?? 'PBI'} · {pbi.title}</strong></Link><small>Vence {formatDate(pbi.dueDate)}</small><SelectControl ariaLabel={`Mover ${pbi.title}`} label="Mover" value={pbi.status} onChange={(status) => onMove(pbi, status as Status)} options={columns.map((status) => ({ value: status, label: statusLabels[status] }))} /></article>;
}
function KanbanColumn({ status, pbis, onMove }: { status: Status; pbis: Pbi[]; onMove: (pbi: Pbi, status: Status) => void }) {
  const { isOver, setNodeRef } = useDroppable({ id: `status:${status}` });
  return <section ref={setNodeRef} data-kanban-column={status} className={`sp-kanban__column${isOver ? ' is-drop-target' : ''}`}><header><span>{statusLabels[status]}</span><b>{pbis.length}</b></header><Stack gap="sm">{pbis.map((pbi) => <KanbanCard key={pbi.id} pbi={pbi} onMove={onMove} />)}{!pbis.length && <p className="sp-empty">Soltá un PBI acá.</p>}</Stack></section>;
}

export default function Backlog() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons, role } = useActiveCampaign(); const [params, setParams] = useSearchParams();
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
  const areasQ = useAuthenticatedQuery<Area[]>(user, base ? `${base}/areas` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const pbisQ = useAuthenticatedQuery<Pbi[]>(user, base ? `${base}/tasks` : null, [base]); const categoriesQ = useAuthenticatedQuery<PbiCategory[]>(user, base ? `${base}/categories` : null, [base]);
  const areas = sortAreas(areasQ.data ?? []); const members = membersQ.data ?? []; const categories = categoriesQ.data ?? []; const pbis = pbisQ.data ?? [];
  const [selectedAreaId, setSelectedAreaId] = useState(params.get('area') || ''); const [showCreate, setShowCreate] = useState(params.get('new') === '1'); const [form, setForm] = useState<Draft>(draft()); const [search, setSearch] = useState(''); const [areaFilter, setAreaFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null);
  const canManage = ['cliente', 'admin'].includes(role) || ['contador', 'pm'].includes(members.find((member) => member.uid === user?.uid)?.smartPlannerRole ?? '');
  useEffect(() => { if (!selectedAreaId && areas[0]) setSelectedAreaId(areas[0].id); }, [areas, selectedAreaId]);
  useEffect(() => { if (showCreate && !form.areaId && areas[0]) setForm((current) => ({ ...current, areaId: selectedAreaId || areas[0].id, assignedTo: current.assignedTo || user?.uid || '' })); }, [areas, form.areaId, selectedAreaId, showCreate, user?.uid]);
  const selectedArea = selectedAreaId || areas[0]?.id || ''; const filtered = useMemo(() => pbis.filter((pbi) => (!areaFilter || pbi.areaId === areaFilter) && (!categoryFilter || pbi.categoryId === categoryFilter) && (!statusFilter || pbi.status === statusFilter) && `${pbi.displayId ?? ''} ${pbi.title}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [areaFilter, categoryFilter, pbis, search, statusFilter]); const visible = filtered.slice(page * pageSize, (page + 1) * pageSize); const areaPbis = pbis.filter((pbi) => pbi.areaId === selectedArea);
  const memberName = (uid?: string) => members.find((member) => member.uid === uid)?.displayName || members.find((member) => member.uid === uid)?.email || 'Sin asignar'; const categoryName = (id?: string) => categories.find((category) => category.id === id);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));
  async function createCategory(name: string) { if (!user || !base) throw new Error('No se pudo crear la categoría.'); const category = await authenticatedFetch<PbiCategory>(user, `${base}/categories`, { method: 'POST', body: JSON.stringify({ name }) }); await categoriesQ.reload(); return category; }
  async function save(event: FormEvent) { event.preventDefault(); if (!user || !base || !form.title.trim()) return; try { await authenticatedFetch(user, `${base}/tasks`, { method: 'POST', body: JSON.stringify(form) }); await pbisQ.reload(); setShowCreate(false); setParams(selectedAreaId ? { area: selectedAreaId } : {}); setNotice({ message: 'PBI creado en el Backlog.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos crear el PBI.', variant: 'danger' }); } }
  async function move(pbi: Pbi, status: Status) { if (!user || !base || pbi.status === status) return; try { await authenticatedFetch(user, `${base}/tasks/${pbi.id}`, { method: 'PUT', body: JSON.stringify({ ...pbi, status }) }); await pbisQ.reload(); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos mover el PBI.', variant: 'danger' }); } }
  async function remove(pbi: Pbi) { if (!user || !base || !window.confirm(`¿Eliminar el PBI “${pbi.title}”?`)) return; await authenticatedFetch(user, `${base}/tasks/${pbi.id}`, { method: 'DELETE' }); await pbisQ.reload(); setNotice({ message: 'PBI eliminado.', variant: 'success' }); }
  function onDragEnd(event: DragEndEvent) { const pbi = event.active.data.current?.pbi as Pbi | undefined; const status = String(event.over?.id ?? '').replace('status:', '') as Status; if (pbi && columns.includes(status) && pbi.status !== status) void move(pbi, status); }
  if (!enabledAddons.smartPlanner) return <PageContainer><EmptyState icon="target" title="SmartPlanner no está habilitado" description="Pedile a un administrador que habilite el add-on." /></PageContainer>;
  return <PageContainer><Stack gap="lg"><HeroBanner icon="target" eyebrow="CUARTEL DE CAMPAÑA" title="Backlog de Campaña" subtitle="Priorizá, asigná y seguí cada PBI de la campaña." ctaLabel={canManage ? 'Nuevo PBI' : undefined} onCtaClick={() => { setForm(draft(selectedArea || areas[0]?.id || '', user?.uid || '')); setShowCreate(true); }} />
    <ContentPanel icon="bars" title="Kanban por área" subtitle="Arrastrá PBIs entre etapas o usá el selector accesible."><Stack gap="md"><Inline gap="sm" wrap className="sp-backlog__area-tabs">{areas.map((area) => <button key={area.id} type="button" className={`sp-tab${selectedArea === area.id ? ' is-active' : ''}`} onClick={() => { setSelectedAreaId(area.id); setParams({ area: area.id }); }}>{area.name}</button>)}</Inline><DndContext sensors={sensors} onDragEnd={onDragEnd}><div className="sp-kanban">{columns.map((status) => <KanbanColumn key={status} status={status} pbis={areaPbis.filter((pbi) => pbi.status === status)} onMove={move} />)}</div></DndContext></Stack></ContentPanel>
    <ContentPanel icon="list" title="Todos los PBIs" subtitle="Filtrá y administrá el Backlog completo."><Stack gap="md"><Inline gap="sm" wrap className="sp-backlog__filters"><SearchInput aria-label="Buscar PBI" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} placeholder="Buscar por ID o título" /><SelectControl ariaLabel="Filtrar PBIs por área" label="Todas las áreas" value={areaFilter} onChange={(value) => { setAreaFilter(value); setPage(0); }} options={[{ value: '', label: 'Todas las áreas' }, ...areas.map((area) => ({ value: area.id, label: area.name }))]} /><SelectControl ariaLabel="Filtrar PBIs por categoría" label="Todas las categorías" value={categoryFilter} onChange={(value) => { setCategoryFilter(value); setPage(0); }} options={[{ value: '', label: 'Todas las categorías' }, ...categories.map((category) => ({ value: category.id, label: category.name }))]} /><SelectControl ariaLabel="Filtrar PBIs por estado" label="Todos los estados" value={statusFilter} onChange={(value) => { setStatusFilter(value); setPage(0); }} options={[{ value: '', label: 'Todos los estados' }, ...columns.map((status) => ({ value: status, label: statusLabels[status] }))]} /></Inline>{visible.length ? <><div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>ID</th><th>TÍTULO</th><th>CREACIÓN</th><th>CATEGORÍA</th><th>CREADO POR</th><th>ACCIONES</th></tr></thead><tbody>{visible.map((pbi) => <tr key={pbi.id}><td><strong>{pbi.displayId ?? 'PBI pendiente'}</strong></td><td><Link to={`/smartplanner/pbi/${pbi.id}`}>{pbi.title}</Link></td><td>{formatDate(pbi.createdAt)}</td><td>{categoryName(pbi.categoryId) ? <span className="sp-pbi-category" style={{ '--pbi-category-color': categoryName(pbi.categoryId)?.color } as CSSProperties}>{categoryName(pbi.categoryId)?.name}</span> : '—'}</td><td>{memberName(pbi.createdBy)}</td><td><Inline gap="xs"><Link className="btn btn-sm btn-outline-primary" to={`/smartplanner/pbi/${pbi.id}`}>Editar</Link>{canManage && <button className="btn btn-sm btn-outline-danger" type="button" onClick={() => void remove(pbi)}>Eliminar</button>}</Inline></td></tr>)}</tbody></table></div><TablePagination total={filtered.length} visible={visible.length} label="PBIs" page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize} /></> : <EmptyState icon="list" title="No encontramos PBIs" description="Probá cambiar los filtros o creá el primero." ctaLabel={canManage ? 'Nuevo PBI' : undefined} onCtaClick={canManage ? () => setShowCreate(true) : undefined} />}</Stack></ContentPanel>
    <Modal show={showCreate} onHide={() => { setShowCreate(false); setParams(selectedAreaId ? { area: selectedAreaId } : {}); }}><form onSubmit={save}><Modal.Header closeButton><Modal.Title>Nuevo PBI</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Título del PBI" className="form-control" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Resultado a lograr" required /><textarea aria-label="Descripción del PBI" className="form-control" value={form.description ?? ''} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Contexto y criterio de éxito" /><SelectControl ariaLabel="Área del PBI" label="Área" value={form.areaId} onChange={(areaId) => setForm({ ...form, areaId })} options={areas.map((area) => ({ value: area.id, label: area.name }))} /><PbiCategoryField value={form.categoryId ?? ''} categories={categories} onChange={(categoryId) => setForm({ ...form, categoryId })} onCreate={createCategory} /><SelectControl ariaLabel="Responsable del PBI" label="Responsable" value={form.assignedTo} onChange={(assignedTo) => setForm({ ...form, assignedTo })} options={members.map((member) => ({ value: member.uid, label: memberName(member.uid) }))} /><Inline gap="md"><input aria-label="Inicio del PBI" type="date" className="form-control" value={form.startDate ?? ''} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /><input aria-label="Fecha límite del PBI" type="date" className="form-control" value={form.dueDate ?? ''} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></Inline><SelectControl ariaLabel="Prioridad del PBI" label="Prioridad media" value={form.priority} onChange={(priority) => setForm({ ...form, priority: priority as Draft['priority'] })} options={[{ value: 'baja', label: 'Baja' }, { value: 'media', label: 'Media' }, { value: 'alta', label: 'Alta' }]} /></Stack></Modal.Body><Modal.Footer><PrimaryButton icon="plus" type="submit">Crear PBI</PrimaryButton></Modal.Footer></form></Modal>{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </Stack></PageContainer>;
}
