import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import Modal from 'react-bootstrap/Modal';
import { useAuth } from '../../../context/AuthContext';
import { useCampaign } from '../Organization/useCampaign';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import { Icon } from '../../../components/Shared/Icons';

type Channel = { id: string; name: string; type: 'area' | 'custom' | 'direct'; areaId?: string; tags: string[]; memberIds: string[]; lastMessage?: Message | null };
type Message = { id: string; senderId: string; senderName: string; senderPhotoURL?: string; text: string; attachments?: Attachment[]; createdAt: string | null };
type Attachment = { type: 'image' | 'file'; url: string; name: string; size: number };
type Member = { uid: string; displayName?: string; firstName?: string; lastName?: string; email?: string; photoURL?: string };
const links = /(https?:\/\/[^\s]+)/g;
const readKey = (uid: string) => `cloudsuite.spChannelRead.${uid}`;
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();
const memberName = (member: Member) => member.displayName || [member.firstName, member.lastName].filter(Boolean).join(' ') || member.email || 'Miembro';
const handle = (member: Member) => memberName(member).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]/g, '');
const newer = (left?: string | null, right?: string | null) => new Date(left ?? 0).getTime() > new Date(right ?? 0).getTime();
const usablePhoto = (...candidates: Array<string | null | undefined>) => candidates.find((candidate) => typeof candidate === 'string' && /^https?:\/\//.test(candidate)) || undefined;
function renderedText(text: string) { return text.split(links).map((part, index) => /^https?:\/\//.test(part) ? <a key={`${part}-${index}`} href={part} target="_blank" rel="noopener noreferrer">{part}</a> : <span key={`${part}-${index}`}>{part}</span>); }
function readMap(uid: string) { try { return JSON.parse(localStorage.getItem(readKey(uid)) ?? '{}') as Record<string, string>; } catch { return {}; } }
function markRead(uid: string, channelId: string) { localStorage.setItem(readKey(uid), JSON.stringify({ ...readMap(uid), [channelId]: new Date().toISOString() })); }
function title(channel: Channel, members: Member[], userId?: string) { if (channel.type !== 'direct') return channel.name; const peer = members.find((member) => channel.memberIds.includes(member.uid) && member.uid !== userId); return peer ? `Direct · ${memberName(peer)}` : 'Direct'; }
function Avatar({ name, photoURL }: { name: string; photoURL?: string | null }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [photoURL]); const source = usablePhoto(photoURL); return <span className="sp-comms__avatar">{source && !failed ? <img src={source} alt={`Foto de ${name}`} onError={() => setFailed(true)} /> : initials(name)}</span>; }

function Composer({ user, base, channelId, members, onSent, onChannelChanged, compact = false }: { user: any; base: string; channelId: string; members: Member[]; onSent: () => Promise<void>; onChannelChanged?: (id: string) => void | Promise<void>; compact?: boolean }) {
  const [text, setText] = useState(''); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const [mentions, setMentions] = useState<string[]>([]); const [direct, setDirect] = useState<Member | null>(null);
  const token = text.match(/(?:^|\s)([@#])([^\s@#]*)$/); const trigger = token?.[1]; const query = token?.[2].toLocaleLowerCase('es-AR') ?? '';
  const suggestions = trigger ? members.filter((member) => member.uid !== user?.uid && `${memberName(member)} ${handle(member)} ${member.email ?? ''}`.toLocaleLowerCase('es-AR').includes(query)).slice(0, 5) : [];
  const select = (member: Member) => { const value = `@${handle(member)}`; if (trigger === '@') { setText((current) => current.replace(/(?:^|\s)([@#])([^\s@#]*)$/, (matched) => matched.startsWith(' ') ? ` ${value} ` : `${value} `)); setMentions((current) => current.includes(member.uid) ? current : [...current, member.uid]); } else { setText((current) => current.replace(/(?:^|\s)([@#])([^\s@#]*)$/, (matched) => matched.startsWith(' ') ? ' ' : '')); setDirect(member); } };
  async function send(event: FormEvent) { event.preventDefault(); if (!text.trim() && !file) return; setSending(true); setError(''); try { let destination = channelId; if (direct) { const channel = await authenticatedFetch<Channel>(user, `${base}/channels/direct`, { method: 'POST', body: JSON.stringify({ recipientId: direct.uid }) }); destination = channel.id; await onChannelChanged?.(channel.id); } const form = new FormData(); form.set('text', text); if (file) form.set('attachment', file); if (mentions.length) form.set('mentionedIds', JSON.stringify(mentions)); await authenticatedFetch(user, `${base}/channels/${destination}/messages`, { method: 'POST', body: form }); setText(''); setFile(null); setMentions([]); setDirect(null); await onSent(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No pudimos enviar el mensaje.'); } finally { setSending(false); } }
  return <form className={`sp-comms__composer ${compact ? 'is-compact' : ''}`} onSubmit={send}><Stack gap="xs">{error && <div className="alert alert-danger mb-0" role="alert">{error}</div>}{direct && <Inline gap="xs" className="sp-comms__recipient-chip"><span>Directo a {memberName(direct)}</span><button type="button" aria-label="Quitar destinatario directo" onClick={() => setDirect(null)}>×</button></Inline>}{file && <Inline gap="xs" className="sp-comms__attachment-chip"><Icon name="doc" size={14} /><span>{file.name}</span><button type="button" aria-label="Quitar adjunto" onClick={() => setFile(null)}>×</button></Inline>}<div className="sp-comms__composer-row"><label className="sp-comms__attach" aria-label="Adjuntar archivo o imagen"><Icon name="plus" size={18} /><input type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} /></label><div className="sp-comms__composer-input"><input aria-label="Mensaje del canal" className="form-control" value={text} onChange={(event) => setText(event.target.value)} placeholder={direct ? `Mensaje directo para ${memberName(direct)}…` : 'Escribí un mensaje… (@ menciona, # envía directo)'} />{trigger && <div className="sp-comms__mention-menu" role="listbox" aria-label={trigger === '@' ? 'Sugerencias para mencionar' : 'Sugerencias para mensaje directo'}>{suggestions.length ? suggestions.map((member) => <button key={member.uid} type="button" role="option" onMouseDown={(event) => event.preventDefault()} onClick={() => select(member)}><span className="sp-comms__avatar">{initials(memberName(member))}</span><Stack gap="xs"><strong>{memberName(member)}</strong><small>{trigger === '@' ? `Mencionar @${handle(member)}` : `Enviar directo #${handle(member)}`}</small></Stack></button>) : <small>No encontramos integrantes.</small>}</div>}</div><button className="sp-comms__send" disabled={sending} aria-label="Enviar mensaje"><Icon name="chevron-right" size={18} color="#fff" /></button></div></Stack></form>;
}

function ChannelMessages({ user, base, channel, members, compact = false, onSent, onChannelChanged, focusMessageId }: { user: any; base: string; channel: Channel; members: Member[]; compact?: boolean; onSent?: () => Promise<void>; onChannelChanged?: (id: string) => void | Promise<void>; focusMessageId?: string | null }) {
  const query = useAuthenticatedQuery<Message[]>(user, `${base}/channels/${channel.id}/messages`, [base, channel.id]);
  useEffect(() => { if (query.data && user) markRead(user.uid, channel.id); }, [channel.id, query.data, user]);
  useEffect(() => { if (focusMessageId) document.getElementById(`sp-message-${focusMessageId}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }, [focusMessageId, query.data]);
  const refresh = async () => { await query.reload(); await onSent?.(); };
  return <Stack gap="sm" className={compact ? 'sp-comms__compact-thread' : 'sp-comms__thread'}>{query.loading ? <small className="text-muted">Cargando conversación…</small> : query.data?.length ? query.data.map((message) => { const member = members.find((item) => item.uid === message.senderId); const photoURL = usablePhoto(message.senderPhotoURL, member?.photoURL, message.senderId === user?.uid ? user.photoURL : undefined); return <article id={`sp-message-${message.id}`} key={message.id} className={`sp-comms__message ${message.senderId === user?.uid ? 'is-mine' : ''} ${focusMessageId === message.id ? 'is-highlighted' : ''}`}><Inline gap="sm" className="sp-comms__message-head"><Avatar name={message.senderName || 'Miembro'} photoURL={photoURL} /><Stack gap="xs"><Inline gap="xs" className="sp-comms__message-meta"><strong>{message.senderName}</strong><time>{message.createdAt ? new Date(message.createdAt).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' }) : 'ahora'}</time></Inline>{message.text && <p>{renderedText(message.text)}</p>}{message.attachments?.map((attachment) => attachment.type === 'image' ? <a key={attachment.url} href={attachment.url} target="_blank" rel="noopener noreferrer"><img className="sp-comms__image" src={attachment.url} alt={attachment.name} /></a> : <a className="sp-comms__file" key={attachment.url} href={attachment.url} target="_blank" rel="noopener noreferrer"><Icon name="doc" size={18} />{attachment.name}</a>)}</Stack></Inline></article>; }) : <small className="text-muted">Todavía no hay mensajes en este canal.</small>}<Composer user={user} base={base} channelId={channel.id} members={members} compact={compact} onSent={refresh} onChannelChanged={onChannelChanged} /></Stack>;
}

function CreateChannelModal({ show, onHide, user, base, members, done }: { show: boolean; onHide: () => void; user: any; base: string; members: Member[]; done: () => Promise<void> }) {
  const [name, setName] = useState(''); const [tag, setTag] = useState(''); const [tags, setTags] = useState<string[]>([]); const [memberIds, setMemberIds] = useState<string[]>([]); const [error, setError] = useState(''); const addTag = () => { const value = tag.trim(); if (value && !tags.includes(value)) setTags((current) => [...current, value]); setTag(''); };
  async function create(event: FormEvent) { event.preventDefault(); try { await authenticatedFetch(user, `${base}/channels`, { method: 'POST', body: JSON.stringify({ name, tags, memberIds }) }); await done(); onHide(); setName(''); setTags([]); setMemberIds([]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No pudimos crear el canal.'); } }
  return <Modal show={show} onHide={onHide} centered><form onSubmit={create}><Modal.Header closeButton><Modal.Title>Crear canal</Modal.Title></Modal.Header><Modal.Body><Stack gap="md">{error && <div role="alert" className="alert alert-danger mb-0">{error}</div>}<label className="form-label mb-0">Nombre<input aria-label="Nombre del canal" required className="form-control mt-1" value={name} onChange={(event) => setName(event.target.value)} /></label><Stack gap="xs"><label className="form-label mb-0">Etiquetas</label><Inline gap="sm"><input aria-label="Nueva etiqueta" className="form-control" value={tag} onChange={(event) => setTag(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addTag(); } }} /><button type="button" className="btn btn-outline-primary" onClick={addTag}>Agregar</button></Inline><Inline gap="xs" wrap>{tags.map((item) => <button type="button" className="sp-comms__tag" key={item} onClick={() => setTags((current) => current.filter((currentTag) => currentTag !== item))}>{item} ×</button>)}</Inline></Stack><Stack gap="xs"><label className="form-label mb-0">Miembros</label>{members.map((member) => <label className="sp-comms__member-option" key={member.uid}><input type="checkbox" checked={memberIds.includes(member.uid)} onChange={() => setMemberIds((current) => current.includes(member.uid) ? current.filter((id) => id !== member.uid) : [...current, member.uid])} />{memberName(member)}</label>)}</Stack></Stack></Modal.Body><Modal.Footer><button type="button" className="btn btn-outline-secondary" onClick={onHide}>Cancelar</button><button className="btn btn-primary">Crear canal</button></Modal.Footer></form></Modal>;
}

export default function Communications() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const location = useLocation(); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null; const channelsQ = useAuthenticatedQuery<Channel[]>(user, base ? `${base}/channels` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const [activeId, setActiveId] = useState(''); const [activeTag, setActiveTag] = useState(''); const [createOpen, setCreateOpen] = useState(false); const requested = new URLSearchParams(location.search).get('channel'); const messageId = new URLSearchParams(location.search).get('message');
  useEffect(() => { const all = channelsQ.data ?? []; if (requested && all.some((channel) => channel.id === requested)) setActiveId(requested); else if (!activeId && all[0]) setActiveId(all[0].id); }, [activeId, channelsQ.data, requested]);
  const tags = useMemo(() => Array.from(new Set((channelsQ.data ?? []).flatMap((channel) => channel.tags ?? []))), [channelsQ.data]); const shown = (channelsQ.data ?? []).filter((channel) => !activeTag || channel.tags?.includes(activeTag)); const active = (channelsQ.data ?? []).find((channel) => channel.id === activeId) ?? shown[0]; const members = membersQ.data ?? [];
  const focusChannel = async (channelId: string) => { await channelsQ.reload(); setActiveId(channelId); };
  if (!campaign || !base) return <PageContainer><small className="text-muted">Elegí una campaña para abrir Comunicaciones.</small></PageContainer>;
  return <PageContainer className="sp-comms-page"><Stack gap="lg"><HeroBanner icon="pulse" eyebrow="COORDINACIÓN INTERNA" title="Centro de Comunicaciones" subtitle="Canales y mensajes directos para mantener a todo el equipo alineado." ctaLabel="Crear canal" onCtaClick={() => setCreateOpen(true)} /><ContentPanel icon="pulse" title="Direct y canales" subtitle="Conversaciones claras, privadas y conectadas con tu campaña."><div className="sp-comms"><aside className="sp-comms__sidebar"><Stack gap="md"><Inline gap="xs" wrap className="sp-comms__filters"><button type="button" className={!activeTag ? 'is-active' : ''} onClick={() => setActiveTag('')}>Todos</button>{tags.map((tag) => <button key={tag} type="button" className={activeTag === tag ? 'is-active' : ''} onClick={() => setActiveTag(tag)}>{tag}</button>)}</Inline><Stack gap="xs" className="sp-comms__channels">{shown.map((channel) => <button key={channel.id} type="button" aria-label={`Abrir canal ${title(channel, members, user?.uid)}`} className={channel.id === active?.id ? 'is-active' : ''} onClick={() => setActiveId(channel.id)}><Inline gap="sm"><span className="sp-comms__avatar">{initials(title(channel, members, user?.uid).replace('Direct · ', ''))}</span><Stack gap="xs"><Inline gap="xs" className="sp-comms__channel-name"><strong>{title(channel, members, user?.uid)}</strong>{channel.type === 'direct' && <span>Direct</span>}</Inline><small>{channel.lastMessage?.text || 'Sin mensajes todavía'}</small></Stack></Inline></button>)}</Stack></Stack></aside><section className="sp-comms__conversation">{active ? <Stack gap="md"><Inline gap="sm" className="sp-comms__conversation-title"><span className="sp-comms__avatar">{initials(title(active, members, user?.uid).replace('Direct · ', ''))}</span><Stack gap="xs"><h2>{title(active, members, user?.uid)}</h2><small>{active.type === 'direct' ? 'Mensaje directo privado' : active.type === 'area' ? 'Canal de área' : 'Canal personalizado'}</small></Stack></Inline><ChannelMessages user={user} base={base} channel={active} members={members} onSent={channelsQ.reload} onChannelChanged={focusChannel} focusMessageId={messageId} /></Stack> : <small className="text-muted">No hay canales con esta etiqueta.</small>}</section></div></ContentPanel></Stack><CreateChannelModal show={createOpen} onHide={() => setCreateOpen(false)} user={user} base={base} members={members} done={channelsQ.reload} /></PageContainer>;
}

export function CommunicationsWidget() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons } = useActiveCampaign(); const location = useLocation(); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null; const channelsQ = useAuthenticatedQuery<Channel[]>(user, enabledAddons.smartPlanner && base ? `${base}/channels` : null, [base, enabledAddons.smartPlanner]); const membersQ = useAuthenticatedQuery<Member[]>(user, enabledAddons.smartPlanner && base ? `${base}/members` : null, [base, enabledAddons.smartPlanner]); const [open, setOpen] = useState(false); const [activeId, setActiveId] = useState(''); const known = useRef<Record<string, string>>({}); const directs = (channelsQ.data ?? []).filter((channel) => channel.type === 'direct'); const active = directs.find((channel) => channel.id === activeId) ?? directs.sort((left, right) => newer(left.lastMessage?.createdAt, right.lastMessage?.createdAt) ? -1 : 1)[0];
  const unread = useMemo(() => !user ? 0 : directs.filter((channel) => channel.lastMessage && channel.lastMessage.senderId !== user.uid && (!readMap(user.uid)[channel.id] || newer(channel.lastMessage.createdAt, readMap(user.uid)[channel.id]))).length, [directs, user]);
  useEffect(() => { if (!base || !enabledAddons.smartPlanner) return; const timer = window.setInterval(() => { void channelsQ.reload(); }, 8000); return () => window.clearInterval(timer); }, [base, channelsQ.reload, enabledAddons.smartPlanner]);
  useEffect(() => { if (!channelsQ.data || location.pathname.startsWith('/smartplanner/comunicaciones')) return; const incoming = directs.find((channel) => channel.lastMessage && channel.lastMessage.senderId !== user?.uid && newer(channel.lastMessage.createdAt, known.current[channel.id])); directs.forEach((channel) => { if (channel.lastMessage?.createdAt) known.current[channel.id] = channel.lastMessage.createdAt; }); if (incoming) { setActiveId(incoming.id); setOpen(true); } }, [channelsQ.data, directs, location.pathname, user?.uid]);
  if (!enabledAddons.smartPlanner || !base || location.pathname.startsWith('/smartplanner/comunicaciones')) return null;
  return <div className={`sp-comms-widget ${open ? 'is-open' : ''}`} data-communications-widget><button type="button" className="sp-comms-widget__trigger" aria-label="Abrir comunicaciones directas" onClick={() => setOpen((current) => !current)}><Icon name="pulse" size={22} color="#fff" />{unread > 0 && <span>{unread}</span>}</button>{open && <section className="sp-comms-widget__panel"><Stack gap="sm"><Inline gap="sm" className="sp-comms-widget__heading"><span className="sp-comms__avatar">D</span><Stack gap="xs"><strong>Direct</strong><small>Mensajes privados</small></Stack></Inline>{active ? <ChannelMessages user={user} base={base} channel={active} members={membersQ.data ?? []} compact onSent={channelsQ.reload} onChannelChanged={setActiveId} /> : <small className="text-muted">Todavía no tenés mensajes directos.</small>}<Link className="btn btn-primary btn-sm w-100" to={active ? `/smartplanner/comunicaciones?channel=${encodeURIComponent(active.id)}` : '/smartplanner/comunicaciones'}>Ir al Centro de Comunicaciones</Link></Stack></section>}</div>;
}
