import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import Modal from 'react-bootstrap/Modal';
import { useAuth } from '../../../context/AuthContext';
import { useCampaign } from '../Organization/useCampaign';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import { Icon } from '../../../components/Shared/Icons';

type Channel = { id: string; name: string; type: 'area' | 'custom'; areaId?: string; tags: string[]; memberIds: string[]; lastMessage?: Message | null };
type Message = { id: string; senderId: string; senderName: string; text: string; attachments?: Attachment[]; createdAt: string | null };
type Attachment = { type: 'image' | 'file'; url: string; name: string; size: number };
type Member = { uid: string; displayName?: string; email?: string };
const links = /(https?:\/\/[^\s]+)/g;
const readKey = (uid: string) => `cloudsuite.spChannelRead.${uid}`;
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();
function renderedText(text: string) { return text.split(links).map((part, index) => /^https?:\/\//.test(part) ? <a key={`${part}-${index}`} href={part} target="_blank" rel="noopener noreferrer">{part}</a> : <span key={`${part}-${index}`}>{part}</span>); }
function readMap(uid: string) { try { return JSON.parse(localStorage.getItem(readKey(uid)) ?? '{}') as Record<string, string>; } catch { return {}; } }
function markRead(uid: string, channelId: string) { localStorage.setItem(readKey(uid), JSON.stringify({ ...readMap(uid), [channelId]: new Date().toISOString() })); }

function Composer({ userId, base, channelId, onSent }: { userId: any; base: string; channelId: string; onSent: () => Promise<void> }) {
  const [text, setText] = useState(''); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [sending, setSending] = useState(false);
  async function send(event: FormEvent) { event.preventDefault(); if (!text.trim() && !file) return; setSending(true); setError(''); try { const form = new FormData(); form.set('text', text); if (file) form.set('attachment', file); await authenticatedFetch(userId, `${base}/channels/${channelId}/messages`, { method: 'POST', body: form }); setText(''); setFile(null); await onSent(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No pudimos enviar el mensaje.'); } finally { setSending(false); } }
  return <form className="sp-comms__composer" onSubmit={send}><Stack gap="xs">{error && <div className="alert alert-danger mb-0" role="alert">{error}</div>}{file && <Inline gap="xs" className="sp-comms__attachment-chip"><Icon name="doc" size={14} /><span>{file.name}</span><button type="button" aria-label="Quitar adjunto" onClick={() => setFile(null)}>×</button></Inline>}<Inline gap="sm"><label className="sp-comms__attach" aria-label="Adjuntar archivo o imagen"><Icon name="plus" size={18} /><input type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} /></label><input aria-label="Mensaje del canal" className="form-control" value={text} onChange={(event) => setText(event.target.value)} placeholder="Escribí un mensaje…" /><button className="btn btn-primary" disabled={sending} aria-label="Enviar mensaje"><Icon name="chevron-right" size={18} color="#fff" /></button></Inline></Stack></form>;
}
function ChannelMessages({ user, base, channel, compact = false, onSent }: { user: any; base: string; channel: Channel; compact?: boolean; onSent?: () => Promise<void> }) {
  const messagesQ = useAuthenticatedQuery<Message[]>(user, `${base}/channels/${channel.id}/messages`, [base, channel.id]);
  useEffect(() => { if (messagesQ.data && user) markRead(user.uid, channel.id); }, [channel.id, messagesQ.data, user]);
  const refresh = async () => { await messagesQ.reload(); await onSent?.(); };
  return <Stack gap="sm" className={compact ? 'sp-comms__compact-thread' : 'sp-comms__thread'}>{messagesQ.loading ? <small className="text-muted">Cargando conversación…</small> : messagesQ.data?.length ? messagesQ.data.map((message) => <article key={message.id} className={`sp-comms__message ${message.senderId === user?.uid ? 'is-mine' : ''}`}><Inline gap="sm" className="sp-comms__message-head"><span className="sp-comms__avatar">{initials(message.senderName || 'M')}</span><Stack gap="xs"><Inline gap="xs" className="sp-comms__message-meta"><strong>{message.senderName}</strong><time>{message.createdAt ? new Date(message.createdAt).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' }) : 'ahora'}</time></Inline>{message.text && <p>{renderedText(message.text)}</p>}{message.attachments?.map((attachment) => attachment.type === 'image' ? <a key={attachment.url} href={attachment.url} target="_blank" rel="noopener noreferrer"><img className="sp-comms__image" src={attachment.url} alt={attachment.name} /></a> : <a className="sp-comms__file" key={attachment.url} href={attachment.url} target="_blank" rel="noopener noreferrer"><Icon name="doc" size={18} />{attachment.name}</a>)}</Stack></Inline></article>) : <small className="text-muted">Todavía no hay mensajes en este canal.</small>}{!compact && <Composer userId={user} base={base} channelId={channel.id} onSent={refresh} />}</Stack>;
}
function CreateChannelModal({ show, onHide, user, base, members, done }: { show: boolean; onHide: () => void; user: any; base: string; members: Member[]; done: () => Promise<void> }) {
  const [name, setName] = useState(''); const [tag, setTag] = useState(''); const [tags, setTags] = useState<string[]>([]); const [memberIds, setMemberIds] = useState<string[]>([]); const [error, setError] = useState('');
  const addTag = () => { const value = tag.trim(); if (value && !tags.includes(value)) setTags((current) => [...current, value]); setTag(''); };
  async function create(event: FormEvent) { event.preventDefault(); try { await authenticatedFetch(user, `${base}/channels`, { method: 'POST', body: JSON.stringify({ name, tags, memberIds }) }); await done(); onHide(); setName(''); setTags([]); setMemberIds([]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No pudimos crear el canal.'); } }
  return <Modal show={show} onHide={onHide} centered><form onSubmit={create}><Modal.Header closeButton><Modal.Title>Crear canal</Modal.Title></Modal.Header><Modal.Body><Stack gap="md">{error && <div role="alert" className="alert alert-danger mb-0">{error}</div>}<label className="form-label mb-0">Nombre<input aria-label="Nombre del canal" required className="form-control mt-1" value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Equipo de prensa" /></label><Stack gap="xs"><label className="form-label mb-0">Etiquetas</label><Inline gap="sm"><input aria-label="Nueva etiqueta" className="form-control" value={tag} onChange={(event) => setTag(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addTag(); } }} placeholder="Escribí una etiqueta" /><button type="button" className="btn btn-outline-primary" onClick={addTag}>Agregar</button></Inline><Inline gap="xs" wrap>{tags.map((item) => <button type="button" className="sp-comms__tag" key={item} onClick={() => setTags((current) => current.filter((currentTag) => currentTag !== item))}>{item} ×</button>)}</Inline></Stack><Stack gap="xs"><label className="form-label mb-0">Miembros</label>{members.map((member) => <label className="sp-comms__member-option" key={member.uid}><input type="checkbox" checked={memberIds.includes(member.uid)} onChange={() => setMemberIds((current) => current.includes(member.uid) ? current.filter((id) => id !== member.uid) : [...current, member.uid])} />{member.displayName || member.email || member.uid}</label>)}</Stack></Stack></Modal.Body><Modal.Footer><button type="button" className="btn btn-outline-secondary" onClick={onHide}>Cancelar</button><button className="btn btn-primary">Crear canal</button></Modal.Footer></form></Modal>;
}
export default function Communications() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null; const channelsQ = useAuthenticatedQuery<Channel[]>(user, base ? `${base}/channels` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]);
  const [activeId, setActiveId] = useState(''); const [activeTag, setActiveTag] = useState(''); const [createOpen, setCreateOpen] = useState(false); useEffect(() => { if (!activeId && channelsQ.data?.[0]) setActiveId(channelsQ.data[0].id); }, [activeId, channelsQ.data]);
  const tags = useMemo(() => Array.from(new Set((channelsQ.data ?? []).flatMap((channel) => channel.tags ?? []))), [channelsQ.data]); const shown = (channelsQ.data ?? []).filter((channel) => !activeTag || channel.tags?.includes(activeTag)); const active = (channelsQ.data ?? []).find((channel) => channel.id === activeId) ?? shown[0];
  if (!campaign || !base) return <PageContainer><small className="text-muted">Elegí una campaña para abrir Comunicaciones.</small></PageContainer>;
  return <PageContainer className="sp-comms-page"><Stack gap="lg"><HeroBanner icon="pulse" eyebrow="COORDINACIÓN INTERNA" title="Centro de Comunicaciones" subtitle="Canales de trabajo para mantener a todo el equipo alineado." ctaLabel="Crear canal" onCtaClick={() => setCreateOpen(true)} /><ContentPanel icon="pulse" title="Canales de campaña" subtitle="Conversaciones por área y equipos de trabajo."><div className="sp-comms"><aside className="sp-comms__sidebar"><Stack gap="md"><Inline gap="xs" wrap className="sp-comms__filters"><button type="button" className={!activeTag ? 'is-active' : ''} onClick={() => setActiveTag('')}>Todos</button>{tags.map((tag) => <button key={tag} type="button" className={activeTag === tag ? 'is-active' : ''} onClick={() => setActiveTag(tag)}>{tag}</button>)}</Inline><Stack gap="xs" className="sp-comms__channels">{shown.map((channel) => <button key={channel.id} type="button" className={channel.id === active?.id ? 'is-active' : ''} onClick={() => setActiveId(channel.id)}><Inline gap="sm"><span className="sp-comms__channel-icon"><Icon name={channel.type === 'area' ? 'target' : 'people'} size={16} /></span><Stack gap="xs"><strong>{channel.name}</strong><small>{channel.lastMessage?.text || 'Sin mensajes todavía'}</small></Stack></Inline></button>)}</Stack></Stack></aside><section className="sp-comms__conversation">{active ? <Stack gap="md"><Inline gap="sm" className="sp-comms__conversation-title"><span className="sp-comms__channel-icon"><Icon name={active.type === 'area' ? 'target' : 'people'} size={18} /></span><Stack gap="xs"><h2>{active.name}</h2><small>{active.type === 'area' ? 'Canal de área' : 'Canal personalizado'}</small></Stack></Inline><ChannelMessages user={user} base={base} channel={active} onSent={channelsQ.reload} /></Stack> : <small className="text-muted">No hay canales con esta etiqueta.</small>}</section></div></ContentPanel></Stack><CreateChannelModal show={createOpen} onHide={() => setCreateOpen(false)} user={user} base={base} members={membersQ.data ?? []} done={channelsQ.reload} /></PageContainer>;
}
export function CommunicationsWidget() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons } = useActiveCampaign(); const location = useLocation(); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null; const channelsQ = useAuthenticatedQuery<Channel[]>(user, enabledAddons.smartPlanner && base ? `${base}/channels` : null, [base, enabledAddons.smartPlanner]); const [open, setOpen] = useState(false); const requestedArea = new URLSearchParams(location.search).get('area'); const contextual = (channelsQ.data ?? []).find((channel) => channel.areaId === requestedArea) ?? channelsQ.data?.find((channel) => channel.type === 'area') ?? channelsQ.data?.[0];
  const unread = useMemo(() => { if (!user) return 0; const seen = readMap(user.uid); return (channelsQ.data ?? []).filter((channel) => channel.lastMessage && channel.lastMessage.senderId !== user.uid && (!seen[channel.id] || new Date(channel.lastMessage.createdAt ?? 0) > new Date(seen[channel.id]))).length; }, [channelsQ.data, user]);
  if (!enabledAddons.smartPlanner || !base || !contextual) return null;
  return <div className={`sp-comms-widget ${open ? 'is-open' : ''}`} data-communications-widget><button type="button" className="sp-comms-widget__trigger" aria-label="Abrir comunicaciones" onClick={() => setOpen((current) => !current)}><Icon name="pulse" size={22} color="#fff" />{unread > 0 && <span>{unread}</span>}</button>{open && <section className="sp-comms-widget__panel"><Stack gap="sm"><Inline gap="sm" className="sp-comms-widget__heading"><span className="sp-comms__channel-icon"><Icon name="target" size={16} /></span><Stack gap="xs"><strong>{contextual.name}</strong><small>Canal contextual</small></Stack></Inline><ChannelMessages user={user} base={base} channel={contextual} compact onSent={channelsQ.reload} /><Link className="btn btn-primary btn-sm w-100" to="/smartplanner/comunicaciones">Ir al Centro de Comunicaciones</Link></Stack></section>}</div>;
}
