import { FormEvent, useState } from 'react';
import { Modal } from 'react-bootstrap';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer'; import HeroBanner from '../../../components/Shared/HeroBanner'; import ContentPanel from '../../../components/Shared/ContentPanel'; import EmptyState from '../../../components/Shared/EmptyState'; import KpiCard from '../../../components/Shared/KpiCard'; import Stack from '../../../components/Shared/Stack'; import Inline from '../../../components/Shared/Inline'; import SelectControl from '../../../components/Shared/SelectControl'; import PrimaryButton from '../../../components/Shared/PrimaryButton';
type Contributor={id:string;name:string;type:'aportante'|'sponsor';contactInfo:string;stage:'prospecto'|'contactado'|'comprometido'|'confirmado';amount:number;notes:string};
const stages:Contributor['stage'][]=['prospecto','contactado','comprometido','confirmado']; const labels:Record<Contributor['stage'],string>={prospecto:'Prospecto',contactado:'Contactado',comprometido:'Comprometido',confirmado:'Confirmado'}; const blank=()=>({name:'',type:'aportante',contactInfo:'',stage:'prospecto',amount:0,notes:''} as Omit<Contributor,'id'>);
export default function Contributors(){const {user}=useAuth(); const {campaign}=useCampaign(); const {enabledAddons}=useActiveCampaign(); const base=campaign?`/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner/contributors`:null; const query=useAuthenticatedQuery<Contributor[]>(user,base,[base]); const [form,setForm]=useState(blank()); const [editing,setEditing]=useState<Contributor|null>(null); const [show,setShow]=useState(false); const items=query.data??[]; const open=(item?:Contributor)=>{setEditing(item??null);setForm(item?{...item}:blank());setShow(true)}; const save=async(e:FormEvent)=>{e.preventDefault();if(!user||!base)return;await authenticatedFetch(user,editing?`${base}/${editing.id}`:base,{method:editing?'PUT':'POST',body:JSON.stringify(form)});setShow(false);await query.reload()}; const move=async(item:Contributor,stage:Contributor['stage'])=>{if(!user||!base)return;await authenticatedFetch(user,`${base}/${item.id}`,{method:'PUT',body:JSON.stringify({...item,stage})});await query.reload()};
if(!enabledAddons.smartPlanner)return <PageContainer><ContentPanel icon="award" title="SmartPlanner"><EmptyState icon="award" title="Este addon no está habilitado en tu plan" description="Pedile a un administrador global que habilite SmartPlanner."/></ContentPanel></PageContainer>;
const committed=items.filter(i=>i.stage==='comprometido'||i.stage==='confirmado').reduce((sum,i)=>sum+i.amount,0); const confirmed=items.filter(i=>i.stage==='confirmado').reduce((sum,i)=>sum+i.amount,0);
return <PageContainer><HeroBanner icon="target" eyebrow="FINANZAS DE CAMPAÑA" title="Aportantes y Sponsors" subtitle="Gestioná relaciones y compromisos financieros con trazabilidad." ctaLabel="Nuevo aportante" onCtaClick={()=>open()}/><div className="cd-dashboard__kpis"><KpiCard icon="trend" value={`$${committed.toLocaleString('es-AR')}`} label="Total comprometido"/><KpiCard icon="check" iconColor="green" value={`$${confirmed.toLocaleString('es-AR')}`} label="Total confirmado"/><KpiCard icon="people" iconColor="purple" value={items.length} label="Relaciones activas"/></div><ContentPanel icon="people" title="Pipeline de aportes" subtitle="Mové cada relación por su etapa de gestión."><div className="sp-kanban">{stages.map(stage=><section className="sp-kanban__column" key={stage}><header><span>{labels[stage]}</span><b>{items.filter(i=>i.stage===stage).length}</b></header><Stack gap="sm">{items.filter(i=>i.stage===stage).map(item=><article className="sp-task" key={item.id}><strong>{item.name}</strong><small>{item.type==='sponsor'?'Sponsor':'Aportante'} · ${item.amount.toLocaleString('es-AR')}</small><Inline gap="sm"><button type="button" className="btn btn-sm btn-outline-primary" onClick={()=>open(item)}>Editar</button><SelectControl label="Mover" ariaLabel={`Mover ${item.name}`} value={item.stage} onChange={next=>void move(item,next as Contributor['stage'])} options={stages.map(value=>({value,label:labels[value]}))}/></Inline></article>)}{!items.filter(i=>i.stage===stage).length&&<p className="sp-empty">Sin relaciones.</p>}</Stack></section>)}</div></ContentPanel><Modal show={show} onHide={()=>setShow(false)}><form onSubmit={save}><Modal.Header closeButton><Modal.Title>{editing?'Editar relación':'Nuevo aportante o sponsor'}</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Nombre" className="form-control" placeholder="Nombre o razón social" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><SelectControl label="Tipo" ariaLabel="Tipo" value={form.type} onChange={type=>setForm({...form,type:type as Contributor['type']})} options={[{value:'aportante',label:'Aportante'},{value:'sponsor',label:'Sponsor'}]}/><input aria-label="Contacto" className="form-control" placeholder="Teléfono o email" value={form.contactInfo} onChange={e=>setForm({...form,contactInfo:e.target.value})}/><input aria-label="Monto" type="number" min="0" className="form-control" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/><textarea aria-label="Notas" className="form-control" placeholder="Notas de la relación" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Stack></Modal.Body><Modal.Footer><PrimaryButton type="submit" icon="check">Guardar</PrimaryButton></Modal.Footer></form></Modal></PageContainer>}
