import { FormEvent, useState } from 'react';
import { Modal } from 'react-bootstrap';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import PrimaryButton from '../../../components/Shared/PrimaryButton';

type Message = { id: string; title: string; content: string; mediaUrl?: string; status: string; createdBy: string; approvedBy?: string; approvedAt?: string; rejectionReason?: string };
type Member = { uid: string; smartPlannerRole?: string };
const labels: Record<string, string> = { borrador: 'Borrador', pendiente_aprobacion: 'Pendiente de aprobación', aprobado: 'Aprobado', rechazado: 'Rechazado' };
const blank = () => ({ title: '', content: '', mediaUrl: '' });
export default function Messages() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons, role } = useActiveCampaign(); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
  const query = useAuthenticatedQuery<Message[]>(user, base ? `${base}/messages` : null, [base]); const members = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const [editing, setEditing] = useState<Message | null>(null); const [form, setForm] = useState(blank()); const [show, setShow] = useState(false); const [notice, setNotice] = useState('');
  const mine = (members.data ?? []).find((member) => member.uid === user?.uid); const canApprove = ['cliente', 'admin'].includes(role) || mine?.smartPlannerRole === 'pm'; const rows = query.data ?? [];
  const open = (item?: Message) => { setEditing(item ?? null); setForm(item ? { title: item.title, content: item.content, mediaUrl: item.mediaUrl ?? '' } : blank()); setShow(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!user || !base) return; await authenticatedFetch(user, editing ? `${base}/messages/${editing.id}` : `${base}/messages`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); setShow(false); await query.reload(); };
  const action = async (item: Message, actionName: 'submit' | 'approve' | 'reject') => { if (!user || !base) return; const reason = actionName === 'reject' ? window.prompt('Motivo del rechazo') : null; if (actionName === 'reject' && !reason?.trim()) return; await authenticatedFetch(user, `${base}/messages/${item.id}/${actionName}`, { method: 'POST', body: actionName === 'reject' ? JSON.stringify({ reason }) : undefined }); setNotice(`${item.title}: ${actionName === 'submit' ? 'enviado a aprobación' : actionName === 'approve' ? 'aprobado' : 'rechazado'}.`); await query.reload(); };
  const upload = async (file?: File) => { if (!user || !base || !file) return; const data = new FormData(); data.append('media', file); const result = await authenticatedFetch<{ mediaUrl: string }>(user, `${base}/messages/upload`, { method: 'POST', body: data }); setForm((current) => ({ ...current, mediaUrl: result.mediaUrl })); };
  if (!enabledAddons.smartPlanner) return <PageContainer><ContentPanel icon="chat" title="Validación de Mensajes"><EmptyState icon="award" title="Este addon no está habilitado" description="Solicitá la habilitación de SmartPlanner." /></ContentPanel></PageContainer>;
  return <PageContainer><Stack gap="lg"><HeroBanner icon="chat" eyebrow="GOBERNANZA DE MENSAJE" title="Validación de Mensajes" subtitle="Asegurá consistencia política antes de publicar cada mensaje." ctaLabel="Nuevo mensaje" onCtaClick={() => open()} /><ContentPanel icon="chat" title="Hitos de validación" subtitle="Los mensajes enviados quedan bloqueados hasta ser aprobados o rechazados."><Stack gap="sm">{rows.map((item) => <article className="sp-project" key={item.id}><Inline gap="sm" className="sp-project__row"><Stack gap="xs"><strong>{item.title}</strong><small>{labels[item.status]}</small>{item.rejectionReason && <small className="text-danger">Motivo: {item.rejectionReason}</small>}{item.approvedAt && <small>Aprobado el {new Date(item.approvedAt).toLocaleString('es-AR')}</small>}</Stack><Inline gap="xs" wrap>{item.status === 'borrador' && <><button className="btn btn-sm btn-outline-primary" onClick={() => open(item)}>Editar</button><button className="btn btn-sm btn-primary" onClick={() => void action(item, 'submit')}>Enviar a aprobación</button></>}{item.status === 'pendiente_aprobacion' && canApprove && <><button className="btn btn-sm btn-success" onClick={() => void action(item, 'approve')}>Aprobar</button><button className="btn btn-sm btn-outline-danger" onClick={() => void action(item, 'reject')}>Rechazar</button></>}</Inline></Inline></article>)}{!rows.length && <EmptyState icon="chat" title="Todavía no hay mensajes" description="Creá un borrador para iniciar el circuito de validación." />}{notice && <div className="alert alert-success mb-0" role="status">{notice}</div>}</Stack></ContentPanel></Stack><Modal show={show} onHide={() => setShow(false)}><form onSubmit={save}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar mensaje' : 'Nuevo mensaje'}</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Título de mensaje" className="form-control" placeholder="Título" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /><textarea aria-label="Contenido de mensaje" className="form-control" placeholder="Contenido del mensaje" value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} required /><div><label className="form-label" htmlFor="message-media">Adjuntar imagen o archivo</label><input id="message-media" aria-label="Adjuntar archivo al mensaje" className="form-control" type="file" onChange={(event) => void upload(event.target.files?.[0])} />{form.mediaUrl && <small className="text-success">Archivo adjunto.</small>}</div></Stack></Modal.Body><Modal.Footer><PrimaryButton type="submit" icon="check">Guardar borrador</PrimaryButton></Modal.Footer></form></Modal></PageContainer>;
}
