import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { firestore } from '../../../lib/firebase';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import Inline from '../../../components/Shared/Inline';
import Stack from '../../../components/Shared/Stack';
import SelectControl from '../../../components/Shared/SelectControl';
import PrimaryButton from '../../../components/Shared/PrimaryButton';
import Timeline from '../../../components/Planning/Timeline';
import { Toast } from '../../../components/Toast';
import PbiCategoryField, { PbiCategory } from './PbiCategoryField';
import type { Pbi, PbiAcceptanceCriterion, PbiChecklistItem, PbiUserStory } from './Backlog';

type Area = { id: string; name: string };
type Member = { uid: string; displayName?: string; email: string };
type Status = Pbi['status'];
type Comment = { id: string; text: string; authorId: string; authorName: string; createdAt?: { toDate?: () => Date } | string | null };
type Activity = { id: string; fieldLabel?: string; oldValue?: string; newValue?: string; changedByName?: string; changedAt?: string | null };
const statuses: { value: Status; label: string }[] = [{ value: 'por_hacer', label: 'Por hacer' }, { value: 'en_progreso', label: 'En progreso' }, { value: 'en_revision', label: 'En revisión' }, { value: 'completada', label: 'Completada' }];
const priorities = [{ value: 'baja', label: 'Baja' }, { value: 'media', label: 'Media' }, { value: 'alta', label: 'Alta' }];
const identifier = (prefix: string) => `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
const asDate = (value?: Comment['createdAt']) => typeof value === 'string' ? value : value?.toDate?.().toISOString?.() ?? new Date().toISOString();
const handle = (member: Member) => (member.displayName || member.email).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

export default function PbiDetail() {
  const { pbiId = '' } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons } = useActiveCampaign();
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
  const pbisQ = useAuthenticatedQuery<Pbi[]>(user, base ? `${base}/tasks` : null, [base]); const areasQ = useAuthenticatedQuery<Area[]>(user, base ? `${base}/areas` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const categoriesQ = useAuthenticatedQuery<PbiCategory[]>(user, base ? `${base}/categories` : null, [base]); const activityQ = useAuthenticatedQuery<Activity[]>(user, base && pbiId ? `${base}/tasks/${pbiId}/activity` : null, [base, pbiId]);
  const pbi = (pbisQ.data ?? []).find((item) => item.id === pbiId); const [form, setForm] = useState<Pbi | null>(null); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [commentText, setCommentText] = useState(''); const [mentionedIds, setMentionedIds] = useState<string[]>([]); const [commentError, setCommentError] = useState('');
  useEffect(() => { if (pbi) setForm((current) => current?.id === pbi.id ? current : pbi); }, [pbi?.id]);
  useEffect(() => {
    if (!campaign || !pbiId) return undefined;
    return onSnapshot(query(collection(firestore, 'organizations', campaign.orgId, 'campaigns', campaign.campId, 'spTasks', pbiId, 'comments'), orderBy('createdAt', 'asc')), (snapshot) => setComments(snapshot.docs.map((document) => ({ id: document.id, ...document.data() } as Comment))), () => setCommentError('No pudimos actualizar la discusión en tiempo real.'));
  }, [campaign?.orgId, campaign?.campId, pbiId]);
  const members = membersQ.data ?? []; const memberName = (uid?: string) => members.find((member) => member.uid === uid)?.displayName || members.find((member) => member.uid === uid)?.email || 'Sin asignar';
  const children = (pbisQ.data ?? []).filter((item) => item.parentPbiId === pbiId); const completedChildren = children.filter((item) => item.status === 'completada').length; const childProgress = children.length ? Math.round((completedChildren / children.length) * 100) : 0;
  const story: PbiUserStory = form?.userStory ?? { role: '', action: '', benefit: '' }; const criteria = form?.acceptanceCriteria ?? []; const checklist = form?.checklist ?? [];
  const trigger = /(?:^|\s)@([\w.-]*)$/.exec(commentText)?.[1]; const mentionSuggestions = useMemo(() => trigger === undefined ? [] : members.filter((member) => member.uid !== user?.uid && `${memberName(member.uid)} ${member.email} ${handle(member)}`.toLowerCase().includes(trigger.toLowerCase())).slice(0, 6), [members, trigger, user?.uid]);
  async function createCategory(name: string) { if (!user || !base) throw new Error('No se pudo crear la categoría.'); const category = await authenticatedFetch<PbiCategory>(user, `${base}/categories`, { method: 'POST', body: JSON.stringify({ name }) }); await categoriesQ.reload(); return category; }
  async function save() { if (!user || !base || !form?.title.trim()) return; try { const saved = await authenticatedFetch<Pbi>(user, `${base}/tasks/${pbiId}`, { method: 'PUT', body: JSON.stringify(form) }); setForm((current) => current ? { ...current, ...saved } : saved); await Promise.all([pbisQ.reload(), activityQ.reload()]); setNotice({ message: 'Cambios del PBI guardados.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos guardar el PBI.', variant: 'danger' }); } }
  async function remove() { if (!user || !base || !form || !window.confirm(`¿Eliminar el PBI “${form.title}”?`)) return; await authenticatedFetch(user, `${base}/tasks/${pbiId}`, { method: 'DELETE' }); navigate('/smartplanner/backlog'); }
  async function sendComment(event: FormEvent) { event.preventDefault(); if (!user || !base || !commentText.trim()) return; try { await authenticatedFetch(user, `${base}/tasks/${pbiId}/comments`, { method: 'POST', body: JSON.stringify({ text: commentText, mentionedIds }) }); setCommentText(''); setMentionedIds([]); setCommentError(''); } catch (error) { setCommentError(error instanceof Error ? error.message : 'No pudimos publicar el comentario.'); } }
  const updateStory = (field: keyof PbiUserStory, value: string) => setForm((current) => current ? { ...current, userStory: { ...(current.userStory ?? { role: '', action: '', benefit: '' }), [field]: value } } : current);
  const updateCriterion = (id: string, patch: Partial<PbiAcceptanceCriterion>) => setForm((current) => current ? { ...current, acceptanceCriteria: (current.acceptanceCriteria ?? []).map((item) => item.id === id ? { ...item, ...patch } : item) } : current);
  const updateChecklist = (id: string, patch: Partial<PbiChecklistItem>) => setForm((current) => current ? { ...current, checklist: (current.checklist ?? []).map((item) => item.id === id ? { ...item, ...patch } : item) } : current);
  if (!enabledAddons.smartPlanner) return null;
  if (!pbi || !form) return <PageContainer backTo="/smartplanner/backlog"><EmptyState icon="list" title="PBI no encontrado" description="Puede haber sido eliminado o no pertenecer a la campaña activa." ctaLabel="Volver al Backlog" onCtaClick={() => navigate('/smartplanner/backlog')} /></PageContainer>;
  const activityEvents = (activityQ.data ?? []).map((entry) => ({ id: entry.id, type: 'event' as const, date: entry.changedAt || new Date().toISOString(), title: `${entry.changedByName || 'Un integrante'} cambió ${entry.fieldLabel || 'un campo'}`, description: `De “${entry.oldValue || 'sin definir'}” a “${entry.newValue || 'sin definir'}”.` }));
  return <PageContainer backTo="/smartplanner/backlog"><Stack gap="lg"><HeroBanner icon="doc" eyebrow="PBI DE CAMPAÑA" title={form.displayId ?? 'PBI'} subtitle="Actualizá el alcance, responsables y progreso." backTo="/smartplanner/backlog" />
    <ContentPanel icon="doc" title="Detalle del PBI" subtitle="Los cambios se guardan de forma explícita."><Stack gap="md"><div className="sp-pbi-detail__heading"><label htmlFor="pbi-title">Título</label><input id="pbi-title" aria-label="Título del PBI" className="form-control" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></div><Inline gap="sm" wrap className="sp-pbi-detail__badges"><span>{statuses.find((item) => item.value === form.status)?.label}</span><span>{priorities.find((item) => item.value === form.priority)?.label}</span><span>{memberName(form.assignedTo)}</span><span>{categoriesQ.data?.find((category) => category.id === form.categoryId)?.name || 'Sin categoría'}</span></Inline><label className="form-label" htmlFor="pbi-description">Descripción</label><textarea id="pbi-description" aria-label="Descripción del PBI" className="form-control" rows={5} value={form.description ?? ''} onChange={(event) => setForm({ ...form, description: event.target.value })} /><div className="sp-pbi-detail__fields"><SelectControl ariaLabel="Estado del PBI" label="Estado" value={form.status} onChange={(status) => setForm({ ...form, status: status as Status })} options={statuses} /><SelectControl ariaLabel="Prioridad del PBI" label="Prioridad" value={form.priority} onChange={(priority) => setForm({ ...form, priority: priority as Pbi['priority'] })} options={priorities} /><SelectControl ariaLabel="Responsable del PBI" label="Responsable" value={form.assignedTo} onChange={(assignedTo) => setForm({ ...form, assignedTo })} options={members.map((member) => ({ value: member.uid, label: memberName(member.uid) }))} /><SelectControl ariaLabel="Área del PBI" label="Área" value={form.areaId} onChange={(areaId) => setForm({ ...form, areaId })} options={(areasQ.data ?? []).map((area) => ({ value: area.id, label: area.name }))} /><PbiCategoryField value={form.categoryId ?? ''} categories={categoriesQ.data ?? []} onChange={(categoryId) => setForm({ ...form, categoryId })} onCreate={createCategory} /></div><Inline gap="md" wrap className="sp-pbi-detail__metadata"><span>Creado: {form.createdAt ? new Date(form.createdAt).toLocaleString('es-AR') : '—'}</span><span>Creado por: {memberName(form.createdBy)}</span></Inline><Inline gap="sm" wrap><PrimaryButton icon="check" onClick={() => void save()}>Guardar cambios</PrimaryButton><button type="button" className="btn btn-outline-danger" onClick={() => void remove()}>Eliminar</button></Inline></Stack></ContentPanel>
    <ContentPanel icon="target" title="Historia de Usuario" subtitle="Definí el valor esperado desde la perspectiva de quien lo necesita."><Stack gap="sm"><div className="sp-pbi-detail__fields"><input aria-label="Rol de historia de usuario" className="form-control" value={story.role} onChange={(event) => updateStory('role', event.target.value)} placeholder="rol" /><input aria-label="Acción de historia de usuario" className="form-control" value={story.action} onChange={(event) => updateStory('action', event.target.value)} placeholder="acción" /><input aria-label="Beneficio de historia de usuario" className="form-control" value={story.benefit} onChange={(event) => updateStory('benefit', event.target.value)} placeholder="beneficio" /></div><p className="sp-pbi-detail__story">Como <strong>{story.role || '…'}</strong>, quiero <strong>{story.action || '…'}</strong>, para <strong>{story.benefit || '…'}</strong>.</p></Stack></ContentPanel>
    <ContentPanel icon="check" title="Criterios de Aceptación" subtitle={`${criteria.filter((item) => item.completed).length} de ${criteria.length} completados.`}><Stack gap="sm">{criteria.map((criterion, index) => { const bdd = criterion.useGivenWhenThen === true || Boolean(criterion.given || criterion.when || criterion.then); return <article className="sp-pbi-detail__item" key={criterion.id}><Stack gap="sm"><Inline gap="sm" className="align-items-center"><input aria-label={`Completar AC${String(index + 1).padStart(2, '0')}`} type="checkbox" checked={criterion.completed} onChange={(event) => updateCriterion(criterion.id, { completed: event.target.checked })} /><strong>AC{String(index + 1).padStart(2, '0')}</strong><input aria-label={`Descripción AC${String(index + 1).padStart(2, '0')}`} className="form-control" value={criterion.description} onChange={(event) => updateCriterion(criterion.id, { description: event.target.value })} placeholder="Resultado verificable" /><button type="button" className="btn btn-sm btn-outline-secondary" onClick={() => updateCriterion(criterion.id, { useGivenWhenThen: !bdd, ...(bdd ? { given: '', when: '', then: '' } : {}) })}>{bdd ? 'Ocultar Given/When/Then' : 'Usar Given/When/Then'}</button><button type="button" aria-label={`Quitar AC${String(index + 1).padStart(2, '0')}`} className="btn btn-sm btn-outline-danger" onClick={() => setForm((current) => current ? { ...current, acceptanceCriteria: (current.acceptanceCriteria ?? []).filter((item) => item.id !== criterion.id) } : current)}>×</button></Inline>{bdd && <div className="sp-pbi-detail__fields"><input aria-label={`Given AC${String(index + 1).padStart(2, '0')}`} className="form-control" value={criterion.given || ''} onChange={(event) => updateCriterion(criterion.id, { given: event.target.value })} placeholder="Dado" /><input aria-label={`When AC${String(index + 1).padStart(2, '0')}`} className="form-control" value={criterion.when || ''} onChange={(event) => updateCriterion(criterion.id, { when: event.target.value })} placeholder="Cuando" /><input aria-label={`Then AC${String(index + 1).padStart(2, '0')}`} className="form-control" value={criterion.then || ''} onChange={(event) => updateCriterion(criterion.id, { then: event.target.value })} placeholder="Entonces" /></div>}</Stack></article>; })}<button type="button" className="btn btn-outline-primary align-self-start" onClick={() => setForm((current) => current ? { ...current, acceptanceCriteria: [...(current.acceptanceCriteria ?? []), { id: identifier('ac'), description: '', completed: false }] } : current)}>+ Agregar criterio</button></Stack></ContentPanel>
    <ContentPanel icon="list" title="Checklist" subtitle={`${checklist.filter((item) => item.completed).length} de ${checklist.length} completados.`}><Stack gap="sm">{checklist.map((item, index) => <article className="sp-pbi-detail__item" key={item.id}><Inline gap="sm" wrap className="align-items-center"><input aria-label={`Completar checklist ${index + 1}`} type="checkbox" checked={item.completed} onChange={(event) => updateChecklist(item.id, { completed: event.target.checked })} /><input aria-label={`Nombre checklist ${index + 1}`} className="form-control flex-grow-1" value={item.name} onChange={(event) => updateChecklist(item.id, { name: event.target.value })} placeholder="Paso concreto" /><SelectControl ariaLabel={`Responsable checklist ${index + 1}`} label="Responsable" value={item.responsible || ''} onChange={(responsible) => updateChecklist(item.id, { responsible })} options={[{ value: '', label: 'Sin responsable' }, ...members.map((member) => ({ value: member.uid, label: memberName(member.uid) }))]} /><input aria-label={`Fecha checklist ${index + 1}`} type="date" className="form-control" value={item.dueDate || ''} onChange={(event) => updateChecklist(item.id, { dueDate: event.target.value })} /><button type="button" aria-label={`Quitar checklist ${index + 1}`} className="btn btn-sm btn-outline-danger" onClick={() => setForm((current) => current ? { ...current, checklist: (current.checklist ?? []).filter((entry) => entry.id !== item.id) } : current)}>×</button></Inline></article>)}<button type="button" className="btn btn-outline-primary align-self-start" onClick={() => setForm((current) => current ? { ...current, checklist: [...(current.checklist ?? []), { id: identifier('check'), name: '', completed: false }] } : current)}>+ Agregar ítem</button></Stack></ContentPanel>
    <ContentPanel icon="bars" title="Subtareas" subtitle={`${completedChildren} de ${children.length} completadas — ${childProgress}%`} headerAction={<button type="button" className="btn btn-sm btn-primary" onClick={() => navigate(`/smartplanner/backlog?new=1&parent=${encodeURIComponent(pbiId)}&area=${encodeURIComponent(form.areaId)}`)}>+ Crear subtarea</button>}><Stack gap="sm"><div className="progress"><div className="progress-bar" style={{ width: `${childProgress}%` }} /></div>{children.length ? children.map((child) => <Inline gap="sm" className="sp-pbi-detail__item" key={child.id}><Link to={`/smartplanner/pbi/${child.id}`}>{child.displayId || 'PBI'} · {child.title}</Link><span>{statuses.find((item) => item.value === child.status)?.label}</span><span>{memberName(child.assignedTo)}</span><span>{priorities.find((item) => item.value === child.priority)?.label}</span></Inline>) : <small className="text-muted">Todavía no hay subtareas.</small>}</Stack></ContentPanel>
    <ContentPanel icon="chat" title="Discusión" subtitle="Comentarios y decisiones visibles en tiempo real."><Stack gap="sm"><Stack gap="sm" className="sp-pbi-detail__discussion">{comments.length ? comments.map((comment) => <article className="sp-pbi-detail__comment" key={comment.id}><strong>{comment.authorName}</strong><small>{new Date(asDate(comment.createdAt)).toLocaleString('es-AR')}</small><p>{comment.text}</p></article>) : <small className="text-muted">Iniciá la discusión de este PBI.</small>}</Stack>{commentError && <div className="alert alert-danger mb-0" role="alert">{commentError}</div>}<form onSubmit={sendComment}><Stack gap="xs"><div className="position-relative"><input aria-label="Comentario del PBI" className="form-control" value={commentText} onChange={(event) => setCommentText(event.target.value)} placeholder="Escribí un comentario… (@ menciona)" />{trigger !== undefined && <div className="sp-pbi-detail__mentions" role="listbox" aria-label="Sugerencias de menciones">{mentionSuggestions.map((member) => <button type="button" role="option" key={member.uid} onClick={() => { setCommentText((current) => current.replace(/@[\w.-]*$/, `@${handle(member)} `)); setMentionedIds((current) => [...new Set([...current, member.uid])]); }}><strong>{memberName(member.uid)}</strong><small>@{handle(member)}</small></button>)}{!mentionSuggestions.length && <small>No encontramos integrantes.</small>}</div>}</div><Inline gap="sm"><button type="submit" className="btn btn-primary">Comentar</button><small className="text-muted">Las menciones generan una notificación.</small></Inline></Stack></form></Stack></ContentPanel>
    <ContentPanel icon="clock" title="Actividad" subtitle="Cambios automáticos del PBI."><Timeline events={activityEvents} /></ContentPanel>{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}</Stack></PageContainer>;
}
