import { CSSProperties, FormEvent, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import Chart from 'react-apexcharts';
import { Modal } from 'react-bootstrap';
import { DndContext, DragEndEvent, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from '@dnd-kit/core';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import KpiCard from '../../../components/Shared/KpiCard';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import SelectControl from '../../../components/Shared/SelectControl';
import PrimaryButton from '../../../components/Shared/PrimaryButton';
import { Toast } from '../../../components/Toast';

type Status = 'por_hacer' | 'en_progreso' | 'en_revision' | 'completada';
type Area = { id: string; name: string; description: string; color: string };
type Task = { id: string; title: string; description: string; areaId: string; assignedTo: string; status: Status; priority: 'baja' | 'media' | 'alta'; startDate: string; dueDate: string; cost: number };
type Member = { uid: string; displayName?: string; email: string; smartPlannerRole?: 'contador' | 'pm' | 'miembro' };
type NewTask = Omit<Task, 'id' | 'status'>;
type Period = 'hoy' | 'semana' | 'mes' | 'todas';

const columns: Status[] = ['por_hacer', 'en_progreso', 'en_revision', 'completada'];
const statusLabels: Record<Status, string> = { por_hacer: 'Por hacer', en_progreso: 'En progreso', en_revision: 'En revisión', completada: 'Completada' };
const priorityLabels = { baja: 'Baja', media: 'Media', alta: 'Alta' };
const emptyTask = (): NewTask => ({ title: '', description: '', areaId: '', assignedTo: '', priority: 'media', startDate: new Date().toISOString().slice(0, 10), dueDate: new Date().toISOString().slice(0, 10), cost: 0 });
const parseDay = (date: string) => date ? new Date(`${date}T12:00:00`) : null;
const formatDay = (date: string) => parseDay(date)?.toLocaleDateString('es-AR', { day: '2-digit', month: 'short' }) ?? 'Sin fecha';
const canonicalAreaNames = ['estrategia', 'comunicacion', 'avanzada y logistica', 'finanzas', 'juridico'];
const normalizedName = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const sortAreas = (items: Area[]) => [...items].sort((left, right) => {
  const leftOrder = canonicalAreaNames.indexOf(normalizedName(left.name)); const rightOrder = canonicalAreaNames.indexOf(normalizedName(right.name));
  return (leftOrder < 0 ? 1000 : leftOrder) - (rightOrder < 0 ? 1000 : rightOrder) || left.name.localeCompare(right.name);
});

function KanbanColumn({ status, tasks, memberName, onMove }: { status: Status; tasks: Task[]; memberName: (uid: string) => string; onMove: (task: Task, status: Status) => void }) {
  const { isOver, setNodeRef } = useDroppable({ id: `status:${status}` });
  return <section ref={setNodeRef} className={`sp-kanban__column${isOver ? ' is-drop-target' : ''}`} data-kanban-column={status}><header><span>{statusLabels[status]}</span><b>{tasks.length}</b></header><Stack gap="sm">{tasks.map((task) => <DraggableTask key={task.id} task={task} memberName={memberName} onMove={onMove} />)}{!tasks.length && <p className="sp-empty">Soltá una tarea acá.</p>}</Stack></section>;
}

function DraggableTask({ task, memberName, onMove }: { task: Task; memberName: (uid: string) => string; onMove: (task: Task, status: Status) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: task.id, data: { task } });
  const style = transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : undefined;
  return <article ref={setNodeRef} style={style} className={`sp-task${isDragging ? ' is-dragging' : ''}`} data-kanban-task={task.id} {...attributes} {...listeners}><span className={`sp-task__priority ${task.priority}`} /><strong>{task.title}</strong><small>{memberName(task.assignedTo)} · vence {formatDay(task.dueDate)}</small><SelectControl ariaLabel={`Mover ${task.title}`} label="Mover" value={task.status} onChange={(next) => onMove(task, next as Status)} options={columns.map((value) => ({ value, label: statusLabels[value] }))} /></article>;
}

export default function SmartPlanner() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons, role } = useActiveCampaign();
  const [searchParams, setSearchParams] = useSearchParams(); const [period, setPeriod] = useState<Period>('todas'); const [showTaskModal, setShowTaskModal] = useState(false); const [taskForm, setTaskForm] = useState<NewTask>(emptyTask()); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
  const areasQ = useAuthenticatedQuery<Area[]>(user, base ? `${base}/areas` : null, [base]); const tasksQ = useAuthenticatedQuery<Task[]>(user, base ? `${base}/tasks` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const financeQ = useAuthenticatedQuery<{ legalSpendingLimit: number; spent: number; remaining?: number | null; exceeded: boolean }>(user, base ? `${base}/finance-overview` : null, [base]); const configQ = useAuthenticatedQuery<{ accent?: string }>(user, base ? `${base}/config` : null, [base]);
  const areas = sortAreas(areasQ.data ?? []); const tasks = tasksQ.data ?? []; const members = membersQ.data ?? []; const selectedAreaId = searchParams.get('area') || areas[0]?.id || ''; const selectedArea = areas.find((area) => area.id === selectedAreaId); const myMembership = members.find((member) => member.uid === user?.uid); const canManage = ['cliente', 'admin'].includes(role) || ['contador', 'pm'].includes(myMembership?.smartPlannerRole ?? 'miembro');
  const memberName = (uid: string) => members.find((member) => member.uid === uid)?.displayName || members.find((member) => member.uid === uid)?.email || 'Sin asignar';
  const reload = () => Promise.all([areasQ.reload(), tasksQ.reload(), membersQ.reload(), financeQ.reload()]);
  const chooseArea = (areaId: string) => { setSearchParams({ area: areaId }); window.setTimeout(() => document.getElementById('smartplanner-board')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); };
  const activeTasks = tasks.filter((task) => task.status !== 'completada');
  const progressRows = useMemo(() => areas.map((area) => { const areaTasks = tasks.filter((task) => task.areaId === area.id); const done = areaTasks.filter((task) => task.status === 'completada').length; return { area, total: areaTasks.length, done, progress: areaTasks.length ? Math.round((done / areaTasks.length) * 100) : 0 }; }), [areas, tasks]);
  const overallProgress = tasks.length ? Math.round((tasks.filter((task) => task.status === 'completada').length / tasks.length) * 100) : 0;
  const periodTasks = useMemo(() => { const now = new Date(); now.setHours(0, 0, 0, 0); const endOfWeek = new Date(now); endOfWeek.setDate(now.getDate() + ((7 - now.getDay()) % 7)); const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0); return activeTasks.filter((task) => { const due = parseDay(task.dueDate); if (!due || period === 'todas') return true; if (period === 'hoy') return due.toDateString() === now.toDateString(); if (period === 'semana') return due >= now && due <= endOfWeek; return due >= now && due <= endOfMonth; }).sort((left, right) => (left.dueDate || '9999').localeCompare(right.dueDate || '9999')); }, [activeTasks, period]);
  const upcoming = [...activeTasks].filter((task) => task.dueDate).sort((left, right) => left.dueDate.localeCompare(right.dueDate)).slice(0, 4); const selectedTasks = tasks.filter((task) => task.areaId === selectedAreaId); const featuredMembers = [...members].sort((left, right) => Number(right.uid === user?.uid) - Number(left.uid === user?.uid)).slice(0, 5); const financialProgress = financeQ.data?.legalSpendingLimit ? Math.min(100, Math.round(((financeQ.data.spent || 0) / financeQ.data.legalSpendingLimit) * 100)) : 0;
  const donut = { series: [overallProgress, Math.max(0, 100 - overallProgress)], options: { chart: { type: 'donut' as const, sparkline: { enabled: true } }, colors: ['#2f6fe4', '#e9f0fb'], stroke: { width: 0 }, dataLabels: { enabled: false }, tooltip: { enabled: false }, legend: { show: false }, plotOptions: { pie: { donut: { size: '72%' } } } } };
  const openTask = (areaId = selectedAreaId) => { setTaskForm({ ...emptyTask(), areaId, assignedTo: user?.uid ?? '' }); setShowTaskModal(true); };
  async function saveTask(event: FormEvent) { event.preventDefault(); if (!user || !base || !taskForm.title.trim() || !(taskForm.areaId || selectedAreaId)) return; try { await authenticatedFetch(user, `${base}/tasks`, { method: 'POST', body: JSON.stringify({ ...taskForm, areaId: taskForm.areaId || selectedAreaId, status: 'por_hacer' }) }); setShowTaskModal(false); setTaskForm(emptyTask()); setNotice({ message: 'Tarea creada en el cuartel.', variant: 'success' }); await reload(); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos crear la tarea.', variant: 'danger' }); } }
  async function moveTask(task: Task, status: Status) { if (!user || !base || task.status === status) return; try { await authenticatedFetch(user, `${base}/tasks/${task.id}`, { method: 'PUT', body: JSON.stringify({ ...task, status }) }); await tasksQ.reload(); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos mover la tarea.', variant: 'danger' }); } }
  async function changeMemberRole(memberId: string, smartPlannerRole: string) { if (!user || !base) return; try { await authenticatedFetch(user, `${base}/members/${memberId}/role`, { method: 'PUT', body: JSON.stringify({ smartPlannerRole }) }); await membersQ.reload(); setNotice({ message: 'Rol actualizado.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos actualizar el rol.', variant: 'danger' }); } }
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));
  function handleDragEnd(event: DragEndEvent) { const task = event.active.data.current?.task as Task | undefined; const target = String(event.over?.id ?? ''); const status = target.replace('status:', '') as Status; if (task && columns.includes(status) && task.status !== status) void moveTask(task, status); }

  if (!enabledAddons.smartPlanner) return <PageContainer><HeroBanner icon="settings" title="SmartPlanner" subtitle="Gestión profesional de proyectos para tu campaña." /><ContentPanel icon="settings" title="Add-on no habilitado"><EmptyState icon="award" title="Este addon no está habilitado en tu plan" description="Pedile a un administrador global que habilite SmartPlanner para esta organización." /></ContentPanel></PageContainer>;
  return <PageContainer><Stack gap="lg"><div data-smartplanner="workspace" className="sp-home" style={{ '--smartplanner-accent': configQ.data?.accent || '#0060F0' } as CSSProperties}>
    <HeroBanner icon="target" eyebrow="CUARTEL DE CAMPAÑA" title="SmartPlanner" subtitle="Convertí la estrategia de campaña en acción." subtitleDetail="Planificá, asigná, coordiná y hacé seguimiento de cada frente desde un solo lugar." ctaLabel={canManage ? 'Nueva tarea' : undefined} onCtaClick={() => openTask()} tags={[{ icon: 'users', label: 'Equipo conectado' }, { icon: 'check-circle', label: 'Flujo profesional' }]} />
    <div className="cd-dashboard__kpis sp-kpis"><KpiCard icon="list" value={activeTasks.length} label="Tareas activas" caption="En el cuartel" progress={tasks.length ? Math.round((activeTasks.length / tasks.length) * 100) : 0} /><KpiCard icon="bars" iconColor="purple" value={tasks.filter((task) => task.status === 'en_progreso').length} label="En ejecución" caption="Trabajo en marcha" /><KpiCard icon="check" iconColor="green" value={tasks.filter((task) => task.status === 'completada').length} label="Completadas" caption="Resultados cerrados" progress={overallProgress} /><KpiCard icon="clock" iconColor="red" value={tasks.filter((task) => task.priority === 'alta' && task.status !== 'completada').length} label="Alta prioridad" caption="Foco inmediato" /></div>
    <div className="sp-home__top-grid"><ContentPanel icon="list" title="Plan de trabajo" subtitle="Priorizá lo que mueve la campaña hoy." headerAction={<Link className="btn btn-sm btn-outline-primary" to={selectedAreaId ? `/smartplanner?area=${selectedAreaId}#smartplanner-board` : '/smartplanner#smartplanner-board'}>Ver tablero</Link>}><Stack gap="sm"><Inline gap="xs" className="sp-home__filters">{([{ id: 'hoy', label: 'Hoy' }, { id: 'semana', label: 'Esta semana' }, { id: 'mes', label: 'Este mes' }, { id: 'todas', label: 'Todas' }] as { id: Period; label: string }[]).map((item) => <button key={item.id} type="button" className={`sp-tab ${period === item.id ? 'is-active' : ''}`} onClick={() => setPeriod(item.id)}>{item.label}</button>)}</Inline><Stack gap="xs">{periodTasks.slice(0, 5).map((task) => <article className="sp-home__task" key={task.id}><Inline gap="sm"><span className={`sp-home__priority ${task.priority}`} /><Stack gap="xs" className="sp-home__task-copy"><strong>{task.title}</strong><small>{areas.find((area) => area.id === task.areaId)?.name || 'Sin área'} · {formatDay(task.dueDate)} · {memberName(task.assignedTo)}</small></Stack><span className={`sp-home__task-status ${task.priority}`}>{priorityLabels[task.priority]}</span></Inline></article>)}{!periodTasks.length && <EmptyState icon="list" title="No hay tareas para este período" description="Creá una tarea o cambiá el filtro temporal." />}</Stack></Stack></ContentPanel><Stack gap="md"><ContentPanel icon="pie" title="Estado de la campaña" subtitle="Avance general por frentes y equipo."><div className="sp-home__status"><div className="sp-home__donut"><Chart type="donut" width={142} height={142} options={donut.options} series={donut.series} /><strong>{overallProgress}%</strong><small>avance general</small></div><Stack gap="xs" className="sp-home__area-progress">{progressRows.slice(0, 5).map(({ area, progress }) => <button key={area.id} type="button" onClick={() => chooseArea(area.id)}><span style={{ background: area.color }} /><b>{area.name}</b><em>{progress}%</em></button>)}</Stack></div></ContentPanel><ContentPanel icon="cal" title="Próximas entregas" subtitle="Fechas que requieren seguimiento."><Stack gap="xs">{upcoming.map((task) => <button type="button" className="sp-home__deadline" key={task.id} onClick={() => chooseArea(task.areaId)}><strong>{formatDay(task.dueDate)}</strong><Stack gap="xs"><b>{task.title}</b><small>{areas.find((area) => area.id === task.areaId)?.name || 'Sin área'}</small></Stack></button>)}{!upcoming.length && <EmptyState icon="cal" title="No hay entregas próximas" description="Las tareas con fecha límite aparecerán acá." />}</Stack></ContentPanel></Stack></div>
    <ContentPanel icon="target" title="Cuartel de campaña" subtitle="Gestioná el trabajo por área y mantené el foco en lo importante."><div className="sp-home__areas">{progressRows.map(({ area, total }) => <article className="sp-home__area" key={area.id} style={{ '--sp-color': area.color } as CSSProperties}><Stack gap="sm"><button type="button" className="sp-home__area-title" onClick={() => chooseArea(area.id)}><span /><Stack gap="xs"><strong>{area.name}</strong><small>{area.description || 'Frente estratégico de campaña'}</small></Stack><b>{total}</b></button><Stack gap="xs">{tasks.filter((task) => task.areaId === area.id).slice(0, 3).map((task) => <button type="button" className="sp-home__area-task" key={task.id} onClick={() => chooseArea(area.id)}><i className={task.status === 'completada' ? 'is-done' : ''} />{task.title}<small>{formatDay(task.dueDate)}</small></button>)}{!tasks.some((task) => task.areaId === area.id) && <small className="text-muted">Sin tareas todavía.</small>}</Stack>{canManage && <button type="button" className="sp-home__new-task" onClick={() => openTask(area.id)}>+ Nueva tarea</button>}</Stack></article>)}</div></ContentPanel>
    <div className="sp-home__operations-grid"><ContentPanel icon="trend" title="Control de tope legal y presupuesto" subtitle="Seguimiento financiero en tiempo real." headerAction={canManage ? <Link className="btn btn-sm btn-outline-primary" to="/smartplanner/settings">Definir tope</Link> : undefined}><Stack gap="md"><Inline gap="md" className="sp-home__budget-values"><Stack gap="xs"><small>Gasto acumulado</small><strong>${Number(financeQ.data?.spent ?? 0).toLocaleString('es-AR')}</strong></Stack><Stack gap="xs"><small>Tope legal</small><strong>{financeQ.data?.legalSpendingLimit ? `$${financeQ.data.legalSpendingLimit.toLocaleString('es-AR')}` : 'Sin definir'}</strong></Stack><Stack gap="xs"><small>Disponible</small><strong>{financeQ.data?.remaining === null || financeQ.data?.remaining === undefined ? '—' : `$${financeQ.data.remaining.toLocaleString('es-AR')}`}</strong></Stack></Inline><div className="sp-home__budget-progress"><span style={{ width: `${financialProgress}%` }} /></div><small className={financeQ.data?.exceeded ? 'text-danger' : 'text-success'}>{financeQ.data?.exceeded ? 'El gasto supera el tope legal.' : 'El gasto permanece dentro del límite legal.'}</small></Stack></ContentPanel><ContentPanel icon="clock" title="Jornada electoral" subtitle="Accesos directos para el operativo crítico del Día D." headerAction={<Link className="btn btn-danger btn-sm" to="/smartplanner/election-day">Ver Panel del Día D</Link>}><Inline gap="sm" wrap><Link className="btn btn-sm btn-outline-danger" to="/smartplanner/war-room">War Room</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/promises">Propuestas</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/tickets">Tickets</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/comunicaciones">Chat</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/reports">Reportes</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/staff">Personal</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/settings">Configuración</Link></Inline></ContentPanel></div>
    <div className="sp-home__bottom-grid"><ContentPanel icon="target" title="Centro de Comunicaciones" subtitle="Canales de coordinación por área y equipos."><Stack gap="sm"><small className="text-muted">Abrí el centro para conversar, compartir imágenes y documentos con tu equipo.</small><Link className="btn btn-outline-primary btn-sm" to={selectedAreaId ? `/smartplanner/comunicaciones?area=${selectedAreaId}` : '/smartplanner/comunicaciones'}>Abrir comunicaciones</Link></Stack></ContentPanel><ContentPanel icon="users" title="Roles SmartPlanner" subtitle="Los responsables gestionan las tareas de su frente." headerAction={<Link className="btn btn-sm btn-outline-primary" to="/smartplanner/settings">Gestionar roles</Link>}><Stack gap="xs">{featuredMembers.map((member) => <Inline key={member.uid} gap="sm" className="sp-role"><span className="sp-avatar">{(member.displayName || member.email).slice(0, 2).toUpperCase()}</span><Stack gap="xs" className="sp-role__copy"><strong>{member.displayName || member.email}</strong><small>{member.smartPlannerRole || 'Miembro'}</small></Stack><SelectControl ariaLabel={`Rol de ${member.displayName || member.email}`} label={member.smartPlannerRole || 'Miembro'} value={member.smartPlannerRole || 'miembro'} disabled={!['cliente', 'admin'].includes(role)} onChange={(next) => void changeMemberRole(member.uid, next)} options={[{ value: 'miembro', label: 'Miembro' }, { value: 'pm', label: 'Project Manager' }, { value: 'contador', label: 'Contador' }]} /></Inline>)}{!members.length && <EmptyState icon="users" title="Sin equipo vinculado" description="Vinculá miembros a la campaña para asignarles responsabilidades." />}</Stack></ContentPanel></div>
    <div id="smartplanner-board"><ContentPanel icon="bars" title={selectedArea ? `Tablero de ${selectedArea.name}` : 'Tablero del cuartel'} subtitle="Arrastrá cada tarea a su etapa de ejecución o usá el selector accesible."><DndContext sensors={sensors} onDragEnd={handleDragEnd}><div className="sp-kanban">{columns.map((status) => <KanbanColumn key={status} status={status} tasks={selectedTasks.filter((task) => task.status === status)} memberName={memberName} onMove={(task, nextStatus) => void moveTask(task, nextStatus)} />)}</div></DndContext></ContentPanel></div>
    <Modal show={showTaskModal} onHide={() => setShowTaskModal(false)}><form onSubmit={saveTask}><Modal.Header closeButton><Modal.Title>Nueva tarea estratégica</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Título de tarea" className="form-control" placeholder="Definí el resultado a lograr…" value={taskForm.title} onChange={(event) => setTaskForm({ ...taskForm, title: event.target.value })} required /><textarea aria-label="Descripción de tarea" className="form-control" placeholder="Contexto y criterio de éxito" value={taskForm.description} onChange={(event) => setTaskForm({ ...taskForm, description: event.target.value })} /><input aria-label="Costo estimado de tarea" type="number" min="0" className="form-control" placeholder="Costo estimado" value={taskForm.cost} onChange={(event) => setTaskForm({ ...taskForm, cost: Number(event.target.value) })} /><SelectControl ariaLabel="Área" label="Área estratégica" value={taskForm.areaId || selectedAreaId} onChange={(next) => setTaskForm({ ...taskForm, areaId: next })} options={areas.map((area) => ({ value: area.id, label: area.name }))} /><SelectControl ariaLabel="Responsable" label="Asignar responsable" value={taskForm.assignedTo} onChange={(next) => setTaskForm({ ...taskForm, assignedTo: next })} options={members.map((member) => ({ value: member.uid, label: member.displayName || member.email }))} /><Inline gap="md"><input aria-label="Inicio" type="date" className="form-control" value={taskForm.startDate} onChange={(event) => setTaskForm({ ...taskForm, startDate: event.target.value })} /><input aria-label="Fecha límite" type="date" className="form-control" value={taskForm.dueDate} onChange={(event) => setTaskForm({ ...taskForm, dueDate: event.target.value })} /></Inline><SelectControl ariaLabel="Prioridad" label="Prioridad media" value={taskForm.priority} onChange={(next) => setTaskForm({ ...taskForm, priority: next as NewTask['priority'] })} options={[{ value: 'baja', label: 'Baja' }, { value: 'media', label: 'Media' }, { value: 'alta', label: 'Alta' }]} /></Stack></Modal.Body><Modal.Footer><PrimaryButton icon="plus" type="submit">Crear tarea</PrimaryButton></Modal.Footer></form></Modal>
  </div>{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}</Stack></PageContainer>;
}
