import { CSSProperties, FormEvent, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import Chart from 'react-apexcharts';
import { Modal } from 'react-bootstrap';
import { useAuth } from '../../../context/AuthContext';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import KpiCard from '../../../components/Shared/KpiCard';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import SelectControl from '../../../components/Shared/SelectControl';
import PrimaryButton from '../../../components/Shared/PrimaryButton';
import { Toast } from '../../../components/Toast';

type Status = 'por_hacer' | 'en_progreso' | 'en_revision' | 'completada';
type Area = { id: string; name: string; description: string; color: string };
type Task = { id: string; displayId?: string; title: string; description: string; areaId: string; assignedTo: string; status: Status; priority: 'baja' | 'media' | 'alta'; startDate: string; dueDate: string; cost: number };
type Member = { uid: string; displayName?: string; email: string; smartPlannerRole?: 'contador' | 'pm' | 'miembro' };
type NewTask = Omit<Task, 'id' | 'status'>;
type Period = 'hoy' | 'semana' | 'mes' | 'todas';

const priorityLabels = { baja: 'Baja', media: 'Media', alta: 'Alta' };
const smartPlannerRoleLabels = { miembro: 'Miembro', pm: 'Project Manager', contador: 'Contador' } as const;
const smartPlannerRoleLabel = (role?: Member['smartPlannerRole']) => smartPlannerRoleLabels[role ?? 'miembro'];
const emptyTask = (): NewTask => ({ title: '', description: '', areaId: '', assignedTo: '', priority: 'media', startDate: new Date().toISOString().slice(0, 10), dueDate: new Date().toISOString().slice(0, 10), cost: 0 });
const parseDay = (date: string) => date ? new Date(`${date}T12:00:00`) : null;
const formatDay = (date: string) => parseDay(date)?.toLocaleDateString('es-AR', { day: '2-digit', month: 'short' }) ?? 'Sin fecha';
const canonicalAreaNames = ['estrategia', 'comunicacion', 'avanzada y logistica', 'finanzas', 'juridico'];
const normalizedName = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const sortAreas = (items: Area[]) => [...items].sort((left, right) => {
  const leftOrder = canonicalAreaNames.indexOf(normalizedName(left.name)); const rightOrder = canonicalAreaNames.indexOf(normalizedName(right.name));
  return (leftOrder < 0 ? 1000 : leftOrder) - (rightOrder < 0 ? 1000 : rightOrder) || left.name.localeCompare(right.name);
});

export default function SmartPlanner() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { enabledAddons, role } = useActiveCampaign();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams(); const [period, setPeriod] = useState<Period>('todas'); const [showTaskModal, setShowTaskModal] = useState(false); const [showAreaModal, setShowAreaModal] = useState(false); const [newAreaName, setNewAreaName] = useState(''); const [taskForm, setTaskForm] = useState<NewTask>(emptyTask()); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
  const areasQ = useAuthenticatedQuery<Area[]>(user, base ? `${base}/areas` : null, [base]); const tasksQ = useAuthenticatedQuery<Task[]>(user, base ? `${base}/tasks` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const configQ = useAuthenticatedQuery<{ accent?: string }>(user, base ? `${base}/config` : null, [base]);
  const areas = sortAreas(areasQ.data ?? []); const tasks = tasksQ.data ?? []; const members = membersQ.data ?? []; const selectedAreaId = searchParams.get('area') || areas[0]?.id || ''; const canManage = true;
  const memberName = (uid: string) => members.find((member) => member.uid === uid)?.displayName || members.find((member) => member.uid === uid)?.email || 'Sin asignar';
  const reload = () => Promise.all([areasQ.reload(), tasksQ.reload(), membersQ.reload()]);
  const chooseArea = (areaId: string) => navigate(`/smartplanner/backlog?area=${encodeURIComponent(areaId)}`);
  const activeTasks = tasks.filter((task) => task.status !== 'completada');
  const progressRows = useMemo(() => areas.map((area) => { const areaTasks = tasks.filter((task) => task.areaId === area.id); const done = areaTasks.filter((task) => task.status === 'completada').length; return { area, total: areaTasks.length, done, progress: areaTasks.length ? Math.round((done / areaTasks.length) * 100) : 0 }; }), [areas, tasks]);
  const overallProgress = tasks.length ? Math.round((tasks.filter((task) => task.status === 'completada').length / tasks.length) * 100) : 0;
  const periodTasks = useMemo(() => { const now = new Date(); now.setHours(0, 0, 0, 0); const endOfWeek = new Date(now); endOfWeek.setDate(now.getDate() + ((7 - now.getDay()) % 7)); const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0); return activeTasks.filter((task) => { const due = parseDay(task.dueDate); if (!due || period === 'todas') return true; if (period === 'hoy') return due.toDateString() === now.toDateString(); if (period === 'semana') return due >= now && due <= endOfWeek; return due >= now && due <= endOfMonth; }).sort((left, right) => (left.dueDate || '9999').localeCompare(right.dueDate || '9999')); }, [activeTasks, period]);
  const upcoming = [...activeTasks].filter((task) => task.dueDate).sort((left, right) => left.dueDate.localeCompare(right.dueDate)).slice(0, 4); const featuredMembers = [...members].sort((left, right) => Number(right.uid === user?.uid) - Number(left.uid === user?.uid)).slice(0, 5);
  const donut = { series: [overallProgress, Math.max(0, 100 - overallProgress)], options: { chart: { type: 'donut' as const, sparkline: { enabled: true } }, colors: ['#2f6fe4', '#e9f0fb'], stroke: { width: 0 }, dataLabels: { enabled: false }, tooltip: { enabled: false }, legend: { show: false }, plotOptions: { pie: { donut: { size: '72%' } } } } };
  const openTask = (areaId = selectedAreaId) => navigate(`/smartplanner/backlog?new=1&area=${encodeURIComponent(areaId)}`);
  async function saveTask(event: FormEvent) { event.preventDefault(); if (!user || !base || !taskForm.title.trim() || !(taskForm.areaId || selectedAreaId)) return; try { await authenticatedFetch(user, `${base}/tasks`, { method: 'POST', body: JSON.stringify({ ...taskForm, areaId: taskForm.areaId || selectedAreaId, status: 'por_hacer' }) }); setShowTaskModal(false); setTaskForm(emptyTask()); setNotice({ message: 'Tarea creada en el cuartel.', variant: 'success' }); await reload(); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos crear la tarea.', variant: 'danger' }); } }
  async function saveArea(event: FormEvent) { event.preventDefault(); if (!user || !base || !newAreaName.trim()) return; try { await authenticatedFetch(user, `${base}/areas`, { method: 'POST', body: JSON.stringify({ name: newAreaName.trim(), description: 'Área personalizada', color: '#0060F0' }) }); setShowAreaModal(false); setNewAreaName(''); setNotice({ message: 'Área creada en el cuartel.', variant: 'success' }); await areasQ.reload(); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos crear el área.', variant: 'danger' }); } }
  async function changeMemberRole(memberId: string, smartPlannerRole: string) { if (!user || !base) return; try { await authenticatedFetch(user, `${base}/members/${memberId}/role`, { method: 'PUT', body: JSON.stringify({ smartPlannerRole }) }); await membersQ.reload(); setNotice({ message: 'Rol actualizado.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos actualizar el rol.', variant: 'danger' }); } }

  if (!enabledAddons.smartPlanner) return <PageContainer><HeroBanner icon="settings" title="SmartPlanner" subtitle="Gestión profesional de proyectos para tu campaña." /><ContentPanel icon="settings" title="Add-on no habilitado"><EmptyState icon="award" title="Este addon no está habilitado en tu plan" description="Pedile a un administrador global que habilite SmartPlanner para esta organización." /></ContentPanel></PageContainer>;
  return <PageContainer><Stack gap="lg"><div data-smartplanner="workspace" className="sp-home" style={{ '--smartplanner-accent': configQ.data?.accent || '#0060F0' } as CSSProperties}>
    <HeroBanner icon="target" eyebrow="CUARTEL DE CAMPAÑA" title="SmartPlanner" subtitle="Convertí la estrategia de campaña en acción." subtitleDetail="Planificá, asigná, coordiná y hacé seguimiento de cada frente desde un solo lugar." ctaLabel={canManage ? 'Nuevo PBI' : undefined} onCtaClick={() => openTask()} tags={[{ icon: 'users', label: 'Equipo conectado' }, { icon: 'check-circle', label: 'Flujo profesional' }]} />
    <div className="cd-dashboard__kpis sp-kpis"><KpiCard icon="list" value={activeTasks.length} label="PBIs activos" caption="En el cuartel" progress={tasks.length ? Math.round((activeTasks.length / tasks.length) * 100) : 0} /><KpiCard icon="bars" iconColor="purple" value={tasks.filter((task) => task.status === 'en_progreso').length} label="En ejecución" caption="Trabajo en marcha" /><KpiCard icon="check" iconColor="green" value={tasks.filter((task) => task.status === 'completada').length} label="Completados" caption="Resultados cerrados" progress={overallProgress} /><KpiCard icon="clock" iconColor="red" value={tasks.filter((task) => task.priority === 'alta' && task.status !== 'completada').length} label="Alta prioridad" caption="Foco inmediato" /></div>
    <div className="sp-home__top-grid"><ContentPanel icon="list" title="PBIs prioritarios" subtitle="Priorizá lo que mueve la campaña hoy." headerAction={<Link className="btn btn-sm btn-outline-primary" to={selectedAreaId ? `/smartplanner/backlog?area=${selectedAreaId}` : '/smartplanner/backlog'}>Ver Backlog</Link>}><Stack gap="sm"><Inline gap="xs" className="sp-home__filters">{([{ id: 'hoy', label: 'Hoy' }, { id: 'semana', label: 'Esta semana' }, { id: 'mes', label: 'Este mes' }, { id: 'todas', label: 'Todas' }] as { id: Period; label: string }[]).map((item) => <button key={item.id} type="button" className={`sp-tab ${period === item.id ? 'is-active' : ''}`} onClick={() => setPeriod(item.id)}>{item.label}</button>)}</Inline><Stack gap="xs">{periodTasks.slice(0, 5).map((task) => <Link className="sp-home__task" data-priority-pbi={task.id} key={task.id} to={`/smartplanner/pbi/${task.id}`} aria-label={`Abrir ${task.displayId ?? 'PBI'}: ${task.title}`}><Inline gap="sm"><span className={`sp-home__priority ${task.priority}`} /><Stack gap="xs" className="sp-home__task-copy"><strong>{task.title}</strong><small>{areas.find((area) => area.id === task.areaId)?.name || 'Sin área'} · {formatDay(task.dueDate)} · {memberName(task.assignedTo)}</small></Stack><span className={`sp-home__task-status ${task.priority}`}>{priorityLabels[task.priority]}</span></Inline></Link>)}{!periodTasks.length && <EmptyState icon="list" title="No hay PBIs para este período" description="Creá un PBI o cambiá el filtro temporal." />}</Stack></Stack></ContentPanel><Stack gap="md"><ContentPanel icon="pie" title="Estado de la campaña" subtitle="Avance general por frentes y equipo."><div className="sp-home__status"><div className="sp-home__donut"><Chart type="donut" width={142} height={142} options={donut.options} series={donut.series} /><strong>{overallProgress}%</strong><small>avance general</small></div><Stack gap="xs" className="sp-home__area-progress">{progressRows.slice(0, 5).map(({ area, progress }) => <button key={area.id} type="button" onClick={() => chooseArea(area.id)}><span style={{ background: area.color }} /><b>{area.name}</b><em>{progress}%</em></button>)}</Stack></div></ContentPanel><ContentPanel icon="cal" title="Próximas entregas" subtitle="Fechas que requieren seguimiento."><Stack gap="xs">{upcoming.map((task) => <button type="button" className="sp-home__deadline" key={task.id} onClick={() => chooseArea(task.areaId)}><strong>{formatDay(task.dueDate)}</strong><Stack gap="xs"><b>{task.title}</b><small>{areas.find((area) => area.id === task.areaId)?.name || 'Sin área'}</small></Stack></button>)}{!upcoming.length && <EmptyState icon="cal" title="No hay entregas próximas" description="Los PBIs con fecha límite aparecerán acá." />}</Stack></ContentPanel></Stack></div>
    <ContentPanel icon="target" title="Cuartel de campaña" subtitle="Resumen de PBIs por área." headerAction={<Inline gap="sm"><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/backlog">Ver Backlog completo</Link>{canManage && <button type="button" className="btn btn-sm btn-primary" onClick={() => setShowAreaModal(true)}>+ Nueva área</button>}</Inline>}><div className="sp-home__areas">{progressRows.map(({ area, total }) => <article className="sp-home__area" key={area.id} style={{ '--sp-color': area.color } as CSSProperties}><Stack gap="sm"><button type="button" className="sp-home__area-title" onClick={() => chooseArea(area.id)}><span /><Stack gap="xs"><strong>{area.name}</strong><small>{area.description || 'Frente estratégico de campaña'}</small></Stack><b>{total}</b></button><Stack gap="xs">{tasks.filter((task) => task.areaId === area.id).slice(0, 3).map((task) => <button type="button" className="sp-home__area-task" key={task.id} onClick={() => chooseArea(area.id)}><i className={task.status === 'completada' ? 'is-done' : ''} />{task.title}<small>{formatDay(task.dueDate)}</small></button>)}{!tasks.some((task) => task.areaId === area.id) && <small className="text-muted">Sin PBIs todavía.</small>}</Stack>{canManage && <button type="button" className="sp-home__new-task" onClick={() => openTask(area.id)}>+ Nuevo PBI</button>}</Stack></article>)}</div></ContentPanel>
    <div className="sp-home__operations-grid"><ContentPanel icon="clock" title="Jornada electoral" subtitle="Accesos directos para el operativo crítico del Día D." headerAction={<Link className="btn btn-danger btn-sm" to="/smartplanner/election-day">Ver Panel del Día D</Link>}><Inline gap="sm" wrap><Link className="btn btn-sm btn-outline-danger" to="/smartplanner/war-room">War Room</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/promises">Propuestas</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/tickets">Tickets</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/comunicaciones">Chat</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/reports">Reportes</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/staff">Personal</Link><Link className="btn btn-sm btn-outline-primary" to="/smartplanner/settings">Configuración</Link></Inline></ContentPanel></div>
    <div className="sp-home__bottom-grid"><ContentPanel icon="target" title="Centro de Comunicaciones" subtitle="Canales de coordinación por área y equipos."><Stack gap="sm"><small className="text-muted">Abrí el centro para conversar, compartir imágenes y documentos con tu equipo.</small><Link className="btn btn-outline-primary btn-sm" to={selectedAreaId ? `/smartplanner/comunicaciones?area=${selectedAreaId}` : '/smartplanner/comunicaciones'}>Abrir comunicaciones</Link></Stack></ContentPanel><ContentPanel icon="users" title="Roles SmartPlanner" subtitle="Los responsables gestionan las tareas de su frente." headerAction={<Link className="btn btn-sm btn-outline-primary" to="/smartplanner/settings">Gestionar roles</Link>}><Stack gap="xs">{featuredMembers.map((member) => <Inline key={member.uid} gap="sm" className="sp-role"><span className="sp-avatar">{(member.displayName || member.email).slice(0, 2).toUpperCase()}</span><Stack gap="xs" className="sp-role__copy"><strong>{member.displayName || member.email}</strong><small>{smartPlannerRoleLabel(member.smartPlannerRole)}</small></Stack><SelectControl ariaLabel={`Rol de ${member.displayName || member.email}`} label={smartPlannerRoleLabel(member.smartPlannerRole)} value={member.smartPlannerRole || 'miembro'} disabled={!['cliente', 'admin'].includes(role)} onChange={(next) => void changeMemberRole(member.uid, next)} options={[{ value: 'miembro', label: 'Miembro' }, { value: 'pm', label: 'Project Manager' }, { value: 'contador', label: 'Contador' }]} /></Inline>)}{!members.length && <EmptyState icon="users" title="Sin equipo vinculado" description="Vinculá miembros a la campaña para asignarles responsabilidades." />}</Stack></ContentPanel></div>
    <Modal show={showTaskModal} onHide={() => setShowTaskModal(false)}><form onSubmit={saveTask}><Modal.Header closeButton><Modal.Title>Nueva tarea estratégica</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Título de tarea" className="form-control" placeholder="Definí el resultado a lograr…" value={taskForm.title} onChange={(event) => setTaskForm({ ...taskForm, title: event.target.value })} required /><textarea aria-label="Descripción de tarea" className="form-control" placeholder="Contexto y criterio de éxito" value={taskForm.description} onChange={(event) => setTaskForm({ ...taskForm, description: event.target.value })} /><input aria-label="Costo estimado de tarea" type="number" min="0" className="form-control" placeholder="Costo estimado" value={taskForm.cost} onChange={(event) => setTaskForm({ ...taskForm, cost: Number(event.target.value) })} /><SelectControl ariaLabel="Área" label="Área estratégica" value={taskForm.areaId || selectedAreaId} onChange={(next) => setTaskForm({ ...taskForm, areaId: next })} options={areas.map((area) => ({ value: area.id, label: area.name }))} /><SelectControl ariaLabel="Responsable" label="Asignar responsable" value={taskForm.assignedTo} onChange={(next) => setTaskForm({ ...taskForm, assignedTo: next })} options={members.map((member) => ({ value: member.uid, label: member.displayName || member.email }))} /><Inline gap="md"><input aria-label="Inicio" type="date" className="form-control" value={taskForm.startDate} onChange={(event) => setTaskForm({ ...taskForm, startDate: event.target.value })} /><input aria-label="Fecha límite" type="date" className="form-control" value={taskForm.dueDate} onChange={(event) => setTaskForm({ ...taskForm, dueDate: event.target.value })} /></Inline><SelectControl ariaLabel="Prioridad" label="Prioridad media" value={taskForm.priority} onChange={(next) => setTaskForm({ ...taskForm, priority: next as NewTask['priority'] })} options={[{ value: 'baja', label: 'Baja' }, { value: 'media', label: 'Media' }, { value: 'alta', label: 'Alta' }]} /></Stack></Modal.Body><Modal.Footer><PrimaryButton icon="plus" type="submit">Crear tarea</PrimaryButton></Modal.Footer></form></Modal><Modal show={showAreaModal} onHide={() => setShowAreaModal(false)}><form onSubmit={saveArea}><Modal.Header closeButton><Modal.Title>Nueva área</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><input aria-label="Nombre de nueva área" className="form-control" value={newAreaName} onChange={(event) => setNewAreaName(event.target.value)} placeholder="Ej. Movilización" required /></Stack></Modal.Body><Modal.Footer><PrimaryButton type="submit">Crear área</PrimaryButton></Modal.Footer></form></Modal>
  </div>{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}</Stack></PageContainer>;
}
