import { FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../../../context/AuthContext';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import PrimaryButton from '../../../components/Shared/PrimaryButton';

type Member = { uid: string; displayName?: string; email?: string };
type Leave = { startDate: string; endDate: string; type: string; status: string };
type StaffMember = { id: string; userId: string; position: string; salary?: number; startDate?: string; attendance?: { date: string; status: string }[]; leaves?: Leave[] };
const baseFor = (campaign: any) => campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
const today = () => new Date().toISOString().slice(0, 10);

export function Staff() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const base = baseFor(campaign);
  const staffQ = useAuthenticatedQuery<StaffMember[]>(user, base ? `${base}/staff` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]);
  const [form, setForm] = useState({ userId: '', position: '', salary: '', startDate: today() }); const [leaveFor, setLeaveFor] = useState<StaffMember | null>(null); const [leaveForm, setLeaveForm] = useState({ startDate: today(), endDate: today(), type: 'vacaciones' });
  async function add(event: FormEvent) { event.preventDefault(); if (!user || !base) return; await authenticatedFetch(user, `${base}/staff`, { method: 'POST', body: JSON.stringify({ ...form, salary: form.salary ? Number(form.salary) : null }) }); setForm({ userId: '', position: '', salary: '', startDate: today() }); await staffQ.reload(); }
  async function attendance(staff: StaffMember, status: string) { if (!user || !base) return; await authenticatedFetch(user, `${base}/staff/${staff.id}/attendance`, { method: 'PUT', body: JSON.stringify({ date: today(), status }) }); await staffQ.reload(); }
  async function saveLeave(event: FormEvent) { event.preventDefault(); if (!user || !base || !leaveFor) return; await authenticatedFetch(user, `${base}/staff/${leaveFor.id}/leaves`, { method: 'POST', body: JSON.stringify(leaveForm) }); setLeaveFor(null); await staffQ.reload(); }
  async function decide(staff: StaffMember, index: number, status: string) { if (!user || !base) return; await authenticatedFetch(user, `${base}/staff/${staff.id}/leaves`, { method: 'POST', body: JSON.stringify({ leaveIndex: index, status }) }); await staffQ.reload(); }
  return <PageContainer><Stack gap="lg"><HeroBanner icon="users" title="Personal" subtitle="Asistencia y licencias del equipo pago." />
    <ContentPanel icon="plus" title="Incorporar personal"><form onSubmit={add}><Inline gap="sm" wrap><select aria-label="Usuario del personal" className="form-select" value={form.userId} onChange={(event) => setForm({ ...form, userId: event.target.value })} required><option value="">Usuario</option>{(membersQ.data ?? []).map((member) => <option key={member.uid} value={member.uid}>{member.displayName || member.email}</option>)}</select><input aria-label="Cargo" className="form-control" value={form.position} onChange={(event) => setForm({ ...form, position: event.target.value })} placeholder="Cargo" required /><input aria-label="Salario opcional" className="form-control" type="number" min="0" value={form.salary} onChange={(event) => setForm({ ...form, salary: event.target.value })} placeholder="Salario opcional" /><input aria-label="Fecha de inicio" className="form-control" type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /><PrimaryButton type="submit">Agregar</PrimaryButton></Inline></form></ContentPanel>
    <ContentPanel icon="users" title="Equipo contratado"><Stack gap="sm">{(staffQ.data ?? []).map((staff) => { const name = (membersQ.data ?? []).find((member) => member.uid === staff.userId)?.displayName || staff.userId; const current = staff.attendance?.find((entry) => entry.date === today())?.status; return <article className="sp-project" key={staff.id}><Stack gap="sm"><Inline gap="sm" className="sp-project__row" wrap><Stack gap="xs"><strong>{name}</strong><small>{staff.position}{staff.salary ? ` · $${Number(staff.salary).toLocaleString('es-AR')}` : ''}</small><small>Hoy: {current || 'sin registrar'}</small></Stack><Inline gap="xs" wrap><button type="button" className="btn btn-outline-success" onClick={() => void attendance(staff, 'presente')}>Presente</button><button type="button" className="btn btn-outline-danger" onClick={() => void attendance(staff, 'ausente')}>Ausente</button><button type="button" className="btn btn-outline-warning" onClick={() => void attendance(staff, 'tarde')}>Tarde</button><button type="button" className="btn btn-outline-primary" onClick={() => setLeaveFor(staff)}>Solicitar licencia</button></Inline></Inline>{(staff.leaves ?? []).map((leave, index) => <Inline gap="xs" key={`${leave.startDate}-${index}`} wrap><small>{leave.type}: {leave.startDate} a {leave.endDate} · {leave.status}</small>{leave.status === 'pendiente' && <><button type="button" className="btn btn-sm btn-success" onClick={() => void decide(staff, index, 'aprobada')}>Aprobar</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => void decide(staff, index, 'rechazada')}>Rechazar</button></>}</Inline>)}</Stack></article>; })}{!(staffQ.data ?? []).length && <small className="text-muted">Todavía no incorporaste personal pago.</small>}</Stack></ContentPanel>
    {leaveFor && <ContentPanel icon="calendar" title={`Licencia de ${leaveFor.position}`}><form onSubmit={saveLeave}><Inline gap="sm" wrap><input aria-label="Inicio de licencia" className="form-control" type="date" value={leaveForm.startDate} onChange={(event) => setLeaveForm({ ...leaveForm, startDate: event.target.value })} required /><input aria-label="Fin de licencia" className="form-control" type="date" value={leaveForm.endDate} onChange={(event) => setLeaveForm({ ...leaveForm, endDate: event.target.value })} required /><select aria-label="Tipo de licencia" className="form-select" value={leaveForm.type} onChange={(event) => setLeaveForm({ ...leaveForm, type: event.target.value })}><option value="vacaciones">Vacaciones</option><option value="enfermedad">Enfermedad</option><option value="otro">Otro</option></select><PrimaryButton type="submit">Enviar solicitud</PrimaryButton><button type="button" className="btn btn-outline-secondary" onClick={() => setLeaveFor(null)}>Cancelar</button></Inline></form></ContentPanel>}
  </Stack></PageContainer>;
}

export function Settings() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const base = baseFor(campaign); const areasQ = useAuthenticatedQuery<any[]>(user, base ? `${base}/areas` : null, [base]); const configQ = useAuthenticatedQuery<any>(user, base ? `${base}/config` : null, [base]); const financeQ = useAuthenticatedQuery<any>(user, base ? `${base}/finance-overview` : null, [base]);
  const [accent, setAccent] = useState('#0060F0'); const [legalLimit, setLegalLimit] = useState(''); const [newArea, setNewArea] = useState('');
  useEffect(() => { if (configQ.data?.accent) setAccent(configQ.data.accent); }, [configQ.data?.accent]); useEffect(() => { if (financeQ.data?.legalSpendingLimit !== undefined) setLegalLimit(String(financeQ.data.legalSpendingLimit || '')); }, [financeQ.data?.legalSpendingLimit]);
  async function saveTheme() { if (!user || !base) return; await authenticatedFetch(user, `${base}/config`, { method: 'PUT', body: JSON.stringify({ accent }) }); document.documentElement.style.setProperty('--smartplanner-accent', accent); await configQ.reload(); }
  async function saveLimit() { if (!user || !base) return; await authenticatedFetch(user, `${base}/finance-overview/legal-limit`, { method: 'PUT', body: JSON.stringify({ legalSpendingLimit: Number(legalLimit) }) }); await financeQ.reload(); }
  async function addArea(event: FormEvent) { event.preventDefault(); if (!user || !base || !newArea.trim()) return; await authenticatedFetch(user, `${base}/areas`, { method: 'POST', body: JSON.stringify({ name: newArea.trim(), description: 'Área personalizada', color: accent }) }); setNewArea(''); await areasQ.reload(); }
  return <PageContainer><Stack gap="lg"><HeroBanner icon="settings" title="Configuración" subtitle="Personalizá áreas, color y límites de SmartPlanner." />
    <ContentPanel icon="settings" title="Tema"><Inline gap="sm" wrap><select aria-label="Color de acento" className="form-select" value={accent} onChange={(event) => setAccent(event.target.value)}><option value="#0060F0">Azul CloudSuite</option><option value="#7C3AED">Violeta</option><option value="#10B981">Verde</option><option value="#F97316">Naranja</option></select><PrimaryButton onClick={() => void saveTheme()}>Guardar tema</PrimaryButton></Inline></ContentPanel>
    <ContentPanel icon="trend" title="Límite legal de gasto"><Inline gap="sm" wrap><input aria-label="Límite legal de gasto" className="form-control" type="number" min="0" value={legalLimit} onChange={(event) => setLegalLimit(event.target.value)} placeholder="Monto máximo" /><PrimaryButton onClick={() => void saveLimit()}>Guardar límite</PrimaryButton></Inline></ContentPanel>
    <ContentPanel icon="target" title="Áreas del cuartel"><Stack gap="sm"><form onSubmit={addArea}><Inline gap="sm"><input aria-label="Nueva área" className="form-control" value={newArea} onChange={(event) => setNewArea(event.target.value)} placeholder="Nueva área personalizada" /><PrimaryButton type="submit">Agregar área</PrimaryButton></Inline></form>{(areasQ.data ?? []).map((area) => <Inline gap="sm" className="sp-project" key={area.id}><strong>{area.name}</strong><button type="button" className="btn btn-sm btn-outline-primary" onClick={async () => { const name = window.prompt('Nombre del área', area.name); if (name && user && base) { await authenticatedFetch(user, `${base}/areas/${area.id}`, { method: 'PUT', body: JSON.stringify({ ...area, name }) }); await areasQ.reload(); } }}>Renombrar</button></Inline>)}</Stack></ContentPanel>
  </Stack></PageContainer>;
}
