import { FormEvent, useEffect, useRef, useState } from 'react';
import { useAuth } from '../../../context/AuthContext';
import { useCampaign } from '../Organization/useCampaign';
import { useActiveCampaign } from '../../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import PageContainer from '../../../components/Shared/PageContainer';
import HeroBanner from '../../../components/Shared/HeroBanner';
import ContentPanel from '../../../components/Shared/ContentPanel';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import PrimaryButton from '../../../components/Shared/PrimaryButton';
import SelectControl from '../../../components/Shared/SelectControl';
import { loadGoogleMapsApi } from '../../../components/Shared/GoogleMapCanvas';

type Member = { uid: string; displayName?: string; email?: string };
type Leave = { startDate: string; endDate: string; type: string; status: string };
type StaffMember = { id: string; userId: string; position: string; salary?: number; startDate?: string; attendance?: { date: string; status: string }[]; leaves?: Leave[] };
type GlobalConfiguration = { partyName: string; partyAcronym: string; partyLogoUrl: string | null; address: string; lat: number | null; lng: number | null };
const baseFor = (campaign: any) => campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/smartplanner` : null;
const today = () => new Date().toISOString().slice(0, 10);

export function Staff() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const base = baseFor(campaign);
  const staffQ = useAuthenticatedQuery<StaffMember[]>(user, base ? `${base}/staff` : null, [base]); const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]);
  const [form, setForm] = useState({ userId: '', position: '', salary: '', startDate: today() }); const [leaveFor, setLeaveFor] = useState<StaffMember | null>(null); const [leaveForm, setLeaveForm] = useState({ startDate: today(), endDate: today(), type: 'vacaciones' });
  async function add(event: FormEvent) { event.preventDefault(); if (!user || !base) return; await authenticatedFetch(user, `${base}/staff`, { method: 'POST', body: JSON.stringify({ ...form, salary: form.salary ? Number(form.salary) : null }) }); setForm({ userId: '', position: '', salary: '', startDate: today() }); await staffQ.reload(); }
  async function attendance(staff: StaffMember, status: string) { if (!user || !base) return; await authenticatedFetch(user, `${base}/staff/${staff.id}/attendance`, { method: 'PUT', body: JSON.stringify({ date: today(), status }) }); await staffQ.reload(); }
  async function saveLeave(event: FormEvent) { event.preventDefault(); if (!user || !base || !leaveFor) return; await authenticatedFetch(user, `${base}/staff/${leaveFor.id}/leaves`, { method: 'POST', body: JSON.stringify(leaveForm) }); setLeaveFor(null); await staffQ.reload(); }
  async function decide(staff: StaffMember, index: number, status: string) { if (!user || !base) return; await authenticatedFetch(user, `${base}/staff/${staff.id}/leaves`, { method: 'POST', body: JSON.stringify({ leaveIndex: index, status }) }); await staffQ.reload(); }
  return <PageContainer><Stack gap="lg"><HeroBanner icon="users" title="Personal" subtitle="Asistencia y licencias del equipo pago." />
    <ContentPanel icon="plus" title="Incorporar personal"><form onSubmit={add}><Inline gap="sm" wrap><SelectControl ariaLabel="Usuario del personal" label="Usuario" value={form.userId} onChange={(userId) => setForm({ ...form, userId })} options={[{ value: '', label: 'Usuario', disabled: true }, ...(membersQ.data ?? []).map((member) => ({ value: member.uid, label: member.displayName || member.email || member.uid }))]} /><input aria-label="Cargo" className="form-control" value={form.position} onChange={(event) => setForm({ ...form, position: event.target.value })} placeholder="Cargo" required /><input aria-label="Salario opcional" className="form-control" type="number" min="0" value={form.salary} onChange={(event) => setForm({ ...form, salary: event.target.value })} placeholder="Salario opcional" /><input aria-label="Fecha de inicio" className="form-control" type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /><PrimaryButton type="submit">Agregar</PrimaryButton></Inline></form></ContentPanel>
    <ContentPanel icon="users" title="Equipo contratado"><Stack gap="sm">{(staffQ.data ?? []).map((staff) => { const name = (membersQ.data ?? []).find((member) => member.uid === staff.userId)?.displayName || staff.userId; const current = staff.attendance?.find((entry) => entry.date === today())?.status; return <article className="sp-project" key={staff.id}><Stack gap="sm"><Inline gap="sm" className="sp-project__row" wrap><Stack gap="xs"><strong>{name}</strong><small>{staff.position}{staff.salary ? ` · $${Number(staff.salary).toLocaleString('es-AR')}` : ''}</small><small>Hoy: {current || 'sin registrar'}</small></Stack><Inline gap="xs" wrap><button type="button" className="btn btn-outline-success" onClick={() => void attendance(staff, 'presente')}>Presente</button><button type="button" className="btn btn-outline-danger" onClick={() => void attendance(staff, 'ausente')}>Ausente</button><button type="button" className="btn btn-outline-warning" onClick={() => void attendance(staff, 'tarde')}>Tarde</button><button type="button" className="btn btn-outline-primary" onClick={() => setLeaveFor(staff)}>Solicitar licencia</button></Inline></Inline>{(staff.leaves ?? []).map((leave, index) => <Inline gap="xs" key={`${leave.startDate}-${index}`} wrap><small>{leave.type}: {leave.startDate} a {leave.endDate} · {leave.status}</small>{leave.status === 'pendiente' && <><button type="button" className="btn btn-sm btn-success" onClick={() => void decide(staff, index, 'aprobada')}>Aprobar</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={() => void decide(staff, index, 'rechazada')}>Rechazar</button></>}</Inline>)}</Stack></article>; })}{!(staffQ.data ?? []).length && <small className="text-muted">Todavía no incorporaste personal pago.</small>}</Stack></ContentPanel>
    {leaveFor && <ContentPanel icon="calendar" title={`Licencia de ${leaveFor.position}`}><form onSubmit={saveLeave}><Inline gap="sm" wrap><input aria-label="Inicio de licencia" className="form-control" type="date" value={leaveForm.startDate} onChange={(event) => setLeaveForm({ ...leaveForm, startDate: event.target.value })} required /><input aria-label="Fin de licencia" className="form-control" type="date" value={leaveForm.endDate} onChange={(event) => setLeaveForm({ ...leaveForm, endDate: event.target.value })} required /><SelectControl ariaLabel="Tipo de licencia" label="Vacaciones" value={leaveForm.type} onChange={(type) => setLeaveForm({ ...leaveForm, type })} options={[{ value: 'vacaciones', label: 'Vacaciones' }, { value: 'enfermedad', label: 'Enfermedad' }, { value: 'otro', label: 'Otro' }]} /><PrimaryButton type="submit">Enviar solicitud</PrimaryButton><button type="button" className="btn btn-outline-secondary" onClick={() => setLeaveFor(null)}>Cancelar</button></Inline></form></ContentPanel>}
  </Stack></PageContainer>;
}

export function Settings() {
  const { user } = useAuth(); const { campaign } = useCampaign(); const { organizationId } = useActiveCampaign(); const base = baseFor(campaign); const areasQ = useAuthenticatedQuery<any[]>(user, base ? `${base}/areas` : null, [base]); const configQ = useAuthenticatedQuery<any>(user, base ? `${base}/config` : null, [base]); const financeQ = useAuthenticatedQuery<any>(user, base ? `${base}/finance-overview` : null, [base]); const globalPath = organizationId ? `/api/organizations/${organizationId}/global-configuration` : null; const globalQ = useAuthenticatedQuery<GlobalConfiguration>(user, globalPath, [globalPath]);
  const [accent, setAccent] = useState('#0060F0'); const [legalLimit, setLegalLimit] = useState(''); const [newArea, setNewArea] = useState(''); const [global, setGlobal] = useState<GlobalConfiguration>({ partyName: '', partyAcronym: '', partyLogoUrl: null, address: '', lat: null, lng: null }); const [globalNotice, setGlobalNotice] = useState(''); const [placesNotice, setPlacesNotice] = useState(''); const addressInput = useRef<HTMLInputElement>(null);
  useEffect(() => { if (configQ.data?.accent) setAccent(configQ.data.accent); }, [configQ.data?.accent]); useEffect(() => { if (financeQ.data?.legalSpendingLimit !== undefined) setLegalLimit(String(financeQ.data.legalSpendingLimit || '')); }, [financeQ.data?.legalSpendingLimit]);
  useEffect(() => { if (globalQ.data) setGlobal(globalQ.data); }, [globalQ.data]);
  useEffect(() => { if (!globalPath) return; let listener: any; let cancelled = false; const frame = window.requestAnimationFrame(() => { void loadGoogleMapsApi().then((maps) => { if (cancelled || !addressInput.current || !maps?.places?.Autocomplete) return; const autocomplete = new maps.places.Autocomplete(addressInput.current, { componentRestrictions: { country: 'ar' }, fields: ['formatted_address', 'geometry'], types: ['address'] }); listener = autocomplete.addListener('place_changed', () => { const place = autocomplete.getPlace(); const location = place?.geometry?.location; if (!place?.formatted_address || !location) { setPlacesNotice('Elegí una sugerencia válida de Google Maps para ubicar el pin.'); return; } setGlobal((current) => ({ ...current, address: place.formatted_address, lat: location.lat(), lng: location.lng() })); setPlacesNotice('Dirección verificada para el globo.'); }); }).catch(() => { if (!cancelled) setPlacesNotice('Google Places no está disponible ahora. Podés guardar la dirección y seleccionar su ubicación más tarde.'); }); }); return () => { cancelled = true; window.cancelAnimationFrame(frame); listener?.remove?.(); }; }, [globalPath]);
  async function saveTheme() { if (!user || !base) return; await authenticatedFetch(user, `${base}/config`, { method: 'PUT', body: JSON.stringify({ accent }) }); document.documentElement.style.setProperty('--smartplanner-accent', accent); await configQ.reload(); }
  async function saveLimit() { if (!user || !base) return; await authenticatedFetch(user, `${base}/finance-overview/legal-limit`, { method: 'PUT', body: JSON.stringify({ legalSpendingLimit: Number(legalLimit) }) }); await financeQ.reload(); }
  async function addArea(event: FormEvent) { event.preventDefault(); if (!user || !base || !newArea.trim()) return; await authenticatedFetch(user, `${base}/areas`, { method: 'POST', body: JSON.stringify({ name: newArea.trim(), description: 'Área personalizada', color: accent }) }); setNewArea(''); await areasQ.reload(); }
  async function saveGlobal(event: FormEvent) { event.preventDefault(); if (!user || !globalPath) return; setGlobalNotice(''); try { const saved = await authenticatedFetch<GlobalConfiguration>(user, globalPath, { method: 'PUT', body: JSON.stringify(global) }); setGlobal(saved); setGlobalNotice('Configuración global guardada.'); await globalQ.reload(); } catch (error) { setGlobalNotice(error instanceof Error ? error.message : 'No pudimos guardar la configuración global.'); } }
  async function uploadLogo(logo?: File) { if (!logo || !user || !globalPath) return; setGlobalNotice(''); try { const body = new FormData(); body.set('logo', logo); const saved = await authenticatedFetch<{ partyLogoUrl: string }>(user, `${globalPath}/party-logo`, { method: 'POST', body }); setGlobal((current) => ({ ...current, partyLogoUrl: saved.partyLogoUrl })); setGlobalNotice('Logo del partido actualizado.'); await globalQ.reload(); } catch (error) { setGlobalNotice(error instanceof Error ? error.message : 'No pudimos subir el logo.'); } }
  return <PageContainer><Stack gap="lg"><HeroBanner icon="settings" title="Configuración" subtitle="Personalizá áreas, color y límites de SmartPlanner." />
    <ContentPanel icon="target" title="Configuración Global" subtitle="Identidad del partido y ubicación principal de la campaña."><form onSubmit={saveGlobal}><Stack gap="md">{globalNotice && <div className={globalNotice.includes('guardada') || globalNotice.includes('actualizado') ? 'alert alert-success mb-0' : 'alert alert-danger mb-0'} role="status">{globalNotice}</div>}<Inline gap="sm" wrap><label className="form-label mb-0 flex-grow-1">Partido político<input aria-label="Partido político" className="form-control mt-1" value={global.partyName} onChange={(event) => setGlobal((current) => ({ ...current, partyName: event.target.value }))} placeholder="Nombre del partido" maxLength={120} /></label><label className="form-label mb-0">Sigla<input aria-label="Sigla del partido" className="form-control mt-1" value={global.partyAcronym} onChange={(event) => setGlobal((current) => ({ ...current, partyAcronym: event.target.value }))} placeholder="Ej. PJ" maxLength={24} /></label></Inline><Inline gap="sm" wrap><label className="form-label mb-0 flex-grow-1">Dirección principal<input ref={addressInput} aria-label="Dirección principal" className="form-control mt-1" value={global.address} onChange={(event) => { setGlobal((current) => ({ ...current, address: event.target.value, lat: null, lng: null })); setPlacesNotice('Elegí una sugerencia de Google Maps para fijar la ubicación.'); }} placeholder="Escribí y elegí la dirección en Google Maps" /></label><label className="form-label mb-0">Latitud<input aria-label="Latitud del partido" className="form-control mt-1" type="number" step="any" value={global.lat ?? ''} onChange={(event) => setGlobal((current) => ({ ...current, lat: event.target.value ? Number(event.target.value) : null }))} /></label><label className="form-label mb-0">Longitud<input aria-label="Longitud del partido" className="form-control mt-1" type="number" step="any" value={global.lng ?? ''} onChange={(event) => setGlobal((current) => ({ ...current, lng: event.target.value ? Number(event.target.value) : null }))} /></label></Inline>{placesNotice && <small className="text-muted">{placesNotice}</small>}<Inline gap="sm" wrap><label className="btn btn-outline-primary mb-0">Subir logo del partido<input className="d-none" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event) => { const logo = event.currentTarget.files?.[0]; event.currentTarget.value = ''; void uploadLogo(logo); }} /></label>{global.partyLogoUrl && <img className="sp-global-config__logo" src={global.partyLogoUrl} alt="Logo actual del partido" />}<PrimaryButton type="submit">Guardar configuración global</PrimaryButton></Inline></Stack></form></ContentPanel>
    <ContentPanel icon="settings" title="Tema"><Inline gap="sm" wrap><SelectControl ariaLabel="Color de acento" label="Azul CloudSuite" value={accent} onChange={setAccent} options={[{ value: '#0060F0', label: 'Azul CloudSuite' }, { value: '#7C3AED', label: 'Violeta' }, { value: '#10B981', label: 'Verde' }, { value: '#F97316', label: 'Naranja' }]} /><PrimaryButton onClick={() => void saveTheme()}>Guardar tema</PrimaryButton></Inline></ContentPanel>
    <ContentPanel icon="trend" title="Límite legal de gasto"><Inline gap="sm" wrap><input aria-label="Límite legal de gasto" className="form-control" type="number" min="0" value={legalLimit} onChange={(event) => setLegalLimit(event.target.value)} placeholder="Monto máximo" /><PrimaryButton onClick={() => void saveLimit()}>Guardar límite</PrimaryButton></Inline></ContentPanel>
    <ContentPanel icon="target" title="Áreas del cuartel"><Stack gap="sm"><form onSubmit={addArea}><Inline gap="sm"><input aria-label="Nueva área" className="form-control" value={newArea} onChange={(event) => setNewArea(event.target.value)} placeholder="Nueva área personalizada" /><PrimaryButton type="submit">Agregar área</PrimaryButton></Inline></form>{(areasQ.data ?? []).map((area) => <Inline gap="sm" className="sp-project" key={area.id}><strong>{area.name}</strong><button type="button" className="btn btn-sm btn-outline-primary" onClick={async () => { const name = window.prompt('Nombre del área', area.name); if (name && user && base) { await authenticatedFetch(user, `${base}/areas/${area.id}`, { method: 'PUT', body: JSON.stringify({ ...area, name }) }); await areasQ.reload(); } }}>Renombrar</button></Inline>)}</Stack></ContentPanel>
  </Stack></PageContainer>;
}
