import { useEffect, useMemo, useState } from 'react';
import { Button } from 'react-bootstrap';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch } from '../../../lib/api';
import { Toast } from '../../../components/Toast';

type AuditItem = { id: string; timestamp: string | null; userEmail: string; action: string; resource: string; resourceId?: string; changes?: { before?: unknown; after?: unknown } };
const labels: Record<string, string> = { INVITE_USER: 'Invitó usuario', CREATE_TEAM: 'Creó equipo', CREATE_FUNCTION: 'Creó función', IMPORT_VOTERS: 'Importó electores', START_VISIT: 'Registró visita', RECORD_FEEDBACK: 'Guardó respuestas', RECORD_CONVERSION: 'Registró conversión', CREATE_QUESTION_SET: 'Creó preguntas', UPDATE_QUESTION_SET: 'Editó preguntas' };
export default function AuditLog() { const { user, campaign } = useCampaign(); const [items, setItems] = useState<AuditItem[]>([]); const [query, setQuery] = useState(''); const [action, setAction] = useState(''); const [toast, setToast] = useState(''); useEffect(() => { if (!user || !campaign) return; void authenticatedFetch(user, `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/audit-log`).then(data => setItems(data as AuditItem[])).catch(error => setToast(error.message)); }, [user, campaign]); const filtered = useMemo(() => items.filter(item => (!action || item.action === action) && `${item.userEmail} ${item.resource} ${item.resourceId ?? ''}`.toLowerCase().includes(query.toLowerCase())), [items, action, query]); const exportCsv = () => { const rows = [['Fecha', 'Usuario', 'Acción', 'Recurso', 'Cambios'], ...filtered.map(item => [item.timestamp ?? '', item.userEmail, labels[item.action] ?? item.action, `${item.resource} ${item.resourceId ?? ''}`, JSON.stringify(item.changes ?? {})])]; const blob = new Blob([`\ufeff${rows.map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(';')).join('\n')}`], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'control-de-revision.csv'; link.click(); URL.revokeObjectURL(link.href); };
 return <section className="card"><div className="card-body"><div className="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 className="h4 mb-1">Control de Revisión</h1><p className="text-muted mb-0">Registro histórico, inmutable y de solo lectura.</p></div><Button variant="outline-primary" onClick={exportCsv}>Exportar a CSV</Button></div><div className="row g-2 mb-3"><div className="col-md-6"><input className="form-control" placeholder="Buscar por usuario o recurso" value={query} onChange={event => setQuery(event.target.value)} /></div><div className="col-md-3"><select className="form-select" value={action} onChange={event => setAction(event.target.value)}><option value="">Todas las acciones</option>{[...new Set(items.map(item => item.action))].map(value => <option key={value} value={value}>{labels[value] ?? value}</option>)}</select></div></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Recurso</th><th>Cambios</th></tr></thead><tbody>{filtered.slice(0, 50).map(item => <tr key={item.id}><td>{item.timestamp ? new Date(item.timestamp).toLocaleString('es-AR') : 'Procesando…'}</td><td>{item.userEmail || 'Sistema'}</td><td>{labels[item.action] ?? item.action}</td><td>{item.resource}{item.resourceId ? ` · ${item.resourceId}` : ''}</td><td><small className="text-muted text-break">{JSON.stringify(item.changes?.after ?? item.changes ?? {})}</small></td></tr>)}{filtered.length === 0 && <tr><td colSpan={5} className="text-muted">No hay eventos para los filtros seleccionados.</td></tr>}</tbody></table></div></div>{toast && <Toast message={toast} variant="danger" onClose={() => setToast('')} />}</section>; }
