import { useMemo, useState } from 'react';
import { useCampaign } from '../Organization/useCampaign';
import { useAuthenticatedQuery } from '../../../lib/api';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import SearchInput from '../../../components/Shared/SearchInput';
import SelectControl from '../../../components/Shared/SelectControl';
import StatCard from '../../../components/Shared/StatCard';
import PageContainer from '../../../components/Shared/PageContainer';

type AuditItem = { id: string; timestamp: string | null; userEmail: string; action: string; resource: string; resourceId?: string; changes?: { before?: unknown; after?: unknown } };
const labels: Record<string, string> = { INVITE_USER:'Invitó usuario', CREATE_TEAM:'Creó equipo', CREATE_FUNCTION:'Creó función', IMPORT_VOTERS:'Importó electores', START_VISIT:'Registró visita', RECORD_FEEDBACK:'Guardó respuestas', RECORD_CONVERSION:'Registró conversión', CREATE_QUESTION_SET:'Creó preguntas', UPDATE_QUESTION_SET:'Editó preguntas' };

export default function AuditLog() {
  const { user, campaign, error: campaignError, reload: reloadCampaign } = useCampaign(); const [query, setQuery] = useState(''); const [action, setAction] = useState('');
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/audit-log` : null;
  const auditQuery = useAuthenticatedQuery<AuditItem[]>(user, path, [campaign?.orgId, campaign?.campId]); const items = auditQuery.data ?? [];
  const filtered = useMemo(() => items.filter(item => (!action || item.action === action) && `${item.userEmail} ${item.resource} ${item.resourceId ?? ''}`.toLowerCase().includes(query.toLowerCase())), [items, action, query]);
  const exportCsv = () => { const rows = [['Fecha','Usuario','Acción','Recurso','Cambios'], ...filtered.map(item => [item.timestamp ?? '', item.userEmail, labels[item.action] ?? item.action, `${item.resource} ${item.resourceId ?? ''}`, JSON.stringify(item.changes ?? {})])]; const blob = new Blob([`\ufeff${rows.map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(';')).join('\n')}`], { type:'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'control-de-revision.csv'; link.click(); URL.revokeObjectURL(link.href); };
  const error = campaignError || auditQuery.error?.message;
  return <PageContainer><HeroBanner icon="activity" title="Control de Revisión" subtitle="Registro histórico, inmutable y de solo lectura." subtitleDetail="Conocé los cambios relevantes de tu campaña y mantené la trazabilidad del equipo." tags={[{ icon:'check-circle', label:'Registro protegido' }, { icon:'users', label:'Actividad del equipo' }]} ctaLabel="Exportar a CSV" ctaIcon="download" onCtaClick={exportCsv} />
    <div className="cd-dashboard__kpis"><StatCard icon="activity" value={items.length} label="Eventos registrados" caption="Actividad de campaña" /><StatCard icon="users" iconColor="green" value={new Set(items.map(item => item.userEmail)).size} label="Usuarios activos" caption="Con actividad registrada" /><StatCard icon="check-circle" iconColor="purple" value={new Set(items.map(item => item.action)).size} label="Tipos de acción" caption="Acciones auditadas" /><StatCard icon="calendar" iconColor="orange" value={items.filter(item => item.timestamp).length} label="Eventos fechados" caption="Con trazabilidad completa" /></div>
    <ContentPanel icon="activity" title="Historial de actividad" subtitle="Revisá cambios y acciones relevantes en tu campaña." headerAction={<SearchInput value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar usuario o recurso…" aria-label="Buscar en audit log" />}>{error ? <EmptyState icon="activity" title="No pudimos cargar el historial" description={error} ctaLabel="Reintentar" onCtaClick={() => void (campaignError ? reloadCampaign() : auditQuery.reload())} /> : auditQuery.loading ? <EmptyState icon="activity" title="Cargando actividad" description="Estamos consultando el registro de auditoría." /> : <><div className="cd-page-controls"><SelectControl ariaLabel="Filtrar acciones" label={labels[action] ?? 'Todas las acciones'} options={[{ value:'', label:'Todas las acciones' }, ...[...new Set(items.map(item => item.action))].map(value => ({ value, label:labels[value] ?? value }))]} value={action} onChange={setAction} /><span className="cd-panel-count">{filtered.length} eventos</span></div>{filtered.length ? <div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>FECHA</th><th>USUARIO</th><th>ACCIÓN</th><th>RECURSO</th><th>CAMBIOS</th></tr></thead><tbody>{filtered.slice(0,50).map(item => <tr key={item.id}><td>{item.timestamp ? new Date(item.timestamp).toLocaleString('es-AR') : 'Procesando…'}</td><td>{item.userEmail || 'Sistema'}</td><td><span className="cd-state-pill">{labels[item.action] ?? item.action}</span></td><td>{item.resource}{item.resourceId ? ` · ${item.resourceId}` : ''}</td><td><small>{JSON.stringify(item.changes?.after ?? item.changes ?? {})}</small></td></tr>)}</tbody></table></div> : <EmptyState icon="activity" title="No hay eventos para estos filtros" description="La actividad de tu campaña aparecerá aquí a medida que el equipo trabaje." />}</>}</ContentPanel>
  </PageContainer>;
}
