import { useEffect, useMemo, useState } from 'react';
import { Button } from 'react-bootstrap';
import { useNavigate, useParams } from 'react-router-dom';
import { authenticatedFetch } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import { Toast } from '../../../components/Toast';
import PageContainer from '../../../components/Shared/PageContainer';
type Question = { id: string; text: string; type: 'text' | 'radio' | 'checkbox'; isRequired: boolean; options: Array<{ label: string; value: string }> };
const fallback: Question[] = [
  { id: 'children', text: '¿Tiene hijos en edad escolar?', type: 'radio', isRequired: false, options: [{ label: 'Sí', value: 'si' }, { label: 'No', value: 'no' }] },
  { id: 'years', text: '¿Vive en la zona desde hace más de 5 años?', type: 'radio', isRequired: false, options: [{ label: 'Sí', value: 'si' }, { label: 'No', value: 'no' }] },
  { id: 'concern', text: '¿Cuál es tu principal preocupación?', type: 'text', isRequired: true, options: [] },
  { id: 'campaign', text: '¿Cómo se enteró de nuestra campaña?', type: 'text', isRequired: true, options: [] },
  { id: 'question', text: '¿Hay algo que te gustaría preguntar?', type: 'text', isRequired: true, options: [] }
];
export default function VisitScreen() { const { voterId = '' } = useParams(); const { user, campaign } = useCampaign(); const navigate = useNavigate(); const [visitId, setVisitId] = useState(''); const [step, setStep] = useState(0); const [questions, setQuestions] = useState<Question[]>(fallback); const [answers, setAnswers] = useState<Record<string, string | string[]>>({}); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [toast, setToast] = useState(''); const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/voters/${voterId}` : '';
  useEffect(() => { if (!user || !campaign) return; void authenticatedFetch(user, `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/question-sets/active`).then((data: { active: { questions: Question[] } | null }) => { if (data.active?.questions?.length) setQuestions(data.active.questions); }).catch(() => setQuestions(fallback)); }, [user, campaign]);
  useEffect(() => { if (!user || !base || visitId) return; void authenticatedFetch(user, `${base}/visits`, { method: 'POST' }).then((result: { visitId: string }) => { setVisitId(result.visitId); const saved = localStorage.getItem(`visit-${result.visitId}`); if (saved) { const data = JSON.parse(saved); setStep(data.step ?? 0); setAnswers(data.answers ?? {}); setNotes(data.notes ?? ''); } }).catch(caught => setError(caught.message)); }, [user, base, visitId]);
  useEffect(() => { if (visitId) localStorage.setItem(`visit-${visitId}`, JSON.stringify({ step, answers, notes })); }, [visitId, step, answers, notes]);
  const required = useMemo(() => questions.filter(question => question.isRequired), [questions]); const optional = useMemo(() => questions.filter(question => !question.isRequired), [questions]); const current = step === 0 ? optional : step === 1 ? required : [];
  const update = (question: Question, value: string) => { if (question.type === 'checkbox') { const previous = Array.isArray(answers[question.id]) ? answers[question.id] as string[] : []; setAnswers({ ...answers, [question.id]: previous.includes(value) ? previous.filter(item => item !== value) : [...previous, value] }); } else setAnswers({ ...answers, [question.id]: value }); };
  const save = async () => { if (user && visitId) await authenticatedFetch(user, `${base}/visits/${visitId}/feedback`, { method: 'POST', body: JSON.stringify({ responses: questions.map(question => ({ questionId: question.id, question: question.text, answer: answers[question.id] ?? null })), notes, timestamp: new Date().toISOString() }) }); };
  const next = async () => { if (step === 1 && required.some(question => !answers[question.id] || (Array.isArray(answers[question.id]) && !answers[question.id].length))) { setError('Respondé todas las preguntas obligatorias.'); return; } try { setError(''); await save(); setStep(currentStep => Math.min(3, currentStep + 1)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo guardar la visita.'); } };
  const decide = async (decision: string) => { try { await save(); await authenticatedFetch(user!, `${base}/visits/${visitId}/conversion`, { method: 'POST', body: JSON.stringify({ decision }) }); localStorage.removeItem(`visit-${visitId}`); setToast('Visita registrada ✓'); window.setTimeout(() => navigate('/electoral-conversion/voters'), 700); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No se pudo cerrar la visita.'); } };
  const renderQuestion = (question: Question) => <div className="mb-3" key={question.id}><label className="form-label">{question.text}{question.isRequired && ' *'}</label>{question.type === 'text' ? <input className="form-control" value={String(answers[question.id] ?? '')} onChange={event => update(question, event.target.value)} /> : question.options.map(option => <div className="form-check" key={option.value}><input className="form-check-input" id={`${question.id}-${option.value}`} type={question.type === 'radio' ? 'radio' : 'checkbox'} name={question.id} checked={question.type === 'checkbox' ? Array.isArray(answers[question.id]) && answers[question.id].includes(option.value) : answers[question.id] === option.value} onChange={() => update(question, option.value)} /><label className="form-check-label" htmlFor={`${question.id}-${option.value}`}>{option.label}</label></div>)}</div>;
  return <PageContainer><section className="card"><div className="card-body p-4"><h1 className="h4">Visita electoral</h1><p className="text-muted">Paso {step + 1} de 4 · Preguntas de campaña y guardado local.</p>{error && <div className="alert alert-danger">{error}</div>}{current.map(renderQuestion)}{step === 2 && <><label className="form-label">Observaciones de la visita</label><textarea className="form-control" rows={6} value={notes} onChange={event => setNotes(event.target.value)} /></>}{step === 3 && <><h2 className="h5">¿Vota al candidato?</h2><div className="d-flex gap-3 flex-wrap"><Button variant="success" size="lg" onClick={() => void decide('yes')}>SI</Button><Button variant="danger" size="lg" onClick={() => void decide('no')}>NO</Button><Button variant="warning" size="lg" onClick={() => void decide('undecided')}>INDECISO</Button></div></>}<div className="mt-4 d-flex justify-content-between">{step > 0 ? <Button variant="outline-secondary" onClick={() => setStep(step - 1)}>Anterior</Button> : <span />}{step < 3 && <Button onClick={() => void next()}>Siguiente</Button>}</div></div>{toast && <Toast message={toast} onClose={() => setToast('')} />}</section></PageContainer>; }
