import { useCallback, useEffect, useMemo, useState } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';
import { Button, Modal, Nav } from 'react-bootstrap';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch } from '../../../lib/api';
import { Toast } from '../../../components/Toast';
import HeroSection from '../../../components/Planning/HeroSection';
import StatCard from '../../../components/Planning/StatCard';
import DataPanel from '../../../components/Planning/DataPanel';
import ProgressIndicator from '../../../components/Planning/ProgressIndicator';
import Timeline from '../../../components/Planning/Timeline';
import MapContainer from '../../../components/Planning/MapContainer';
import RouteCard from '../../../components/Planning/RouteCard';
import BudgetBreakdown from '../../../components/Planning/BudgetBreakdown';
import AISuggestionCard from '../../../components/Planning/AISuggestionCard';

export type PlanningArea = 'calendar' | 'territory' | 'goals' | 'routes' | 'surveys' | 'budget' | 'advisor';
type Item = Record<string, any> & { id: string };
const meta: Record<PlanningArea, { title: string; description: string; icon: string; endpoint?: string; action: string }> = {
  calendar: { title: 'Calendario Electoral', description: 'Organizá hitos, veda y eventos de campaña.', icon: 'calendar-event', endpoint: 'calendar', action: 'Crear evento' },
  territory: { title: 'Mapa Territorial', description: 'Visualizá circuitos, zonas y cobertura territorial.', icon: 'map-2', action: 'Crear circuito' },
  goals: { title: 'Metas de Campaña', description: 'Definí qué querés lograr y seguí el progreso.', icon: 'target-arrow', endpoint: 'goals', action: 'Agregar meta' },
  routes: { title: 'Planificador de rutas', description: 'Distribuí recorridas y optimizá el trabajo territorial.', icon: 'route', endpoint: 'routes', action: 'Auto-distribuir' },
  surveys: { title: 'Encuestas', description: 'Creá cuestionarios para cada momento de la campaña.', icon: 'clipboard-text', endpoint: 'surveys', action: 'Nueva encuesta' },
  budget: { title: 'Presupuesto', description: 'Gestioná el gasto y los recursos de tu campaña.', icon: 'wallet', endpoint: 'budgets', action: 'Agregar línea' },
  advisor: { title: 'Asesor de Estrategia con IA', description: 'Obtené recomendaciones para tu campaña.', icon: 'sparkles', endpoint: 'ai-suggestions', action: 'Pedir análisis' }
};
const manager = (role?: string) => role === 'cliente' || role === 'admin';

export default function PlanningWorkspace({ area }: { area: PlanningArea }) {
  const { user, campaign, error } = useCampaign();
  const [items, setItems] = useState<Item[]>([]); const [circuits, setCircuits] = useState<Item[]>([]); const [zones, setZones] = useState<Item[]>([]);
  const [summary, setSummary] = useState<any>({}); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(true); const [show, setShow] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [surveyType, setSurveyType] = useState<'pre_campaign' | 'post_visit'>('pre_campaign');
  const base = campaign ? '/api/organizations/' + campaign.orgId + '/campaigns/' + campaign.campId : ''; const canManage = manager(campaign?.role);
  const load = useCallback(async () => { if (!user || !campaign) return; setBusy(true); try { if (area === 'territory') { const values = await Promise.all([authenticatedFetch(user, base + '/circuitos'), authenticatedFetch(user, base + '/zones')]); setCircuits(values[0] as Item[]); setZones(values[1] as Item[]); } else { const value = await authenticatedFetch(user, base + '/' + meta[area].endpoint); if (area === 'budget') { setSummary(value); setItems((value as any).items ?? []); } else setItems(value as Item[]); } } catch (e) { setNotice(e instanceof Error ? e.message : 'No pudimos cargar los datos.'); } finally { setBusy(false); } }, [area, base, campaign, user]);
  useEffect(() => { void load(); }, [load]);
  const api = async (path: string, method = 'POST', body?: object) => { if (!user) return; await authenticatedFetch(user, base + path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); };
  const action = async () => { try { if (area === 'routes') { await api('/routes/auto-distribute'); setNotice('Rutas distribuidas.'); } else if (area === 'advisor') { setBusy(true); await api('/ai-suggestions/request'); setNotice('Análisis generado.'); } else { setEditing(null); setShow(true); return; } void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudo completar la acción.'); } finally { setBusy(false); } };
  const feedback = async (id: string, value: string) => { try { await api('/ai-suggestions/' + id + '/feedback', 'PUT', { feedback: value }); setNotice(value === 'applied' ? 'Sugerencia aplicada.' : 'Sugerencia ignorada.'); void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudo actualizar.'); } };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const value = (key: string) => String(fd.get(key) ?? ''); let path = '/' + (meta[area].endpoint ?? ''); let data: any = {}; if (area === 'calendar') data = { title: value('title'), date: value('date'), type: value('type'), description: value('description') }; if (area === 'goals') data = { type: value('type'), target: Number(value('target')), description: value('description') }; if (area === 'surveys') data = { name: value('name'), type: value('type'), questions: value('questions').split('\n').filter(Boolean).map((text, index) => ({ id: 'q_' + index, text, type: 'text', isRequired: false })) }; if (area === 'budget') data = { category: value('category'), amount: Number(value('amount')), spent: Number(value('spent')), description: value('description') }; if (area === 'territory') { path = editing?.kind === 'zone' ? '/zones' : '/circuitos'; data = editing?.kind === 'zone' ? { name: value('name'), neighborhood: value('neighborhood'), circuitoId: value('circuitoId'), polygon: JSON.parse(value('polygon')) } : { name: value('name'), district: value('district'), schools: JSON.parse(value('schools') || '[]') }; } try { await api(path + (editing?.id ? '/' + editing.id : ''), editing?.id ? 'PUT' : 'POST', data); setShow(false); setNotice('Cambios guardados correctamente.'); void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudieron guardar los cambios.'); } };
  const percent = (goal: Item) => goal.target ? goal.progress / goal.target * 100 : 0; const average = Math.round(items.reduce((sum, item) => sum + percent(item), 0) / Math.max(1, items.length)); const events = useMemo(() => items.map(item => ({ id: item.id, title: item.title, start: item.date, backgroundColor: item.type === 'election' ? '#EF4444' : item.type === 'veda' ? '#F97316' : '#0060F0', borderColor: 'transparent', extendedProps: item })), [items]);
  if (error) return <div className="alert alert-warning">{error}</div>; if (busy && !items.length && area !== 'territory') return <div className="p-4 text-muted">Cargando planificación…</div>;
  const stats = area === 'goals' ? <><span>{items.length} metas activas</span><span>•</span><span>{average}% de progreso promedio</span></> : area === 'advisor' ? <span>Análisis disponible: 1 por día</span> : undefined;
  return <div className="planning-workspace"><HeroSection {...meta[area]} action={canManage ? <Button onClick={action} disabled={busy}><i className="ti ti-plus" /> {meta[area].action}</Button> : undefined} stats={stats} />
    {area === 'calendar' && <><DataPanel title="Vista de calendario" icon="calendar"><FullCalendar plugins={[dayGridPlugin, interactionPlugin]} initialView="dayGridMonth" events={events} height="auto" eventMouseEnter={info => { info.el.title = info.event.extendedProps.description || info.event.title; }} dateClick={arg => canManage && (setEditing({ id: '', date: arg.dateStr, type: 'event' }), setShow(true))} eventClick={arg => canManage && (setEditing(arg.event.extendedProps as Item), setShow(true))} /></DataPanel><DataPanel title="Próximos eventos" icon="timeline-event"><Timeline events={items.filter(item => new Date(item.date) >= new Date()).slice(0, 7).map(item => ({ id: item.id, title: String(item.title ?? ''), date: String(item.date ?? ''), type: item.type as 'election' | 'veda' | 'event', description: String(item.description ?? '') }))} /></DataPanel></>}
    {area === 'territory' && <MapContainer floating={canManage && <><Button size="sm" onClick={() => { setEditing({ id: '', kind: 'circuito' }); setShow(true); }}>Circuito</Button><Button size="sm" onClick={() => { setEditing({ id: '', kind: 'zone' }); setShow(true); }}>Zona</Button></>} sidebar={<><h2 className="h6 mb-3"><i className="ti ti-sitemap" /> Circuitos y zonas</h2>{circuits.map(c => <div className="mb-3" key={c.id}><strong>{c.name}</strong><small className="d-block text-muted">{c.district} · {c.schools?.length ?? 0} escuelas</small>{zones.filter(z => z.circuitoId === c.id).map(z => <button className="btn btn-light btn-sm w-100 text-start mt-2" key={z.id}><i className="ti ti-map-pin" /> {z.name}<span className="badge text-bg-primary float-end">zona</span></button>)}</div>)}</>}><div className="position-absolute top-50 start-50 translate-middle text-center text-muted"><i className="ti ti-map-2 display-5 d-block mb-2" /><strong>Mapa territorial</strong><small className="d-block">Configurá Google Maps para mostrar polígonos y marcadores.</small></div></MapContainer>}
    {area === 'goals' && <><div className="row g-3 mb-4"><div className="col-md-4"><StatCard icon="target-arrow" value={items.length} label="Metas activas" progress={100} /></div><div className="col-md-4"><StatCard icon="circle-check" value={items.filter(goal => percent(goal) >= 100).length} label="Metas alcanzadas" progress={items.length ? items.filter(goal => percent(goal) >= 100).length / items.length * 100 : 0} tone="success" /></div><div className="col-md-4"><StatCard icon="chart-line" value={average + '%'} label="Progreso promedio" progress={average} /></div></div><DataPanel empty={{ icon: 'target-off', title: 'No hay metas todavía', description: 'Creá la primera meta para dar foco a la campaña.', action: canManage ? <Button onClick={action}>Crear primera meta</Button> : undefined }}><div className="row g-3">{items.map(goal => <div className="col-md-6" key={goal.id}><article className="planning-panel h-100"><div className="d-flex justify-content-between"><h2 className="h6">{goal.type === 'coverage' ? 'Cobertura' : 'Conversión'}</h2><span className="badge text-bg-light">{goal.zoneId ? 'Zona asignada' : 'Campaña'}</span></div><ProgressIndicator value={percent(goal)} label={goal.progress + ' de ' + goal.target + ' electores'} /><p className="small text-muted mt-3 mb-0">{goal.description || 'Meta de campaña'}</p></article></div>)}</div></DataPanel></>}
    {area === 'routes' && <DataPanel title="Rutas activas" icon="route" empty={{ icon: 'route-off', title: 'No hay rutas todavía', description: 'Distribuí automáticamente los electores para crear las primeras rutas.', action: canManage ? <Button onClick={action}>Auto-distribuir</Button> : undefined }}><div className="row g-3">{items.map(route => <div className="col-xl-6" key={route.id}><RouteCard route={route} onOptimize={() => setNotice('La optimización avanzada requiere Google Maps.')} /></div>)}</div></DataPanel>}
    {area === 'surveys' && <><Nav variant="pills" className="mb-3 gap-2"><Nav.Item><Nav.Link active={surveyType === 'pre_campaign'} onClick={() => setSurveyType('pre_campaign')}>Pre-campaña</Nav.Link></Nav.Item><Nav.Item><Nav.Link active={surveyType === 'post_visit'} onClick={() => setSurveyType('post_visit')}>Post-visita</Nav.Link></Nav.Item></Nav><DataPanel empty={{ icon: 'clipboard-off', title: 'No hay encuestas todavía', description: 'Creá el primer cuestionario para tu campaña.', action: canManage ? <Button onClick={action}>Nueva encuesta</Button> : undefined }}><div className="row g-3">{items.filter(item => item.type === surveyType).map(survey => <div className="col-md-6" key={survey.id}><article className="planning-panel h-100"><span className="badge text-bg-primary mb-2">{survey.type === 'pre_campaign' ? 'Pre-campaña' : 'Post-visita'}</span><h2 className="h6">{survey.name}</h2><p className="text-muted small">{survey.questions?.length ?? 0} preguntas configuradas</p><Button variant="outline-primary" size="sm" onClick={() => { setEditing(survey); setShow(true); }}>Ver cuestionario</Button></article></div>)}</div></DataPanel></>}
    {area === 'budget' && <><div className="row g-3 mb-4"><div className="col-md-4"><StatCard icon="wallet" value={'$' + (summary.totalAmount ?? 0)} label="Total presupuestado" /></div><div className="col-md-4"><StatCard icon="receipt" value={'$' + (summary.totalSpent ?? 0)} label="Total gastado" progress={summary.consumedPercent ?? 0} tone="warning" /></div><div className="col-md-4"><StatCard icon="pig-money" value={'$' + (summary.available ?? 0)} label="Disponible" progress={100 - (summary.consumedPercent ?? 0)} tone="success" /></div></div><DataPanel title="Distribución del presupuesto" icon="chart-donut"><BudgetBreakdown items={items} /></DataPanel></>}
    {area === 'advisor' && <><div className="alert alert-info d-flex gap-2"><i className="ti ti-info-circle" /> Análisis disponibles: 1 por día. Próximo: mañana a las 09:00.</div><DataPanel title="Recomendaciones actuales" icon="bulb" empty={{ icon: 'bulb-off', title: 'Todavía no hay recomendaciones', description: 'Solicitá un análisis para recibir sugerencias estratégicas.' }}><div className="row g-3">{items.map(item => <div className="col-lg-6" key={item.id}><AISuggestionCard item={item} onFeedback={value => feedback(item.id, value)} /></div>)}</div></DataPanel></>}
    <PlanningModal area={area} show={show} item={editing} circuits={circuits} onHide={() => setShow(false)} onSubmit={submit} />{notice && <Toast message={notice} onClose={() => setNotice('')} />}
  </div>;
}
function PlanningModal({ area, show, item, circuits, onHide, onSubmit }: any) { const field = (name: string, label: string, value: any = '', type = 'text') => <div className="mb-3"><label className="form-label">{label}</label><input name={name} className="form-control" type={type} defaultValue={value} required={name !== 'spent'} /></div>; return <Modal show={show} onHide={onHide} centered className="planning-workspace"><form onSubmit={onSubmit}><Modal.Header closeButton><Modal.Title>{item?.id ? 'Editar' : 'Crear'} {meta[area as PlanningArea].title}</Modal.Title></Modal.Header><Modal.Body>{area === 'calendar' && <>{field('title', 'Título', item?.title)}{field('date', 'Fecha', item?.date, 'date')}<select name="type" className="form-select mb-3" defaultValue={item?.type || 'event'}><option value="event">Evento</option><option value="election">Elección</option><option value="veda">Veda</option></select><textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}{area === 'goals' && <><select name="type" className="form-select mb-3" defaultValue={item?.type || 'coverage'}><option value="coverage">Cobertura</option><option value="conversion">Conversión</option></select>{field('target', 'Objetivo', item?.target, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}{area === 'surveys' && <>{field('name', 'Nombre de la encuesta', item?.name)}<select name="type" className="form-select mb-3" defaultValue={item?.type || 'pre_campaign'}><option value="pre_campaign">Pre-campaña</option><option value="post_visit">Post-visita</option></select><textarea name="questions" rows={6} className="form-control" defaultValue={item?.questions?.map((q: any) => q.text).join('\n')} placeholder="Una pregunta por línea" /></>}{area === 'budget' && <>{field('category', 'Categoría', item?.category)}{field('amount', 'Monto presupuestado', item?.amount, 'number')}{field('spent', 'Monto gastado', item?.spent ?? 0, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}{area === 'territory' && item?.kind === 'zone' && <>{field('name', 'Nombre de zona')}{field('neighborhood', 'Barrio')}<select name="circuitoId" className="form-select mb-3">{circuits.map((c: Item) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea name="polygon" className="form-control" defaultValue='[{"lat":-34.61,"lng":-58.39},{"lat":-34.62,"lng":-58.39},{"lat":-34.61,"lng":-58.38}]' /></>}{area === 'territory' && item?.kind !== 'zone' && <>{field('name', 'Nombre del circuito')}{field('district', 'Distrito')}<textarea name="schools" className="form-control" defaultValue="[]" /></>}</Modal.Body><Modal.Footer><Button variant="light" onClick={onHide}>Cancelar</Button><Button type="submit">Guardar</Button></Modal.Footer></form></Modal>; }
