import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';
import { Button, Modal, ProgressBar } from 'react-bootstrap';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch } from '../../../lib/api';
import { Toast } from '../../../components/Toast';

type Area = 'calendar' | 'territory' | 'goals' | 'routes' | 'surveys' | 'budget' | 'advisor';
type Item = Record<string, any> & { id: string };
const labels: Record<Area, string> = { calendar: 'Calendario de campaña', territory: 'Mapa territorial', goals: 'Metas de campaña', routes: 'Planificador de rutas', surveys: 'Encuestas', budget: 'Presupuesto', advisor: 'Asesor de campaña' };
const endpoint: Partial<Record<Area, string>> = { calendar: 'calendar', goals: 'goals', routes: 'routes', surveys: 'surveys', budget: 'budgets', advisor: 'ai-suggestions' };
const isManager = (role?: string) => role === 'cliente' || role === 'admin';

export default function PlanningWorkspace({ area }: { area: Area }) {
  const { user, campaign, error: campaignError } = useCampaign(); const [items, setItems] = useState<Item[]>([]); const [circuits, setCircuits] = useState<Item[]>([]); const [zones, setZones] = useState<Item[]>([]); const [summary, setSummary] = useState<any>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [show, setShow] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const manager = isManager(campaign?.role);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}` : '';
  const load = useCallback(async () => { if (!user || !campaign) return; setLoading(true); try { if (area === 'territory') { const [c, z] = await Promise.all([authenticatedFetch(user, `${base}/circuitos`), authenticatedFetch(user, `${base}/zones`)]); setCircuits(c as Item[]); setZones(z as Item[]); } else { const result = await authenticatedFetch(user, `${base}/${endpoint[area]}`); if (area === 'budget') { setSummary(result); setItems((result as any).items ?? []); } else setItems(result as Item[]); } } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudieron cargar los datos.'); } finally { setLoading(false); } }, [area, base, campaign, user]);
  useEffect(() => { void load(); }, [load]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!user || !campaign) return; const form = new FormData(event.currentTarget); const value = (key: string) => String(form.get(key) ?? ''); let path = ''; let body: any = {}; if (area === 'calendar') { path = 'calendar'; body = { type: value('type'), date: value('date'), title: value('title'), description: value('description') }; } if (area === 'goals') { path = 'goals'; body = { type: value('type'), target: Number(value('target')), description: value('description') }; } if (area === 'surveys') { path = 'surveys'; body = { name: value('name'), type: value('type'), questions: value('questions').split('\n').filter(Boolean).map((text, index) => ({ id: `q_${index + 1}`, text, type: 'text', isRequired: false })) }; } if (area === 'budget') { path = 'budgets'; body = { category: value('category'), amount: Number(value('amount')), spent: Number(value('spent')), description: value('description') }; } if (area === 'territory') { path = editing?.kind === 'zone' ? 'zones' : 'circuitos'; body = editing?.kind === 'zone' ? { name: value('name'), neighborhood: value('neighborhood'), circuitoId: value('circuitoId'), polygon: JSON.parse(value('polygon')) } : { name: value('name'), district: value('district'), schools: value('schools') ? JSON.parse(value('schools')) : [] }; } try { await authenticatedFetch(user, `${base}/${path}${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(body) }); setShow(false); setEditing(null); setMessage('Cambios guardados.'); void load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudieron guardar los cambios.'); } };
  const remove = async (path: string, id: string) => { if (!user || !confirm('¿Eliminar este elemento?')) return; try { await authenticatedFetch(user, `${base}/${path}/${id}`, { method: 'DELETE' }); void load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo eliminar.'); } };
  const open = (item: Item | null = null, kind?: string) => { setEditing(item ? { ...item, kind } : kind ? { id: '', kind } : null); setShow(true); };
  const calendarEvents = useMemo(() => items.map(item => ({ id: item.id, title: item.title, start: item.date, backgroundColor: item.type === 'election' ? '#EF4444' : item.type === 'veda' ? '#F97316' : '#0060F0', borderColor: 'transparent', extendedProps: item })), [items]);
  if (campaignError) return <div className="alert alert-warning">{campaignError}</div>;
  if (loading) return <div className="text-muted p-4">Cargando planificación…</div>;
  const addButton = manager && area !== 'advisor' && area !== 'routes' ? <Button onClick={() => open()}><i className="ph ph-plus me-1" />Agregar</Button> : null;
  return <section className="card"><div className="card-body p-4"><div className="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><h1 className="h4 mb-1">{labels[area]}</h1><p className="text-muted mb-0">{campaign ? 'Datos aislados para la campaña actual.' : 'Cargando campaña…'}</p></div>{addButton}</div>
    {area === 'calendar' && <FullCalendar plugins={[dayGridPlugin, interactionPlugin]} initialView="dayGridMonth" events={calendarEvents} height="auto" dateClick={(arg) => manager && (setEditing({ id: '', date: arg.dateStr, type: 'event' }), setShow(true))} eventClick={(arg) => manager && open(arg.event.extendedProps as Item)} />}
    {area === 'territory' && <div className="row g-4"><div className="col-lg-8"><div className="border rounded position-relative overflow-hidden" style={{ minHeight: 420, background: 'linear-gradient(135deg, var(--bs-primary-bg-subtle), var(--bs-tertiary-bg)' }}><div className="position-absolute top-50 start-50 translate-middle text-center text-muted"><i className="ph ph-map-trifold display-5 d-block mb-2" />Mapa territorial listo para Google Maps.<br /><small>Configurá VITE_GOOGLE_MAPS_API_KEY para el mapa base.</small></div>{zones.map((zone, index) => <span key={zone.id} className="position-absolute badge text-bg-primary" style={{ left: `${18 + index * 26}%`, top: `${25 + index * 18}%` }}>{zone.name}</span>)}</div></div><div className="col-lg-4"><div className="d-flex justify-content-between"><h2 className="h6">Circuitos</h2>{manager && <button className="btn btn-sm btn-outline-primary" onClick={() => open(null, 'circuito')}>Nuevo</button>}</div>{circuits.map(c => <div className="border rounded p-2 mb-2" key={c.id}><strong>{c.name}</strong><br /><small className="text-muted">{c.district} · {c.schools?.length ?? 0} escuelas</small></div>)}<div className="d-flex justify-content-between mt-3"><h2 className="h6">Zonas</h2>{manager && <button className="btn btn-sm btn-outline-primary" onClick={() => open(null, 'zone')}>Nueva</button>}</div>{zones.map(z => <div className="border rounded p-2 mb-2" key={z.id}><strong>{z.name}</strong><br /><small className="text-muted">{z.neighborhood || 'Sin barrio'}</small></div>)}</div></div>}
    {area === 'goals' && <div className="row g-3">{items.map(goal => <div className="col-md-6" key={goal.id}><div className="border rounded p-3"><div className="d-flex justify-content-between"><strong>{goal.type === 'coverage' ? 'Cobertura' : 'Conversión'}</strong><span>{goal.progress}/{goal.target}</span></div><ProgressBar className="my-2" now={Math.min(100, Math.round((goal.progress || 0) / goal.target * 100))} /><small className="text-muted">{goal.description || 'Meta de campaña'}</small></div></div>)}</div>}
    {area === 'routes' && <RouteArea user={user} base={base} items={items} reload={load} notify={setMessage} manager={manager} />}
    {area === 'surveys' && <div className="row g-3">{items.map(survey => <div className="col-md-6" key={survey.id}><div className="border rounded p-3"><strong>{survey.name}</strong><span className="badge text-bg-light ms-2">{survey.type === 'pre_campaign' ? 'Pre campaña' : 'Post visita'}</span><p className="text-muted small mt-2 mb-2">{survey.questions?.length ?? 0} preguntas</p>{manager && <button className="btn btn-sm btn-outline-danger" onClick={() => remove('surveys', survey.id)}>Eliminar</button>}</div></div>)}</div>}
    {area === 'budget' && <><div className="row g-3 mb-4"><Metric label="Presupuesto" value={`$${summary?.totalAmount ?? 0}`} /><Metric label="Gastado" value={`$${summary?.totalSpent ?? 0}`} /><Metric label="Disponible" value={`$${summary?.available ?? 0}`} /></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Categoría</th><th>Asignado</th><th>Gastado</th><th>Disponible</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.category}</td><td>${item.amount}</td><td>${item.spent}</td><td>${item.amount - item.spent}</td></tr>)}</tbody></table></div></>}
    {area === 'advisor' && <Advisor user={user} base={base} items={items} reload={load} notify={setMessage} manager={manager} />}
  </div>{message && <Toast message={message} onClose={() => setMessage('')} />}<PlannerModal area={area} show={show} item={editing} circuits={circuits} onHide={() => { setShow(false); setEditing(null); }} onSubmit={save} /></section>;
}
const Metric = ({ label, value }: { label: string; value: string }) => <div className="col-md-4"><div className="border rounded p-3"><small className="text-muted">{label}</small><div className="h4 mb-0">{value}</div></div></div>;
function RouteArea({ user, base, items, reload, notify, manager }: any) { const auto = async () => { try { const data = await authenticatedFetch(user, `${base}/routes/auto-distribute`, { method: 'POST' }) as any[]; notify(data.length ? `${data.length} rutas creadas.` : 'No hay electores pendientes para distribuir.'); void reload(); } catch (error) { notify(error instanceof Error ? error.message : 'No se pudieron distribuir las rutas.'); } }; return <><div className="d-flex justify-content-end mb-3">{manager && <Button onClick={auto}>Distribuir automáticamente</Button>}</div><div className="table-responsive"><table className="table"><thead><tr><th>Ruta</th><th>Electores</th><th>Estado</th><th>Tiempo</th></tr></thead><tbody>{items.map((route: Item) => <tr key={route.id}><td>{route.name}</td><td>{route.voters?.length ?? 0}</td><td><span className="badge text-bg-light">{route.status}</span></td><td>{route.estimatedTime} min</td></tr>)}</tbody></table></div></>; }
function Advisor({ user, base, items, reload, notify, manager }: any) { const request = async () => { try { await authenticatedFetch(user, `${base}/ai-suggestions/request`, { method: 'POST' }); notify('Análisis generado.'); void reload(); } catch (error) { notify(error instanceof Error ? error.message : 'No se pudo generar el análisis.'); } }; const feedback = async (id: string, value: string) => { await authenticatedFetch(user, `${base}/ai-suggestions/${id}/feedback`, { method: 'PUT', body: JSON.stringify({ feedback: value }) }); void reload(); }; return <><div className="alert alert-info">El asesor analiza cobertura, conversión, rutas y recursos. Se permite una solicitud por día.</div>{manager && <Button className="mb-3" onClick={request}>Solicitar análisis</Button>}{items.map((item: Item) => <div className="border rounded p-3 mb-2" key={item.id}><strong>{item.content}</strong><p className="text-muted mb-2">{item.reasoning}</p><small className="d-block mb-2">Impacto: {item.potential_gain || 'A evaluar'}</small>{manager && <div className="btn-group btn-group-sm"><button className="btn btn-outline-success" onClick={() => feedback(item.id, 'applied')}>Aplicada</button><button className="btn btn-outline-secondary" onClick={() => feedback(item.id, 'modified')}>Modificar</button><button className="btn btn-outline-danger" onClick={() => feedback(item.id, 'ignored')}>Ignorar</button></div>}</div>)}</>; }
function PlannerModal({ area, show, item, circuits, onHide, onSubmit }: any) { const field = (name: string, label: string, value = '', type = 'text') => <div className="mb-3"><label className="form-label">{label}</label><input name={name} className="form-control" type={type} defaultValue={value} required={name !== 'description' && name !== 'spent'} /></div>; return <Modal show={show} onHide={onHide}><form onSubmit={onSubmit}><Modal.Header closeButton><Modal.Title>Configurar {labels[area as Area]}</Modal.Title></Modal.Header><Modal.Body>{area === 'calendar' && <>{field('title', 'Título', item?.title)}{field('date', 'Fecha', item?.date, 'date')}<select name="type" className="form-select mb-3" defaultValue={item?.type || 'event'}><option value="event">Evento</option><option value="election">Elección</option><option value="veda">Veda</option></select><textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}{area === 'goals' && <><select name="type" className="form-select mb-3" defaultValue={item?.type || 'coverage'}><option value="coverage">Cobertura</option><option value="conversion">Conversión</option></select>{field('target', 'Objetivo', item?.target, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} /></>}{area === 'surveys' && <>{field('name', 'Nombre', item?.name)}<select name="type" className="form-select mb-3" defaultValue={item?.type || 'pre_campaign'}><option value="pre_campaign">Pre campaña</option><option value="post_visit">Post visita</option></select><textarea name="questions" className="form-control" rows={5} defaultValue={item?.questions?.map((q: any) => q.text).join('\n')} placeholder="Una pregunta por línea" /></>}{area === 'budget' && <>{field('category', 'Categoría', item?.category)}{field('amount', 'Monto asignado', item?.amount, 'number')}{field('spent', 'Monto gastado', item?.spent || 0, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} /></>}{area === 'territory' && item?.kind === 'zone' && <>{field('name', 'Nombre de la zona')}{field('neighborhood', 'Barrio')}<select name="circuitoId" className="form-select mb-3">{circuits.map((c: Item) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea name="polygon" className="form-control" defaultValue='[{"lat":-34.61,"lng":-58.39},{"lat":-34.62,"lng":-58.39},{"lat":-34.61,"lng":-58.38}]' /></>}{area === 'territory' && item?.kind !== 'zone' && <>{field('name', 'Nombre del circuito')}{field('district', 'Distrito')}<textarea name="schools" className="form-control" defaultValue='[]' placeholder='[{"name":"Escuela","address":"Dirección"}]' /></>}</Modal.Body><Modal.Footer><Button variant="light" onClick={onHide}>Cancelar</Button><Button type="submit">Guardar</Button></Modal.Footer></form></Modal>; }
