import { useCallback, useEffect, useMemo, useState } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';
import { Button, Modal, Nav } from 'react-bootstrap';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch, authenticatedRequest } from '../../../lib/api';
import { Toast } from '../../../components/Toast';
import HeroBanner from '../../../components/Shared/HeroBanner';
import StatCard from '../../../components/Shared/StatCard';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import ProgressIndicator from '../../../components/Planning/ProgressIndicator';
import Timeline from '../../../components/Planning/Timeline';
import MapContainer from '../../../components/Planning/MapContainer';
import RouteCard from '../../../components/Planning/RouteCard';
import BudgetBreakdown from '../../../components/Planning/BudgetBreakdown';
import AISuggestionCard from '../../../components/Planning/AISuggestionCard';
import PageContainer from '../../../components/Shared/PageContainer';
import SelectControl from '../../../components/Shared/SelectControl';
import Inline from '../../../components/Shared/Inline';
import Stack from '../../../components/Shared/Stack';
import { useActiveCampaign } from '../../../context/CampaignContext';

export type PlanningArea = 'calendar' | 'territory' | 'goals' | 'routes' | 'surveys' | 'budget' | 'advisor';
type Item = Record<string, any> & { id: string };
const meta: Record<PlanningArea, { title: string; description: string; icon: string; endpoint?: string; action: string }> = {
  calendar: { title: 'Calendario Electoral', description: 'Organizá hitos, veda y eventos de campaña.', icon: 'calendar', endpoint: 'calendar', action: 'Crear evento' },
  territory: { title: 'Territorio', description: 'Visualizá circuitos, zonas y cobertura territorial.', icon: 'map', action: 'Crear circuito' },
  goals: { title: 'Metas de Campaña', description: 'Definí qué querés lograr y seguí el progreso.', icon: 'target', endpoint: 'goals', action: 'Agregar meta' },
  routes: { title: 'Planificador de rutas', description: 'Distribuí recorridas y optimizá el trabajo territorial.', icon: 'activity', endpoint: 'routes', action: 'Auto-distribuir' },
  surveys: { title: 'Encuestas', description: 'Creá cuestionarios para cada momento de la campaña.', icon: 'clipboard', endpoint: 'surveys', action: 'Nueva encuesta' },
  budget: { title: 'Presupuesto', description: 'Gestioná el gasto y los recursos de tu campaña.', icon: 'dollar-sign', endpoint: 'budgets', action: 'Agregar línea' },
  advisor: { title: 'Asesor de Estrategia con IA', description: 'Obtené recomendaciones para tu campaña.', icon: 'activity', endpoint: 'ai-suggestions', action: 'Pedir análisis' }
};
const manager = (role?: string) => role === 'cliente' || role === 'admin';

export default function PlanningWorkspace({ area }: { area: PlanningArea }) {
  const { user, campaign, error: campaignError, reload: reloadCampaign } = useCampaign();
  const { enabledAddons } = useActiveCampaign();
  const [items, setItems] = useState<Item[]>([]); const [circuits, setCircuits] = useState<Item[]>([]); const [zones, setZones] = useState<Item[]>([]);
  const [summary, setSummary] = useState<any>({}); const [finance, setFinance] = useState<any>(null); const [notice, setNotice] = useState(''); const [loadError, setLoadError] = useState(''); const [busy, setBusy] = useState(true); const [show, setShow] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [surveyType, setSurveyType] = useState<'pre_campaign' | 'post_visit'>('pre_campaign');
  const base = campaign ? '/api/organizations/' + campaign.orgId + '/campaigns/' + campaign.campId : ''; const canManage = manager(campaign?.role);
  const load = useCallback(async () => { if (!user || !base) { setBusy(false); return; } setBusy(true); setLoadError(''); try { if (area === 'territory') { const [circuitsResult, zonesResult] = await Promise.all([authenticatedRequest<Item[]>(user, base + '/circuitos'), authenticatedRequest<Item[]>(user, base + '/zones')]); const failure = circuitsResult.error ?? zonesResult.error; if (failure) { setLoadError(failure.message); return; } setCircuits(circuitsResult.data ?? []); setZones(zonesResult.data ?? []); } else { const result = await authenticatedRequest<any>(user, base + '/' + meta[area].endpoint); if (result.error) { setLoadError(result.error.message); return; } if (area === 'budget') { setSummary(result.data ?? {}); setItems(result.data?.items ?? []); if (enabledAddons.smartPlanner) { const financeResult = await authenticatedRequest<any>(user, base + '/smartplanner/finance-overview'); if (!financeResult.error) setFinance(financeResult.data); } } else setItems(result.data ?? []); } } finally { setBusy(false); } }, [area, base, enabledAddons.smartPlanner, user]);
  useEffect(() => { void load(); }, [load]);
  const api = async (path: string, method = 'POST', body?: object) => { if (!user) return; await authenticatedFetch(user, base + path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); };
  const action = async () => { try { if (area === 'routes') { await api('/routes/auto-distribute'); setNotice('Rutas distribuidas.'); } else if (area === 'advisor') { setBusy(true); await api('/ai-suggestions/request'); setNotice('Análisis generado.'); } else { setEditing(null); setShow(true); return; } void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudo completar la acción.'); } finally { setBusy(false); } };
  const feedback = async (id: string, value: string) => { try { await api('/ai-suggestions/' + id + '/feedback', 'PUT', { feedback: value }); setNotice(value === 'applied' ? 'Sugerencia aplicada.' : 'Sugerencia ignorada.'); void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudo actualizar.'); } };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const value = (key: string) => String(fd.get(key) ?? ''); let path = '/' + (meta[area].endpoint ?? ''); let data: any = {}; if (area === 'calendar') data = { title: value('title'), date: value('date'), type: value('type'), description: value('description') }; if (area === 'goals') data = { type: value('type'), target: Number(value('target')), description: value('description') }; if (area === 'surveys') data = { name: value('name'), type: value('type'), questions: value('questions').split('\n').filter(Boolean).map((text, index) => ({ id: 'q_' + index, text, type: 'text', isRequired: false })) }; if (area === 'budget') data = { category: value('category'), amount: Number(value('amount')), spent: Number(value('spent')), description: value('description') }; if (area === 'territory') { path = editing?.kind === 'zone' ? '/zones' : '/circuitos'; data = editing?.kind === 'zone' ? { name: value('name'), neighborhood: value('neighborhood'), circuitoId: value('circuitoId'), polygon: JSON.parse(value('polygon')) } : { name: value('name'), district: value('district'), schools: JSON.parse(value('schools') || '[]') }; } try { await api(path + (editing?.id ? '/' + editing.id : ''), editing?.id ? 'PUT' : 'POST', data); setShow(false); setNotice('Cambios guardados correctamente.'); void load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'No se pudieron guardar los cambios.'); } };
  const percent = (goal: Item) => goal.target ? goal.progress / goal.target * 100 : 0; const average = Math.round(items.reduce((sum, item) => sum + percent(item), 0) / Math.max(1, items.length)); const events = useMemo(() => items.map(item => ({ id: item.id, title: item.title, start: item.date, backgroundColor: item.type === 'election' ? '#EF4444' : item.type === 'veda' ? '#F97316' : '#0060F0', borderColor: 'transparent', extendedProps: item })), [items]);
  const title = meta[area].title;
  const hero = <HeroBanner icon={meta[area].icon} title={title} subtitle={meta[area].description} tags={[{ icon: 'check-circle', label: 'Campaña activa' }, { icon: 'users', label: 'Todos los equipos' }]} ctaLabel={canManage ? meta[area].action : undefined} ctaIcon="plus" onCtaClick={canManage ? action : undefined} />;
  if (campaignError || loadError) return <PageContainer className="planning-workspace">{hero}<ContentPanel title={title} subtitle="Datos de planificación" icon={meta[area].icon}><EmptyState icon={meta[area].icon} title="No pudimos cargar esta sección" description={campaignError || loadError} ctaLabel="Reintentar" onCtaClick={() => void (campaignError ? reloadCampaign() : load())} /></ContentPanel></PageContainer>;
  if (busy && !items.length && area !== 'territory') return <PageContainer className="planning-workspace">{hero}<ContentPanel title={title} subtitle="Datos de planificación" icon={meta[area].icon}><EmptyState icon={meta[area].icon} title="Cargando planificación" description="Estamos preparando los datos de tu campaña." /></ContentPanel></PageContainer>;
  return <PageContainer className="planning-workspace"><HeroBanner icon={meta[area].icon} title={title} subtitle={meta[area].description} tags={[{ icon: 'check-circle', label: 'Campaña activa' }, { icon: 'users', label: 'Todos los equipos' }]} ctaLabel={canManage ? meta[area].action : undefined} ctaIcon="plus" onCtaClick={canManage ? action : undefined} />
    {area === 'calendar' && <Stack gap="xl"><ContentPanel title="Vista de calendario" subtitle="Todos los eventos de campaña" icon="calendar"><FullCalendar plugins={[dayGridPlugin, interactionPlugin]} initialView="dayGridMonth" events={events} height="auto" eventMouseEnter={info => { info.el.title = info.event.extendedProps.description || info.event.title; }} dateClick={arg => canManage && (setEditing({ id: '', date: arg.dateStr, type: 'event' }), setShow(true))} eventClick={arg => canManage && (setEditing(arg.event.extendedProps as Item), setShow(true))} /></ContentPanel><ContentPanel title="Próximos hitos" subtitle="Eventos clave de las próximas semanas" icon="activity"><Timeline events={items.filter(item => new Date(item.date) >= new Date()).slice(0, 7).map(item => ({ id: item.id, title: String(item.title ?? ''), date: String(item.date ?? ''), type: item.type as 'election' | 'veda' | 'event', description: String(item.description ?? '') }))} /></ContentPanel></Stack>}
    {area === 'territory' && <><div className="row g-3 mb-4"><div className="col-md-3"><StatCard icon="map" value={circuits.length} label="Circuitos" caption="Registrados" /></div><div className="col-md-3"><StatCard icon="map-pin" iconColor="purple" value={zones.length} label="Zonas" caption="Territorios definidos" /></div><div className="col-md-3"><StatCard icon="home" iconColor="green" value={circuits.reduce((sum, circuit) => sum + (circuit.schools?.length ?? 0), 0)} label="Escuelas" caption="Puntos de referencia" /></div><div className="col-md-3"><StatCard icon="target" iconColor="orange" value="0%" label="Cobertura" caption="Sin información" progress={0} /></div></div><ContentPanel title="Mapa territorial" subtitle="Circuitos, zonas y puntos de trabajo" icon="map"><MapContainer floating={canManage && <Inline gap="sm"><Button size="sm" onClick={() => { setEditing({ id: '', kind: 'circuito' }); setShow(true); }}>Circuito</Button><Button size="sm" onClick={() => { setEditing({ id: '', kind: 'zone' }); setShow(true); }}>Zona</Button></Inline>} sidebar={<><h2 className="h6 mb-3"><i className="feather icon-menu" /> Circuitos y zonas</h2>{circuits.map(c => <div className="mb-3" key={c.id}><strong>{c.name}</strong><small className="d-block text-muted">{c.district} · {c.schools?.length ?? 0} escuelas</small>{zones.filter(z => z.circuitoId === c.id).map(z => <button className="btn btn-light btn-sm w-100 text-start mt-2" key={z.id}><i className="feather icon-map-pin" /> {z.name}<span className="badge text-bg-primary float-end">zona</span></button>)}</div>)}</>}><div className="position-absolute top-50 start-50 translate-middle text-center text-muted"><i className="feather icon-map display-5 d-block mb-2" /><strong>Mapa territorial</strong><small className="d-block">Configurá Google Maps para mostrar polígonos y marcadores.</small></div></MapContainer></ContentPanel></>}
    {area === 'goals' && <><div className="row g-3 mb-4"><div className="col-md-4"><StatCard icon="target" value={items.length} label="Metas activas" caption={items.length + ' metas en seguimiento'} progress={100} linkText="Ver detalle" /></div><div className="col-md-4"><StatCard icon="check-circle" iconColor="green" value={items.filter(goal => percent(goal) >= 100).length} label="Metas alcanzadas" caption="Completadas" progress={items.length ? items.filter(goal => percent(goal) >= 100).length / items.length * 100 : 0} linkText="Ver detalle" /></div><div className="col-md-4"><StatCard icon="activity" iconColor="purple" value={average + '%'} label="Progreso promedio" caption="Avance global" progress={average} linkText="Ver tendencia" /></div></div><ContentPanel title="Objetivos prioritarios" subtitle="Las metas más importantes de tu campaña" icon="target">{items.length ? <div className="row g-3">{items.map(goal => <div className="col-md-6" key={goal.id}><article className="planning-panel h-100"><Stack gap="md"><Inline gap="sm" wrap className="justify-content-between"><h2 className="h6 mb-0">{goal.type === 'coverage' ? 'Cobertura' : 'Conversión'}</h2><span className="badge text-bg-light">{goal.zoneId ? 'Zona asignada' : 'Campaña'}</span></Inline><ProgressIndicator value={percent(goal)} label={goal.progress + ' de ' + goal.target + ' electores'} /><p className="small text-muted mb-0">{goal.description || 'Meta de campaña'}</p></Stack></article></div>)}</div> : <EmptyState icon="target" title="No hay metas todavía" description="Creá la primera meta para dar foco a la campaña." ctaLabel={canManage ? "Crear primera meta" : undefined} onCtaClick={action} />}</ContentPanel></>}
    {area === 'routes' && <><div className="row g-3 mb-4"><div className="col-md-3"><StatCard icon="activity" value={items.length} label="Rutas totales" caption="Planificadas" progress={100} /></div><div className="col-md-3"><StatCard icon="users" iconColor="green" value={new Set(items.map(item => item.assignedUid)).size} label="Militantes activos" caption="Con recorrido" /></div><div className="col-md-3"><StatCard icon="map-pin" iconColor="purple" value={items.reduce((sum, item) => sum + (item.voters?.length ?? 0), 0)} label="Voters asignados" caption="En rutas" /></div><div className="col-md-3"><StatCard icon="clock" iconColor="orange" value={Math.round(items.reduce((sum, item) => sum + (item.estimatedTime ?? 0), 0) / Math.max(1, items.length)) + ' min'} label="Tiempo promedio" caption="Estimado" /></div></div><ContentPanel title="Rutas activas" subtitle="Recorridas asignadas a cada militante" icon="activity">{items.length ? <div className="row g-3">{items.map(route => <div className="col-xl-6" key={route.id}><RouteCard route={route} onOptimize={() => setNotice('La optimización avanzada requiere Google Maps.')} /></div>)}</div> : <EmptyState icon="map" title="No hay rutas todavía" description="Distribuí automáticamente los electores para crear las primeras rutas." ctaLabel={canManage ? "Auto-distribuir" : undefined} onCtaClick={action} />}</ContentPanel></>}
    {area === 'surveys' && <><div className="row g-3 mb-4"><div className="col-md-3"><StatCard icon="clipboard" value={items.length} label="Total encuestas" caption="Creadas" /></div><div className="col-md-3"><StatCard icon="edit" iconColor="blue" value={items.filter(item => item.type === 'pre_campaign').length} label="Pre-campaña" caption="Cuestionarios" /></div><div className="col-md-3"><StatCard icon="check-square" iconColor="purple" value={items.filter(item => item.type === 'post_visit').length} label="Post-visita" caption="Seguimiento" /></div><div className="col-md-3"><StatCard icon="activity" iconColor="green" value="0" label="Respuestas" caption="Registradas" /></div></div><ContentPanel title="Cuestionarios de campaña" subtitle="Creá y organizá tus encuestas" icon="clipboard"><Stack gap="md"><Inline gap="sm" wrap><Nav.Item><Nav.Link active={surveyType === 'pre_campaign'} onClick={() => setSurveyType('pre_campaign')}>Pre-campaña</Nav.Link></Nav.Item><Nav.Item><Nav.Link active={surveyType === 'post_visit'} onClick={() => setSurveyType('post_visit')}>Post-visita</Nav.Link></Nav.Item></Inline>{items.filter(item => item.type === surveyType).length ? <div className="row g-3">{items.filter(item => item.type === surveyType).map(survey => <div className="col-md-6" key={survey.id}><article className="planning-panel h-100"><Stack gap="sm"><span className="badge text-bg-primary">{survey.type === 'pre_campaign' ? 'Pre-campaña' : 'Post-visita'}</span><h2 className="h6 mb-0">{survey.name}</h2><p className="text-muted small mb-0">{survey.questions?.length ?? 0} preguntas configuradas</p><Button variant="outline-primary" size="sm" onClick={() => { setEditing(survey); setShow(true); }}>Ver cuestionario</Button></Stack></article></div>)}</div> : <EmptyState icon="clipboard" title="No hay encuestas todavía" description="Creá el primer cuestionario para tu campaña." ctaLabel={canManage ? "Nueva encuesta" : undefined} onCtaClick={action} />}</Stack></ContentPanel></>}
    {area === 'budget' && <>{finance?.legalSpendingLimit > 0 && <div className={`alert ${finance.exceeded ? 'alert-danger' : 'alert-warning'}`} role="status">{finance.exceeded ? `Alerta legal: el gasto total $${finance.spent.toLocaleString('es-AR')} supera el techo de $${finance.legalSpendingLimit.toLocaleString('es-AR')}.` : `Control legal: $${finance.spent.toLocaleString('es-AR')} de $${finance.legalSpendingLimit.toLocaleString('es-AR')}.`}</div>}<div className="row g-3 mb-4"><div className="col-md-4"><StatCard icon="dollar-sign" value={'$' + (summary.totalAmount ?? 0)} label="Total presupuestado" caption="Recursos de campaña" /></div><div className="col-md-4"><StatCard icon="activity" iconColor="orange" value={'$' + (summary.totalSpent ?? 0)} label="Total gastado" caption="Ejecución actual" progress={summary.consumedPercent ?? 0} /></div><div className="col-md-4"><StatCard icon="check-circle" iconColor="green" value={'$' + (summary.available ?? 0)} label="Disponible" caption="Saldo para invertir" progress={100 - (summary.consumedPercent ?? 0)} /></div></div><ContentPanel title="Distribución del presupuesto" subtitle="Asignación y consumo por categoría" icon="dollar-sign"><BudgetBreakdown items={items} /></ContentPanel></>}
    {area === 'advisor' && <Stack gap="xl"><Inline gap="sm" className="alert alert-info mb-0"><i className="feather icon-info" /> Análisis disponibles: 1 por día. Próximo: mañana a las 09:00.</Inline><ContentPanel title="Recomendaciones actuales" subtitle="Acciones sugeridas según los datos de campaña" icon="activity">{items.length ? <div className="row g-3">{items.map(item => <div className="col-lg-6" key={item.id}><AISuggestionCard item={item} onFeedback={value => feedback(item.id, value)} /></div>)}</div> : <EmptyState icon="activity" title="Todavía no hay recomendaciones" description="Solicitá un análisis para recibir sugerencias estratégicas." ctaLabel={canManage ? "Pedir análisis" : undefined} onCtaClick={action} />}</ContentPanel><ContentPanel title="Histórico de sugerencias" subtitle="Estado de las recomendaciones generadas" icon="clock"><div className="table-responsive"><table className="table planning-table mb-0"><thead><tr><th>Tipo</th><th>Contenido</th><th>Feedback</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.type}</td><td>{item.content}</td><td><span className="badge text-bg-light">{item.feedback || 'Pendiente'}</span></td></tr>)}</tbody></table></div></ContentPanel></Stack>}
    <PlanningModal area={area} show={show} item={editing} circuits={circuits} onHide={() => setShow(false)} onSubmit={submit} />{notice && <Toast message={notice} onClose={() => setNotice('')} />}
  </PageContainer>;
}
function PlanningModal({ area, show, item, circuits, onHide, onSubmit }: any) {
  const field = (name: string, label: string, value: any = '', type = 'text') => <div className="mb-3"><label className="form-label">{label}</label><input name={name} className="form-control" type={type} defaultValue={value} required={name !== 'spent'} /></div>;
  const select = (name: string, label: string, options: Array<{ value: string; label: string }>, defaultValue: string) => <div className="mb-3"><label className="form-label">{label}</label><SelectControl name={name} ariaLabel={label} label={options.find(option => option.value === defaultValue)?.label ?? label} options={options} defaultValue={defaultValue} /></div>;
  return <Modal show={show} onHide={onHide} centered className="planning-workspace"><form onSubmit={onSubmit}><Modal.Header closeButton><Modal.Title>{item?.id ? 'Editar' : 'Crear'} {meta[area as PlanningArea].title}</Modal.Title></Modal.Header><Modal.Body>
    {area === 'calendar' && <>{field('title', 'Título', item?.title)}{field('date', 'Fecha', item?.date, 'date')}{select('type', 'Tipo de evento', [{ value:'event', label:'Evento' }, { value:'election', label:'Elección' }, { value:'veda', label:'Veda' }], item?.type || 'event')}<textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}
    {area === 'goals' && <>{select('type', 'Tipo de meta', [{ value:'coverage', label:'Cobertura' }, { value:'conversion', label:'Conversión' }], item?.type || 'coverage')}{field('target', 'Objetivo', item?.target, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}
    {area === 'surveys' && <>{field('name', 'Nombre de la encuesta', item?.name)}{select('type', 'Tipo de encuesta', [{ value:'pre_campaign', label:'Pre-campaña' }, { value:'post_visit', label:'Post-visita' }], item?.type || 'pre_campaign')}<textarea name="questions" rows={6} className="form-control" defaultValue={item?.questions?.map((q: any) => q.text).join('\n')} placeholder="Una pregunta por línea" /></>}
    {area === 'budget' && <>{field('category', 'Categoría', item?.category)}{field('amount', 'Monto presupuestado', item?.amount, 'number')}{field('spent', 'Monto gastado', item?.spent ?? 0, 'number')}<textarea name="description" className="form-control" defaultValue={item?.description} placeholder="Descripción" /></>}
    {area === 'territory' && item?.kind === 'zone' && <>{field('name', 'Nombre de zona')}{field('neighborhood', 'Barrio')}{select('circuitoId', 'Circuito', circuits.map((c: Item) => ({ value:c.id, label:c.name })), item?.circuitoId || circuits[0]?.id || '')}<textarea name="polygon" className="form-control" defaultValue='[{"lat":-34.61,"lng":-58.39},{"lat":-34.62,"lng":-58.39},{"lat":-34.61,"lng":-58.38}]' /></>}
    {area === 'territory' && item?.kind !== 'zone' && <>{field('name', 'Nombre del circuito')}{field('district', 'Distrito')}<textarea name="schools" className="form-control" defaultValue="[]" /></>}
  </Modal.Body><Modal.Footer><Button variant="light" onClick={onHide}>Cancelar</Button><Button type="submit">Guardar</Button></Modal.Footer></form></Modal>;
}
