import { ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import BackButton from './BackButton';
import Chip from './Chip';
import { Icon, Mountain } from './Icons';
import PrimaryButton from './PrimaryButton';

const iconMap: Record<string, Parameters<typeof Icon>[0]['name']> = { 'bar-chart-2': 'bars', bars: 'bars', users: 'people', people: 'people', map: 'map', 'map-pin': 'pin', calendar: 'cal', target: 'target', clock: 'clock', activity: 'pulse', plus: 'plus', download: 'doc', 'upload-cloud': 'doc', file: 'doc', 'user-check': 'check', 'check-circle': 'check', settings: 'gear' };
type Tag = { icon: string; label: string };
export default function HeroBanner({ icon, title, subtitle, eyebrow, subtitleDetail, tags = [], ctaLabel, ctaIcon = 'plus', onCtaClick, ctaDisabled = false, secondaryCtaLabel, secondaryCtaIcon = 'plus', onSecondaryCtaClick, secondaryCtaDisabled = false, extraFilters, backTo, backLabel, heroStats }: { icon: string; title: string; subtitle: string; eyebrow?: string; subtitleDetail?: string; tags?: Tag[]; ctaLabel?: string; ctaIcon?: string; onCtaClick?: () => void; ctaDisabled?: boolean; secondaryCtaLabel?: string; secondaryCtaIcon?: string; onSecondaryCtaClick?: () => void; secondaryCtaDisabled?: boolean; extraFilters?: ReactNode; backTo?: string; backLabel?: string; heroStats?: ReactNode }) {
  const location = useLocation();
  const resolvedBackTo = backTo ?? (location.pathname.startsWith('/smartplanner/') ? '/smartplanner' : undefined);
  return <header className="cd-hero"><Mountain /><div className="cd-hero__content"><span className="cd-hero__tile"><Icon name={iconMap[icon] || 'bars'} size={32} color="#fff" strokeWidth={1.7} /></span><div className="cd-hero__copy">{eyebrow && <span className="cd-hero__eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{subtitle}</p>{subtitleDetail && <small>{subtitleDetail}</small>}<div className="cd-hero__chips">{tags.map(tag => <Chip key={tag.label} icon={iconMap[tag.icon] || 'bars'} label={tag.label} />)}</div></div></div><div className="cd-hero__aside">{heroStats ?? <div className="cd-hero__tagline">Más territorio.<br />Más conversaciones.<br />Más impacto.</div>}<div className="cd-hero__actions">{extraFilters}<div className="cd-hero__cta-group">{secondaryCtaLabel && <button type="button" className="cd-hero__secondary-cta" onClick={onSecondaryCtaClick} disabled={secondaryCtaDisabled}><Icon name={iconMap[secondaryCtaIcon] || 'plus'} size={17} strokeWidth={2} />{secondaryCtaLabel}</button>}{ctaLabel && <PrimaryButton icon={iconMap[ctaIcon] || 'plus'} onClick={onCtaClick} disabled={ctaDisabled}>{ctaLabel}</PrimaryButton>}</div></div></div>{resolvedBackTo && <div className="cd-hero__back-button" data-back-button="hero"><BackButton to={resolvedBackTo} label={backLabel ?? 'Volver a SmartPlanner'} variant="icon" /></div>}</header>;
}
