import { mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const port = Number(process.env.VISUAL_PORT ?? 5182); const host = '127.0.0.1'; const baseUrl = `http://${host}:${port}`;
const webDir = fileURLToPath(new URL('../', import.meta.url)); const screenshotDir = fileURLToPath(new URL('../.screenshots/', import.meta.url));
const chromiumPath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || 'C:/Users/Admin/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
function waitForServer(child) { return new Promise((resolve, reject) => { const timeout = setTimeout(() => reject(new Error('Vite no inició dentro de 20 segundos.')), 20_000); const done = () => { clearTimeout(timeout); resolve(); }; const onData = chunk => { if (chunk.toString().includes(`http://${host}:${port}`)) done(); }; child.stdout.on('data', onData); child.stderr.on('data', onData); child.once('error', reject); }); }
async function preparePage(page) { await page.route('**/api/me', route => route.fulfill({ contentType:'application/json', body:JSON.stringify({ organization:{ id:'visual-org' }, campaigns:[{ id:'visual-campaign' }], role:'cliente' }) })); await page.route('**/api/users/visual-test-user/notifications', route => route.fulfill({ contentType:'application/json', body:'[]' })); await page.route('**/api/organizations/visual-org/campaigns/visual-campaign/voters', route => route.fulfill({ contentType:'application/json', body:JSON.stringify([{ id:'v-1', name:'María González', address:'Av. Colón 1200', section:'Centro', state:'unvisited', lat:-31.4135, lng:-64.1811 }, { id:'v-2', name:'Javier Torres', address:'San Martín 920', section:'Norte', state:'undecided', lat:-31.3982, lng:-64.1783 }]) })); }
const vite = spawn(process.execPath, [resolve(webDir, 'node_modules', 'vite', 'bin', 'vite.js'), '--host', host, '--port', String(port)], { cwd:webDir, stdio:['ignore', 'pipe', 'pipe'] });
try { await waitForServer(vite); await mkdir(screenshotDir, { recursive:true }); const browser = await chromium.launch({ headless:true, executablePath:chromiumPath }); for (const [name, viewport] of [['desktop', { width:1920, height:1080 }], ['mobile', { width:375, height:812 }]]) { const page = await browser.newPage({ viewport, deviceScaleFactor:1 }); const errors = []; page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); await preparePage(page); await page.goto(`${baseUrl}/electoral-conversion/map?e2eDashboard=1`, { waitUntil:'networkidle' }); await page.locator('.cd-page').waitFor(); await page.waitForTimeout(250); if (!await page.getByRole('heading', { name:'Mapa de electores' }).count()) throw new Error(`${name}: no se renderizó Mapa de electores.`); if (await page.getByText('Failed to fetch', { exact:false }).count()) throw new Error(`${name}: muestra Failed to fetch.`); if (name === 'mobile' && await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)) throw new Error('mobile: la página desborda horizontalmente.'); if (errors.length) throw new Error(`${name}: errores de consola: ${errors.join(' | ')}`); await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path:resolve(screenshotDir, `map-${name}.png`), fullPage:false }); await page.locator('.cd-page').screenshot({ path:resolve(screenshotDir, `map-${name}-content.png`) }); await page.close(); } await browser.close(); console.log(`Capturas guardadas en ${resolve(screenshotDir, 'map-desktop.png')} y map-mobile.png`); } finally { vite.kill(); }
