import { Router } from 'express';
import { requireAuth } from '../middleware/requireAuth.js';
import * as controller from '../controllers/campaign.controller.js';
export const campaignRouter = Router();
const base = '/organizations/:orgId/campaigns/:campId';
campaignRouter.get(`${base}/functions`, requireAuth, controller.getFunctions);
campaignRouter.post(`${base}/functions`, requireAuth, controller.postFunction);
campaignRouter.put(`${base}/functions/:funcId`, requireAuth, controller.putFunction);
campaignRouter.delete(`${base}/functions/:funcId`, requireAuth, controller.removeFunction);
campaignRouter.get(`${base}/teams`, requireAuth, controller.getTeams);
campaignRouter.post(`${base}/teams`, requireAuth, controller.postTeam);
campaignRouter.put(`${base}/teams/:teamId`, requireAuth, controller.putTeam);
campaignRouter.delete(`${base}/teams/:teamId`, requireAuth, controller.removeTeam);
campaignRouter.get(`${base}/teams/:teamId/members`, requireAuth, controller.getTeamMembers);
campaignRouter.get(`${base}/members`, requireAuth, controller.getMembers);
campaignRouter.put(`${base}/members/:memberId`, requireAuth, controller.putMember);
campaignRouter.delete(`${base}/members/:memberId`, requireAuth, controller.removeMember);
campaignRouter.delete(`${base}/teams/:teamId/members/:memberId`, requireAuth, controller.removeTeamMember);
campaignRouter.get(`${base}/invitations`, requireAuth, controller.getInvitations);
campaignRouter.post(`${base}/invitations`, requireAuth, controller.postInvitation);
campaignRouter.delete(`${base}/invitations/:invId`, requireAuth, controller.removeInvitation);
campaignRouter.post(`${base}/invitations/:invId/resend`, requireAuth, controller.resendInvitation);
campaignRouter.get('/join-invitation', controller.getInvitationPreview);
campaignRouter.post('/join-invitation', requireAuth, controller.acceptInvitation);
