import { NextFunction, Request, Response, Router } from 'express';
import { requireAuth } from '../middleware/requireAuth.js';
import * as controller from '../controllers/campaign.controller.js';
import multer from 'multer';
export const campaignRouter = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 } });
const avatarUpload = (request: Request, response: Response, next: NextFunction) => upload.single('avatar')(request, response, (error) => {
  if (error instanceof multer.MulterError && error.code === 'LIMIT_FILE_SIZE') return response.status(413).json({ message: 'La imagen no puede superar los 8 MB.' });
  next(error);
});
const candidatePhotoUpload = (request: Request, response: Response, next: NextFunction) => upload.single('photo')(request, response, (error) => {
  if (error instanceof multer.MulterError && error.code === 'LIMIT_FILE_SIZE') return response.status(413).json({ message: 'La imagen no puede superar los 8 MB.' });
  next(error);
});
const base = '/organizations/:orgId/campaigns/:campId';
campaignRouter.get('/organizations/:orgId/users', requireAuth, controller.getOrganizationUsers);
campaignRouter.post('/organizations/:orgId/users', requireAuth, avatarUpload, controller.postOrganizationUser);
campaignRouter.put('/organizations/:orgId/users/:userId', requireAuth, avatarUpload, controller.putOrganizationUser);
campaignRouter.delete('/organizations/:orgId/users/:userId', requireAuth, controller.removeOrganizationUser);
campaignRouter.get('/organizations/:orgId/campaigns', requireAuth, controller.getOrganizationCampaigns);
campaignRouter.get('/organizations/:orgId/campaigns/compare', requireAuth, controller.compareOrganizationCampaigns);
campaignRouter.post('/organizations/:orgId/campaigns', requireAuth, controller.postOrganizationCampaign);
campaignRouter.put('/organizations/:orgId/campaigns/:campId', requireAuth, controller.putOrganizationCampaign);
campaignRouter.delete('/organizations/:orgId/campaigns/:campId', requireAuth, controller.removeOrganizationCampaign);
campaignRouter.get(`${base}/candidates`, requireAuth, controller.getCandidates);
campaignRouter.post(`${base}/candidates`, requireAuth, candidatePhotoUpload, controller.postCandidate);
campaignRouter.put(`${base}/candidates/:candidateId`, requireAuth, candidatePhotoUpload, controller.putCandidate);
campaignRouter.delete(`${base}/candidates/:candidateId`, requireAuth, controller.removeCandidate);
campaignRouter.post(`${base}/candidates/:candidateId/set-principal`, requireAuth, controller.setPrincipalCandidate);
campaignRouter.get(`${base}/functions`, requireAuth, controller.getFunctions);
campaignRouter.post(`${base}/functions`, requireAuth, controller.postFunction);
campaignRouter.put(`${base}/functions/:funcId`, requireAuth, controller.putFunction);
campaignRouter.delete(`${base}/functions/:funcId`, requireAuth, controller.removeFunction);
campaignRouter.get(`${base}/teams`, requireAuth, controller.getTeams);
campaignRouter.post(`${base}/teams`, requireAuth, controller.postTeam);
campaignRouter.put(`${base}/teams/:teamId`, requireAuth, controller.putTeam);
campaignRouter.delete(`${base}/teams/:teamId`, requireAuth, controller.removeTeam);
campaignRouter.get(`${base}/teams/:teamId/members`, requireAuth, controller.getTeamMembers);
campaignRouter.get(`${base}/members`, requireAuth, controller.getMembers);
campaignRouter.put(`${base}/members/:memberId`, requireAuth, controller.putMember);
campaignRouter.delete(`${base}/members/:memberId`, requireAuth, controller.removeMember);
campaignRouter.delete(`${base}/teams/:teamId/members/:memberId`, requireAuth, controller.removeTeamMember);
campaignRouter.get(`${base}/invitations`, requireAuth, controller.getInvitations);
campaignRouter.post(`${base}/invitations`, requireAuth, controller.postInvitation);
campaignRouter.delete(`${base}/invitations/:invId`, requireAuth, controller.removeInvitation);
campaignRouter.post(`${base}/invitations/:invId/resend`, requireAuth, controller.resendInvitation);
campaignRouter.get('/join-invitation', controller.getInvitationPreview);
campaignRouter.post('/join-invitation', requireAuth, controller.acceptInvitation);
