import { NextFunction, Request, Response, Router } from 'express';
import multer from 'multer';
import { requireAuth } from '../middleware/requireAuth.js';
import * as c from '../controllers/planning.controller.js';
export const planningRouter = Router();
const b = '/organizations/:orgId/campaigns/:campId';
const publicationUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15 * 1024 * 1024 } });
const publicationAttachment = (request: Request, response: Response, next: NextFunction) => publicationUpload.single('attachment')(request, response, (error) => error instanceof multer.MulterError && error.code === 'LIMIT_FILE_SIZE' ? response.status(413).json({ message: 'El adjunto no puede superar los 15 MB.' }) : next(error));
planningRouter.get(`${b}/calendar`, requireAuth, c.getCalendar); planningRouter.post(`${b}/calendar`, requireAuth, c.postCalendar);
planningRouter.get(`${b}/calendar/types`, requireAuth, c.getCalendarEventTypes);
planningRouter.post(`${b}/calendar/types`, requireAuth, c.postCalendarEventType);
planningRouter.post(`${b}/calendar/:eventId/attachments`, requireAuth, publicationAttachment, c.postCalendarPublicationAttachment);
planningRouter.delete(`${b}/calendar/:eventId/attachments/:attachmentId`, requireAuth, c.deleteCalendarPublicationAttachment);
planningRouter.get(`${b}/calendar/availability`, requireAuth, c.getCalendarAvailability); planningRouter.post(`${b}/calendar/availability`, requireAuth, c.postCalendarAvailability);
planningRouter.get(`${b}/calendar/resources`, requireAuth, c.getCalendarResources); planningRouter.post(`${b}/calendar/resources`, requireAuth, c.postCalendarResource); planningRouter.put(`${b}/calendar/resources/:resourceId`, requireAuth, c.putCalendarResource); planningRouter.delete(`${b}/calendar/resources/:resourceId`, requireAuth, c.deleteCalendarResource);
planningRouter.get(`${b}/calendar/templates`, requireAuth, c.getCalendarTemplates); planningRouter.post(`${b}/calendar/templates`, requireAuth, c.postCalendarTemplate); planningRouter.put(`${b}/calendar/templates/:templateId`, requireAuth, c.putCalendarTemplate); planningRouter.delete(`${b}/calendar/templates/:templateId`, requireAuth, c.deleteCalendarTemplate);
planningRouter.post(`${b}/calendar/:eventId/cancel`, requireAuth, c.postCalendarCancel); planningRouter.post(`${b}/calendar/:eventId/reschedule-preview`, requireAuth, c.postCalendarReschedulePreview); planningRouter.post(`${b}/calendar/:eventId/response`, requireAuth, c.postCalendarResponse); planningRouter.get(`${b}/calendar/:eventId/export.ics`, requireAuth, c.getCalendarIcs);
planningRouter.put(`${b}/calendar/:eventId`, requireAuth, c.putCalendar); planningRouter.delete(`${b}/calendar/:eventId`, requireAuth, c.deleteCalendar);
planningRouter.get(`${b}/circuitos`, requireAuth, c.getCircuitos); planningRouter.post(`${b}/circuitos`, requireAuth, c.postCircuito); planningRouter.put(`${b}/circuitos/:circuitoId`, requireAuth, c.putCircuito); planningRouter.delete(`${b}/circuitos/:circuitoId`, requireAuth, c.deleteCircuito);
planningRouter.get(`${b}/zones`, requireAuth, c.getZones); planningRouter.post(`${b}/zones`, requireAuth, c.postZone); planningRouter.get(`${b}/zones/:zoneId/voters`, requireAuth, c.getZoneVoters); planningRouter.put(`${b}/zones/:zoneId`, requireAuth, c.putZone); planningRouter.delete(`${b}/zones/:zoneId`, requireAuth, c.deleteZone);
planningRouter.get(`${b}/goals`, requireAuth, c.getGoals); planningRouter.post(`${b}/goals`, requireAuth, c.postGoal); planningRouter.put(`${b}/goals/:goalId`, requireAuth, c.putGoal); planningRouter.delete(`${b}/goals/:goalId`, requireAuth, c.deleteGoal);
planningRouter.get(`${b}/routes`, requireAuth, c.getRoutes); planningRouter.post(`${b}/routes`, requireAuth, c.postRoute); planningRouter.post(`${b}/routes/auto-distribute`, requireAuth, c.postAutoDistribute); planningRouter.get(`${b}/routes/:routeId/optimized`, requireAuth, c.getOptimizedRoute); planningRouter.put(`${b}/routes/:routeId`, requireAuth, c.putRoute);
planningRouter.get(`${b}/surveys`, requireAuth, c.getSurveys); planningRouter.post(`${b}/surveys`, requireAuth, c.postSurvey); planningRouter.put(`${b}/surveys/:surveyId`, requireAuth, c.putSurvey); planningRouter.delete(`${b}/surveys/:surveyId`, requireAuth, c.deleteSurvey);
planningRouter.get(`${b}/budgets`, requireAuth, c.getBudgets); planningRouter.post(`${b}/budgets`, requireAuth, c.postBudget); planningRouter.put(`${b}/budgets/:budgetId`, requireAuth, c.putBudget); planningRouter.delete(`${b}/budgets/:budgetId`, requireAuth, c.deleteBudget);
planningRouter.get(`${b}/ai-suggestions`, requireAuth, c.getSuggestions); planningRouter.post(`${b}/ai-suggestions/request`, requireAuth, c.postSuggestions); planningRouter.put(`${b}/ai-suggestions/:suggestionId/feedback`, requireAuth, c.putSuggestionFeedback);
