import { Router } from 'express'; import { requireAuth } from '../middleware/requireAuth.js'; import { requireAddon } from '../middleware/requireAddon.js'; import * as c from '../controllers/smartplanner.controller.js';
import * as contributors from '../controllers/smartplannerContributors.controller.js';
import * as providers from '../controllers/smartplannerProviders.controller.js';
export const smartplannerRouter=Router(); const b='/organizations/:orgId/campaigns/:campId/smartplanner';
const protectedAddon = [requireAuth, requireAddon('smartPlanner')] as const;
smartplannerRouter.get(`${b}/areas`,...protectedAddon,c.areas); smartplannerRouter.post(`${b}/areas`,...protectedAddon,c.createArea); smartplannerRouter.put(`${b}/areas/:areaId`,...protectedAddon,c.updateArea); smartplannerRouter.delete(`${b}/areas/:areaId`,...protectedAddon,c.removeArea);
smartplannerRouter.get(`${b}/tasks`,...protectedAddon,c.tasks); smartplannerRouter.post(`${b}/tasks`,...protectedAddon,c.createTask); smartplannerRouter.put(`${b}/tasks/:taskId`,...protectedAddon,c.updateTask); smartplannerRouter.delete(`${b}/tasks/:taskId`,...protectedAddon,c.removeTask); smartplannerRouter.get(`${b}/members`,...protectedAddon,c.members); smartplannerRouter.put(`${b}/members/:memberId/role`,...protectedAddon,c.role);
smartplannerRouter.get(`${b}/contributors`,...protectedAddon,contributors.list); smartplannerRouter.post(`${b}/contributors`,...protectedAddon,contributors.create); smartplannerRouter.put(`${b}/contributors/:contributorId`,...protectedAddon,contributors.update); smartplannerRouter.delete(`${b}/contributors/:contributorId`,...protectedAddon,contributors.remove);
smartplannerRouter.get(`${b}/providers`,...protectedAddon,providers.providers); smartplannerRouter.post(`${b}/providers`,...protectedAddon,providers.saveProvider); smartplannerRouter.put(`${b}/providers/:providerId`,...protectedAddon,providers.saveProvider); smartplannerRouter.delete(`${b}/providers/:providerId`,...protectedAddon,providers.removeProvider); smartplannerRouter.get(`${b}/provider-projects`,...protectedAddon,providers.projects); smartplannerRouter.post(`${b}/provider-projects`,...protectedAddon,providers.saveProject); smartplannerRouter.put(`${b}/provider-projects/:projectId`,...protectedAddon,providers.saveProject); smartplannerRouter.delete(`${b}/provider-projects/:projectId`,...protectedAddon,providers.removeProject);
