import { Router } from 'express';
import multer from 'multer';
import { requireAuth } from '../middleware/requireAuth.js';
import { requireAddon } from '../middleware/requireAddon.js';
import * as controller from '../controllers/voteStream.controller.js';
export const voteStreamRouter = Router();
const base = '/organizations/:orgId/campaigns/:campId/vote-streams';
const agentBase = '/organizations/:orgId/campaigns/:campId/vote-stream';
const guarded = [requireAuth, requireAddon('voteStream')] as const;
const assetUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 } });
voteStreamRouter.get(`${agentBase}/mine`, ...guarded, controller.mine);
voteStreamRouter.get(`${agentBase}/:voteStreamId/next-candidate`, ...guarded, controller.nextCandidate);
voteStreamRouter.post(`${agentBase}/:voteStreamId/submissions`, ...guarded, controller.createSubmission);
voteStreamRouter.post(`${base}/:voteStreamId/manual-submissions`, ...guarded, controller.createManualSubmission);
voteStreamRouter.get(`${agentBase}/:voteStreamId/my-submissions`, ...guarded, controller.listMySubmissions);
voteStreamRouter.get(base, ...guarded, controller.list);
voteStreamRouter.post(base, ...guarded, controller.create);
voteStreamRouter.get(`${base}/agents`, ...guarded, controller.agents);
voteStreamRouter.get(`${base}/:voteStreamId/agents-status`, ...guarded, controller.agentsStatus);
voteStreamRouter.get(`${base}/:voteStreamId/submissions/by-batch/:batchId`, ...guarded, controller.submissionsByBatch);
voteStreamRouter.put(`${base}/:voteStreamId/submissions/:submissionId`, ...guarded, controller.editSubmission);
voteStreamRouter.post(`${base}/:voteStreamId/publish-ranking`, ...guarded, controller.publishRanking);
voteStreamRouter.post(`${base}/:voteStreamId/candidates/:candidateId/assets`, ...guarded, assetUpload.fields([{ name: 'photo', maxCount: 1 }, { name: 'partyLogo', maxCount: 1 }]), controller.uploadCandidateAssets);
voteStreamRouter.get(`${base}/:voteStreamId`, ...guarded, controller.get);
voteStreamRouter.put(`${base}/:voteStreamId`, ...guarded, controller.update);
voteStreamRouter.post(`${base}/:voteStreamId/activate`, ...guarded, controller.activate);
voteStreamRouter.post(`${base}/:voteStreamId/close`, ...guarded, controller.close);
voteStreamRouter.delete(`${base}/:voteStreamId`, ...guarded, controller.remove);
