import { Request, Response } from 'express';
import * as service from '../services/smartplanner.service.js';
import { ForbiddenError, NotFoundError, ValidationError } from '../services/access.service.js';
const ids = (r: Request) => [String(r.params.orgId), String(r.params.campId)] as const;
const fail = (s: Response, e: unknown) => { if (e instanceof ForbiddenError) return s.status(403).json({ message:e.message }); if (e instanceof NotFoundError) return s.status(404).json({ message:e.message }); if (e instanceof ValidationError || e instanceof Error) return s.status(400).json({ message:e.message }); return s.status(500).json({ message:'No pudimos completar la operación.' }); };
export const areas = async(r:Request,s:Response)=>{try{s.json(await service.listAreas(r.user!,...ids(r)));}catch(e){fail(s,e)}};
export const createArea = async(r:Request,s:Response)=>{try{s.status(201).json(await service.saveArea(r.user!,...ids(r),null,r.body));}catch(e){fail(s,e)}};
export const updateArea = async(r:Request,s:Response)=>{try{s.json(await service.saveArea(r.user!,...ids(r),String(r.params.areaId),r.body));}catch(e){fail(s,e)}};
export const removeArea = async(r:Request,s:Response)=>{try{await service.deleteArea(r.user!,...ids(r),String(r.params.areaId));s.status(204).end();}catch(e){fail(s,e)}};
export const categories = async(r:Request,s:Response)=>{try{s.json(await service.listCategories(r.user!,...ids(r)));}catch(e){fail(s,e)}};
export const createCategory = async(r:Request,s:Response)=>{try{s.status(201).json(await service.saveCategory(r.user!,...ids(r),null,r.body));}catch(e){fail(s,e)}};
export const updateCategory = async(r:Request,s:Response)=>{try{s.json(await service.saveCategory(r.user!,...ids(r),String(r.params.categoryId),r.body));}catch(e){fail(s,e)}};
export const removeCategory = async(r:Request,s:Response)=>{try{await service.deleteCategory(r.user!,...ids(r),String(r.params.categoryId));s.status(204).end();}catch(e){fail(s,e)}};
export const sprints = async(r:Request,s:Response)=>{try{s.json(await service.listSprints(r.user!,...ids(r)));}catch(e){fail(s,e)}};
export const createSprint = async(r:Request,s:Response)=>{try{s.status(201).json(await service.saveSprint(r.user!,...ids(r),null,r.body));}catch(e){fail(s,e)}};
export const updateSprint = async(r:Request,s:Response)=>{try{s.json(await service.saveSprint(r.user!,...ids(r),String(r.params.sprintId),r.body));}catch(e){fail(s,e)}};
export const removeSprint = async(r:Request,s:Response)=>{try{await service.deleteSprint(r.user!,...ids(r),String(r.params.sprintId));s.status(204).end();}catch(e){fail(s,e)}};
export const tasks = async(r:Request,s:Response)=>{try{s.json(await service.listTasks(r.user!,...ids(r)));}catch(e){fail(s,e)}};
export const members = async(r:Request,s:Response)=>{try{s.json(await service.listMembers(r.user!,...ids(r)));}catch(e){fail(s,e)}};
export const createTask = async(r:Request,s:Response)=>{try{s.status(201).json(await service.saveTask(r.user!,...ids(r),null,r.body));}catch(e){fail(s,e)}};
export const updateTask = async(r:Request,s:Response)=>{try{s.json(await service.saveTask(r.user!,...ids(r),String(r.params.taskId),r.body));}catch(e){fail(s,e)}};
export const patchTask = async(r:Request,s:Response)=>{try{s.json(await service.patchTask(r.user!,...ids(r),String(r.params.taskId),r.body));}catch(e){fail(s,e)}};
export const removeTask = async(r:Request,s:Response)=>{try{await service.deleteTask(r.user!,...ids(r),String(r.params.taskId));s.status(204).end();}catch(e){fail(s,e)}};
export const uploadTaskAttachment = async(r:Request,s:Response)=>{try{s.status(201).json(await service.uploadTaskAttachment(r.user!,...ids(r),String(r.params.taskId),r.file));}catch(e){fail(s,e)}};
export const taskComments = async(r:Request,s:Response)=>{try{s.json(await service.listTaskComments(r.user!,...ids(r),String(r.params.taskId)));}catch(e){fail(s,e)}};
export const createTaskComment = async(r:Request,s:Response)=>{try{s.status(201).json(await service.createTaskComment(r.user!,...ids(r),String(r.params.taskId),r.body));}catch(e){fail(s,e)}};
export const taskActivity = async(r:Request,s:Response)=>{try{s.json(await service.listTaskActivity(r.user!,...ids(r),String(r.params.taskId)));}catch(e){fail(s,e)}};
export const role = async(r:Request,s:Response)=>{try{s.json(await service.setRole(r.user!,...ids(r),String(r.params.memberId),r.body?.smartPlannerRole));}catch(e){fail(s,e)}};
