import { Request, Response } from 'express';
import { ForbiddenError, NotFoundError, ValidationError } from '../services/access.service.js';
import * as analytics from '../services/analytics.service.js';
import * as audit from '../services/audit.service.js';
import * as notifications from '../services/notifications.service.js';
import * as questions from '../services/questions.service.js';

const ids = (request: Request) => [String(request.params.orgId), String(request.params.campId)] as const;
const dateRange = (request: Request) => { const parse = (value: unknown, end = false) => { const text = typeof value === 'string' ? value : ''; const date = /^\d{4}-\d{2}-\d{2}$/.test(text) ? new Date(`${text}T${end ? '23:59:59.999' : '00:00:00.000'}Z`) : undefined; return date && !Number.isNaN(date.getTime()) ? date : undefined; }; return { start: parse(request.query.start), end: parse(request.query.end, true) }; };
function fail(response: Response, error: unknown) { if (error instanceof ForbiddenError) return response.status(403).json({ message: error.message }); if (error instanceof ValidationError) return response.status(400).json({ message: error.message }); if (error instanceof NotFoundError) return response.status(404).json({ message: error.message }); console.error(error); return response.status(500).json({ message: 'No pudimos completar la operación.' }); }
export const getSummary = async (request: Request, response: Response) => { try { response.json(await analytics.getSummary(request.user!, ...ids(request), dateRange(request))); } catch (error) { fail(response, error); } };
export const getTimeline = async (request: Request, response: Response) => { try { response.json(await analytics.getTimeline(request.user!, ...ids(request), dateRange(request))); } catch (error) { fail(response, error); } };
export const getHeatmap = async (request: Request, response: Response) => { try { response.json(await analytics.getHeatmap(request.user!, ...ids(request))); } catch (error) { fail(response, error); } };
export const getAuditLog = async (request: Request, response: Response) => { try { const user = request.user!; if (user.role !== 'cliente' && user.role !== 'admin') throw new ForbiddenError('Solo Cliente o admin puede ver el control de revisión.'); const [orgId, campId] = ids(request); const { campaignRef, assertCampaignAccess } = await import('../services/access.service.js'); assertCampaignAccess(user, orgId, campId); const snap = await campaignRef(orgId, campId).collection('auditLog').orderBy('timestamp', 'desc').limit(500).get(); response.json(snap.docs.map(doc => ({ id: doc.id, ...doc.data(), timestamp: doc.data().timestamp?.toDate?.().toISOString() ?? null }))); } catch (error) { fail(response, error); } };
export const getQuestionSets = async (request: Request, response: Response) => { try { response.json(await questions.listQuestionSets(request.user!, ...ids(request))); } catch (error) { fail(response, error); } };
export const getActiveQuestionSet = async (request: Request, response: Response) => { try { response.json(await questions.getActiveQuestionSet(request.user!, ...ids(request))); } catch (error) { fail(response, error); } };
const auditMeta = (request: Request) => ({ ipAddress: request.ip, userAgent: request.get('user-agent') ?? undefined });
export const postQuestionSet = async (request: Request, response: Response) => { try { const [orgId, campId] = ids(request); const result = await questions.createQuestionSet(request.user!, orgId, campId, request.body); void audit.appendAudit(orgId, campId, request.user!, { action: 'CREATE_QUESTION_SET', resource: 'questionSet', resourceId: result.id, changes: { after: result }, ...auditMeta(request) }).catch(console.error); response.status(201).json(result); } catch (error) { fail(response, error); } };
export const putQuestionSet = async (request: Request, response: Response) => { try { const [orgId, campId] = ids(request); const result = await questions.updateQuestionSet(request.user!, orgId, campId, String(request.params.setId), request.body); void audit.appendAudit(orgId, campId, request.user!, { action: 'UPDATE_QUESTION_SET', resource: 'questionSet', resourceId: result.id, changes: { after: result }, ...auditMeta(request) }).catch(console.error); response.json(result); } catch (error) { fail(response, error); } };
export const getNotifications = async (request: Request, response: Response) => { try { if (request.user!.uid !== request.params.uid) throw new ForbiddenError('Solo podés consultar tus notificaciones.'); response.json(await notifications.listNotifications(request.user!.uid)); } catch (error) { fail(response, error); } };
export const markNotificationRead = async (request: Request, response: Response) => { try { if (request.user!.uid !== request.params.uid) throw new ForbiddenError('Solo podés modificar tus notificaciones.'); await notifications.markRead(request.user!.uid, String(request.params.notificationId)); response.status(204).end(); } catch (error) { fail(response, error); } };
export const archiveNotification = async (request: Request, response: Response) => { try { if (request.user!.uid !== request.params.uid) throw new ForbiddenError('Solo podés modificar tus notificaciones.'); await notifications.archiveNotification(request.user!.uid, String(request.params.notificationId)); response.status(204).end(); } catch (error) { fail(response, error); } };
export const postNotification = async (request: Request, response: Response) => { try { if (request.user!.uid !== request.body.userId) throw new ForbiddenError('El endpoint interno no admite destinatarios ajenos.'); response.status(201).json(await notifications.createNotification(request.user!.uid, request.body)); } catch (error) { fail(response, error); } };
