import { Request, Response } from 'express';
import * as service from '../services/treo.service.js';
import { ConflictError, ForbiddenError, NotFoundError, ValidationError } from '../services/access.service.js';
const ids = (request: Request): [string, string] => [String(request.params.orgId), String(request.params.campId)];
const fail = (response: Response, error: unknown) => { const status = error instanceof ForbiddenError ? 403 : error instanceof NotFoundError ? 404 : error instanceof ConflictError ? 409 : error instanceof ValidationError || error instanceof Error ? 400 : 500; response.status(status).json({ message: error instanceof Error ? error.message : 'No pudimos completar la operación de Treo.', ...(error instanceof ConflictError ? { details: error.details } : {}) }); };
const call = (fn: (request: Request) => Promise<unknown>, status = 200) => async (request: Request, response: Response) => { try { response.status(status).json(await fn(request)); } catch (error) { fail(response, error); } };
export const chart = call((r) => service.chart(r.user!, ...ids(r)));
export const saveAccount = call((r) => service.saveAccount(r.user!, ...ids(r), r.params.accountId ? String(r.params.accountId) : null, r.body), 201);
export const entries = call((r) => service.entries(r.user!, ...ids(r)));
export const createEntry = call((r) => service.createEntry(r.user!, ...ids(r), r.body), 201);
export const postEntry = call((r) => service.postEntry(r.user!, ...ids(r), String(r.params.entryId)));
export const reverseEntry = call((r) => service.reverseEntry(r.user!, ...ids(r), String(r.params.entryId)), 201);
export const adjustEntry = call((r) => service.adjustEntry(r.user!, ...ids(r), String(r.params.entryId), r.body), 201);
export const removeEntry = async (r: Request, p: Response) => { try { await service.removeEntry(r.user!, ...ids(r), String(r.params.entryId)); p.status(204).end(); } catch (e) { fail(p, e); } };
export const ledger = call((r) => service.ledger(r.user!, ...ids(r)));
export const documents = call((r) => service.documents(r.user!, ...ids(r)));
export const documentUrl = call((r) => service.documentUrl(r.user!, ...ids(r), String(r.params.documentId)));
export const uploadDocument = call((r) => service.uploadDocument(r.user!, ...ids(r), r.body, r.file), 201);
export const recognizeDocument = call((r) => service.recognizeDocument(r.user!, ...ids(r), String(r.params.documentId), r.body));
export const payDocument = call((r) => service.payDocument(r.user!, ...ids(r), String(r.params.documentId), r.body));
export const importStatement = call((r) => service.importStatement(r.user!, ...ids(r), r.body), 201);
export const reconcile = call((r) => service.reconcile(r.user!, ...ids(r), r.body), 201);
export const workbench = call((r) => service.workbench(r.user!, ...ids(r)));
