import { ChangeEvent, FormEvent, useMemo, useState } from 'react';
import Cropper, { Area } from 'react-easy-crop';
import { Button, Modal } from 'react-bootstrap';
import { ApiError, authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import Inline from '../../../components/Shared/Inline';
import KpiCard from '../../../components/Shared/KpiCard';
import PageContainer from '../../../components/Shared/PageContainer';
import SelectControl from '../../../components/Shared/SelectControl';
import Stack from '../../../components/Shared/Stack';
import { Toast } from '../../../components/Toast';
import { useCampaign } from './useCampaign';

export const CANDIDATE_TYPES = ['Presidente', 'Vicepresidente', 'Gobernador', 'Vicegobernador', 'Jefe de Gobierno', 'Vicejefe de Gobierno', 'Intendente', 'Viceintendente', 'Alcalde', 'Vicealcalde', 'Prefecto', 'Viceprefecto', 'Jefe Comunal', 'Presidente Comunal', 'Concejal', 'Regidor', 'Edil', 'Diputado Nacional', 'Diputado Provincial / Estatal / Departamental', 'Diputado Distrital', 'Senador Nacional', 'Senador Provincial / Estatal', 'Parlamentario', 'Representante', 'Asambleísta', 'Legislador', 'Constituyente', 'Consejero Regional', 'Consejero Departamental', 'Consejero Provincial', 'Consejero Municipal', 'Miembro de Junta', 'Miembro de Junta Departamental', 'Miembro de Junta Local', 'Vocal', 'Síndico', 'Corregidor', 'Gobernador Regional', 'Gobernador Departamental', 'Gobernador Provincial', 'Gobernador Municipal', 'Intendente Regional', 'Alcalde Metropolitano', 'Alcalde Municipal', 'Alcalde Distrital', 'Alcalde Provincial', 'Alcalde Local', 'Presidente Regional', 'Presidente Provincial', 'Presidente Municipal', 'Presidente de Junta', 'Representante Distrital', 'Representante Departamental', 'Representante Provincial', 'Representante Regional', 'Representante Municipal', 'Representante Comunal', 'Parlamentario Andino', 'Diputado del Parlamento Centroamericano', 'Diputado del Parlamento Regional', 'Miembro de Parlamento Supranacional', 'Candidato a Convencional', 'Candidato a Constituyente', 'Cargo Ejecutivo', 'Cargo Legislativo', 'Cargo Deliberativo', 'Cargo Regional', 'Cargo Provincial', 'Cargo Departamental', 'Cargo Municipal', 'Cargo Comunal', 'Cargo Distrital', 'Cargo Local', 'Otro'];
const MAX_PHOTO_BYTES = 8 * 1024 * 1024;

type Candidate = { id: string; name: string; type: string; customType?: string | null; party?: string | null; photoUrl?: string | null; isPrincipal: boolean };
type Values = { name: string; type: string; customType: string; party: string };

async function cropPhoto(source: string, area: Area) {
  const image = new Image(); image.src = source;
  await new Promise<void>((resolveLoad, reject) => { image.onload = () => resolveLoad(); image.onerror = () => reject(new Error('No pudimos leer la imagen.')); });
  const output = Math.min(700, Math.max(1, Math.round(Math.max(area.width, area.height)))); const canvas = document.createElement('canvas'); canvas.width = output; canvas.height = output;
  canvas.getContext('2d')!.drawImage(image, area.x, area.y, area.width, area.height, 0, 0, output, output);
  return new Promise<Blob>((resolveBlob, reject) => canvas.toBlob((blob) => blob ? resolveBlob(blob) : reject(new Error('No pudimos recortar la imagen.')), 'image/jpeg', .84));
}

function candidateType(candidate: Candidate) { return candidate.type === 'Otro' ? candidate.customType || 'Otro' : candidate.type; }

export default function Candidates() {
  const { user, campaign, error: campaignError } = useCampaign();
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/candidates` : null;
  const query = useAuthenticatedQuery<Candidate[]>(user, path, [campaign?.campId]);
  const candidates = query.data ?? []; const principal = useMemo(() => candidates.find((item) => item.isPrincipal) ?? null, [candidates]);
  const [editor, setEditor] = useState<Candidate | null | 'new'>(null); const [values, setValues] = useState<Values>({ name: '', type: CANDIDATE_TYPES[0], customType: '', party: '' });
  const [source, setSource] = useState(''); const [crop, setCrop] = useState({ x: 0, y: 0 }); const [zoom, setZoom] = useState(1); const [area, setArea] = useState<Area | null>(null); const [photo, setPhoto] = useState<Blob | null>(null);
  const [deleting, setDeleting] = useState<Candidate | null>(null); const [deleteConfirmation, setDeleteConfirmation] = useState(''); const [resetting, setResetting] = useState<Candidate | null>(null); const [resetConfirmation, setResetConfirmation] = useState('');
  const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null);

  const openEditor = (candidate: Candidate | 'new') => { setEditor(candidate); setValues(candidate === 'new' ? { name: '', type: CANDIDATE_TYPES[0], customType: '', party: '' } : { name: candidate.name, type: candidate.type, customType: candidate.customType ?? '', party: candidate.party ?? '' }); setSource(''); setPhoto(null); };
  const choosePhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/') || file.size > MAX_PHOTO_BYTES) { setNotice({ message: !file.type.startsWith('image/') ? 'La foto debe ser una imagen.' : 'La imagen no puede superar los 8 MB.', variant: 'danger' }); event.target.value = ''; return; } setSource(URL.createObjectURL(file)); setPhoto(null); };
  const confirmCrop = () => { if (!source || !area) return; void cropPhoto(source, area).then((blob) => { if (blob.size > MAX_PHOTO_BYTES) throw new Error('La imagen recortada no puede superar los 8 MB.'); setPhoto(blob); }).catch((error) => setNotice({ message: error instanceof Error ? error.message : 'No pudimos recortar la imagen.', variant: 'danger' })); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !path || !editor || saving) return; if (values.type === 'Otro' && !values.customType.trim()) { setNotice({ message: 'Indicá el tipo de cargo personalizado.', variant: 'danger' }); return; } if (source && !photo) { setNotice({ message: 'Confirmá el recorte de la foto antes de guardar.', variant: 'danger' }); return; }
    setSaving(true); try { const body = new FormData(); Object.entries(values).forEach(([key, value]) => body.append(key, value)); if (photo) body.append('photo', photo, 'candidate.jpg'); await authenticatedFetch<Candidate>(user, editor === 'new' ? path : `${path}/${editor.id}`, { method: editor === 'new' ? 'POST' : 'PUT', body }); await query.reload(); setEditor(null); setNotice({ message: editor === 'new' ? 'Candidato agregado.' : 'Candidato actualizado.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos guardar el candidato.', variant: 'danger' }); } finally { setSaving(false); }
  };
  const makePrincipal = async (candidate: Candidate, confirmReset = false) => { if (!user || !path || saving) return; setSaving(true); try { await authenticatedFetch(user, `${path}/${candidate.id}/set-principal`, { method: 'POST', body: JSON.stringify({ confirmReset }) }); await query.reload(); setResetting(null); setResetConfirmation(''); setNotice({ message: `${candidate.name} quedó como candidato Principal.`, variant: 'success' }); } catch (error) { if (error instanceof ApiError && error.status === 409 && !confirmReset) { setResetting(candidate); setResetConfirmation(''); } else setNotice({ message: error instanceof Error ? error.message : 'No pudimos definir el candidato Principal.', variant: 'danger' }); } finally { setSaving(false); } };
  const remove = async () => { if (!user || !path || !deleting || deleteConfirmation !== deleting.name || saving) return; setSaving(true); try { await authenticatedFetch(user, `${path}/${deleting.id}`, { method: 'DELETE', body: JSON.stringify({ confirmClearPrincipal: deleting.isPrincipal }) }); await query.reload(); setDeleting(null); setNotice({ message: 'Candidato eliminado.', variant: 'success' }); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos eliminar el candidato.', variant: 'danger' }); } finally { setSaving(false); } };

  const failure = campaignError || query.error?.message;
  return <PageContainer><Stack gap="lg">
    <HeroBanner icon="users" title="Candidatos" subtitle="Definí las personas que representa tu campaña." subtitleDetail="El candidato Principal define el nombre que verá el militante en la decisión final de una visita." ctaLabel="Agregar candidato" onCtaClick={() => openEditor('new')} />
    <div className="cd-dashboard__kpis"><KpiCard icon="people" value={candidates.length} label="Total de candidatos" caption="Registrados en esta campaña" /><KpiCard icon="target" iconColor="purple" value={principal?.name ?? 'Sin definir'} label="Candidato Principal" caption={principal ? candidateType(principal) : 'La Visita mantiene su texto genérico'} /></div>
    <ContentPanel icon="people" title="Candidatos de la campaña" subtitle="Elegí un Principal para personalizar la pregunta final de las visitas." headerAction={<Button size="sm" onClick={() => openEditor('new')}>Agregar candidato</Button>}>
      {failure ? <EmptyState icon="people" title="No pudimos cargar los candidatos" description={failure} ctaLabel="Reintentar" onCtaClick={() => void query.reload()} /> : query.loading ? <EmptyState icon="people" title="Cargando candidatos" description="Estamos preparando los datos de la campaña." /> : candidates.length ? <div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>FOTO</th><th>NOMBRE</th><th>TIPO</th><th>PARTIDO</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.id}><td>{candidate.photoUrl ? <img className="cd-candidate-photo" src={candidate.photoUrl} alt={`Foto de ${candidate.name}`} /> : <span className="cd-candidate-photo cd-candidate-photo--fallback">{candidate.name.slice(0, 2).toUpperCase()}</span>}</td><td><strong>{candidate.name}</strong></td><td>{candidateType(candidate)}</td><td>{candidate.party || '—'}</td><td>{candidate.isPrincipal ? <span className="badge text-bg-primary">Principal</span> : '—'}</td><td><Inline gap="sm" wrap><Button size="sm" variant="outline-primary" onClick={() => openEditor(candidate)}>Editar</Button>{!candidate.isPrincipal && <Button size="sm" variant="outline-success" onClick={() => void makePrincipal(candidate)}>Marcar como Principal</Button>}<Button size="sm" variant="outline-danger" onClick={() => { setDeleting(candidate); setDeleteConfirmation(''); }}>Borrar</Button></Inline></td></tr>)}</tbody></table></div> : <EmptyState icon="people" title="Todavía no hay candidatos" description="Agregá candidatos para identificar a quién se consulta en la visita." ctaLabel="Agregar candidato" onCtaClick={() => openEditor('new')} />}
    </ContentPanel>
    <Modal show={Boolean(editor)} size="lg" onHide={() => !saving && setEditor(null)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editor === 'new' ? 'Agregar candidato' : 'Editar candidato'}</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><div><label className="form-label" htmlFor="candidate-photo">Foto</label><input id="candidate-photo" type="file" accept="image/*" className="form-control" onChange={choosePhoto} /><small className="text-muted">JPG, PNG o WebP. Máximo 8 MB.</small>{source && <><div className="candidate-cropper"><Cropper image={source} crop={crop} zoom={zoom} aspect={1} onCropChange={setCrop} onZoomChange={setZoom} onCropComplete={(_, pixels) => setArea(pixels)} /></div><Inline gap="sm" wrap><input aria-label="Zoom de foto" type="range" min="1" max="3" step=".1" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /><Button size="sm" variant="outline-primary" type="button" onClick={confirmCrop}>Confirmar recorte</Button>{photo && <span className="text-success small">Foto lista para subir</span>}</Inline></>}</div><div className="row g-3"><div className="col-md-6"><label className="form-label" htmlFor="candidate-name">Nombre</label><input id="candidate-name" className="form-control" value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} required maxLength={160} /></div><div className="col-md-6"><label className="form-label" htmlFor="candidate-type">Tipo de cargo</label><SelectControl id="candidate-type" ariaLabel="Tipo de cargo" label={values.type} options={CANDIDATE_TYPES.map((type) => ({ value: type, label: type }))} value={values.type} onChange={(type) => setValues({ ...values, type, customType: type === 'Otro' ? values.customType : '' })} /></div>{values.type === 'Otro' && <div className="col-md-6"><label className="form-label" htmlFor="candidate-custom-type">Tipo personalizado</label><input id="candidate-custom-type" className="form-control" value={values.customType} onChange={(event) => setValues({ ...values, customType: event.target.value })} required maxLength={120} /></div>}<div className="col-md-6"><label className="form-label" htmlFor="candidate-party">Partido</label><input id="candidate-party" className="form-control" value={values.party} onChange={(event) => setValues({ ...values, party: event.target.value })} maxLength={120} /></div></div></Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setEditor(null)} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar candidato'}</Button></Modal.Footer></form></Modal>
    <Modal show={Boolean(resetting)} onHide={() => !saving && setResetting(null)}><Modal.Header closeButton><Modal.Title>Confirmar cambio de Principal</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><p className="mb-0">Vas a cambiar el candidato Principal de esta campaña. Esto reiniciará <strong>TODAS</strong> las métricas de visitas a cero: los electores vuelven a “no visitados”. Si preferís mantener los datos actuales, creá una campaña nueva para este candidato.</p><div><label className="form-label" htmlFor="candidate-reset-confirmation">Para continuar escribí <strong>REINICIAR</strong></label><input id="candidate-reset-confirmation" className="form-control" value={resetConfirmation} onChange={(event) => setResetConfirmation(event.target.value)} autoComplete="off" /></div></Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setResetting(null)} disabled={saving}>Cancelar</Button><Button variant="danger" disabled={saving || resetConfirmation !== 'REINICIAR'} onClick={() => resetting && void makePrincipal(resetting, true)}>Reiniciar y cambiar Principal</Button></Modal.Footer></Modal>
    <Modal show={Boolean(deleting)} onHide={() => !saving && setDeleting(null)}><Modal.Header closeButton><Modal.Title>Eliminar candidato</Modal.Title></Modal.Header><Modal.Body><p>{deleting?.isPrincipal ? 'Este es el candidato Principal. Al borrarlo la campaña quedará sin Principal y la Visita volverá a su texto genérico.' : 'Esta acción elimina el candidato de la campaña.'}</p><label className="form-label" htmlFor="candidate-delete-confirmation">Para confirmar escribí exactamente: <strong>{deleting?.name}</strong></label><input id="candidate-delete-confirmation" className="form-control" value={deleteConfirmation} onChange={(event) => setDeleteConfirmation(event.target.value)} /></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setDeleting(null)} disabled={saving}>Cancelar</Button><Button variant="danger" disabled={saving || deleteConfirmation !== deleting?.name} onClick={() => void remove()}>Eliminar candidato</Button></Modal.Footer></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </Stack></PageContainer>;
}
