import { FormEvent, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import { DEFAULT_FUNCTION_COLOR, functionColorPalette } from '../../../lib/brand';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import SearchInput from '../../../components/Shared/SearchInput';
import StatCard from '../../../components/Shared/StatCard';
import { useCampaign } from './useCampaign';

type Func = { id: string; name: string; description: string; color: string; active?: boolean };
const empty: { name: string; description: string; color: string } = { name: '', description: '', color: DEFAULT_FUNCTION_COLOR };
const suggestions = ['Coordinador territorial', 'Responsable de comunicación', 'Fiscal general'];

export default function Functions() {
  const { user, campaign, error: campaignError, reload: reloadCampaign } = useCampaign();
  const [editing, setEditing] = useState<Func | null>(null); const [show, setShow] = useState(false); const [form, setForm] = useState(empty); const [actionError, setActionError] = useState(''); const [search, setSearch] = useState('');
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/functions` : null;
  const { data, error, loading, reload } = useAuthenticatedQuery<Func[]>(user, path, [campaign?.orgId, campaign?.campId]);
  const items = (data ?? []).filter(item => `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  const failure = campaignError || error?.message || actionError;
  const open = (item?: Func) => { setEditing(item ?? null); setForm(item ? { name:item.name, description:item.description, color:item.color } : empty); setShow(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !path) return; try { await authenticatedFetch(user, editing ? `${path}/${editing.id}` : path, { method:editing ? 'PUT' : 'POST', body:JSON.stringify(form) }); setShow(false); setActionError(''); await reload(); } catch (caught) { setActionError(caught instanceof Error ? caught.message : 'No pudimos guardar la función.'); } };
  const remove = async (item: Func) => { if (!user || !path || !confirm(`¿Borrar ${item.name}?`)) return; try { await authenticatedFetch(user, `${path}/${item.id}`, { method:'DELETE' }); await reload(); } catch (caught) { setActionError(caught instanceof Error ? caught.message : 'No pudimos borrar la función.'); } };
  return <section className="cd-page cs-page"><HeroBanner icon="users" title="Funciones" subtitle="Definí los cargos de tu campaña y estandarizá responsabilidades." subtitleDetail="Cada función ayuda a ordenar equipos, asignar permisos y operar de forma más eficiente." tags={[{icon:'check-circle',label:'Estructura clara'},{icon:'users',label:'Roles bien definidos'},{icon:'bars',label:'Campaña más organizada'}]} ctaLabel="Crear nueva función" onCtaClick={() => open()} />
    <div className="cd-dashboard__kpis"><StatCard icon="users" value={data?.length ?? 0} label="Total de funciones" caption="Cargos definidos en tu campaña" /><StatCard icon="check-circle" iconColor="green" value={data?.filter(item => item.active !== false).length ?? 0} label="Funciones activas" caption="Funciones en uso actualmente" /><StatCard icon="users" iconColor="purple" value={data?.length ?? 0} label="Roles disponibles" caption="Responsabilidades asignables" /><StatCard icon="target" iconColor="orange" value={new Set(data?.map(item => item.color) ?? []).size} label="Colores definidos" caption="Identidad visual en tu equipo" /></div>
    <div className="row g-3"><div className="col-xl-8"><ContentPanel icon="doc" title="Catálogo de funciones" subtitle="Gestioná la estructura organizativa de tu campaña." headerAction={<SearchInput value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar funciones…" aria-label="Buscar funciones" />}>{failure ? <EmptyState icon="users" title="No pudimos cargar las funciones" description={failure} ctaLabel="Reintentar" onCtaClick={() => void (campaignError ? reloadCampaign() : reload())} /> : loading ? <EmptyState icon="users" title="Cargando funciones" description="Estamos preparando el catálogo de tu campaña." /> : items.length ? <div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>NOMBRE</th><th>DESCRIPCIÓN</th><th>COLOR</th><th>ACCIONES</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.description || 'Sin descripción'}</td><td><span className="badge" style={{ backgroundColor:item.color }}>{item.color}</span></td><td><Button size="sm" variant="outline-primary" onClick={() => open(item)}>Editar</Button>{' '}<Button size="sm" variant="outline-danger" onClick={() => void remove(item)}>Borrar</Button></td></tr>)}</tbody></table></div> : <EmptyState icon="users" title="Todavía no hay funciones" description="Definí los cargos de tu campaña para ordenar responsabilidades." ctaLabel="Crear nueva función" onCtaClick={() => open()} />}</ContentPanel></div><div className="col-xl-4 d-grid gap-3"><ContentPanel icon="award" title="Funciones sugeridas" subtitle="Roles comunes en campañas políticas."><div className="d-grid gap-2">{suggestions.map(name => <button className="cd-suggestion" type="button" key={name} onClick={() => { setForm({ ...empty, name }); setEditing(null); setShow(true); }}><strong>{name}</strong><small>Crear y personalizar esta función</small></button>)}</div></ContentPanel><ContentPanel icon="target" title="Buenas prácticas"><p className="small mb-2">Definí responsabilidades claras, evitá superposiciones y mantené la trazabilidad de los cambios.</p></ContentPanel></div></div>
    <Modal show={show} onHide={() => setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar función' : 'Crear nueva función'}</Modal.Title></Modal.Header><Modal.Body><label className="form-label">Nombre</label><input className="form-control mb-3" value={form.name} onChange={event => setForm({ ...form, name:event.target.value })} required /><label className="form-label">Descripción</label><textarea className="form-control mb-3" value={form.description} onChange={event => setForm({ ...form, description:event.target.value })} /><label className="form-label">Color</label><select className="form-select" value={form.color} onChange={event => setForm({ ...form, color:event.target.value })}>{functionColorPalette.map(color => <option value={color.value} key={color.value}>{color.label}</option>)}</select></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)}>Cancelar</Button><Button type="submit">Guardar</Button></Modal.Footer></form></Modal>
  </section>;
}
