import { FormEvent, useEffect, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, publicFetch } from '../../../lib/api';
import { DEFAULT_FUNCTION_COLOR, functionColorPalette } from '../../../lib/brand';
import { useCampaign } from './useCampaign';

type Func = { id: string; name: string; description: string; color: string };
const empty: { name: string; description: string; color: string } = { name: '', description: '', color: DEFAULT_FUNCTION_COLOR };
export default function Functions() {
  const { user, campaign, error: campaignError } = useCampaign(); const [items, setItems] = useState<Func[]>([]); const [editing, setEditing] = useState<Func | null>(null); const [show, setShow] = useState(false); const [form, setForm] = useState(empty); const [error, setError] = useState('');
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/functions` : '';
  const load = async () => { if (!path) return; try { setItems(await publicFetch(path)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos cargar las Funciones.'); } };
  useEffect(() => { void load(); }, [path]);
  const open = (item?: Func) => { setEditing(item ?? null); setForm(item ? { name: item.name, description: item.description, color: item.color } : empty); setShow(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !path) return; try { await authenticatedFetch(user, editing ? `${path}/${editing.id}` : path, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); setShow(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos guardar la Función.'); } };
  const remove = async (item: Func) => { if (!user || !confirm(`¿Borrar ${item.name}?`)) return; try { await authenticatedFetch(user, `${path}/${item.id}`, { method: 'DELETE' }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos borrar la Función.'); } };
  return <section className="card"><div className="card-body p-4"><div className="d-flex justify-content-between mb-3"><div><h1 className="h4 mb-1">Funciones</h1><p className="text-muted mb-0">Definí los cargos de tu campaña.</p></div><Button onClick={() => open()}>Crear Nueva Función</Button></div>{(error || campaignError) && <div className="alert alert-danger">{error || campaignError}</div>}<div className="table-responsive"><table className="table table-striped table-hover align-middle"><thead><tr><th>Nombre</th><th>Descripción</th><th>Color</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id}><td className="fw-semibold">{item.name}</td><td>{item.description}</td><td><span className="badge" style={{ backgroundColor: item.color }}>{item.color}</span></td><td className="text-end"><Button size="sm" variant="outline-primary" onClick={() => open(item)}>Editar</Button>{' '}<Button size="sm" variant="outline-danger" onClick={() => void remove(item)}>Borrar</Button></td></tr>)}{!items.length && <tr><td colSpan={4} className="text-center text-muted py-4">No hay Funciones todavía.</td></tr>}</tbody></table></div></div><Modal show={show} onHide={() => setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar Función' : 'Crear Nueva Función'}</Modal.Title></Modal.Header><Modal.Body><label className="form-label">Nombre</label><input className="form-control mb-3" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /><label className="form-label">Descripción</label><textarea className="form-control mb-3" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /><label className="form-label">Color</label><select className="form-select" value={form.color} onChange={event => setForm({ ...form, color: event.target.value })}>{functionColorPalette.map(color => <option value={color.value} key={color.value}>{color.label}</option>)}</select></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)}>Cancelar</Button><Button type="submit">Guardar</Button></Modal.Footer></form></Modal></section>;
}
