import { FormEvent, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import { DEFAULT_FUNCTION_COLOR, functionColorPalette } from '../../../lib/brand';
import OrgChart, { availableManagers, type OrgChartMember } from '../../../components/Organization/OrgChart';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import SearchInput from '../../../components/Shared/SearchInput';
import SelectControl from '../../../components/Shared/SelectControl';
import StatCard from '../../../components/Shared/StatCard';
import PageContainer from '../../../components/Shared/PageContainer';
import Inline from '../../../components/Shared/Inline';
import Stack from '../../../components/Shared/Stack';
import { Toast } from '../../../components/Toast';
import { useCampaign } from './useCampaign';

type Func = { id: string; name: string; description: string; color: string; active?: boolean };
const empty: { name: string; description: string; color: string } = { name: '', description: '', color: DEFAULT_FUNCTION_COLOR };
const suggestions = ['Coordinador territorial', 'Responsable de comunicación', 'Fiscal general'];

export default function Functions() {
  const { user, campaign, error: campaignError, reload: reloadCampaign } = useCampaign();
  const [editing, setEditing] = useState<Func | null>(null); const [show, setShow] = useState(false); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null); const [search, setSearch] = useState('');
  const [view, setView] = useState<'functions' | 'chart'>('functions'); const [chartMember, setChartMember] = useState<OrgChartMember | null>(null); const [reportsTo, setReportsTo] = useState('');
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/functions` : null;
  const chartPath = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/org-chart` : null;
  const { data, error, loading, reload } = useAuthenticatedQuery<Func[]>(user, path, [campaign?.orgId, campaign?.campId]);
  const chart = useAuthenticatedQuery<OrgChartMember[]>(user, chartPath, [campaign?.orgId, campaign?.campId]);
  const items = (data ?? []).filter(item => `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()));
  const failure = campaignError || error?.message;
  const open = (item?: Func) => { setEditing(item ?? null); setForm(item ? { name:item.name, description:item.description, color:item.color } : empty); setShow(true); };
  const openMember = (member: OrgChartMember) => { setChartMember(member); setReportsTo(member.reportsTo ?? ''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !path || saving) return; const isEditing = Boolean(editing); setSaving(true); try { await authenticatedFetch(user, editing ? `${path}/${editing.id}` : path, { method:editing ? 'PUT' : 'POST', body:JSON.stringify(form) }); await reload(); setShow(false); setNotice({ message:isEditing ? 'Función actualizada correctamente.' : 'Función creada correctamente.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos guardar la función.', variant:'danger' }); } finally { setSaving(false); } };
  const remove = async (item: Func) => { if (!user || !path || !confirm(`¿Borrar ${item.name}?`)) return; try { await authenticatedFetch(user, `${path}/${item.id}`, { method:'DELETE' }); await reload(); setNotice({ message:'Función eliminada correctamente.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos borrar la función.', variant:'danger' }); } };
  const saveReportsTo = async () => { if (!user || !campaign || !chartMember || saving) return; setSaving(true); try { await authenticatedFetch(user, `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/members/${chartMember.uid}/reports-to`, { method:'PUT', body:JSON.stringify({ reportsTo: reportsTo || null }) }); await chart.reload(); setChartMember(null); setNotice({ message:'La relación jerárquica fue actualizada.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos actualizar el organigrama.', variant:'danger' }); } finally { setSaving(false); } };
  const managerOptions = chartMember ? [{ value: '', label: 'Sin responsable (raíz)' }, ...availableManagers(chartMember, chart.data ?? []).map((member) => ({ value: member.uid, label: member.displayName || member.email }))] : [];

  return <PageContainer><Stack gap="lg"><HeroBanner icon="users" title="Funciones" subtitle="Definí los cargos de tu campaña y estandarizá responsabilidades." subtitleDetail="Cada función ayuda a ordenar equipos, asignar permisos y operar de forma más eficiente." tags={[{icon:'check-circle',label:'Estructura clara'},{icon:'users',label:'Roles bien definidos'},{icon:'bars',label:'Campaña más organizada'}]} ctaLabel={view === 'functions' ? 'Crear nueva función' : undefined} onCtaClick={() => open()} />
    <Inline gap="sm" wrap><Button variant={view === 'functions' ? 'primary' : 'outline-primary'} onClick={() => setView('functions')}>Funciones</Button><Button variant={view === 'chart' ? 'primary' : 'outline-primary'} onClick={() => setView('chart')}>Organigrama</Button></Inline>
    {view === 'chart' ? <ContentPanel icon="users" title="Organigrama de campaña" subtitle="Visualizá responsabilidades y definí a quién reporta cada persona.">{chart.loading ? <EmptyState icon="users" title="Cargando organigrama" description="Estamos reuniendo la estructura de tu campaña." /> : chart.error ? <EmptyState icon="users" title="No pudimos cargar el organigrama" description={chart.error.message} ctaLabel="Reintentar" onCtaClick={() => void chart.reload()} /> : chart.data?.length ? <OrgChart members={chart.data} onSelect={openMember} /> : <EmptyState icon="users" title="Todavía no hay miembros" description="Creá usuarios y asignales funciones para construir tu organigrama." />} </ContentPanel> : <><div className="cd-dashboard__kpis"><StatCard icon="users" value={data?.length ?? 0} label="Total de funciones" caption="Cargos definidos en tu campaña" /><StatCard icon="check-circle" iconColor="green" value={data?.filter(item => item.active !== false).length ?? 0} label="Funciones activas" caption="Funciones en uso actualmente" /><StatCard icon="users" iconColor="purple" value={data?.length ?? 0} label="Roles disponibles" caption="Responsabilidades asignables" /><StatCard icon="target" iconColor="orange" value={new Set(data?.map(item => item.color) ?? []).size} label="Colores definidos" caption="Identidad visual en tu equipo" /></div>
      <div className="row g-3"><div className="col-xl-8"><ContentPanel icon="doc" title="Catálogo de funciones" subtitle="Gestioná la estructura organizativa de tu campaña." headerAction={<SearchInput value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar funciones…" aria-label="Buscar funciones" />}>{failure ? <EmptyState icon="users" title="No pudimos cargar las funciones" description={failure} ctaLabel="Reintentar" onCtaClick={() => void (campaignError ? reloadCampaign() : reload())} /> : loading ? <EmptyState icon="users" title="Cargando funciones" description="Estamos preparando el catálogo de tu campaña." /> : items.length ? <div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>NOMBRE</th><th>DESCRIPCIÓN</th><th>COLOR</th><th>ACCIONES</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.description || 'Sin descripción'}</td><td><span className="badge" style={{ backgroundColor:item.color }}>{item.color}</span></td><td><Inline gap="sm" wrap><Button size="sm" variant="outline-primary" onClick={() => open(item)}>Editar</Button><Button size="sm" variant="outline-danger" onClick={() => void remove(item)}>Borrar</Button></Inline></td></tr>)}</tbody></table></div> : <EmptyState icon="users" title="Todavía no hay funciones" description="Definí los cargos de tu campaña para ordenar responsabilidades." ctaLabel="Crear nueva función" onCtaClick={() => open()} />}</ContentPanel></div><div className="col-xl-4 d-grid gap-3"><ContentPanel icon="award" title="Funciones sugeridas" subtitle="Roles comunes en campañas políticas."><Stack gap="sm">{suggestions.map(name => <button className="cd-suggestion" type="button" key={name} onClick={() => { setForm({ ...empty, name }); setEditing(null); setShow(true); }}><Stack gap="xs"><strong>{name}</strong><small>Crear y personalizar esta función</small></Stack></button>)}</Stack></ContentPanel><ContentPanel icon="target" title="Buenas prácticas"><p className="small mb-2">Definí responsabilidades claras, evitá superposiciones y mantené la trazabilidad de los cambios.</p></ContentPanel></div></div></>}</Stack>
    <Modal show={show} onHide={() => !saving && setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar función' : 'Crear nueva función'}</Modal.Title></Modal.Header><Modal.Body><label className="form-label" htmlFor="function-name">Nombre</label><input id="function-name" className="form-control mb-3" value={form.name} onChange={event => setForm({ ...form, name:event.target.value })} required /><label className="form-label" htmlFor="function-description">Descripción</label><textarea id="function-description" className="form-control mb-3" value={form.description} onChange={event => setForm({ ...form, description:event.target.value })} /><label className="form-label" htmlFor="function-color">Color</label><SelectControl id="function-color" ariaLabel="Color" label={functionColorPalette.find(color => color.value === form.color)?.label ?? 'Seleccionar color'} options={functionColorPalette.map(color => ({ value: color.value, label: color.label }))} value={form.color} onChange={color => setForm({ ...form, color })} /></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</Button></Modal.Footer></form></Modal>
    <Modal show={Boolean(chartMember)} onHide={() => !saving && setChartMember(null)}><Modal.Header closeButton><Modal.Title>Responsable directo</Modal.Title></Modal.Header><Modal.Body><Stack gap="sm"><p className="mb-0">Elegí a quién reporta <strong>{chartMember?.displayName}</strong>.</p><div><label className="form-label" htmlFor="member-reports-to">Reporta a</label><SelectControl id="member-reports-to" ariaLabel="Reporta a" label={managerOptions.find((option) => option.value === reportsTo)?.label ?? 'Sin responsable (raíz)'} value={reportsTo} options={managerOptions} onChange={setReportsTo} /></div></Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setChartMember(null)} disabled={saving}>Cancelar</Button><Button onClick={() => void saveReportsTo()} disabled={saving}>{saving ? 'Guardando…' : 'Guardar relación'}</Button></Modal.Footer></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </PageContainer>;
}
