import { FormEvent, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import SearchInput from '../../../components/Shared/SearchInput';
import StatCard from '../../../components/Shared/StatCard';
import PageContainer from '../../../components/Shared/PageContainer';
import { Toast } from '../../../components/Toast';
import { useCampaign } from './useCampaign';

type Team = { id: string; name: string; description?: string; leaderId?: string | null; memberCount?: number; territoryCount?: number };
type Member = { uid: string; displayName?: string; email: string };
type TeamMember = Member & { role?: string; functionId?: string | null; teamId?: string | null };
const suggestedStructures = [
  ['Equipo por territorio', 'Organizá colaboradores por zonas geográficas.'],
  ['Equipo por tarea', 'Creá equipos enfocados en visitas, encuestas o logística.'],
  ['Equipo mixto', 'Combiná territorios y tareas según tus necesidades.'],
];

export default function Teams() {
  const { user, campaign, error: campaignError, reload: reloadCampaign } = useCampaign();
  const [form, setForm] = useState({ name: '', description: '', leaderId: '' });
  const [editing, setEditing] = useState<Team | null>(null); const [viewing, setViewing] = useState<Team | null>(null); const [show, setShow] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null); const [search, setSearch] = useState('');
  const basePath = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}` : null;
  const teamsQuery = useAuthenticatedQuery<Team[]>(user, basePath ? `${basePath}/teams` : null, [campaign?.orgId, campaign?.campId]);
  const membersQuery = useAuthenticatedQuery<Member[]>(user, basePath ? `${basePath}/members` : null, [campaign?.orgId, campaign?.campId]);
  const detailMembersQuery = useAuthenticatedQuery<TeamMember[]>(user, viewing && basePath ? `${basePath}/teams/${viewing.id}/members` : null, [viewing?.id, campaign?.orgId, campaign?.campId]);
  const teams = teamsQuery.data ?? []; const members = membersQuery.data ?? [];
  const filtered = teams.filter(team => `${team.name} ${team.description ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  const failure = campaignError || teamsQuery.error?.message || membersQuery.error?.message;
  const reload = async () => { await Promise.all([teamsQuery.reload(), membersQuery.reload()]); };
  const open = (team?: Team) => { setEditing(team ?? null); setForm(team ? { name: team.name, description: team.description ?? '', leaderId: team.leaderId ?? '' } : { name: '', description: '', leaderId: '' }); setShow(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !basePath || saving) return; const isEditing = Boolean(editing); setSaving(true); try { await authenticatedFetch(user, editing ? `${basePath}/teams/${editing.id}` : `${basePath}/teams`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, leaderId: form.leaderId || null }) }); await reload(); setShow(false); setNotice({ message:isEditing ? 'Equipo actualizado correctamente.' : 'Equipo creado correctamente.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos guardar el equipo.', variant:'danger' }); } finally { setSaving(false); } };
  const remove = async (team: Team) => { if (!user || !basePath || !confirm(`¿Borrar ${team.name}?`)) return; try { await authenticatedFetch(user, `${basePath}/teams/${team.id}`, { method: 'DELETE' }); await reload(); setNotice({ message:'Equipo eliminado correctamente.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos borrar el equipo.', variant:'danger' }); } };
  const removeMember = async (member: TeamMember) => { if (!user || !basePath || !viewing || !confirm(`¿Quitar a ${member.displayName || member.email} de este equipo?`)) return; try { await authenticatedFetch(user, `${basePath}/teams/${viewing.id}/members/${member.uid}`, { method:'DELETE' }); await Promise.all([detailMembersQuery.reload(), reload()]); setNotice({ message:'Miembro quitado del equipo.', variant:'success' }); } catch (caught) { setNotice({ message:caught instanceof Error ? caught.message : 'No pudimos quitar al miembro.', variant:'danger' }); } };
  const totalMembers = teams.reduce((total, team) => total + (team.memberCount ?? 0), 0);
  const territories = teams.reduce((total, team) => total + (team.territoryCount ?? 0), 0);
  return <PageContainer>
    <HeroBanner icon="users" title="Equipos" subtitle="Organizá a tus colaboradores por territorio o tarea." subtitleDetail="Creá equipos, asigná miembros, definí responsabilidades y potenciá el trabajo en campo." tags={[{ icon:'map-pin', label:'Trabajo en equipo' }, { icon:'trending-up', label:'Mejores resultados' }, { icon:'bars', label:'Campañas más fuertes' }]} ctaLabel="Crear nuevo equipo" onCtaClick={() => open()} />
    <div className="cd-dashboard__kpis"><StatCard icon="users" value={teams.length} label="Total de equipos" caption={teams.length ? 'Equipos activos en campaña' : 'Aún no hay equipos'} /><StatCard icon="users" iconColor="green" value={totalMembers} label="Miembros totales" caption="Colaboradores organizados" /><StatCard icon="map" iconColor="purple" value={territories} label="Territorios asignados" caption="Zonas de trabajo" /><StatCard icon="target" iconColor="orange" value={teams.length ? 1 : 0} label="Metas con equipos" caption="Campañas activas" /></div>
    {failure ? <ContentPanel icon="users" title="Tus equipos de campaña" subtitle="Gestioná el trabajo de tus colaboradores."><EmptyState icon="users" title="No pudimos cargar los equipos" description={failure} ctaLabel="Reintentar" onCtaClick={() => void (campaignError ? reloadCampaign() : reload())} /></ContentPanel> : <div className="row g-3"><div className="col-xl-8"><ContentPanel icon="users" title="Tus equipos de campaña" subtitle="Gestioná, visualizá y coordiná el trabajo de tus colaboradores." headerAction={<SearchInput value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar equipo…" aria-label="Buscar equipo" />}>
      {teamsQuery.loading || membersQuery.loading ? <EmptyState icon="users" title="Cargando equipos" description="Estamos preparando la organización de tu campaña." /> : filtered.length ? <div className="row g-3">{filtered.map(team => <div className="col-md-6" key={team.id}><article className="cd-team-card h-100"><div><h3>{team.name}</h3><p>{team.description || 'Sin descripción todavía.'}</p><small>Líder: {members.find(member => member.uid === team.leaderId)?.displayName || members.find(member => member.uid === team.leaderId)?.email || 'Sin asignar'}</small></div><div className="d-flex justify-content-between align-items-center gap-2 mt-3"><span className="cd-state-pill">{team.memberCount ?? 0} miembros</span><span><Button size="sm" variant="outline-secondary" onClick={() => setViewing(team)}>Ver miembros</Button>{' '}<Button size="sm" variant="outline-primary" onClick={() => open(team)}>Editar</Button>{' '}<Button size="sm" variant="outline-danger" onClick={() => void remove(team)}>Borrar</Button></span></div></article></div>)}</div> : <EmptyState icon="users" title="Aún no tenés equipos creados" description="Organizá a tus colaboradores por territorio o tarea para comenzar a trabajar de forma más eficiente." ctaLabel="Crear nuevo equipo" onCtaClick={() => open()} />}
    </ContentPanel></div><div className="col-xl-4 d-grid gap-3"><ContentPanel icon="award" title="Estructuras sugeridas" subtitle="Modelos comunes de organización para tu campaña."><div className="d-grid gap-2">{suggestedStructures.map(([name, description]) => <button className="cd-suggestion" type="button" key={name} onClick={() => { setForm({ name, description:'', leaderId:'' }); setEditing(null); setShow(true); }}><strong>{name}</strong><small>{description}</small></button>)}</div></ContentPanel><ContentPanel icon="map" title="Gestión de territorios" subtitle="Asigná equipos a territorios para una mejor cobertura."><div className="cd-map-notice"><p>{teams.length ? 'Seleccioná un equipo para organizar su cobertura territorial.' : 'Primero creá tus equipos. Después podrás asignarles territorios y visualizar su cobertura en el mapa.'}</p></div></ContentPanel></div></div>}
    <Modal show={show} onHide={() => !saving && setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar equipo' : 'Crear nuevo equipo'}</Modal.Title></Modal.Header><Modal.Body><label className="form-label" htmlFor="team-name">Nombre</label><input id="team-name" className="form-control mb-3" value={form.name} onChange={event => setForm({ ...form, name:event.target.value })} required /><label className="form-label" htmlFor="team-description">Descripción</label><textarea id="team-description" className="form-control mb-3" value={form.description} onChange={event => setForm({ ...form, description:event.target.value })} /><label className="form-label" htmlFor="team-leader">Líder</label><select id="team-leader" className="form-select" value={form.leaderId} onChange={event => setForm({ ...form, leaderId:event.target.value })}><option value="">Sin asignar</option>{members.map(member => <option key={member.uid} value={member.uid}>{member.displayName || member.email}</option>)}</select></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</Button></Modal.Footer></form></Modal>
    <Modal show={Boolean(viewing)} onHide={() => setViewing(null)}><Modal.Header closeButton><Modal.Title>Miembros de {viewing?.name}</Modal.Title></Modal.Header><Modal.Body>{detailMembersQuery.loading ? <p className="mb-0">Cargando miembros…</p> : detailMembersQuery.error ? <p className="text-danger mb-0">{detailMembersQuery.error.message}</p> : detailMembersQuery.data?.length ? <div className="list-group">{detailMembersQuery.data.map(member => <div className="list-group-item d-flex align-items-center justify-content-between gap-2" key={member.uid}><div><strong>{member.displayName || member.email}</strong><small className="d-block text-muted">{member.email}</small></div><Button size="sm" variant="outline-danger" onClick={() => void removeMember(member)}>Quitar del equipo</Button></div>)}</div> : <p className="mb-0 text-muted">Este equipo todavía no tiene miembros asignados.</p>}</Modal.Body></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </PageContainer>;
}
