import { useEffect, useMemo, useState } from 'react';
import { Button, Dropdown, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import HeroBanner from '../../../components/Shared/HeroBanner';
import Inline from '../../../components/Shared/Inline';
import PageContainer from '../../../components/Shared/PageContainer';
import SearchInput from '../../../components/Shared/SearchInput';
import SelectControl from '../../../components/Shared/SelectControl';
import Stack from '../../../components/Shared/Stack';
import TablePagination from '../../../components/Shared/TablePagination';
import { Toast } from '../../../components/Toast';
import CreateUserModal from '../../../components/Organization/CreateUserModal';
import { useCampaign } from './useCampaign';

type Member = { uid: string; displayName?: string; email: string; role: string; functionId?: string; teamId?: string; emailSent?: boolean };
type Item = { id: string; name: string; color?: string };
type OrgUser = { uid: string; firstName?: string; lastName?: string; displayName?: string; email: string; phone?: string; photoURL?: string; role: string; campaignId?: string; functionId?: string; teamId?: string };

function initials(name?: string, email?: string) { const source = (name || email || '?').trim(); const words = source.split(/\s+/).filter(Boolean); return words.length > 1 ? `${words[0][0]}${words[1][0]}`.toUpperCase() : source.slice(0, 2).toUpperCase(); }
function roleLabel(role?: string) { return role ? `${role.slice(0, 1).toUpperCase()}${role.slice(1)}` : 'Usuario'; }
function UserIdentity({ name, email, photoURL, secondary }: { name?: string; email: string; photoURL?: string; secondary?: string }) { const [photoUnavailable, setPhotoUnavailable] = useState(false); const label = name || email; return <div className="cd-user-identity">{!photoUnavailable && photoURL ? <img className="cd-user-identity__avatar" src={photoURL} alt={`Foto de ${label}`} onError={() => setPhotoUnavailable(true)} /> : <span className="cd-user-identity__fallback" aria-hidden="true">{initials(label, email)}</span>}<div className="cd-user-identity__copy"><strong>{label}</strong><small>{secondary ?? email}</small></div></div>; }
function StatusPill() { return <span className="cd-user-pill cd-user-pill--active"><i className="ti ti-circle-filled" aria-hidden="true" /> Activo</span>; }
function ValuePill({ tone, children }: { tone: 'function' | 'team' | 'role' | 'muted'; children: string }) { return <span className={`cd-user-pill cd-user-pill--${tone}`}>{children}</span>; }
function RowActions({ subject, onEdit, onDelete }: { subject: string; onEdit: () => void; onDelete: () => void }) { return <Inline gap="xs" className="cd-user-row-actions"><button type="button" className="cd-user-row-action" aria-label={`Editar ${subject}`} title="Editar" onClick={onEdit}><i className="ti ti-pencil" aria-hidden="true" /></button><Dropdown align="end"><Dropdown.Toggle className="cd-user-row-action" aria-label={`Más acciones para ${subject}`} title="Más acciones"><i className="ti ti-dots-vertical" aria-hidden="true" /></Dropdown.Toggle><Dropdown.Menu><Dropdown.Item className="text-danger" onClick={onDelete}><i className="ti ti-trash me-2" aria-hidden="true" />Eliminar</Dropdown.Item></Dropdown.Menu></Dropdown></Inline>; }

function MemberAssignmentModal({ member, functions, teams, onHide, onSave }: { member: Member | null; functions: Item[]; teams: Item[]; onHide: () => void; onSave: (values: { functionId: string; teamId: string }) => Promise<void> }) {
  const [functionId, setFunctionId] = useState(''); const [teamId, setTeamId] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setFunctionId(member?.functionId ?? ''); setTeamId(member?.teamId ?? ''); setError(''); }, [member]);
  const save = async () => { setSaving(true); setError(''); try { await onSave({ functionId, teamId }); onHide(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos actualizar la asignación.'); } finally { setSaving(false); } };
  return <Modal show={Boolean(member)} onHide={() => !saving && onHide()}><Modal.Header closeButton><Modal.Title>Editar asignación en campaña</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><p className="text-muted small mb-0">Actualizá la función o el equipo de {member?.displayName ?? member?.email} en esta campaña.</p><div><label className="form-label" htmlFor="member-function">Función</label><SelectControl id="member-function" ariaLabel="Función del miembro" label={functions.find(item => item.id === functionId)?.name ?? 'Sin función'} options={[{ value: '', label: 'Sin función' }, ...functions.map(item => ({ value: item.id, label: item.name }))]} value={functionId} onChange={setFunctionId} /></div><div><label className="form-label" htmlFor="member-team">Equipo</label><SelectControl id="member-team" ariaLabel="Equipo del miembro" label={teams.find(item => item.id === teamId)?.name ?? 'Sin equipo'} options={[{ value: '', label: 'Sin equipo' }, ...teams.map(item => ({ value: item.id, label: item.name }))]} value={teamId} onChange={setTeamId} /></div>{error && <p role="alert" className="text-danger small mb-0">{error}</p>}</Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide} disabled={saving}>Cancelar</Button><Button onClick={() => void save()} disabled={saving}>{saving ? 'Guardando…' : 'Guardar cambios'}</Button></Modal.Footer></Modal>;
}

export default function Users() {
  const { user, campaign } = useCampaign();
  const [showCreate, setShowCreate] = useState(false); const [editingMember, setEditingMember] = useState<Member | null>(null); const [editingUser, setEditingUser] = useState<OrgUser | null>(null); const [removingMember, setRemovingMember] = useState<Member | null>(null); const [removingMemberPending, setRemovingMemberPending] = useState(false); const [deletingUser, setDeletingUser] = useState<OrgUser | null>(null); const [confirmEmail, setConfirmEmail] = useState(''); const [deleting, setDeleting] = useState(false); const [notice, setNotice] = useState<{ message: string; variant: 'success' | 'danger' } | null>(null);
  const [memberSearch, setMemberSearch] = useState(''); const [memberFunction, setMemberFunction] = useState(''); const [memberTeam, setMemberTeam] = useState(''); const [memberPage, setMemberPage] = useState(0); const [memberPageSize, setMemberPageSize] = useState(10); const [orgSearch, setOrgSearch] = useState(''); const [orgPage, setOrgPage] = useState(0); const [orgPageSize, setOrgPageSize] = useState(10);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}` : null;
  const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]); const functionsQ = useAuthenticatedQuery<Item[]>(user, base ? `${base}/functions` : null, [base]); const teamsQ = useAuthenticatedQuery<Item[]>(user, base ? `${base}/teams` : null, [base]); const usersQ = useAuthenticatedQuery<OrgUser[]>(user, campaign ? `/api/organizations/${campaign.orgId}/users` : null, [campaign?.orgId]);
  const members = membersQ.data ?? []; const functions = functionsQ.data ?? []; const teams = teamsQ.data ?? []; const orgUsers = usersQ.data ?? [];
  const reloadPeople = async () => { await Promise.all([membersQ.reload(), usersQ.reload(), teamsQ.reload()]); };
  const filteredMembers = useMemo(() => members.filter((member) => `${member.displayName ?? ''} ${member.email}`.toLowerCase().includes(memberSearch.toLowerCase()) && (!memberFunction || member.functionId === memberFunction) && (!memberTeam || member.teamId === memberTeam)), [members, memberSearch, memberFunction, memberTeam]);
  const filteredOrgUsers = useMemo(() => orgUsers.filter((person) => `${person.displayName ?? ''} ${person.email}`.toLowerCase().includes(orgSearch.toLowerCase())), [orgUsers, orgSearch]);
  useEffect(() => setMemberPage(0), [memberSearch, memberFunction, memberTeam, memberPageSize]); useEffect(() => setOrgPage(0), [orgSearch, orgPageSize]);
  const visibleMembers = filteredMembers.slice(memberPage * memberPageSize, memberPage * memberPageSize + memberPageSize); const visibleOrgUsers = filteredOrgUsers.slice(orgPage * orgPageSize, orgPage * orgPageSize + orgPageSize);
  const create = async (data: FormData) => { if (!user || !campaign) return; const created = await authenticatedFetch<Member>(user, `/api/organizations/${campaign.orgId}/users`, { method: 'POST', body: data }); await reloadPeople(); setShowCreate(false); setNotice({ message: created.emailSent ? `${created.displayName} fue creado correctamente. Le enviamos un email de bienvenida.` : `${created.displayName} fue creado correctamente, pero no pudimos enviarle el email de bienvenida.`, variant: created.emailSent ? 'success' : 'danger' }); };
  const updateProfile = async (data: FormData) => { if (!user || !campaign || !editingUser) return; const updated = await authenticatedFetch<OrgUser>(user, `/api/organizations/${campaign.orgId}/users/${editingUser.uid}`, { method: 'PUT', body: data }); await reloadPeople(); setEditingUser(null); setNotice({ message: `${updated.displayName} fue actualizado correctamente.`, variant: 'success' }); };
  const updateMember = async ({ functionId, teamId }: { functionId: string; teamId: string }) => { if (!user || !base || !editingMember) return; await authenticatedFetch(user, `${base}/members/${editingMember.uid}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role: editingMember.role, functionId: functionId || null, teamId: teamId || null }) }); await reloadPeople(); setNotice({ message: 'La asignación del miembro fue actualizada.', variant: 'success' }); };
  const unlinkMember = async () => { if (!user || !base || !removingMember) return; setRemovingMemberPending(true); try { await authenticatedFetch(user, `${base}/members/${removingMember.uid}`, { method: 'DELETE' }); await reloadPeople(); setNotice({ message: `${removingMember.displayName ?? removingMember.email} fue desvinculado de esta campaña.`, variant: 'success' }); setRemovingMember(null); } catch (caught) { setNotice({ message: caught instanceof Error ? caught.message : 'No pudimos desvincular al miembro.', variant: 'danger' }); } finally { setRemovingMemberPending(false); } };
  const deleteOrganizationUser = async () => { if (!user || !campaign || !deletingUser) return; setDeleting(true); try { await authenticatedFetch(user, `/api/organizations/${campaign.orgId}/users/${deletingUser.uid}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmEmail }) }); await reloadPeople(); setDeletingUser(null); setConfirmEmail(''); setNotice({ message: `${deletingUser.email} fue eliminado de la organización y de todas sus campañas.`, variant: 'success' }); } catch (caught) { setNotice({ message: caught instanceof Error ? caught.message : 'No pudimos eliminar la cuenta.', variant: 'danger' }); } finally { setDeleting(false); } };
  const memberControls = <Inline gap="sm" className="cd-users__filters"><SearchInput value={memberSearch} onChange={(event) => setMemberSearch(event.target.value)} placeholder="Buscar miembro…" aria-label="Buscar miembros de la campaña" /><SelectControl ariaLabel="Filtrar miembros por función" label={functions.find((item) => item.id === memberFunction)?.name ?? 'Todas las funciones'} value={memberFunction} options={[{ value: '', label: 'Todas las funciones' }, ...functions.map((item) => ({ value: item.id, label: item.name }))]} onChange={setMemberFunction} /><SelectControl ariaLabel="Filtrar miembros por equipo" label={teams.find((item) => item.id === memberTeam)?.name ?? 'Todos los equipos'} value={memberTeam} options={[{ value: '', label: 'Todos los equipos' }, ...teams.map((item) => ({ value: item.id, label: item.name }))]} onChange={setMemberTeam} /></Inline>;
  const orgControls = <SearchInput className="cd-users__org-search" value={orgSearch} onChange={(event) => setOrgSearch(event.target.value)} placeholder="Buscar usuario…" aria-label="Buscar usuarios de la organización" />;

  return <PageContainer><Stack gap="lg"><HeroBanner icon="users" title="Usuarios" subtitle="Gestioná a los colaboradores de tu campaña." subtitleDetail="Creá usuarios, asigná funciones y organizá el trabajo en equipo." tags={[]} ctaLabel="Crear usuario" onCtaClick={() => setShowCreate(true)} />
    <div className="cd-users__panels">
      <ContentPanel icon="users" title="Miembros de la campaña" subtitle="Personas vinculadas a la campaña activa." headerAction={memberControls}>{members.length ? <>{visibleMembers.length ? <div className="cd-table-scroll"><table className="cd-data-table cd-users-table"><thead><tr><th>USUARIO</th><th>CORREO</th><th>FUNCIÓN</th><th>EQUIPO</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{visibleMembers.map((member) => { const profile = orgUsers.find((person) => person.uid === member.uid); const functionName = functions.find((item) => item.id === member.functionId)?.name ?? 'Sin función'; const teamName = teams.find((item) => item.id === member.teamId)?.name ?? 'Sin equipo'; return <tr key={member.uid}><td><UserIdentity name={member.displayName || profile?.displayName} email={member.email} photoURL={profile?.photoURL} /></td><td>{member.email}</td><td><ValuePill tone={member.functionId ? 'function' : 'muted'}>{functionName}</ValuePill></td><td><ValuePill tone={member.teamId ? 'team' : 'muted'}>{teamName}</ValuePill></td><td><StatusPill /></td><td><RowActions subject={member.displayName ?? member.email} onEdit={() => setEditingMember(member)} onDelete={() => setRemovingMember(member)} /></td></tr>; })}</tbody></table></div> : <EmptyState icon="users" title="No encontramos miembros" description="Probá ajustar los filtros de función, equipo o búsqueda." />}{filteredMembers.length ? <TablePagination total={filteredMembers.length} visible={visibleMembers.length} label="miembros" page={memberPage} pageSize={memberPageSize} onPageChange={setMemberPage} onPageSizeChange={setMemberPageSize} /> : null}</> : <EmptyState icon="users" title="Aún no hay miembros" description="Creá un usuario para esta campaña." ctaLabel="Crear usuario" onCtaClick={() => setShowCreate(true)} />}</ContentPanel>
      <ContentPanel icon="users" title="Usuarios de la organización" subtitle="Incluye usuarios sin campaña asignada." headerAction={orgControls}>{orgUsers.length ? <>{visibleOrgUsers.length ? <div className="cd-table-scroll"><table className="cd-data-table cd-users-table"><thead><tr><th>USUARIO</th><th>CORREO</th><th>TELÉFONO</th><th>FUNCIÓN</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{visibleOrgUsers.map((person) => { const membership = members.find((member) => member.uid === person.uid); return <tr key={person.uid}><td><UserIdentity name={person.displayName} email={person.email} photoURL={person.photoURL} secondary={roleLabel(person.role)} /></td><td>{person.email}</td><td>{person.phone ?? '—'}</td><td><ValuePill tone="role">{roleLabel(person.role)}</ValuePill></td><td><StatusPill /></td><td><RowActions subject={person.displayName ?? person.email} onEdit={() => setEditingUser({ ...person, campaignId: membership ? campaign?.campId : '', functionId: membership?.functionId ?? '', teamId: membership?.teamId ?? '' })} onDelete={() => { setDeletingUser(person); setConfirmEmail(''); }} /></td></tr>; })}</tbody></table></div> : <EmptyState icon="users" title="No encontramos usuarios" description="Probá buscar por otro nombre o email." />}{filteredOrgUsers.length ? <TablePagination total={filteredOrgUsers.length} visible={visibleOrgUsers.length} label="usuarios" page={orgPage} pageSize={orgPageSize} onPageChange={setOrgPage} onPageSizeChange={setOrgPageSize} /> : null}</> : <EmptyState icon="users" title="Aún no hay usuarios" description="Creá el primer usuario." />}</ContentPanel>
    </div>
    <CreateUserModal show={showCreate} functions={functions} teams={teams} campaigns={campaign ? [{ id: campaign.campId, name: 'Campaña actual' }] : []} onHide={() => setShowCreate(false)} onSubmit={create} />
    <CreateUserModal show={Boolean(editingUser)} mode="edit" initialUser={editingUser} functions={functions} teams={teams} campaigns={campaign ? [{ id: campaign.campId, name: 'Campaña actual' }] : []} onHide={() => setEditingUser(null)} onSubmit={updateProfile} />
    <MemberAssignmentModal member={editingMember} functions={functions} teams={teams} onHide={() => setEditingMember(null)} onSave={updateMember} />
    <Modal show={Boolean(removingMember)} onHide={() => !removingMemberPending && setRemovingMember(null)}><Modal.Header closeButton><Modal.Title>Quitar miembro de la campaña</Modal.Title></Modal.Header><Modal.Body><Stack gap="sm"><p className="mb-0">¿Quitar a <strong>{removingMember?.displayName ?? removingMember?.email}</strong> de esta campaña?</p><p className="mb-0 text-muted small">La cuenta y su perfil global no se eliminarán.</p></Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setRemovingMember(null)} disabled={removingMemberPending}>Cancelar</Button><Button variant="danger" onClick={() => void unlinkMember()} disabled={removingMemberPending}>{removingMemberPending ? 'Quitando…' : 'Quitar de campaña'}</Button></Modal.Footer></Modal>
    <Modal show={Boolean(deletingUser)} onHide={() => !deleting && setDeletingUser(null)}><Modal.Header closeButton><Modal.Title>Eliminar cuenta de usuario</Modal.Title></Modal.Header><Modal.Body><Stack gap="md"><p className="mb-0">Esta acción elimina la cuenta de Firebase Authentication, el perfil, la foto y todas sus asignaciones de campaña. No se puede deshacer.</p><div><label className="form-label" htmlFor="confirm-delete-email">Para confirmar, escribí el email de la persona</label><input id="confirm-delete-email" className="form-control" value={confirmEmail} onChange={event => setConfirmEmail(event.target.value)} placeholder={deletingUser?.email} autoComplete="off" /></div></Stack></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setDeletingUser(null)} disabled={deleting}>Cancelar</Button><Button variant="danger" onClick={() => void deleteOrganizationUser()} disabled={deleting || confirmEmail.trim().toLowerCase() !== deletingUser?.email.toLowerCase()}>{deleting ? 'Eliminando…' : 'Eliminar cuenta'}</Button></Modal.Footer></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </Stack></PageContainer>;
}
