import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db, storage } from '../config/firebase.js';
import { appendAudit } from './audit.service.js';
import { assertCampaignAccess, campaignRef, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';

type TransactionType = 'ingreso' | 'egreso';
type TransactionStatus = 'pendiente' | 'confirmado';
const accountTypes = new Set(['banco', 'billetera_virtual', 'caja_chica']);
const transactionTypes = new Set<TransactionType>(['ingreso', 'egreso']);
const transactionStatuses = new Set<TransactionStatus>(['pendiente', 'confirmado']);
// Extensible when the Tesorería/Apoderado role is introduced in the next phase.
const financeRoles = new Set(['cliente', 'admin']);
const defaultCategories = [
  ['ingresos-aportes', 'Aportes', 'ingreso'], ['ingresos-donaciones', 'Donaciones', 'ingreso'], ['ingresos-eventos', 'Eventos', 'ingreso'], ['ingresos-otros', 'Otros ingresos', 'ingreso'],
  ['egresos-publicidad', 'Publicidad', 'egreso'], ['egresos-actos', 'Actos', 'egreso'], ['egresos-viaticos', 'Viáticos', 'egreso'], ['egresos-sueldos', 'Sueldos', 'egreso'], ['egresos-alquiler', 'Alquiler', 'egreso'], ['egresos-imprenta', 'Imprenta', 'egreso'], ['egresos-transporte', 'Transporte', 'egreso'], ['egresos-tecnologia', 'Tecnología', 'egreso'], ['egresos-otros', 'Otros egresos', 'egreso']
] as const;

const serialize = (snap: FirebaseFirestore.QueryDocumentSnapshot | FirebaseFirestore.DocumentSnapshot) => {
  const data = snap.data() ?? {};
  const date = (value: unknown) => value && typeof (value as any).toDate === 'function' ? (value as any).toDate().toISOString() : value ?? null;
  return { id: snap.id, ...data, createdAt: date(data.createdAt), updatedAt: date(data.updatedAt), date: date(data.date), dueDate: date(data.dueDate) };
};
const number = (value: unknown, name: string, min = 0) => { const parsed = Number(value); if (!Number.isFinite(parsed) || parsed < min) throw new ValidationError(`${name} no es válido.`); return parsed; };
const text = (value: unknown, name: string, max: number, required = false) => { const result = typeof value === 'string' ? value.trim() : ''; if (required && !result) throw new ValidationError(`${name} es obligatorio.`); return result.slice(0, max); };
const isoDate = (value: unknown) => { const raw = typeof value === 'string' ? value : ''; const parsed = new Date(raw); if (!raw || Number.isNaN(parsed.valueOf())) throw new ValidationError('La fecha no es válida.'); return parsed; };
const optionalDate = (value: unknown) => { if (value === undefined || value === null || value === '') return null; return isoDate(value); };
const currency = (value: unknown) => { const result = text(value ?? 'ARS', 'La moneda', 3, true).toUpperCase(); if (!/^[A-Z]{3}$/.test(result)) throw new ValidationError('La moneda debe ser un código ISO de tres letras.'); return result; };
const accountDetails = (input: any, type: string) => {
  if (type === 'caja_chica') return { currency: currency(input.currency), institutionName: '', bankCountry: '', branch: '', accountKind: '', accountNumber: '', holderName: '', holderTaxId: '', localBankCode: '', alias: '', swiftBic: '', iban: '' };
  const bankCountry = text(input.bankCountry, 'El país del banco', 2).toUpperCase();
  const localBankCode = text(input.localBankCode, 'El código bancario local', 40).replace(/\s/g, '');
  if (bankCountry === 'AR' && localBankCode && !/^\d{22}$/.test(localBankCode)) throw new ValidationError('El CBU/CVU argentino debe tener 22 dígitos.');
  return {
    currency: currency(input.currency), institutionName: text(input.institutionName, 'La institución', 140, true), bankCountry, branch: text(input.branch, 'La sucursal', 100), accountKind: text(input.accountKind, 'El tipo de cuenta', 80), accountNumber: text(input.accountNumber, 'El número de cuenta', 80), holderName: text(input.holderName, 'El titular', 180), holderTaxId: text(input.holderTaxId, 'La identificación fiscal', 60), localBankCode, alias: text(input.alias, 'El alias', 100), swiftBic: text(input.swiftBic, 'El SWIFT/BIC', 20).toUpperCase(), iban: text(input.iban, 'El IBAN', 40).replace(/\s/g, '').toUpperCase()
  };
};

/** Central Treo gate. Campaign accountant/treasurer roles are deliberately
 * resolved server-side from membership so the browser never grants access. */
export async function assertTreoAccess(user: DecodedIdToken, orgId: string, campId: string) {
  assertCampaignAccess(user, orgId, campId);
  if (!(await campaignRef(orgId, campId).get()).exists) throw new ForbiddenError('No tenés acceso a esta campaña.');
  const org = await db.collection('organizations').doc(orgId).get();
  if (org.data()?.enabledAddons?.finance !== true) throw new ForbiddenError('Treo no está habilitado en esta organización.');
  if (financeRoles.has(String(user.role))) return;
  const member = await campaignRef(orgId, campId).collection('members').doc(user.uid).get();
  const treoRole = String(member.data()?.treoRole ?? member.data()?.smartPlannerRole ?? '');
  if (!['contador', 'tesorero', 'apoderado'].includes(treoRole)) throw new ForbiddenError('Solo Cliente, Administrador, Contador o Tesorería pueden acceder a Treo.');
}
const financeAccess = assertTreoAccess;
const refs = (orgId: string, campId: string) => { const campaign = campaignRef(orgId, campId); return { campaign, accounts: campaign.collection('financeAccounts'), categories: campaign.collection('financeCategories'), transactions: campaign.collection('financeTransactions') }; };
async function seedCategories(orgId: string, campId: string) { const { categories } = refs(orgId, campId); const batch = db.batch(); defaultCategories.forEach(([id, name, type]) => batch.set(categories.doc(id), { orgId, campaignId: campId, name, type, system: true, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }, { merge: true })); await batch.commit(); }
async function audit(user: DecodedIdToken, orgId: string, campId: string, action: string, resource: string, resourceId: string, before: unknown, after: unknown) { await appendAudit(orgId, campId, user, { action, resource, resourceId, changes: { before, after } }); }

export async function recalculateAccount(orgId: string, campId: string, accountId: string) {
  const { accounts, transactions } = refs(orgId, campId); const account = await accounts.doc(accountId).get(); if (!account.exists) throw new NotFoundError('La cuenta no existe.');
  const all = await transactions.where('accountId', '==', accountId).where('status', '==', 'confirmado').get();
  const movements = all.docs.reduce((total, snapshot) => { const item = snapshot.data(); return total + (item.type === 'ingreso' ? Number(item.amount) : -Number(item.amount)); }, 0);
  const currentBalance = Number(account.data()?.initialBalance ?? 0) + movements;
  await account.ref.update({ currentBalance, updatedAt: FieldValue.serverTimestamp() }); return currentBalance;
}

export async function listAccounts(user: DecodedIdToken, orgId: string, campId: string) { await financeAccess(user, orgId, campId); const { accounts } = refs(orgId, campId); const snapshot = await accounts.orderBy('createdAt', 'desc').get(); const legacy = snapshot.docs.filter((item) => item.data().type === 'mercadopago'); if (legacy.length) { const batch = db.batch(); legacy.forEach((item) => batch.update(item.ref, { type: 'billetera_virtual', updatedAt: FieldValue.serverTimestamp() })); await batch.commit(); } return (await accounts.orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function createAccount(user: DecodedIdToken, orgId: string, campId: string, input: any) { await financeAccess(user, orgId, campId); const name = text(input.name, 'El nombre', 120, true); const type = text(input.type, 'El tipo', 40, true); if (!accountTypes.has(type)) throw new ValidationError('El tipo de cuenta no es válido.'); const initialBalance = number(input.initialBalance, 'El saldo inicial'); const ref = refs(orgId, campId).accounts.doc(); const document = { orgId, campaignId: campId, name, type, initialBalance, currentBalance: initialBalance, ...accountDetails(input, type), createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(document); await audit(user, orgId, campId, 'FINANCE_ACCOUNT_CREATED', 'financeAccount', ref.id, null, { name, type, initialBalance, currency: document.currency }); return serialize(await ref.get()); }
export async function updateAccount(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await financeAccess(user, orgId, campId); const ref = refs(orgId, campId).accounts.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('La cuenta no existe.'); const type = text(input.type, 'El tipo', 40, true) === 'mercadopago' ? 'billetera_virtual' : text(input.type, 'El tipo', 40, true); const changes = { name: text(input.name, 'El nombre', 120, true), type, initialBalance: number(input.initialBalance, 'El saldo inicial'), ...accountDetails(input, type), updatedAt: FieldValue.serverTimestamp() }; if (!accountTypes.has(changes.type)) throw new ValidationError('El tipo de cuenta no es válido.'); await ref.update(changes); await recalculateAccount(orgId, campId, id); const after = await ref.get(); await audit(user, orgId, campId, 'FINANCE_ACCOUNT_UPDATED', 'financeAccount', id, serialize(before), serialize(after)); return serialize(after); }
export async function deleteAccount(user: DecodedIdToken, orgId: string, campId: string, id: string) { await financeAccess(user, orgId, campId); const { accounts, transactions } = refs(orgId, campId); const ref = accounts.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('La cuenta no existe.'); if (!(await transactions.where('accountId', '==', id).limit(1).get()).empty) throw new ValidationError('No podés eliminar una cuenta con movimientos.'); await ref.delete(); await audit(user, orgId, campId, 'FINANCE_ACCOUNT_DELETED', 'financeAccount', id, serialize(before), null); }

export async function listCategories(user: DecodedIdToken, orgId: string, campId: string) { await financeAccess(user, orgId, campId); await seedCategories(orgId, campId); return (await refs(orgId, campId).categories.orderBy('name').get()).docs.map(serialize); }
export async function createCategory(user: DecodedIdToken, orgId: string, campId: string, input: any) { await financeAccess(user, orgId, campId); const name = text(input.name, 'El nombre', 100, true); const type = text(input.type, 'El tipo', 20, true); if (!transactionTypes.has(type as TransactionType)) throw new ValidationError('El tipo de categoría no es válido.'); const ref = refs(orgId, campId).categories.doc(); await ref.set({ orgId, campaignId: campId, name, type, system: false, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }); await audit(user, orgId, campId, 'FINANCE_CATEGORY_CREATED', 'financeCategory', ref.id, null, { name, type }); return serialize(await ref.get()); }
export async function updateCategory(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await financeAccess(user, orgId, campId); const ref = refs(orgId, campId).categories.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('La categoría no existe.'); const name = text(input.name, 'El nombre', 100, true); const type = text(input.type, 'El tipo', 20, true); if (!transactionTypes.has(type as TransactionType)) throw new ValidationError('El tipo de categoría no es válido.'); await ref.update({ name, type, updatedAt: FieldValue.serverTimestamp() }); const after = await ref.get(); await audit(user, orgId, campId, 'FINANCE_CATEGORY_UPDATED', 'financeCategory', id, serialize(before), serialize(after)); return serialize(after); }
export async function deleteCategory(user: DecodedIdToken, orgId: string, campId: string, id: string) { await financeAccess(user, orgId, campId); const { categories, transactions } = refs(orgId, campId); const ref = categories.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('La categoría no existe.'); if (before.data()?.system) throw new ValidationError('Las categorías iniciales no se eliminan. Podés crear categorías propias.'); if (!(await transactions.where('categoryId', '==', id).limit(1).get()).empty) throw new ValidationError('No podés eliminar una categoría usada por movimientos.'); await ref.delete(); await audit(user, orgId, campId, 'FINANCE_CATEGORY_DELETED', 'financeCategory', id, serialize(before), null); }

async function receiptFor(orgId: string, campId: string, transactionId: string, file?: Express.Multer.File) { if (!file) return null; if (!['image/jpeg', 'image/png', 'image/webp', 'application/pdf'].includes(file.mimetype)) throw new ValidationError('El comprobante debe ser una imagen JPG, PNG, WEBP o PDF.'); const extension = (file.originalname.split('.').pop() || 'bin').replace(/[^a-z0-9]/gi, '').toLowerCase(); const path = `organizations/${orgId}/campaigns/${campId}/finance/receipts/${transactionId}/${randomUUID()}.${extension}`; await storage.bucket().file(path).save(file.buffer, { resumable: false, contentType: file.mimetype, metadata: { cacheControl: 'private, max-age=0' } }); return { path, fileName: file.originalname.slice(0, 180), mimeType: file.mimetype, size: file.size }; }
function txInput(input: any) { const type = text(input.type, 'El tipo', 20, true) as TransactionType; const status = text(input.status ?? 'confirmado', 'El estado', 20, true) as TransactionStatus; if (!transactionTypes.has(type) || !transactionStatuses.has(status)) throw new ValidationError('El tipo o estado no es válido.'); const dueDate = optionalDate(input.dueDate); if (status !== 'pendiente' && dueDate) throw new ValidationError('La fecha de vencimiento o cobro solo corresponde a movimientos pendientes.'); return { type, status, amount: number(input.amount, 'El monto', 0.01), date: isoDate(input.date), dueDate, accountId: text(input.accountId, 'La cuenta', 120, true), categoryId: text(input.categoryId, 'La categoría', 120, true), paymentMethod: text(input.paymentMethod, 'El medio de pago', 80), description: text(input.description, 'La descripción', 1000), documentNumber: text(input.documentNumber, 'El número de comprobante', 100), currency: currency(input.currency), exchangeRate: number(input.exchangeRate ?? 1, 'El tipo de cambio', 0.000001), vendorId: type === 'egreso' ? text(input.vendorId, 'El proveedor', 120) : '', contributorId: type === 'ingreso' ? text(input.contributorId, 'El aportante', 120) : '', source: text(input.source, 'El origen/aportante', 180) }; }
async function validateTxRelations(orgId: string, campId: string, input: ReturnType<typeof txInput>) { const { accounts, categories, campaign } = refs(orgId, campId); const [account, category, party] = await Promise.all([accounts.doc(input.accountId).get(), categories.doc(input.categoryId).get(), input.vendorId ? campaign.collection('treoVendors').doc(input.vendorId).get() : input.contributorId ? campaign.collection('treoContributors').doc(input.contributorId).get() : Promise.resolve(null)]); if (!account.exists) throw new ValidationError('La cuenta elegida no existe.'); if (!category.exists || category.data()?.type !== input.type) throw new ValidationError('La categoría no corresponde al tipo de movimiento.'); if (party && !party.exists) throw new ValidationError(input.vendorId ? 'El proveedor no pertenece a esta campaña.' : 'El aportante no pertenece a esta campaña.'); }
export async function listTransactions(user: DecodedIdToken, orgId: string, campId: string, query: any) { await financeAccess(user, orgId, campId); const page = Math.max(1, Math.min(10000, Number(query.page ?? 1) || 1)); const pageSize = Math.max(1, Math.min(100, Number(query.pageSize ?? 20) || 20)); let rows = (await refs(orgId, campId).transactions.orderBy('date', 'desc').get()).docs.map(serialize) as any[]; for (const key of ['accountId', 'categoryId', 'type', 'status']) if (typeof query[key] === 'string' && query[key]) rows = rows.filter((row) => row[key] === query[key]); if (query.from) rows = rows.filter((row) => row.date >= new Date(String(query.from)).toISOString()); if (query.to) rows = rows.filter((row) => row.date <= new Date(`${String(query.to)}T23:59:59.999Z`).toISOString()); return { items: rows.slice((page - 1) * pageSize, pageSize), total: rows.length, page }; }
export async function createTransaction(user: DecodedIdToken, orgId: string, campId: string, input: any, file?: Express.Multer.File) { await financeAccess(user, orgId, campId); const values = txInput(input); await validateTxRelations(orgId, campId, values); const ref = refs(orgId, campId).transactions.doc(); const receipt = await receiptFor(orgId, campId, ref.id, file); await ref.set({ orgId, campaignId: campId, ...values, reconciliationStatus: 'pendiente', receipt, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }); if (values.status === 'confirmado') await recalculateAccount(orgId, campId, values.accountId); const after = await ref.get(); await audit(user, orgId, campId, 'FINANCE_TRANSACTION_CREATED', 'financeTransaction', ref.id, null, serialize(after)); return serialize(after); }
export async function updateTransaction(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any, file?: Express.Multer.File) { await financeAccess(user, orgId, campId); const ref = refs(orgId, campId).transactions.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El movimiento no existe.'); const values = txInput(input); await validateTxRelations(orgId, campId, values); const receipt = file ? await receiptFor(orgId, campId, id, file) : before.data()?.receipt ?? null; await ref.update({ ...values, receipt, reconciliationStatus: before.data()?.reconciliationStatus ?? 'pendiente', updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }); await Promise.all([...new Set([String(before.data()?.accountId), values.accountId])].map((accountId) => recalculateAccount(orgId, campId, accountId))); const after = await ref.get(); await audit(user, orgId, campId, 'FINANCE_TRANSACTION_UPDATED', 'financeTransaction', id, serialize(before), serialize(after)); return serialize(after); }
export async function deleteTransaction(user: DecodedIdToken, orgId: string, campId: string, id: string) { await financeAccess(user, orgId, campId); const ref = refs(orgId, campId).transactions.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El movimiento no existe.'); await ref.delete(); await recalculateAccount(orgId, campId, String(before.data()?.accountId)); await audit(user, orgId, campId, 'FINANCE_TRANSACTION_DELETED', 'financeTransaction', id, serialize(before), null); }
export async function receiptUrl(user: DecodedIdToken, orgId: string, campId: string, id: string) { await financeAccess(user, orgId, campId); const item = await refs(orgId, campId).transactions.doc(id).get(); if (!item.exists) throw new NotFoundError('El movimiento no existe.'); const receipt = item.data()?.receipt; if (!receipt?.path) throw new NotFoundError('Este movimiento no tiene comprobante.'); const [url] = await storage.bucket().file(receipt.path).getSignedUrl({ action: 'read', expires: Date.now() + 5 * 60 * 1000 }); return { url, fileName: receipt.fileName, mimeType: receipt.mimeType }; }
export async function dashboard(user: DecodedIdToken, orgId: string, campId: string) { await financeAccess(user, orgId, campId); const { accounts, transactions } = refs(orgId, campId); const [accountRows, txRows] = await Promise.all([accounts.get(), transactions.orderBy('date', 'asc').get()]); const tx = txRows.docs.map(serialize) as any[]; const confirmed = tx.filter((item) => item.status === 'confirmado'); const totalIncome = confirmed.filter((item) => item.type === 'ingreso').reduce((sum, item) => sum + Number(item.amount), 0); const totalExpense = confirmed.filter((item) => item.type === 'egreso').reduce((sum, item) => sum + Number(item.amount), 0); const byCategory = Object.values(confirmed.filter((item) => item.type === 'egreso').reduce((result: Record<string, any>, item) => { const key = item.categoryId; result[key] ??= { categoryId: key, label: key, amount: 0 }; result[key].amount += Number(item.amount); return result; }, {})); const timeline = Object.values(confirmed.reduce((result: Record<string, any>, item) => { const key = String(item.date).slice(0, 10); result[key] ??= { date: key, ingresos: 0, egresos: 0 }; result[key][item.type === 'ingreso' ? 'ingresos' : 'egresos'] += Number(item.amount); return result; }, {})); return { kpis: { totalIncome, totalExpense, balance: accountRows.docs.reduce((sum, item) => sum + Number(item.data().currentBalance ?? 0), 0), pending: tx.filter((item) => item.status === 'pendiente').length }, accounts: accountRows.docs.map(serialize), byCategory, timeline, transactions: tx }; }
