import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { assertCampaignAccess, assertCampaignManager, campaignRef, NotFoundError, ValidationError } from './access.service.js';

type Input = Record<string, unknown>;
const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const number = (value: unknown, fallback = 0) => typeof value === 'number' && Number.isFinite(value) ? value : fallback;
const serialize = (doc: FirebaseFirestore.QueryDocumentSnapshot | FirebaseFirestore.DocumentSnapshot) => ({ id: doc.id, ...doc.data() });
const assertText = (value: unknown, label: string) => { const result = text(value); if (!result) throw new ValidationError(`${label} es obligatorio.`); return result; };
const collection = (orgId: string, campId: string, name: string) => campaignRef(orgId, campId).collection(name);
const geocode = async (address: string) => { const key = process.env.GOOGLE_MAPS_API_KEY; if (!key) return { lat: null, lng: null }; const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${key}`); const data = await response.json() as { status?: string; results?: Array<{ geometry?: { location?: { lat?: number; lng?: number } } }> }; const location = data.results?.[0]?.geometry?.location; return data.status === 'OK' && typeof location?.lat === 'number' && typeof location.lng === 'number' ? { lat: location.lat, lng: location.lng } : { lat: null, lng: null }; };
const pointInside = (lat: number, lng: number, polygon: Array<{ lat: number; lng: number }>) => { let inside = false; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) { const a = polygon[i]; const b = polygon[j]; const intersects = ((a.lng > lng) !== (b.lng > lng)) && lat < (b.lat - a.lat) * (lng - a.lng) / (b.lng - a.lng) + a.lat; if (intersects) inside = !inside; } return inside; };

export async function listCalendar(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'calendar').orderBy('date').get(); return snap.docs.filter(doc => !doc.data().deleted).map(serialize); }
export async function createCalendar(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const type = text(input.type); if (!['election', 'veda', 'event'].includes(type)) throw new ValidationError('El tipo de evento no es válido.'); const date = assertText(input.date, 'La fecha'); const title = assertText(input.title, 'El título'); const ref = collection(orgId, campId, 'calendar').doc(); const data = { type, date, title, description: text(input.description), createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(data); return { eventId: ref.id, ...data }; }
export async function updateCalendar(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'calendar').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('El evento no existe.'); const type = text(input.type); if (!['election', 'veda', 'event'].includes(type)) throw new ValidationError('El tipo de evento no es válido.'); const data = { type, date: assertText(input.date, 'La fecha'), title: assertText(input.title, 'El título'), description: text(input.description), updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { eventId: id, ...data }; }
export async function deleteCalendar(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'calendar').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }

export async function listCircuitos(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'circuitos').get(); return snap.docs.filter(doc => !doc.data().deleted).map(serialize); }
const cleanSchools = async (value: unknown) => Promise.all((Array.isArray(value) ? value : []).map(async value => { const school = value as Input; const name = assertText(school.name, 'El nombre de la escuela'); const address = assertText(school.address, 'La dirección de la escuela'); const lat = number(school.lat, NaN); const lng = number(school.lng, NaN); return { name, address, ...(Number.isFinite(lat) && Number.isFinite(lng) ? { lat, lng } : await geocode(address)) }; }));
export async function createCircuito(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'circuitos').doc(); const data = { name: assertText(input.name, 'El nombre del circuito'), district: assertText(input.district, 'El distrito'), schools: await cleanSchools(input.schools), leaderId: text(input.leaderId) || null, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { circuitoId: ref.id, ...data }; }
export async function updateCircuito(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const existing = await collection(orgId, campId, 'circuitos').doc(id).get(); if (!existing.exists) throw new NotFoundError('El circuito no existe.'); const data = { name: assertText(input.name, 'El nombre del circuito'), district: assertText(input.district, 'El distrito'), schools: await cleanSchools(input.schools), leaderId: text(input.leaderId) || null, updatedAt: FieldValue.serverTimestamp() }; await existing.ref.update(data); return { circuitoId: id, ...data }; }
export async function deleteCircuito(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'circuitos').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }

const cleanPolygon = (value: unknown) => { const polygon = Array.isArray(value) ? value.map(point => ({ lat: number((point as Input).lat, NaN), lng: number((point as Input).lng, NaN) })) : []; if (polygon.length < 3 || polygon.some(point => !Number.isFinite(point.lat) || !Number.isFinite(point.lng))) throw new ValidationError('La zona necesita al menos tres puntos válidos.'); return polygon; };
export async function listZones(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'zones').get(); return snap.docs.filter(doc => !doc.data().deleted).map(serialize); }
export async function createZone(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const circuitoId = assertText(input.circuitoId, 'El circuito'); if (!(await collection(orgId, campId, 'circuitos').doc(circuitoId).get()).exists) throw new ValidationError('El circuito seleccionado no existe.'); const ref = collection(orgId, campId, 'zones').doc(); const data = { name: assertText(input.name, 'El nombre de la zona'), neighborhood: text(input.neighborhood), circuitoId, leaderId: text(input.leaderId) || null, polygon: cleanPolygon(input.polygon), createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { zoneId: ref.id, ...data }; }
export async function updateZone(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'zones').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('La zona no existe.'); const data = { name: assertText(input.name, 'El nombre de la zona'), neighborhood: text(input.neighborhood), circuitoId: assertText(input.circuitoId, 'El circuito'), leaderId: text(input.leaderId) || null, polygon: cleanPolygon(input.polygon), updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { zoneId: id, ...data }; }
export async function deleteZone(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'zones').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }
export async function zoneVoters(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignAccess(user, orgId, campId); const zone = await collection(orgId, campId, 'zones').doc(id).get(); if (!zone.exists) throw new NotFoundError('La zona no existe.'); const polygon = zone.data()?.polygon as Array<{ lat: number; lng: number }> ?? []; const voters = await collection(orgId, campId, 'voters').get(); return voters.docs.map(serialize).filter((voter) => { const data = voter as Input; return typeof data.lat === 'number' && typeof data.lng === 'number' && pointInside(data.lat, data.lng, polygon); }); }

const progressFor = async (orgId: string, campId: string, goal: Input) => { const voters = await collection(orgId, campId, 'voters').get(); const type = goal.type; const count = voters.docs.filter(doc => type === 'coverage' ? doc.data().state !== 'unvisited' : doc.data().state === 'converted_yes').length; return count; };
export async function listGoals(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'goals').get(); return Promise.all(snap.docs.filter(doc => !doc.data().deleted).map(async doc => ({ ...serialize(doc), progress: await progressFor(orgId, campId, doc.data()) }))); }
export async function createGoal(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const type = text(input.type); if (!['coverage', 'conversion'].includes(type)) throw new ValidationError('El tipo de meta no es válido.'); const target = number(input.target, NaN); if (!Number.isFinite(target) || target <= 0) throw new ValidationError('La meta debe ser mayor que cero.'); const ref = collection(orgId, campId, 'goals').doc(); const data = { type, target, zoneId: text(input.zoneId) || null, functionId: text(input.functionId) || null, description: text(input.description), progress: 0, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { goalId: ref.id, ...data }; }
export async function updateGoal(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'goals').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('La meta no existe.'); const target = number(input.target, NaN); if (!Number.isFinite(target) || target <= 0) throw new ValidationError('La meta debe ser mayor que cero.'); const data = { type: text(input.type), target, zoneId: text(input.zoneId) || null, functionId: text(input.functionId) || null, description: text(input.description), updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { goalId: id, ...data }; }
export async function deleteGoal(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'goals').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }
export async function completeReachedGoals(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const goals = await collection(orgId, campId, 'goals').get(); const completed: Array<{ goalId: string; description: string; progress: number; target: number }> = []; for (const goal of goals.docs) { const data = goal.data(); if (data.deleted || data.completedAt) continue; const progress = await progressFor(orgId, campId, data); const target = number(data.target, Number.MAX_SAFE_INTEGER); if (progress >= target) { await goal.ref.update({ progress, completedAt: FieldValue.serverTimestamp(), completedBy: user.uid }); completed.push({ goalId: goal.id, description: text(data.description) || 'Objetivo de campaña', progress, target }); } } return completed; }

const routeVoters = (value: unknown) => Array.isArray(value) ? value.map(item => ({ voterId: text((item as Input).voterId) })).filter(item => item.voterId) : [];
const estimateRoute = (voters: Array<{ voterId: string }>) => Math.max(0, voters.length * 9);
export async function listRoutes(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'routes').get(); return snap.docs.filter(doc => !doc.data().deleted).map(serialize); }
export async function createRoute(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const voters = routeVoters(input.voters); if (!voters.length) throw new ValidationError('La ruta necesita al menos un elector.'); const ref = collection(orgId, campId, 'routes').doc(); const data = { name: assertText(input.name, 'El nombre de la ruta'), assignedUid: assertText(input.assignedUid, 'El militante'), voters, estimatedTime: number(input.estimatedTime, estimateRoute(voters)), assignedDate: text(input.assignedDate) || new Date().toISOString().slice(0, 10), status: ['pending', 'in_progress', 'completed'].includes(text(input.status)) ? text(input.status) : 'pending', createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { routeId: ref.id, ...data }; }
export async function updateRoute(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'routes').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('La ruta no existe.'); const voters = routeVoters(input.voters); const data = { name: assertText(input.name, 'El nombre de la ruta'), assignedUid: assertText(input.assignedUid, 'El militante'), voters, estimatedTime: number(input.estimatedTime, estimateRoute(voters)), status: ['pending', 'in_progress', 'completed'].includes(text(input.status)) ? text(input.status) : 'pending', updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { routeId: id, ...data }; }
export async function optimizeRoute(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignAccess(user, orgId, campId); const route = await collection(orgId, campId, 'routes').doc(id).get(); if (!route.exists) throw new NotFoundError('La ruta no existe.'); const voters = routeVoters(route.data()?.voters); const voterDocs = await Promise.all(voters.map(async voter => ({ ...voter, ...((await collection(orgId, campId, 'voters').doc(voter.voterId).get()).data() ?? {}) }))); return { waypoints: voterDocs.map((voter, index) => ({ voterId: voter.voterId, address: text((voter as Input).address), order: index + 1 })), estimatedTime: number(route.data()?.estimatedTime, estimateRoute(voters)), optimized: false, message: 'Orden de prueba: configurá Google Maps para optimización avanzada.' }; }
export async function autoDistributeRoutes(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignManager(user, orgId, campId); const [members, voters, routes] = await Promise.all([collection(orgId, campId, 'members').get(), collection(orgId, campId, 'voters').get(), collection(orgId, campId, 'routes').get()]); const assigned = new Set(routes.docs.flatMap(doc => routeVoters(doc.data().voters).map(item => item.voterId))); const agents = members.docs.filter(doc => ['cliente', 'admin', 'usuario'].includes(String(doc.data().role))).map(doc => doc.id); const pending = voters.docs.filter(doc => !assigned.has(doc.id)); if (!agents.length || !pending.length) return []; const buckets = new Map(agents.map(id => [id, [] as Array<{ voterId: string }>])); pending.forEach((voter, index) => buckets.get(agents[index % agents.length])!.push({ voterId: voter.id })); const created = []; for (const [uid, voterList] of buckets) if (voterList.length) created.push(await createRoute(user, orgId, campId, { name: `Ruta ${created.length + 1}`, assignedUid: uid, voters: voterList })); return created; }

export async function listSurveys(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'surveys').get(); return snap.docs.filter(doc => !doc.data().deleted).map(serialize); }
export async function createSurvey(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const type = text(input.type); if (!['pre_campaign', 'post_visit'].includes(type)) throw new ValidationError('El tipo de encuesta no es válido.'); const questions = Array.isArray(input.questions) ? input.questions : []; const ref = collection(orgId, campId, 'surveys').doc(); const data = { name: assertText(input.name, 'El nombre de la encuesta'), type, questions, zoneId: text(input.zoneId) || null, functionId: text(input.functionId) || null, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { surveyId: ref.id, ...data }; }
export async function updateSurvey(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'surveys').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('La encuesta no existe.'); const data = { name: assertText(input.name, 'El nombre de la encuesta'), type: text(input.type), questions: Array.isArray(input.questions) ? input.questions : [], zoneId: text(input.zoneId) || null, functionId: text(input.functionId) || null, updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { surveyId: id, ...data }; }
export async function deleteSurvey(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'surveys').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }

export async function listBudgets(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'budgets').get(); const items = snap.docs.filter(doc => !doc.data().deleted).map(serialize); const totalAmount = items.reduce((sum, item) => sum + number((item as Input).amount), 0); const totalSpent = items.reduce((sum, item) => sum + number((item as Input).spent), 0); return { items, totalAmount, totalSpent, available: totalAmount - totalSpent, consumedPercent: totalAmount ? Math.round(totalSpent / totalAmount * 100) : 0 }; }
export async function createBudget(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignManager(user, orgId, campId); const amount = number(input.amount, NaN); if (!Number.isFinite(amount) || amount < 0) throw new ValidationError('El monto no es válido.'); const ref = collection(orgId, campId, 'budgets').doc(); const data = { category: assertText(input.category, 'La categoría'), amount, spent: number(input.spent, 0), description: text(input.description), createdAt: FieldValue.serverTimestamp(), createdBy: user.uid, deleted: false }; await ref.set(data); return { budgetId: ref.id, ...data }; }
export async function updateBudget(user: DecodedIdToken, orgId: string, campId: string, id: string, input: Input) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'budgets').doc(id); if (!(await ref.get()).exists) throw new NotFoundError('La línea presupuestaria no existe.'); const amount = number(input.amount, NaN); if (!Number.isFinite(amount) || amount < 0) throw new ValidationError('El monto no es válido.'); const data = { category: assertText(input.category, 'La categoría'), amount, spent: number(input.spent, 0), description: text(input.description), updatedAt: FieldValue.serverTimestamp() }; await ref.update(data); return { budgetId: id, ...data }; }
export async function deleteBudget(user: DecodedIdToken, orgId: string, campId: string, id: string) { assertCampaignManager(user, orgId, campId); await collection(orgId, campId, 'budgets').doc(id).update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }

export async function listSuggestions(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await collection(orgId, campId, 'aiSuggestions').orderBy('createdAt', 'desc').get(); return snap.docs.map(serialize); }
export async function requestSuggestions(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignManager(user, orgId, campId); const ref = collection(orgId, campId, 'aiSuggestions'); const today = new Date(); today.setHours(0, 0, 0, 0); const latest = await ref.where('createdAt', '>=', Timestamp.fromDate(today)).limit(1).get(); if (!latest.empty) throw new ValidationError('El análisis ya fue solicitado hoy. Volvé a intentarlo mañana.'); const voters = await collection(orgId, campId, 'voters').get(); const undecided = voters.docs.filter(doc => doc.data().state === 'undecided').length; const apiKey = process.env.GEMINI_API_KEY; if (!apiKey) throw new ValidationError('Configurá GEMINI_API_KEY para activar el Asesor de Estrategia.'); const prompt = `Sos asesor de una campaña política. Redactá UNA recomendación concreta, prudente y accionable en español rioplatense, de máximo 80 palabras. Usá sólo estos datos: electores totales ${voters.size}, indecisos ${undecided}. No inventes cifras ni datos. Incluí una acción para las próximas 48 horas.`; const model = process.env.GEMINI_MODEL ?? 'gemini-flash-latest'; const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(apiKey)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { temperature: 0.35 } }) }); if (!response.ok) throw new ValidationError(`Gemini no pudo generar recomendaciones (${response.status}).`); const payload = await response.json() as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> }; const content = payload.candidates?.[0]?.content?.parts?.map(part => part.text ?? '').join('').trim(); if (!content) throw new ValidationError('Gemini devolvió una recomendación vacía.'); const doc = ref.doc(); const suggestion = { type: 'gemini_strategy', content, reasoning: `Análisis generado con Gemini sobre ${voters.size} electores y ${undecided} indecisos.`, potential_gain: 'Prioridad operativa para las próximas 48 horas', createdAt: FieldValue.serverTimestamp(), feedback: 'pending', source: 'gemini', requestedBy: user.uid }; await doc.set(suggestion); return [{ suggestionId: doc.id, ...suggestion }]; }
export async function setSuggestionFeedback(user: DecodedIdToken, orgId: string, campId: string, id: string, feedback: string) { assertCampaignManager(user, orgId, campId); if (!['ignored', 'applied', 'modified'].includes(feedback)) throw new ValidationError('El feedback no es válido.'); await collection(orgId, campId, 'aiSuggestions').doc(id).update({ feedback, feedbackAt: FieldValue.serverTimestamp(), feedbackBy: user.uid }); }
