import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { assertCampaignAccess, assertCampaignAdmin, campaignRef, NotFoundError, ValidationError } from './access.service.js';

type Question = { id?: string; text?: string; type?: string; isRequired?: boolean; options?: Array<{ label?: string; value?: string }> };
type Input = { name?: string; questions?: Question[]; active?: boolean };
function clean(input: Input) { const name = input.name?.trim(); if (!name) throw new ValidationError('El nombre del conjunto es obligatorio.'); const questions = (input.questions ?? []).map((question, index) => { const text = question.text?.trim(); if (!text) throw new ValidationError(`La pregunta ${index + 1} no tiene texto.`); const type = ['radio', 'checkbox', 'text'].includes(question.type ?? '') ? question.type! : 'text'; return { id: question.id?.trim() || `q_${Date.now()}_${index}`, text, type, isRequired: Boolean(question.isRequired), options: type === 'text' ? [] : (question.options ?? []).filter(option => option.label?.trim()).map(option => ({ label: option.label!.trim(), value: option.value?.trim() || option.label!.trim() })) }; }); return { name, questions, active: input.active !== false }; }
export async function listQuestionSets(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await campaignRef(orgId, campId).collection('questionSets').orderBy('updatedAt', 'desc').get(); return snap.docs.map(doc => ({ id: doc.id, ...doc.data() })); }
export async function getActiveQuestionSet(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await campaignRef(orgId, campId).collection('questionSets').where('active', '==', true).limit(1).get(); return snap.empty ? { active: null } : { active: { id: snap.docs[0].id, ...snap.docs[0].data() } }; }
export async function createQuestionSet(user: DecodedIdToken, orgId: string, campId: string, input: Input) { assertCampaignAdmin(user, orgId, campId); const data = clean(input); const campaign = campaignRef(orgId, campId); const ref = campaign.collection('questionSets').doc(); const batch = campaign.firestore.batch(); if (data.active) { const active = await campaign.collection('questionSets').where('active', '==', true).get(); active.docs.forEach(doc => batch.update(doc.ref, { active: false, updatedAt: FieldValue.serverTimestamp() })); } batch.set(ref, { ...data, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }); await batch.commit(); return { id: ref.id, ...data }; }
export async function updateQuestionSet(user: DecodedIdToken, orgId: string, campId: string, setId: string, input: Input) { assertCampaignAdmin(user, orgId, campId); const campaign = campaignRef(orgId, campId); const ref = campaign.collection('questionSets').doc(setId); if (!(await ref.get()).exists) throw new NotFoundError('El conjunto de preguntas no existe.'); const data = clean(input); const batch = campaign.firestore.batch(); if (data.active) { const active = await campaign.collection('questionSets').where('active', '==', true).get(); active.docs.filter(doc => doc.id !== setId).forEach(doc => batch.update(doc.ref, { active: false, updatedAt: FieldValue.serverTimestamp() })); } batch.update(ref, { ...data, updatedAt: FieldValue.serverTimestamp(), updatedBy: user.uid }); await batch.commit(); return { id: setId, ...data }; }

