import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db, storage } from '../config/firebase.js';
import { assertCampaignAccess, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';

const campaign = (orgId: string, campId: string) => db.collection('organizations').doc(orgId).collection('campaigns').doc(campId);
const invoiceTypes = ['factura', 'nota_credito']; const invoiceStatuses = ['borrador', 'emitida', 'pagada', 'anulada']; const contractStatuses = ['borrador', 'enviado', 'firmado', 'cancelado'];
const serialize = (doc: FirebaseFirestore.QueryDocumentSnapshot) => ({ id: doc.id, ...doc.data(), createdAt: doc.data().createdAt?.toDate?.().toISOString?.() ?? null });
async function readable(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const organization = await db.collection('organizations').doc(orgId).get(); if (organization.data()?.enabledAddons?.smartPlanner !== true) throw new ForbiddenError('SmartPlanner no está habilitado en el plan de esta organización.'); }
async function writable(user: DecodedIdToken, orgId: string, campId: string) { await readable(user, orgId, campId); if (['cliente', 'admin'].includes(String(user.role))) return; const member = await campaign(orgId, campId).collection('members').doc(user.uid).get(); if (!['contador', 'pm'].includes(String(member.data()?.smartPlannerRole ?? 'miembro'))) throw new ForbiddenError('Solo Contador, PM o Cliente puede administrar finanzas.'); }
const money = (value: unknown) => { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? Math.max(0, parsed) : 0; };

export async function listInvoices(user: DecodedIdToken, orgId: string, campId: string) { await readable(user, orgId, campId); return (await campaign(orgId, campId).collection('spInvoices').orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function saveInvoice(user: DecodedIdToken, orgId: string, campId: string, invoiceId: string | null, input: Record<string, unknown>) { await writable(user, orgId, campId); const type = String(input.type ?? 'factura'); const status = String(input.status ?? 'borrador'); const description = String(input.description ?? '').trim(); if (!description || !invoiceTypes.includes(type) || !invoiceStatuses.includes(status)) throw new ValidationError('Tipo, estado o descripción de factura inválidos.'); const ref = invoiceId ? campaign(orgId, campId).collection('spInvoices').doc(invoiceId) : campaign(orgId, campId).collection('spInvoices').doc(); if (invoiceId && !(await ref.get()).exists) throw new NotFoundError('Factura no encontrada.'); const data = { type, status, description, amount: money(input.amount), providerId: String(input.providerId ?? ''), issuedDate: String(input.issuedDate ?? ''), baseInvoiceId: String(input.baseInvoiceId ?? '') }; await ref.set({ ...data, ...(invoiceId ? { updatedAt: FieldValue.serverTimestamp() } : { createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }) }, { merge: true }); return { id: ref.id, ...data }; }
export async function createCreditNote(user: DecodedIdToken, orgId: string, campId: string, invoiceId: string, input: Record<string, unknown>) { await writable(user, orgId, campId); const invoice = await campaign(orgId, campId).collection('spInvoices').doc(invoiceId).get(); if (!invoice.exists || invoice.data()?.type !== 'factura') throw new ValidationError('La factura original no existe o no admite nota de crédito.'); return saveInvoice(user, orgId, campId, null, { type: 'nota_credito', status: 'emitida', description: input.description || `Nota de crédito de ${invoice.data()?.description}`, amount: input.amount ?? invoice.data()?.amount, providerId: invoice.data()?.providerId ?? '', issuedDate: input.issuedDate ?? new Date().toISOString().slice(0, 10), baseInvoiceId: invoiceId }); }
export async function removeInvoice(user: DecodedIdToken, orgId: string, campId: string, invoiceId: string) { await writable(user, orgId, campId); await campaign(orgId, campId).collection('spInvoices').doc(invoiceId).delete(); }
export async function listContracts(user: DecodedIdToken, orgId: string, campId: string) { await readable(user, orgId, campId); return (await campaign(orgId, campId).collection('spContracts').orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function saveContract(user: DecodedIdToken, orgId: string, campId: string, contractId: string | null, input: Record<string, unknown>) { await writable(user, orgId, campId); const title = String(input.title ?? '').trim(); const status = String(input.status ?? 'borrador'); if (!title || !contractStatuses.includes(status)) throw new ValidationError('Título o estado de contrato inválidos.'); const ref = contractId ? campaign(orgId, campId).collection('spContracts').doc(contractId) : campaign(orgId, campId).collection('spContracts').doc(); if (contractId && !(await ref.get()).exists) throw new NotFoundError('Contrato no encontrado.'); const data = { title, providerId: String(input.providerId ?? ''), description: String(input.description ?? ''), amount: money(input.amount), status, startDate: String(input.startDate ?? ''), endDate: String(input.endDate ?? '') }; await ref.set({ ...data, ...(contractId ? { updatedAt: FieldValue.serverTimestamp() } : { createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }) }, { merge: true }); return { id: ref.id, ...data }; }
export async function signContract(user: DecodedIdToken, orgId: string, campId: string, contractId: string, signature?: Express.Multer.File) { await writable(user, orgId, campId); if (!signature?.buffer) throw new ValidationError('La firma electrónica es obligatoria.'); const ref = campaign(orgId, campId).collection('spContracts').doc(contractId); if (!(await ref.get()).exists) throw new NotFoundError('Contrato no encontrado.'); const path = `smartplanner/contracts/${orgId}/${campId}/${contractId}/signature-${Date.now()}.png`; const token = randomUUID(); await storage.bucket().file(path).save(signature.buffer, { resumable: false, contentType: signature.mimetype || 'image/png', metadata: { metadata: { firebaseStorageDownloadTokens: token } } }); const signatureUrl = `gs://${storage.bucket().name}/${path}`; await ref.set({ status: 'firmado', signatureUrl, signatureToken: token, signedAt: FieldValue.serverTimestamp(), signedBy: user.uid }, { merge: true }); return { id: contractId, signatureUrl, status: 'firmado' }; }
export async function removeContract(user: DecodedIdToken, orgId: string, campId: string, contractId: string) { await writable(user, orgId, campId); const ref = campaign(orgId, campId).collection('spContracts').doc(contractId); const document = await ref.get(); if (!document.exists) throw new NotFoundError('Contrato no encontrado.'); const signatureUrl = String(document.data()?.signatureUrl ?? ''); if (signatureUrl.startsWith('gs://')) await storage.bucket().file(signatureUrl.replace(/^gs:\/\/[^/]+\//, '')).delete({ ignoreNotFound: true }); await ref.delete(); }
