import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { db } from '../config/firebase.js';
import { assertCampaignAccess, campaignAuthorizationPolicy, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';
import { createNotification } from './notifications.service.js';
const camp=(o:string,c:string)=>db.collection('organizations').doc(o).collection('campaigns').doc(c);
async function access(u:DecodedIdToken,o:string,c:string,write=false){assertCampaignAccess(u,o,c);const org=await db.collection('organizations').doc(o).get();if(org.data()?.enabledAddons?.smartPlanner!==true)throw new ForbiddenError('SmartPlanner no está habilitado.');if(write&&!campaignAuthorizationPolicy.collaboratorsManageCampaignResources&&!['cliente','admin'].includes(String(u.role))){const m=await camp(o,c).collection('members').doc(u.uid).get();if(m.data()?.smartPlannerRole!=='pm')throw new ForbiddenError('Solo PM o Cliente puede administrar este flujo.');}}
const out=(d:any)=>({id:d.id,...d.data(),createdAt:d.data().createdAt?.toDate?.().toISOString?.()??null});
async function notifyCampaign(o:string,c:string,exclude:string,input:{type:string;title:string;message:string;metadata?:Record<string,unknown>}){const members=await camp(o,c).collection('members').get();await Promise.all(members.docs.filter(member=>member.id!==exclude).map(member=>createNotification(member.id,input)));}
export async function protocols(u:DecodedIdToken,o:string,c:string){await access(u,o,c);return (await camp(o,c).collection('spCrisisProtocols').orderBy('createdAt','desc').get()).docs.map(out)}
export async function saveProtocol(u:DecodedIdToken,o:string,c:string,id:string|null,x:any){await access(u,o,c,true);const name=String(x.name??'').trim();if(!name)throw new ValidationError('El nombre es obligatorio.');const templates=Array.isArray(x.taskTemplates)?x.taskTemplates:[];const ref=id?camp(o,c).collection('spCrisisProtocols').doc(id):camp(o,c).collection('spCrisisProtocols').doc();await ref.set({name,description:String(x.description??''),taskTemplates:templates,...(id?{updatedAt:FieldValue.serverTimestamp()}:{createdAt:FieldValue.serverTimestamp()})},{merge:true});return{id:ref.id,name,description:String(x.description??''),taskTemplates:templates}}
export async function activate(u:DecodedIdToken,o:string,c:string,id:string,reason:unknown){await access(u,o,c,true);const p=await camp(o,c).collection('spCrisisProtocols').doc(id).get();if(!p.exists)throw new NotFoundError('El protocolo no existe.');const why=String(reason??'').trim();if(!why)throw new ValidationError('Indicá el motivo de la activación.');const areas=await camp(o,c).collection('spAreas').get();const activation=camp(o,c).collection('spCrisisActivations').doc();const tasks:any[]=[];for(const t of (p.data()?.taskTemplates??[])){const role=String(t.assignedRole??'');const fallback=areas.docs.find(a=>a.data().name==='Jurídico'&&/legal/i.test(role))??areas.docs.find(a=>a.data().name==='Comunicación'&&/(prensa|diseño|diseno)/i.test(role))??areas.docs[0];const areaId=String(t.areaId??fallback?.id??'');if(!areaId)throw new ValidationError('Cada tarea del protocolo necesita un área.');const ref=camp(o,c).collection('spTasks').doc();tasks.push(ref);await ref.set({title:String(t.title??'Tarea de crisis'),description:String(t.description??''),areaId,assignedTo:String(t.assignedTo??u.uid),assignedRole:role,status:'por_hacer',priority:'alta',startDate:new Date().toISOString().slice(0,10),dueDate:new Date().toISOString().slice(0,10),cost:0,fromCrisisActivation:activation.id,createdAt:FieldValue.serverTimestamp()});}await activation.set({protocolId:id,activatedBy:u.uid,activatedAt:FieldValue.serverTimestamp(),reason:why,generatedTaskIds:tasks.map(t=>t.id)});await notifyCampaign(o,c,u.uid,{type:'smartplanner_crisis_activated',title:'Protocolo de crisis activado',message:`${p.data()?.name??'Un protocolo'} fue activado: ${why}`,metadata:{path:'/smartplanner/war-room',orgId:o,campId:c,activationId:activation.id}});return{id:activation.id,generatedTaskIds:tasks.map(t=>t.id)}}
export async function listActivations(u:DecodedIdToken,o:string,c:string){await access(u,o,c);return (await camp(o,c).collection('spCrisisActivations').orderBy('activatedAt','desc').get()).docs.map(out)}
export async function promises(u:DecodedIdToken,o:string,c:string){await access(u,o,c);return (await camp(o,c).collection('spPromises').orderBy('createdAt','desc').get()).docs.map(out)}
export async function savePromise(u:DecodedIdToken,o:string,c:string,id:string|null,x:any){await access(u,o,c);const title=String(x.title??'').trim();if(!title)throw new ValidationError('El título es obligatorio.');const ref=id?camp(o,c).collection('spPromises').doc(id):camp(o,c).collection('spPromises').doc();const old=id?await ref.get():null;if(old?.exists&&old.data()?.status!=='propuesta')throw new ForbiddenError('La propuesta ya no puede editarse.');await ref.set({title,description:String(x.description??''),status:'propuesta',...(id?{updatedAt:FieldValue.serverTimestamp()}:{createdAt:FieldValue.serverTimestamp(),createdBy:u.uid})},{merge:true});return{id:ref.id,title}}
export async function legal(u:DecodedIdToken,o:string,c:string,id:string,action:'submit'|'approve'|'reject',x:any){await access(u,o,c,action!=='submit');const ref=camp(o,c).collection('spPromises').doc(id);const p=await ref.get();if(!p.exists)throw new NotFoundError('La propuesta no existe.');const promise=p.data()??{};if(action==='submit'){await ref.update({status:'en_revision_legal'});return{status:'en_revision_legal'}}if(action==='reject'){const legalNotes=String(x.reason??'').trim();if(!legalNotes)throw new ValidationError('Indicá el motivo del rechazo.');await ref.update({status:'rechazada',legalReviewedBy:u.uid,legalReviewedAt:FieldValue.serverTimestamp(),legalNotes});if(promise.createdBy&&promise.createdBy!==u.uid)await createNotification(promise.createdBy,{type:'smartplanner_legal_rejected',title:'Propuesta rechazada por Jurídico',message:`${promise.title}: ${legalNotes}`,metadata:{path:'/smartplanner/promises',orgId:o,campId:c,promiseId:id}});return{status:'rechazada'}}let linkedTaskId='';if(x.createTask!==false){const area=(await camp(o,c).collection('spAreas').where('name','==','Comunicación').limit(1).get()).docs[0];if(area){const t=camp(o,c).collection('spTasks').doc();linkedTaskId=t.id;await t.set({title:`Difusión: ${promise.title}`,description:promise.description??'',areaId:area.id,assignedTo:u.uid,status:'por_hacer',priority:'media',startDate:'',dueDate:new Date().toISOString().slice(0,10),cost:0,createdAt:FieldValue.serverTimestamp()});}}await ref.update({status:'aprobada',legalReviewedBy:u.uid,legalReviewedAt:FieldValue.serverTimestamp(),legalNotes:String(x.notes??''),linkedTaskId});if(promise.createdBy&&promise.createdBy!==u.uid)await createNotification(promise.createdBy,{type:'smartplanner_legal_approved',title:'Propuesta aprobada por Jurídico',message:String(promise.title??'La propuesta fue aprobada.'),metadata:{path:'/smartplanner/promises',orgId:o,campId:c,promiseId:id}});return{status:'aprobada',linkedTaskId}}
const seed=[['07:00','Confirmación de instalación de representantes en las mesas','instalacion'],['13:00','Reporte de incidentes legales o compra de votos','incidente'],['18:00','Recolección y escaneo de actas de escrutinio','escrutinio']];
export async function dayTasks(u:DecodedIdToken,o:string,c:string){await access(u,o,c);const r=camp(o,c).collection('spElectionDayTasks');let s=await r.orderBy('time').get();if(s.empty){for(const [time,title,category]of seed)await r.add({time,title,description:'',assignedTo:'',status:'pendiente',category,createdAt:FieldValue.serverTimestamp()});s=await r.orderBy('time').get()}return s.docs.map(out)}
export async function saveDayTask(u:DecodedIdToken,o:string,c:string,id:string|null,x:any){await access(u,o,c,true);const title=String(x.title??'').trim(),time=String(x.time??'').trim();if(!title||!time)throw new ValidationError('Hora y título son obligatorios.');const r=id?camp(o,c).collection('spElectionDayTasks').doc(id):camp(o,c).collection('spElectionDayTasks').doc();await r.set({time,title,description:String(x.description??''),assignedTo:String(x.assignedTo??''),status:x.status==='completada'?'completada':'pendiente',category:String(x.category??'otro'),...(id?{updatedAt:FieldValue.serverTimestamp()}:{createdAt:FieldValue.serverTimestamp()})},{merge:true});return{id:r.id}}
