import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db, storage } from '../config/firebase.js';
import { assertCampaignAccess, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';

const statuses = ['borrador', 'pendiente_aprobacion', 'aprobado', 'rechazado'];
const campaign = (orgId: string, campId: string) => db.collection('organizations').doc(orgId).collection('campaigns').doc(campId);
const serialize = (document: FirebaseFirestore.QueryDocumentSnapshot) => ({ id: document.id, ...document.data(), createdAt: document.data().createdAt?.toDate?.().toISOString?.() ?? null, approvedAt: document.data().approvedAt?.toDate?.().toISOString?.() ?? null });
async function readable(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const organization = await db.collection('organizations').doc(orgId).get(); if (organization.data()?.enabledAddons?.smartPlanner !== true) throw new ForbiddenError('SmartPlanner no está habilitado en el plan de esta organización.'); }
async function manager(user: DecodedIdToken, orgId: string, campId: string) { await readable(user, orgId, campId); if (['cliente', 'admin'].includes(String(user.role))) return; const member = await campaign(orgId, campId).collection('members').doc(user.uid).get(); if (member.data()?.smartPlannerRole !== 'pm') throw new ForbiddenError('Solo un PM o Cliente puede aprobar mensajes.'); }
export async function list(user: DecodedIdToken, orgId: string, campId: string) { await readable(user, orgId, campId); return (await campaign(orgId, campId).collection('spMessages').orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function save(user: DecodedIdToken, orgId: string, campId: string, messageId: string | null, input: Record<string, unknown>) { await readable(user, orgId, campId); const title = String(input.title ?? '').trim(); const content = String(input.content ?? '').trim(); if (!title || !content) throw new ValidationError('El título y contenido son obligatorios.'); const reference = messageId ? campaign(orgId, campId).collection('spMessages').doc(messageId) : campaign(orgId, campId).collection('spMessages').doc(); const current = messageId ? await reference.get() : null; if (messageId && !current?.exists) throw new NotFoundError('El mensaje no existe.'); if (current?.data()?.status && current.data()!.status !== 'borrador') throw new ForbiddenError('El mensaje está en validación y no puede editarse.'); const data = { title, content, mediaUrl: String(input.mediaUrl ?? current?.data()?.mediaUrl ?? ''), status: 'borrador' }; await reference.set({ ...data, ...(messageId ? { updatedAt: FieldValue.serverTimestamp() } : { createdBy: user.uid, createdAt: FieldValue.serverTimestamp() }) }, { merge: true }); return { id: reference.id, ...data }; }
export async function submit(user: DecodedIdToken, orgId: string, campId: string, messageId: string) { await readable(user, orgId, campId); const reference = campaign(orgId, campId).collection('spMessages').doc(messageId); const item = await reference.get(); if (!item.exists) throw new NotFoundError('El mensaje no existe.'); if (item.data()?.status !== 'borrador') throw new ValidationError('Solo los borradores pueden enviarse a aprobación.'); await reference.update({ status: 'pendiente_aprobacion', submittedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); return { id: messageId, status: 'pendiente_aprobacion' }; }
export async function approve(user: DecodedIdToken, orgId: string, campId: string, messageId: string) { await manager(user, orgId, campId); const reference = campaign(orgId, campId).collection('spMessages').doc(messageId); const item = await reference.get(); if (!item.exists) throw new NotFoundError('El mensaje no existe.'); if (item.data()?.status !== 'pendiente_aprobacion') throw new ValidationError('El mensaje no está pendiente de aprobación.'); await reference.update({ status: 'aprobado', approvedBy: user.uid, approvedAt: FieldValue.serverTimestamp(), rejectionReason: '' }); return { id: messageId, status: 'aprobado' }; }
export async function reject(user: DecodedIdToken, orgId: string, campId: string, messageId: string, reason: unknown) { await manager(user, orgId, campId); const rejectionReason = String(reason ?? '').trim(); if (!rejectionReason) throw new ValidationError('Indicá el motivo del rechazo.'); const reference = campaign(orgId, campId).collection('spMessages').doc(messageId); const item = await reference.get(); if (!item.exists) throw new NotFoundError('El mensaje no existe.'); if (item.data()?.status !== 'pendiente_aprobacion') throw new ValidationError('El mensaje no está pendiente de aprobación.'); await reference.update({ status: 'rechazado', rejectionReason, approvedBy: user.uid, approvedAt: FieldValue.serverTimestamp() }); return { id: messageId, status: 'rechazado', rejectionReason }; }
export async function upload(user: DecodedIdToken, orgId: string, campId: string, file?: Express.Multer.File) { await readable(user, orgId, campId); if (!file?.buffer) throw new ValidationError('Seleccioná un archivo para adjuntar.'); const path = `smartplanner/messages/${orgId}/${campId}/${Date.now()}-${randomUUID()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_')}`; await storage.bucket().file(path).save(file.buffer, { resumable: false, contentType: file.mimetype, metadata: { metadata: { firebaseStorageDownloadTokens: randomUUID() } } }); return { mediaUrl: `gs://${storage.bucket().name}/${path}` }; }
export async function remove(user: DecodedIdToken, orgId: string, campId: string, messageId: string) { await readable(user, orgId, campId); const reference = campaign(orgId, campId).collection('spMessages').doc(messageId); const item = await reference.get(); if (!item.exists) throw new NotFoundError('El mensaje no existe.'); if (item.data()?.createdBy !== user.uid && !['cliente', 'admin'].includes(String(user.role))) throw new ForbiddenError('No podés borrar este mensaje.'); await reference.delete(); }
