import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { assertCampaignAccess, assertCampaignAdmin, campaignRef, NotFoundError, ValidationError } from './access.service.js';

type TeamInput = { name?: string; description?: string; leaderId?: string | null };
const normalize = (input: TeamInput) => { const name = input.name?.trim(); if (!name) throw new ValidationError('El nombre del Equipo es obligatorio.'); return { name, description: input.description?.trim() ?? '', leaderId: input.leaderId ?? null }; };
async function validateLeader(orgId: string, campId: string, leaderId: string | null) { if (leaderId && !(await campaignRef(orgId, campId).collection('members').doc(leaderId).get()).exists) throw new ValidationError('El líder debe ser miembro de la campaña.'); }
const serialize = (doc: FirebaseFirestore.QueryDocumentSnapshot) => ({ id: doc.id, ...doc.data() });
export async function listTeams(user: DecodedIdToken, orgId: string, campId: string) { assertCampaignAccess(user, orgId, campId); const snap = await campaignRef(orgId, campId).collection('teams').where('deleted', '!=', true).get(); return Promise.all(snap.docs.map(async d => ({ ...serialize(d), memberCount: (await d.ref.collection('members').get()).size }))); }
export async function createTeam(user: DecodedIdToken, orgId: string, campId: string, input: TeamInput) { assertCampaignAdmin(user, orgId, campId); const data = normalize(input); await validateLeader(orgId, campId, data.leaderId); const ref = campaignRef(orgId, campId).collection('teams').doc(); await ref.set({ ...data, deleted: false, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); return { teamId: ref.id, ...data }; }
export async function updateTeam(user: DecodedIdToken, orgId: string, campId: string, teamId: string, input: TeamInput) { assertCampaignAdmin(user, orgId, campId); const ref = campaignRef(orgId, campId).collection('teams').doc(teamId); if (!(await ref.get()).exists) throw new NotFoundError('El Equipo no existe.'); const data = normalize(input); await validateLeader(orgId, campId, data.leaderId); await ref.update({ ...data, updatedAt: FieldValue.serverTimestamp() }); return { teamId, ...data }; }
export async function deleteTeam(user: DecodedIdToken, orgId: string, campId: string, teamId: string) { assertCampaignAdmin(user, orgId, campId); const ref = campaignRef(orgId, campId).collection('teams').doc(teamId); if (!(await ref.get()).exists) throw new NotFoundError('El Equipo no existe.'); await ref.update({ deleted: true, deletedAt: FieldValue.serverTimestamp() }); }
export async function listTeamMembers(user: DecodedIdToken, orgId: string, campId: string, teamId: string) { assertCampaignAccess(user, orgId, campId); const ref = campaignRef(orgId, campId); const assignments = await ref.collection('members').where('teamId', '==', teamId).get(); return assignments.docs.map(d => ({ uid: d.id, ...d.data() })); }
