import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db } from '../config/firebase.js';
import { appendAudit } from './audit.service.js';
import { campaignRef, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';
import { assertTreoAccess } from './finance.service.js';
import { createEntry, postEntry } from './treo.service.js';
const txt=(v:unknown,n:string,req=true)=>{const x=typeof v==='string'?v.trim().slice(0,500):'';if(req&&!x)throw new ValidationError(`${n} es obligatorio.`);return x}; const num=(v:unknown)=>{const x=Number(v);if(!Number.isFinite(x)||x<0)throw new ValidationError('El importe no es válido.');return x}; const serial=(s:any)=>({id:s.id,...s.data()});
const refs=(o:string,c:string)=>{const x=campaignRef(o,c);return{c:x,budgets:x.collection('treoBudgetLines'),vendors:x.collection('treoVendors'),orders:x.collection('treoProcurements'),payments:x.collection('treoPayments'),advances:x.collection('treoAdvances')}}; const audit=(u:DecodedIdToken,o:string,c:string,a:string,r:string,id:string,b:any,n:any)=>appendAudit(o,c,u,{action:a,resource:r,resourceId:id,changes:{before:b,after:n}});
async function treasurer(user:DecodedIdToken,o:string,c:string){if(['cliente','admin'].includes(String(user.role)))return;const member=await campaignRef(o,c).collection('members').doc(user.uid).get();if(!['tesorero','apoderado'].includes(String(member.data()?.treoRole??'')))throw new ForbiddenError('Solo Tesorería o Apoderado puede autorizar o ejecutar pagos.');}
export async function migrate(user:DecodedIdToken,o:string,c:string){await assertTreoAccess(user,o,c);const r=refs(o,c);const [oldBudget,oldVendors,oldProjects]=await Promise.all([r.c.collection('budgets').get(),r.c.collection('spProviders').get(),r.c.collection('spProviderProjects').get()]);const batch=db.batch();oldBudget.docs.forEach(d=>batch.set(r.budgets.doc(`legacy-budget-${d.id}`),{...d.data(),orgId:o,campaignId:c,source:'planning',approved:num(d.data().amount),committed:0,recognized:num(d.data().spent),paid:0,migratedAt:FieldValue.serverTimestamp()},{merge:true}));oldVendors.docs.forEach(d=>batch.set(r.vendors.doc(`legacy-vendor-${d.id}`),{...d.data(),orgId:o,campaignId:c,source:'smartplanner',migratedAt:FieldValue.serverTimestamp()},{merge:true}));oldProjects.docs.forEach(d=>batch.set(r.orders.doc(`legacy-project-${d.id}`),{...d.data(),orgId:o,campaignId:c,source:'smartplanner',operationId:`legacy-project-${d.id}`,status:'migrado',migratedAt:FieldValue.serverTimestamp()},{merge:true}));await batch.commit();await audit(user,o,c,'TREO_SPEND_MIGRATED','treoMigration',c,null,{budgets:oldBudget.size,vendors:oldVendors.size,projects:oldProjects.size});return{budgets:oldBudget.size,vendors:oldVendors.size,projects:oldProjects.size}}
export async function budgets(user:DecodedIdToken,o:string,c:string){await migrate(user,o,c);return(await refs(o,c).budgets.get()).docs.map(serial)}; export async function saveBudget(user:DecodedIdToken,o:string,c:string,input:any){await assertTreoAccess(user,o,c);const r=refs(o,c).budgets.doc();const d={orgId:o,campaignId:c,name:txt(input.name,'La partida'),approved:num(input.approved),committed:0,recognized:0,paid:0,stage:txt(input.stage,'La etapa',false),activity:txt(input.activity,'La actividad',false),teamId:input.teamId??null,costCenter:txt(input.costCenter,'El centro de costo',false),restricted:Boolean(input.restricted),createdAt:FieldValue.serverTimestamp()};await r.set(d);await audit(user,o,c,'TREO_BUDGET_CREATED','treoBudgetLine',r.id,null,d);return serial(await r.get())}
export async function createOrder(user:DecodedIdToken,o:string,c:string,input:any){await assertTreoAccess(user,o,c);const x=refs(o,c),budget=await x.budgets.doc(txt(input.budgetId,'La partida')).get();if(!budget.exists)throw new NotFoundError('La partida no existe.');const amount=num(input.amount),b=budget.data()!,available=num(b.approved)-num(b.committed)-num(b.recognized);if(amount>available)throw new ValidationError('La partida no tiene disponibilidad para este compromiso.');const ref=x.orders.doc(),d={orgId:o,campaignId:c,operationId:txt(input.operationId,'La operación',false)||randomUUID(),vendorId:txt(input.vendorId,'El proveedor'),budgetId:budget.id,object:txt(input.object,'El objeto'),orderedQty:num(input.orderedQty??1),receivedQty:0,amount,status:'orden_emitida',createdAt:FieldValue.serverTimestamp()};await ref.set(d);await budget.ref.update({committed:num(b.committed)+amount});await audit(user,o,c,'TREO_ORDER_CREATED','treoProcurement',ref.id,null,d);return serial(await ref.get())}
export async function receive(user:DecodedIdToken,o:string,c:string,id:string,input:any){await assertTreoAccess(user,o,c);const ref=refs(o,c).orders.doc(id),d=await ref.get();if(!d.exists)throw new NotFoundError('La orden no existe.');await ref.update({receivedQty:num(input.receivedQty),evidence:txt(input.evidence,'La evidencia'),status:'recibido'});return serial(await ref.get())}
export async function recognize(user:DecodedIdToken,o:string,c:string,id:string,input:any){await assertTreoAccess(user,o,c);const r=refs(o,c),order=await r.orders.doc(id).get();if(!order.exists)throw new NotFoundError('La orden no existe.');const d=order.data()!,invoice=num(input.amount);if(num(d.receivedQty)<num(d.orderedQty)||invoice>num(d.amount))throw new ValidationError('La factura no supera el control orden/recepción: requiere revisión.');const entry=await postEntry(user,o,c,(await createEntry(user,o,c,{operationId:d.operationId,description:`Factura ${d.object}`,lines:[{accountId:txt(input.expenseAccountId,'La cuenta de gasto'),debit:invoice,credit:0},{accountId:'2-1-01',debit:0,credit:invoice}]})).id);const b=await r.budgets.doc(d.budgetId).get();await b.ref.update({committed:num(b.data()?.committed)-num(d.amount),recognized:num(b.data()?.recognized)+invoice});await order.ref.update({status:'factura_reconocida',invoiceAmount:invoice,entryId:entry.id});return serial(await order.ref.get())}
export async function preparePayment(user:DecodedIdToken,o:string,c:string,input:any){await assertTreoAccess(user,o,c);const r=refs(o,c),order=await r.orders.doc(txt(input.orderId,'La orden')).get();if(!order.exists||order.data()?.status!=='factura_reconocida')throw new ValidationError('La factura debe estar reconocida antes de preparar el pago.');const due=num(order.data()?.invoiceAmount), prior=(await r.payments.where('orderId','==',order.id).get()).docs.reduce((s,d)=>s+num(d.data().amount),0),amount=num(input.amount);if(amount>due-prior)throw new ValidationError('El pago supera el saldo pendiente.');const ref=r.payments.doc(),d={orgId:o,campaignId:c,operationId:order.data()?.operationId,orderId:order.id,amount,status:'preparado',bankAccountId:txt(input.bankAccountId,'La cuenta origen'),createdAt:FieldValue.serverTimestamp(),createdBy:user.uid};await ref.set(d);await audit(user,o,c,'TREO_PAYMENT_PREPARED','treoPayment',ref.id,null,d);return serial(await ref.get())}
export async function paymentAction(user:DecodedIdToken,o:string,c:string,id:string,action:string){await assertTreoAccess(user,o,c);await treasurer(user,o,c);const ref=refs(o,c).payments.doc(id),before=await ref.get();if(!before.exists)throw new NotFoundError('El pago no existe.');const d=before.data()!;if(action==='approve'&&d.status==='preparado')await ref.update({status:'aprobado',approvedBy:user.uid});else if(action==='send'&&d.status==='aprobado')await ref.update({status:'enviado',sentAt:FieldValue.serverTimestamp()});else if(action==='confirm'&&d.status==='enviado'){const entry=await postEntry(user,o,c,(await createEntry(user,o,c,{operationId:d.operationId,description:`Pago ${d.orderId}`,lines:[{accountId:'2-1-01',debit:d.amount,credit:0},{accountId:d.bankAccountId,debit:0,credit:d.amount}]})).id);await ref.update({status:'confirmado',entryId:entry.id,confirmedAt:FieldValue.serverTimestamp()})}else if(action==='reconcile'&&d.status==='confirmado')await ref.update({status:'conciliado'});else throw new ValidationError('La transición del pago no es válida.');await audit(user,o,c,`TREO_PAYMENT_${action.toUpperCase()}`,'treoPayment',id,serial(before),await ref.get().then(serial));return serial(await ref.get())}
export async function createAdvance(user:DecodedIdToken,o:string,c:string,input:any){await assertTreoAccess(user,o,c);const ref=refs(o,c).advances.doc(),d={orgId:o,campaignId:c,operationId:txt(input.operationId,'La operación',false)||randomUUID(),responsibleId:txt(input.responsibleId,'El responsable'),purpose:txt(input.purpose,'La finalidad'),amount:num(input.amount),approvedExpenses:0,returned:0,status:'autorizado',createdAt:FieldValue.serverTimestamp()};await ref.set(d);return serial(await ref.get())}
export async function settleAdvance(user:DecodedIdToken,o:string,c:string,id:string,input:any){await assertTreoAccess(user,o,c);const ref=refs(o,c).advances.doc(id),before=await ref.get();if(!before.exists)throw new NotFoundError('El anticipo no existe.');const d=before.data()!,spent=num(input.approvedExpenses),returned=num(input.returned);if(spent+returned!==num(d.amount))throw new ValidationError('La rendición debe distribuir todo el anticipo.');const entry=await postEntry(user,o,c,(await createEntry(user,o,c,{operationId:d.operationId,description:`Rendición ${d.purpose}`,lines:[{accountId:txt(input.expenseAccountId,'La cuenta de gasto'),debit:spent,credit:0},{accountId:txt(input.advanceAccountId,'La cuenta de anticipos'),debit:0,credit:spent}]})).id);await ref.update({status:'rendido',approvedExpenses:spent,returned,entryId:entry.id});return serial(await ref.get())}
