import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db } from '../config/firebase.js';
import { appendAudit } from './audit.service.js';
import { campaignRef, NotFoundError, ValidationError } from './access.service.js';
import { assertTreoAccess } from './finance.service.js';
import { createEntry, postEntry } from './treo.service.js';

const text = (v: unknown, label: string, required = true) => { const value = typeof v === 'string' ? v.trim().slice(0, 500) : ''; if (required && !value) throw new ValidationError(`${label} es obligatorio.`); return value; };
const money = (v: unknown) => { const value = Number(v); if (!Number.isFinite(value) || value <= 0) throw new ValidationError('El importe debe ser mayor a cero.'); return value; };
const serialize = (s: FirebaseFirestore.DocumentSnapshot | FirebaseFirestore.QueryDocumentSnapshot) => { const d = s.data() ?? {}; const iso = (v: any) => v?.toDate ? v.toDate().toISOString() : v ?? null; return { id: s.id, ...d, createdAt: iso(d.createdAt), updatedAt: iso(d.updatedAt) }; };
const refs = (orgId: string, campId: string) => { const campaign = campaignRef(orgId, campId); return { campaign, contributors: campaign.collection('treoContributors'), contributions: campaign.collection('treoContributions'), inKind: campaign.collection('treoInKindContributions'), sources: campaign.collection('treoFundingSources') }; };
const audit = (u: DecodedIdToken, o: string, c: string, action: string, resource: string, id: string, before: unknown, after: unknown) => appendAudit(o, c, u, { action, resource, resourceId: id, changes: { before, after } });

export async function contributors(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); const { contributors, contributions } = refs(orgId, campId); const [people, rows] = await Promise.all([contributors.orderBy('name').get(), contributions.get()]); return people.docs.map((person) => ({ ...serialize(person), acceptedTotal: rows.docs.filter((row) => row.data().contributorId === person.id).reduce((sum, row) => sum + Number(row.data().acceptedAmount ?? 0), 0) })); }
export async function saveContributor(user: DecodedIdToken, orgId: string, campId: string, id: string | null, input: any) { await assertTreoAccess(user, orgId, campId); const ref = id ? refs(orgId, campId).contributors.doc(id) : refs(orgId, campId).contributors.doc(); const before = await ref.get(); if (id && !before.exists) throw new NotFoundError('El aportante no existe.'); const data = { orgId, campaignId: campId, name: text(input.name, 'La identidad'), identification: text(input.identification, 'DNI/CUIT'), type: ['persona_fisica', 'persona_juridica'].includes(String(input.type)) ? input.type : 'persona_fisica', contact: text(input.contact, 'El contacto', false), updatedAt: FieldValue.serverTimestamp() }; if (id) await ref.update(data); else await ref.set({ ...data, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }); await audit(user, orgId, campId, id ? 'TREO_CONTRIBUTOR_UPDATED' : 'TREO_CONTRIBUTOR_CREATED', 'treoContributor', ref.id, before.exists ? serialize(before) : null, data); return serialize(await ref.get()); }
export async function listContributions(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); return (await refs(orgId, campId).contributions.orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function createContribution(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const contributor = await refs(orgId, campId).contributors.doc(text(input.contributorId, 'El aportante')).get(); if (!contributor.exists) throw new ValidationError('El aportante no pertenece a esta campaña.'); const ref = refs(orgId, campId).contributions.doc(); const data = { orgId, campaignId: campId, operationId: text(input.operationId, 'La operación', false) || randomUUID(), contributorId: contributor.id, amount: money(input.amount), status: 'pendiente_revision', bankReconciliationId: null, supportingDocumentId: input.supportingDocumentId ?? null, notes: text(input.notes, 'La observación', false), createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(data); await audit(user, orgId, campId, 'TREO_CONTRIBUTION_CREATED', 'treoContribution', ref.id, null, data); return serialize(await ref.get()); }
export async function transitionContribution(user: DecodedIdToken, orgId: string, campId: string, id: string, action: string, input: any) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).contributions.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El aporte no existe.'); const row = before.data()!; if (action === 'accredit') { if (!['pendiente_revision', 'observado'].includes(row.status)) throw new ValidationError('El aporte no puede acreditarse en este estado.'); await ref.update({ status: 'acreditado', bankReconciliationId: text(input.bankReconciliationId, 'La acreditación bancaria'), updatedAt: FieldValue.serverTimestamp() }); }
  else if (action === 'accept') { if (row.status !== 'acreditado') throw new ValidationError('Solo un aporte acreditado puede aceptarse para utilizarse.'); const entry = await createEntry(user, orgId, campId, { operationId: row.operationId, description: `Aporte aceptado: ${row.contributorId}`, lines: [{ accountId: text(input.bankAccountId, 'La cuenta bancaria'), debit: row.amount, credit: 0 }, { accountId: '4-1-01', debit: 0, credit: row.amount }] }); const posted = await postEntry(user, orgId, campId, entry.id); await ref.update({ status: 'aceptado', entryId: posted.id, acceptedAmount: row.amount, acceptedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); }
  else if (action === 'observe') await ref.update({ status: 'observado', notes: text(input.notes, 'El motivo'), updatedAt: FieldValue.serverTimestamp() });
  else if (action === 'refund') { if (!['acreditado', 'aceptado'].includes(row.status)) throw new ValidationError('Solo se devuelve un aporte acreditado o aceptado.'); const entry = await createEntry(user, orgId, campId, { operationId: row.operationId, description: `Devolución de aporte ${row.contributorId}`, lines: [{ accountId: row.status === 'aceptado' ? '4-1-01' : text(input.holdingAccountId, 'La cuenta transitoria'), debit: row.amount, credit: 0 }, { accountId: text(input.bankAccountId, 'La cuenta bancaria'), debit: 0, credit: row.amount }] }); const posted = await postEntry(user, orgId, campId, entry.id); await ref.update({ status: 'devuelto', refundEntryId: posted.id, updatedAt: FieldValue.serverTimestamp() }); }
  else throw new ValidationError('La acción del aporte no es válida.'); const after = await ref.get(); await audit(user, orgId, campId, `TREO_CONTRIBUTION_${action.toUpperCase()}`, 'treoContribution', id, serialize(before), serialize(after)); return serialize(after); }
export async function createInKind(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const contributorId = text(input.contributorId, 'El aportante'); if (!(await refs(orgId, campId).contributors.doc(contributorId).get()).exists) throw new ValidationError('El aportante no pertenece a esta campaña.'); const ref = refs(orgId, campId).inKind.doc(); const data = { orgId, campaignId: campId, operationId: text(input.operationId, 'La operación', false) || randomUUID(), contributorId, kind: ['bien', 'servicio', 'cesion_temporal', 'voluntariado'].includes(String(input.kind)) ? input.kind : 'bien', description: text(input.description, 'La descripción'), quantity: Number(input.quantity ?? 1), period: text(input.period, 'El período', false), valuation: Number(input.valuation ?? 0), valuationCriterion: text(input.valuationCriterion, 'El criterio de valoración', false), activityId: input.activityId ?? null, status: 'pendiente_revision', createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }; await ref.set(data); await audit(user, orgId, campId, 'TREO_IN_KIND_CREATED', 'treoInKindContribution', ref.id, null, data); return serialize(await ref.get()); }
export async function approveInKind(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).inKind.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El aporte en especie no existe.'); const row = before.data()!; if (row.kind === 'voluntariado') { await ref.update({ status: 'excluido', reviewedBy: user.uid, updatedAt: FieldValue.serverTimestamp() }); return serialize(await ref.get()); } const valuation = money(input.valuation ?? row.valuation); const entry = await createEntry(user, orgId, campId, { operationId: row.operationId, description: `Aporte en especie: ${row.description}`, lines: [{ accountId: text(input.debitAccountId, 'La cuenta de destino'), debit: valuation, credit: 0 }, { accountId: '4-1-01', debit: 0, credit: valuation }] }); const posted = await postEntry(user, orgId, campId, entry.id); await ref.update({ status: 'valorado', valuation, entryId: posted.id, reviewedBy: user.uid, updatedAt: FieldValue.serverTimestamp() }); await audit(user, orgId, campId, 'TREO_IN_KIND_APPROVED', 'treoInKindContribution', id, serialize(before), { entryId: posted.id }); return serialize(await ref.get()); }
export async function sources(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); return (await refs(orgId, campId).sources.orderBy('createdAt', 'desc').get()).docs.map(serialize); }
export async function createSource(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const type = text(input.type, 'El tipo'); if (!['aporte_privado', 'fondos_propios', 'financiamiento_publico', 'transferencia_autorizada', 'prestamo', 'otro'].includes(type)) throw new ValidationError('La fuente no es admisible.'); const ref = refs(orgId, campId).sources.doc(); const data = { orgId, campaignId: campId, operationId: text(input.operationId, 'La operación', false) || randomUUID(), type, amount: money(input.amount), status: input.status === 'autorizado' ? 'autorizado_no_acreditado' : 'solicitado', conditions: text(input.conditions, 'Las condiciones', false), dueDate: input.dueDate ?? null, outstandingBalance: money(input.amount), createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }; await ref.set(data); await audit(user, orgId, campId, 'TREO_SOURCE_CREATED', 'treoFundingSource', ref.id, null, data); return serialize(await ref.get()); }
export async function disburseSource(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).sources.doc(id); const before = await ref.get(); if (!before.exists || before.data()?.status !== 'autorizado_no_acreditado') throw new ValidationError('La fuente no está autorizada para acreditar.'); const row = before.data()!; const credit = row.type === 'prestamo' ? '2-1-03' : row.type === 'financiamiento_publico' ? '2-1-04' : '3-1-01'; const entry = await createEntry(user, orgId, campId, { operationId: row.operationId, description: `Desembolso ${row.type}`, lines: [{ accountId: text(input.bankAccountId, 'La cuenta bancaria'), debit: row.amount, credit: 0 }, { accountId: credit, debit: 0, credit: row.amount }] }); const posted = await postEntry(user, orgId, campId, entry.id); await ref.update({ status: 'acreditado', entryId: posted.id, outstandingBalance: row.type === 'prestamo' ? row.amount : 0, updatedAt: FieldValue.serverTimestamp() }); await audit(user, orgId, campId, 'TREO_SOURCE_DISBURSED', 'treoFundingSource', id, serialize(before), { entryId: posted.id }); return serialize(await ref.get()); }
