import { DecodedIdToken } from 'firebase-admin/auth';
import { FieldValue } from 'firebase-admin/firestore';
import { randomUUID } from 'node:crypto';
import { db, storage } from '../config/firebase.js';
import { appendAudit } from './audit.service.js';
import { campaignRef, ConflictError, ForbiddenError, NotFoundError, ValidationError } from './access.service.js';
import { assertTreoAccess } from './finance.service.js';

type EntryLine = { accountId: string; debit: number; credit: number; dimensions?: Record<string, string> };
const accountSeed = [
  ['1.1.01', 'Caja', 'activo'], ['1.1.02', 'Bancos', 'activo'], ['1.1.03', 'Medios digitales', 'activo'], ['1.1.04', 'Anticipos a rendir', 'activo'],
  ['2.1.01', 'Proveedores por pagar', 'pasivo'], ['2.1.02', 'Fondos restringidos', 'pasivo'],
  ['3.1.01', 'Fondos de campaña', 'patrimonio'], ['4.1.01', 'Aportes', 'ingreso'], ['2.1.03', 'Préstamos por pagar', 'pasivo'], ['2.1.04', 'Fondos públicos por rendir', 'pasivo'],
  ['5.1.01', 'Publicidad', 'egreso'], ['5.1.02', 'Actos y territorio', 'egreso'], ['5.1.03', 'Viáticos y logística', 'egreso'], ['5.1.04', 'Comisiones financieras', 'egreso']
] as const;
const date = (value: unknown) => { const parsed = new Date(String(value)); if (Number.isNaN(parsed.valueOf())) throw new ValidationError('La fecha es inválida.'); return parsed; };
const string = (value: unknown, label: string, required = true, max = 240) => { const result = typeof value === 'string' ? value.trim().slice(0, max) : ''; if (required && !result) throw new ValidationError(`${label} es obligatorio.`); return result; };
const amount = (value: unknown) => { const result = Number(value); if (!Number.isFinite(result) || result < 0) throw new ValidationError('El importe es inválido.'); return result; };
const serial = (snapshot: FirebaseFirestore.DocumentSnapshot | FirebaseFirestore.QueryDocumentSnapshot) => { const data = snapshot.data() ?? {}; const iso = (v: any) => v?.toDate ? v.toDate().toISOString() : v ?? null; return { id: snapshot.id, ...data, createdAt: iso(data.createdAt), updatedAt: iso(data.updatedAt), date: iso(data.date) }; };
const refs = (orgId: string, campId: string) => { const campaign = campaignRef(orgId, campId); return { campaign, chart: campaign.collection('treoChartOfAccounts'), entries: campaign.collection('treoJournalEntries'), documents: campaign.collection('treoDocuments'), statements: campaign.collection('treoStatements'), reconciliations: campaign.collection('treoReconciliations') }; };
async function audit(user: DecodedIdToken, orgId: string, campId: string, action: string, resource: string, resourceId: string, before: unknown, after: unknown) { await appendAudit(orgId, campId, user, { action, resource, resourceId, changes: { before, after } }); }
async function seedChart(orgId: string, campId: string) { const { chart } = refs(orgId, campId); const batch = db.batch(); accountSeed.forEach(([code, name, type]) => batch.set(chart.doc(code.replaceAll('.', '-')), { orgId, campaignId: campId, code, name, type, system: true, active: true, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }, { merge: true })); await batch.commit(); }
function lines(input: unknown): EntryLine[] { if (!Array.isArray(input) || input.length < 2) throw new ValidationError('Un asiento requiere al menos dos líneas.'); const parsed = input.map((line: any) => ({ accountId: string(line?.accountId, 'La cuenta'), debit: amount(line?.debit ?? 0), credit: amount(line?.credit ?? 0), dimensions: line?.dimensions && typeof line.dimensions === 'object' ? line.dimensions : {} })); const debit = parsed.reduce((sum, line) => sum + line.debit, 0); const credit = parsed.reduce((sum, line) => sum + line.credit, 0); if (!debit || Math.abs(debit - credit) > .005) throw new ValidationError(`El asiento no está equilibrado: debe ${debit.toFixed(2)}, haber ${credit.toFixed(2)}.`); if (parsed.some((line) => (line.debit && line.credit) || (!line.debit && !line.credit))) throw new ValidationError('Cada línea debe imputar solo debe o haber.'); return parsed; }
async function ensureAccounts(orgId: string, campId: string, entryLines: EntryLine[]) { const { chart } = refs(orgId, campId); const docs = await Promise.all(entryLines.map((line) => chart.doc(line.accountId).get())); if (docs.some((doc) => !doc.exists || doc.data()?.active === false)) throw new ValidationError('Una cuenta del plan no existe o está inactiva.'); }

export async function chart(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); await seedChart(orgId, campId); return (await refs(orgId, campId).chart.orderBy('code').get()).docs.map(serial); }
export async function saveAccount(user: DecodedIdToken, orgId: string, campId: string, id: string | null, input: any) { await assertTreoAccess(user, orgId, campId); const ref = id ? refs(orgId, campId).chart.doc(id) : refs(orgId, campId).chart.doc(); const before = await ref.get(); if (id && !before.exists) throw new NotFoundError('La cuenta contable no existe.'); const data = { orgId, campaignId: campId, code: string(input.code, 'El código'), name: string(input.name, 'El nombre'), type: string(input.type, 'El tipo'), active: input.active !== false, system: before.data()?.system === true, updatedAt: FieldValue.serverTimestamp() };
  if (!id) await ref.set({ ...data, createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }); else await ref.update(data); await audit(user, orgId, campId, id ? 'TREO_ACCOUNT_UPDATED' : 'TREO_ACCOUNT_CREATED', 'treoChartAccount', ref.id, before.exists ? serial(before) : null, data); return serial(await ref.get()); }

export async function entries(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); return (await refs(orgId, campId).entries.orderBy('date', 'desc').get()).docs.map(serial); }
export async function createEntry(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const entryLines = lines(input.lines); await ensureAccounts(orgId, campId, entryLines); const ref = refs(orgId, campId).entries.doc(); const operationId = string(input.operationId, 'La operación', false, 120) || randomUUID(); const data = { orgId, campaignId: campId, operationId, date: date(input.date ?? new Date()), description: string(input.description, 'La descripción'), lines: entryLines, status: 'propuesto', documentId: input.documentId ?? null, sourceType: input.sourceType ?? 'manual', createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(data); await audit(user, orgId, campId, 'TREO_ENTRY_CREATED', 'treoJournalEntry', ref.id, null, data); return serial(await ref.get()); }
export async function postEntry(user: DecodedIdToken, orgId: string, campId: string, id: string) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).entries.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El asiento no existe.'); if (before.data()?.status !== 'propuesto') throw new ValidationError('Solo se contabilizan asientos propuestos.'); const entryLines = lines(before.data()?.lines); await ensureAccounts(orgId, campId, entryLines); await ref.update({ status: 'contabilizado', postedAt: FieldValue.serverTimestamp(), postedBy: user.uid, updatedAt: FieldValue.serverTimestamp() }); const after = await ref.get(); await audit(user, orgId, campId, 'TREO_ENTRY_POSTED', 'treoJournalEntry', id, serial(before), serial(after)); return serial(after); }
export async function removeEntry(user: DecodedIdToken, orgId: string, campId: string, id: string) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).entries.doc(id); const before = await ref.get(); if (!before.exists) throw new NotFoundError('El asiento no existe.'); if (before.data()?.status !== 'propuesto') throw new ValidationError('Un asiento contabilizado se conserva: usá reversión o ajuste.'); await ref.delete(); await audit(user, orgId, campId, 'TREO_ENTRY_DELETED_DRAFT', 'treoJournalEntry', id, serial(before), null); }
export async function reverseEntry(user: DecodedIdToken, orgId: string, campId: string, id: string) { await assertTreoAccess(user, orgId, campId); const original = await refs(orgId, campId).entries.doc(id).get(); if (!original.exists || original.data()?.status !== 'contabilizado') throw new ValidationError('Solo se revierten asientos contabilizados.'); const ref = refs(orgId, campId).entries.doc(); const lines = (original.data()?.lines as EntryLine[]).map((line) => ({ ...line, debit: line.credit, credit: line.debit })); const data = { ...original.data(), orgId, campaignId: campId, operationId: original.data()?.operationId, description: `Reversión: ${original.data()?.description}`, lines, status: 'contabilizado', reversalOfId: id, sourceType: 'reversion', createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid, postedAt: FieldValue.serverTimestamp(), postedBy: user.uid }; delete (data as any).date; await ref.set({ ...data, date: new Date() }); await original.ref.update({ status: 'revertido', reversedById: ref.id, updatedAt: FieldValue.serverTimestamp() }); await audit(user, orgId, campId, 'TREO_ENTRY_REVERSED', 'treoJournalEntry', id, serial(original), { reversalId: ref.id }); return serial(await ref.get()); }
/** A reclassification never rewrites a posted entry. It creates an auditable
 * compensating adjustment linked to the original operation instead. */
export async function adjustEntry(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) {
  await assertTreoAccess(user, orgId, campId);
  const original = await refs(orgId, campId).entries.doc(id).get();
  if (!original.exists || !['contabilizado', 'revertido'].includes(String(original.data()?.status))) throw new ValidationError('Solo se ajustan asientos contabilizados o revertidos.');
  const adjustment = await createEntry(user, orgId, campId, {
    ...input,
    operationId: String(original.data()?.operationId),
    documentId: original.data()?.documentId ?? null,
    sourceType: 'ajuste',
    description: input.description || `Ajuste de ${original.data()?.description}`
  });
  const posted = await postEntry(user, orgId, campId, adjustment.id);
  await original.ref.update({ status: 'ajustado', adjustmentIds: FieldValue.arrayUnion(posted.id), updatedAt: FieldValue.serverTimestamp() });
  await audit(user, orgId, campId, 'TREO_ENTRY_ADJUSTED', 'treoJournalEntry', id, serial(original), { adjustmentId: posted.id });
  return posted;
}
export async function ledger(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); const [accounts, rows] = await Promise.all([chart(user, orgId, campId), refs(orgId, campId).entries.get()]); const balances = new Map(accounts.map((account: any) => [account.id, { ...account, debit: 0, credit: 0, balance: 0, entries: [] as any[] }])); rows.docs.map(serial).filter((entry: any) => entry.status === 'contabilizado').sort((a: any, b: any) => String(a.date).localeCompare(String(b.date))).forEach((entry: any) => entry.lines.forEach((line: EntryLine) => { const account = balances.get(line.accountId); if (account) { account.debit += line.debit; account.credit += line.credit; account.balance = account.debit - account.credit; account.entries.push({ entryId: entry.id, date: entry.date, description: entry.description, debit: line.debit, credit: line.credit, operationId: entry.operationId }); } })); const trial = [...balances.values()]; return { trialBalance: trial, totalDebit: trial.reduce((sum, account: any) => sum + account.debit, 0), totalCredit: trial.reduce((sum, account: any) => sum + account.credit, 0) }; }

async function documentFile(orgId: string, campId: string, id: string, file?: Express.Multer.File) { if (!file) throw new ValidationError('Seleccioná al menos un documento.'); if (!['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'text/plain'].includes(file.mimetype)) throw new ValidationError('El documento debe ser PDF, imagen o texto.'); const path = `organizations/${orgId}/campaigns/${campId}/treo/documents/${id}/${randomUUID()}-${file.originalname.replace(/[^a-z0-9._-]/gi, '_')}`; await storage.bucket().file(path).save(file.buffer, { resumable: false, contentType: file.mimetype, metadata: { cacheControl: 'private,max-age=0' } }); const rawText = file.mimetype === 'text/plain' ? file.buffer.toString('utf8').slice(0, 20000) : ''; const number = rawText.match(/(?:factura|invoice|nro)\s*[:#-]?\s*([\w-]+)/i)?.[1] ?? ''; const extractedAmount = Number(rawText.match(/(?:total|importe)\s*[:$]?\s*([\d.,]+)/i)?.[1]?.replace('.', '').replace(',', '.') ?? 0); return { path, fileName: file.originalname, mimeType: file.mimetype, size: file.size, rawText, extracted: { documentNumber: number, supplier: '', amount: Number.isFinite(extractedAmount) ? extractedAmount : 0, date: null, source: rawText ? 'texto' : 'pendiente de revisión' } }; }
export async function documents(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); return (await refs(orgId, campId).documents.orderBy('createdAt', 'desc').get()).docs.map(serial); }
export async function documentUrl(user: DecodedIdToken, orgId: string, campId: string, id: string) {
  await assertTreoAccess(user, orgId, campId);
  const document = await refs(orgId, campId).documents.doc(id).get();
  if (!document.exists) throw new NotFoundError('El documento no existe.');
  const file = document.data()?.file;
  if (!file?.path) throw new NotFoundError('El documento no tiene un archivo disponible.');
  const [url] = await storage.bucket().file(file.path).getSignedUrl({ action: 'read', expires: Date.now() + 5 * 60 * 1000 });
  return { url, fileName: file.fileName, mimeType: file.mimeType };
}
export async function uploadDocument(user: DecodedIdToken, orgId: string, campId: string, input: any, file?: Express.Multer.File) { await assertTreoAccess(user, orgId, campId); const ref = refs(orgId, campId).documents.doc(); const fileData = await documentFile(orgId, campId, ref.id, file); const extracted = { ...fileData.extracted, supplier: string(input.supplier, 'El proveedor', false), amount: input.amount === undefined ? fileData.extracted.amount : amount(input.amount), documentNumber: string(input.documentNumber, 'El número', false) || fileData.extracted.documentNumber }; const existing = await refs(orgId, campId).documents.get(); const duplicateOfId = existing.docs.find((doc) => { const item = doc.data(); return extracted.documentNumber && item.extracted?.documentNumber === extracted.documentNumber && item.extracted?.supplier === extracted.supplier && Number(item.extracted?.amount) === extracted.amount; })?.id ?? null; const data = { orgId, campaignId: campId, operationId: string(input.operationId, 'La operación', false) || randomUUID(), kind: string(input.kind, 'El tipo', false) || 'factura', status: 'recibido', file: fileData, extracted, duplicateOfId, linkedEntryId: null, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(data); await audit(user, orgId, campId, 'TREO_DOCUMENT_UPLOADED', 'treoDocument', ref.id, null, data); return { ...serial(await ref.get()), duplicateWarning: Boolean(duplicateOfId) }; }
export async function recognizeDocument(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await assertTreoAccess(user, orgId, campId); const document = await refs(orgId, campId).documents.doc(id).get(); if (!document.exists) throw new NotFoundError('El documento no existe.'); const extracted = { ...(document.data()?.extracted ?? {}), ...(input.extracted ?? {}) }; const expenseAccountId = string(input.expenseAccountId, 'La cuenta de gasto'); const payableAccountId = string(input.payableAccountId, 'La cuenta por pagar'); const total = amount(extracted.amount); if (!total) throw new ValidationError('El documento debe tener un importe para contabilizar.'); const entry = await createEntry(user, orgId, campId, { operationId: document.data()?.operationId, date: extracted.date ?? new Date(), description: `Factura ${extracted.documentNumber || document.data()?.file?.fileName}`, documentId: id, sourceType: 'documento', lines: [{ accountId: expenseAccountId, debit: total, credit: 0, dimensions: input.dimensions ?? {} }, { accountId: payableAccountId, debit: 0, credit: total, dimensions: input.dimensions ?? {} }] }); const posted = await postEntry(user, orgId, campId, entry.id); await document.ref.update({ status: 'contabilizado', extracted, linkedEntryId: posted.id, updatedAt: FieldValue.serverTimestamp() }); await audit(user, orgId, campId, 'TREO_DOCUMENT_RECOGNIZED', 'treoDocument', id, serial(document), { entryId: posted.id }); return { document: serial(await document.ref.get()), entry: posted }; }
export async function payDocument(user: DecodedIdToken, orgId: string, campId: string, id: string, input: any) { await assertTreoAccess(user, orgId, campId); const document = await refs(orgId, campId).documents.doc(id).get(); if (!document.exists || document.data()?.status !== 'contabilizado') throw new ValidationError('Primero contabilizá la factura.'); const payable = string(input.payableAccountId, 'La cuenta por pagar'); const bank = string(input.bankAccountId, 'La cuenta bancaria'); const total = amount(input.amount ?? document.data()?.extracted?.amount); const entry = await createEntry(user, orgId, campId, { operationId: document.data()?.operationId, date: input.date ?? new Date(), description: `Pago de factura ${document.data()?.extracted?.documentNumber || id}`, documentId: id, sourceType: 'pago', lines: [{ accountId: payable, debit: total, credit: 0 }, { accountId: bank, debit: 0, credit: total }] }); const posted = await postEntry(user, orgId, campId, entry.id); await document.ref.update({ status: 'pagado', paymentEntryId: posted.id, updatedAt: FieldValue.serverTimestamp() }); await audit(user, orgId, campId, 'TREO_DOCUMENT_PAID', 'treoDocument', id, null, { paymentEntryId: posted.id }); return { entry: posted, document: serial(await document.ref.get()) }; }

export async function importStatement(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const fingerprint = string(input.fingerprint, 'El identificador del extracto'); const existing = await refs(orgId, campId).statements.where('fingerprint', '==', fingerprint).limit(1).get(); if (!existing.empty) throw new ConflictError('Este extracto ya fue importado.', { statementId: existing.docs[0].id }); if (!Array.isArray(input.lines) || !input.lines.length) throw new ValidationError('El extracto no contiene movimientos.'); const ref = refs(orgId, campId).statements.doc(); const lines = input.lines.map((line: any, index: number) => ({ id: String(index + 1), reference: string(line.reference, 'La referencia', false), amount: amount(line.amount), date: date(line.date ?? new Date()), counterparty: string(line.counterparty, 'La contraparte', false), reconciled: false })); await ref.set({ orgId, campaignId: campId, fingerprint, accountId: string(input.accountId, 'La cuenta'), lines, importedAt: FieldValue.serverTimestamp(), createdBy: user.uid }); await audit(user, orgId, campId, 'TREO_STATEMENT_IMPORTED', 'treoStatement', ref.id, null, { fingerprint, lines: lines.length }); return serial(await ref.get()); }
export async function reconcile(user: DecodedIdToken, orgId: string, campId: string, input: any) { await assertTreoAccess(user, orgId, campId); const gross = amount(input.grossAmount); const commission = amount(input.commissionAmount); const net = amount(input.netAmount); if (Math.abs((gross - commission) - net) > .005) throw new ValidationError('La conciliación no cuadra: bruto menos comisión debe ser neto.'); const statement = await refs(orgId, campId).statements.doc(string(input.statementId, 'El extracto')).get(); if (!statement.exists) throw new NotFoundError('El extracto no existe.'); const entryIds: string[] = Array.isArray(input.entryIds) ? input.entryIds.map(String) : []; const linked = await Promise.all(entryIds.map((id: string) => refs(orgId, campId).entries.doc(id).get())); if (linked.some((entry) => !entry.exists)) throw new ValidationError('Un asiento vinculado no existe.'); const ref = refs(orgId, campId).reconciliations.doc(); const data = { orgId, campaignId: campId, operationId: string(input.operationId, 'La operación', false) || randomUUID(), statementId: statement.id, statementLineIds: Array.isArray(input.statementLineIds) ? input.statementLineIds.map(String) : [], entryIds, grossAmount: gross, commissionAmount: commission, netAmount: net, status: 'conciliado', createdAt: FieldValue.serverTimestamp(), createdBy: user.uid }; await ref.set(data); await audit(user, orgId, campId, 'TREO_RECONCILIATION_CREATED', 'treoReconciliation', ref.id, null, data); return serial(await ref.get()); }
export async function workbench(user: DecodedIdToken, orgId: string, campId: string) { await assertTreoAccess(user, orgId, campId); const campaign = campaignRef(orgId, campId); const [docs, entries, reconciliations, contributions, payments, orders, advances] = await Promise.all([refs(orgId, campId).documents.get(), refs(orgId, campId).entries.get(), refs(orgId, campId).reconciliations.get(), campaign.collection('treoContributions').get(), campaign.collection('treoPayments').get(), campaign.collection('treoProcurements').get(), campaign.collection('treoAdvances').get()]); const threeWayDifferences = orders.docs.reduce((count, order) => { const data = order.data(); const lines = Array.isArray(data.lines) ? data.lines : [{ orderedQty: data.orderedQty, receivedQty: data.receivedQty }]; return count + lines.filter((line: any) => Number(line.receivedQty ?? 0) < Number(line.orderedQty ?? 0)).length; }, 0); return { review: { documents: docs.docs.filter((doc) => doc.data().status === 'recibido').length, duplicateDocuments: docs.docs.filter((doc) => doc.data().duplicateOfId).length, proposedEntries: entries.docs.filter((entry) => entry.data().status === 'propuesto').length, reconciliationDifferences: reconciliations.docs.filter((item) => item.data().status !== 'conciliado').length, contributionsPending: contributions.docs.filter((item) => ['pendiente_revision', 'observado'].includes(item.data().status)).length, refundsPending: contributions.docs.filter((item) => item.data().status === 'devolucion_pendiente').length, paymentsPending: payments.docs.filter((item) => item.data().status === 'preparado').length, threeWayDifferences, advancesPending: advances.docs.filter((item) => item.data().status !== 'rendido').length }, areas: ['Contabilidad', 'Documentos', 'Conciliación', 'Financiamiento', 'Gasto y tesorería', 'Control electoral (próximamente)'] }; }
