import { useState } from 'react';
import ContentPanel from '../../components/Shared/ContentPanel';
import Inline from '../../components/Shared/Inline';
import PageContainer from '../../components/Shared/PageContainer';
import PrimaryButton from '../../components/Shared/PrimaryButton';
import Stack from '../../components/Shared/Stack';
import { useAuth } from '../../context/AuthContext';
import { useActiveCampaign } from '../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../lib/api';
type Kind='costCenters'|'stages'|'activities'|'paymentMethods'; type Item={id:string;name:string};
const labels:Record<Kind,string>={costCenters:'Centros de costo',stages:'Etapas',activities:'Actividades',paymentMethods:'Medios de pago'};
export default function TreoCatalogManagement(){const{user}=useAuth();const{organizationId,activeCampaignId}=useActiveCampaign();const base=organizationId&&activeCampaignId?`/api/organizations/${organizationId}/campaigns/${activeCampaignId}/treo`:null;const[kind,setKind]=useState<Kind>('costCenters');const[name,setName]=useState('');const[notice,setNotice]=useState('');const query=useAuthenticatedQuery<Item[]>(user,base?`${base}/spend/catalogs/${kind}`:null,[base,kind]);const reload=()=>query.reload();const create=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!base)return;try{await authenticatedFetch(user,`${base}/spend/catalogs/${kind}`,{method:'POST',body:JSON.stringify({name})});setName('');setNotice('Valor guardado.');await reload()}catch(error){setNotice(error instanceof Error?error.message:'No pudimos guardar el catálogo.')}};const remove=async(item:Item)=>{if(!user||!base||!window.confirm(`¿Eliminar ${item.name}?`))return;try{await authenticatedFetch(user,`${base}/spend/catalogs/${kind}/${item.id}`,{method:'DELETE'});setNotice('Valor eliminado.');await reload()}catch(error){setNotice(error instanceof Error?error.message:'No se puede eliminar un valor en uso.')}};return <PageContainer backTo="/treo" backLabel="Volver a Treo"><Stack gap="lg"><ContentPanel icon="list" title="Catálogos de Treo"><Stack gap="md"><p className="mb-0">Gestioná los valores relacionales de esta campaña. Los valores utilizados no se eliminan para conservar el historial contable.</p>{notice&&<div className="alert alert-info">{notice}</div>}<Inline gap="sm" wrap>{(Object.keys(labels) as Kind[]).map(item=><button type="button" className={`btn ${kind===item?'btn-primary':'btn-light'}`} key={item} onClick={()=>setKind(item)}>{labels[item]}</button>)}</Inline><form onSubmit={create}><Inline gap="sm" wrap><input aria-label={`Nuevo ${labels[kind]}`} className="form-control" value={name} onChange={event=>setName(event.target.value)} placeholder={`Nuevo valor de ${labels[kind].toLocaleLowerCase('es-AR')}`}/><PrimaryButton type="submit" icon="plus">Agregar</PrimaryButton></Inline></form><div className="table-responsive"><table className="table"><thead><tr><th>Nombre</th><th className="text-end">Acciones</th></tr></thead><tbody>{(query.data??[]).map(item=><tr key={item.id}><td>{item.name}</td><td className="text-end"><button type="button" className="btn btn-sm btn-outline-danger" onClick={()=>remove(item)}>Eliminar</button></td></tr>)}</tbody></table></div></Stack></ContentPanel></Stack></PageContainer>}
