import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ContentPanel from '../../components/Shared/ContentPanel';
import Inline from '../../components/Shared/Inline';
import PageContainer from '../../components/Shared/PageContainer';
import PrimaryButton from '../../components/Shared/PrimaryButton';
import Stack from '../../components/Shared/Stack';
import { useAuth } from '../../context/AuthContext';
import { useActiveCampaign } from '../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../lib/api';
type Budget={id:string;name:string;code?:string;currency?:string;validFrom?:string;validTo?:string;responsibleId?:string;description?:string;alertThreshold?:number;stage?:string;activity?:string;costCenter?:string;restricted?:boolean};
export default function TreoBudgetEdit(){const{budgetId}=useParams();const navigate=useNavigate();const{user}=useAuth();const{organizationId,activeCampaignId}=useActiveCampaign();const base=organizationId&&activeCampaignId?`/api/organizations/${organizationId}/campaigns/${activeCampaignId}/treo`:null;const budgetsQ=useAuthenticatedQuery<Budget[]>(user,base?`${base}/spend/budgets`:null,[base]);const budget=useMemo(()=>budgetsQ.data?.find(item=>item.id===budgetId),[budgetsQ.data,budgetId]);const[form,setForm]=useState<any>({});const[error,setError]=useState('');useEffect(()=>{if(budget)setForm({...budget,validFrom:String(budget.validFrom??'').slice(0,10),validTo:String(budget.validTo??'').slice(0,10)})},[budget]);const save=async(e:FormEvent)=>{e.preventDefault();if(!user||!base||!budget)return;try{await authenticatedFetch(user,`${base}/spend/budgets/${budget.id}`,{method:'PUT',body:JSON.stringify(form)});navigate('/treo')}catch(x){setError(x instanceof Error?x.message:'No pudimos actualizar la partida.')}};if(budgetsQ.data&&!budget)return <PageContainer backTo="/treo"><ContentPanel icon="target" title="Partida no encontrada"><p className="mb-0">No pertenece a la campaña activa.</p></ContentPanel></PageContainer>;return <PageContainer backTo="/treo" backLabel="Volver a Treo"><ContentPanel icon="target" title="Editar partida presupuestaria"><form onSubmit={save}><Stack gap="lg">{error&&<div className="alert alert-danger">{error}</div>}<div className="treo-form-grid"><label>Nombre<input className="form-control" required value={form.name??''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Código<input className="form-control" value={form.code??''} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Vigencia desde<input className="form-control" type="date" value={form.validFrom??''} onChange={e=>setForm({...form,validFrom:e.target.value})}/></label><label>Vigencia hasta<input className="form-control" type="date" value={form.validTo??''} onChange={e=>setForm({...form,validTo:e.target.value})}/></label><label>Responsable<input className="form-control" value={form.responsibleId??''} onChange={e=>setForm({...form,responsibleId:e.target.value})}/></label><label>Umbral de alerta (%)<input className="form-control" type="number" min="0" max="100" value={form.alertThreshold??''} onChange={e=>setForm({...form,alertThreshold:Number(e.target.value)})}/></label><label className="treo-form-grid__wide">Descripción<textarea className="form-control" rows={4} value={form.description??''} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><small className="text-muted">El importe aprobado no se edita acá: requiere una modificación presupuestaria auditada.</small><Inline gap="sm"><button type="button" className="btn btn-light" onClick={()=>navigate('/treo')}>Cancelar</button><PrimaryButton type="submit" icon="check">Guardar cambios</PrimaryButton></Inline></Stack></form></ContentPanel></PageContainer>}
