import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ContentPanel from '../../components/Shared/ContentPanel';
import Inline from '../../components/Shared/Inline';
import PageContainer from '../../components/Shared/PageContainer';
import PrimaryButton from '../../components/Shared/PrimaryButton';
import Stack from '../../components/Shared/Stack';
import { useAuth } from '../../context/AuthContext';
import { useActiveCampaign } from '../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../lib/api';

type Line = { id: string; description: string; orderedQty: number; unitPrice: number; lineTotal?: number; budgetId: string; receivedQty?: number; recognizedAmount?: number };
type Order = { id: string; status: string; object: string; request?: string; amount: number; budgetId: string; lines?: Line[]; issueDate?: string; expectedDeliveryDate?: string; paymentTerms?: string; deliveryInstructions?: string; approverId?: string; currency?: string };
type Budget = { id: string; name: string };
const blankLine = (): Line => ({ id: `linea-${crypto.randomUUID()}`, description: '', orderedQty: 1, unitPrice: 0, budgetId: '' });
const legacyLine = (order: Order): Line => ({ id: 'linea-legacy-1', description: order.object, orderedQty: Number((order as any).orderedQty ?? 1), unitPrice: Number((order as any).unitPrice ?? order.amount), budgetId: order.budgetId });

export default function TreoOrderEdit() {
  const { orderId } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const { organizationId, activeCampaignId } = useActiveCampaign(); const base = organizationId && activeCampaignId ? `/api/organizations/${organizationId}/campaigns/${activeCampaignId}/treo` : null;
  const queue = useAuthenticatedQuery<{ orders: Order[] }>(user, base ? `${base}/spend/queue` : null, [base]); const budgets = useAuthenticatedQuery<Budget[]>(user, base ? `${base}/spend/budgets` : null, [base]); const order = useMemo(() => queue.data?.orders.find(item => item.id === orderId), [queue.data, orderId]);
  const [form, setForm] = useState<any>({ lines: [] }); const [error, setError] = useState('');
  useEffect(() => { if (order) setForm({ ...order, issueDate: String(order.issueDate ?? '').slice(0, 10), expectedDeliveryDate: String(order.expectedDeliveryDate ?? '').slice(0, 10), lines: order.lines?.length ? order.lines : [legacyLine(order)] }); }, [order]);
  const total = (form.lines ?? []).reduce((sum: number, line: Line) => sum + Number(line.orderedQty || 0) * Number(line.unitPrice || 0), 0);
  const updateLine = (id: string, patch: Partial<Line>) => setForm({ ...form, lines: form.lines.map((line: Line) => line.id === id ? { ...line, ...patch } : line) });
  const save = async (event: FormEvent) => { event.preventDefault(); if (!user || !base || !order) return; const { amount: _amount, unitPrice: _unitPrice, orderedQty: _orderedQty, ...payload } = form; try { await authenticatedFetch(user, `${base}/spend/orders/${order.id}`, { method: 'PUT', body: JSON.stringify({ ...payload, object: form.lines.map((line: Line) => line.description).join(' · '), amount: total }) }); navigate('/treo'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se puede editar una orden después de recepción o contabilización.'); } };
  if (queue.data && !order) return <PageContainer backTo="/treo"><ContentPanel icon="doc" title="Orden no encontrada"><p className="mb-0">No pertenece a la campaña activa.</p></ContentPanel></PageContainer>;
  return <PageContainer backTo="/treo" backLabel="Volver a Treo"><ContentPanel icon="doc" title="Editar compra / orden"><form onSubmit={save}><Stack gap="lg">{error && <div className="alert alert-danger">{error}</div>}<Stack gap="md">{(form.lines ?? []).map((line: Line, index: number) => <ContentPanel key={line.id} icon="list" title={`Línea ${index + 1}`}><div className="treo-form-grid"><label className="treo-form-grid__wide">Descripción<input className="form-control" required value={line.description} onChange={event => updateLine(line.id, { description: event.target.value })}/></label><label>Cantidad<input className="form-control" required min="1" type="number" value={line.orderedQty} onChange={event => updateLine(line.id, { orderedQty: Number(event.target.value) })}/></label><label>Precio unitario<input className="form-control" required min="0.01" type="number" value={line.unitPrice} onChange={event => updateLine(line.id, { unitPrice: Number(event.target.value) })}/></label><label>Partida<select className="form-select" required value={line.budgetId} onChange={event => updateLine(line.id, { budgetId: event.target.value })}>{(budgets.data ?? []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Total de línea<input className="form-control" readOnly value={(Number(line.orderedQty || 0) * Number(line.unitPrice || 0)).toFixed(2)}/></label></div></ContentPanel>)}</Stack><Inline gap="sm" wrap><button className="btn btn-outline-primary" type="button" onClick={() => setForm({ ...form, lines: [...form.lines, { ...blankLine(), budgetId: form.budgetId }] })}>Agregar línea</button>{form.lines?.length > 1 && <button className="btn btn-outline-danger" type="button" onClick={() => setForm({ ...form, lines: form.lines.slice(0, -1) })}>Quitar última línea</button>}<strong>Subtotal: {total.toFixed(2)} {form.currency ?? 'ARS'}</strong></Inline><small className="text-muted">La edición queda bloqueada al registrar recepción; lo contabilizado se conserva y se corrige mediante ajuste o reversión.</small><Inline gap="sm"><button className="btn btn-light" type="button" onClick={() => navigate('/treo')}>Cancelar</button><PrimaryButton icon="check" type="submit">Guardar orden</PrimaryButton></Inline></Stack></form></ContentPanel></PageContainer>;
}
