import { useEffect, useMemo, useState } from 'react';
import { doc, onSnapshot } from 'firebase/firestore';
import { Modal } from 'react-bootstrap';
import { useAuth } from '../../context/AuthContext';
import { useActiveCampaign } from '../../context/CampaignContext';
import { authenticatedFetch, useAuthenticatedQuery } from '../../lib/api';
import { Toast } from '../../components/Toast';
import ContentPanel from '../../components/Shared/ContentPanel';
import EmptyState from '../../components/Shared/EmptyState';
import HeroBanner from '../../components/Shared/HeroBanner';
import Inline from '../../components/Shared/Inline';
import PageContainer from '../../components/Shared/PageContainer';
import PrimaryButton from '../../components/Shared/PrimaryButton';
import SelectControl from '../../components/Shared/SelectControl';
import Stack from '../../components/Shared/Stack';
import { firestore } from '../../lib/firebase';

type Option = { id: string; name: string };
type Candidate = { id: string; name: string; party?: string | null; photoUrl?: string | null };
type Stream = { id: string; name: string; location: string; date: string; status: 'activa' | 'pendiente' | 'cerrada'; candidates: Candidate[]; subLocations: Option[]; genderOptions: Option[]; ageRanges: Option[] };
type Entry = { id: string; candidateId: string; votes: number; submittedAt?: string };
type Notice = { message: string; variant: 'success' | 'error' };

const selectOptions = (items: Option[]) => [{ value: '', label: 'Sin especificar' }, ...items.map((item) => ({ value: item.id, label: item.name }))];
function Avatar({ candidate }: { candidate: Candidate }) { return candidate.photoUrl ? <img className="vote-avatar vote-avatar--large" src={candidate.photoUrl} alt="" /> : <span className="vote-avatar vote-avatar--large">{candidate.name.slice(0, 2).toUpperCase()}</span>; }
function Ranking({ stream, totals }: { stream: Stream; totals: Record<string, number> }) { const total = Object.values(totals).reduce((a, b) => a + b, 0); return <ContentPanel icon="bar-chart-2" title="Ranking actual" subtitle="Solo lectura y actualización en tiempo real."><Stack gap="sm">{[...stream.candidates].sort((a,b) => (totals[b.id] ?? 0) - (totals[a.id] ?? 0)).map((candidate, index) => <Inline gap="sm" className="vote-agent-ranking__row" key={candidate.id}><span className="vote-agent-ranking__position">#{index + 1}</span><Avatar candidate={candidate} /><Stack gap="xs" className="vote-agent-ranking__name"><strong>{candidate.name}</strong><small>{candidate.party || 'Partido no informado'}</small></Stack><strong>{total ? Math.round((totals[candidate.id] ?? 0) / total * 100) : 0}%</strong></Inline>)}</Stack></ContentPanel>; }
function StreamGroups({ streams, onSelect }: { streams: Stream[]; onSelect: (stream: Stream) => void }) { return <Stack gap="lg">{(['activa', 'pendiente', 'cerrada'] as const).map((status) => { const group = streams.filter((stream) => stream.status === status); const title = status === 'activa' ? 'Activas' : status === 'pendiente' ? 'Pendientes' : 'Cerradas'; return <ContentPanel key={status} icon={status === 'activa' ? 'target' : 'calendar'} title={title} subtitle={status === 'activa' ? 'Podés enviar resultados en este momento.' : status === 'pendiente' ? 'Esta Stream aún no fue activada.' : 'La jornada terminó y solo conserva consulta.'}>{group.length ? <Stack gap="sm">{group.map((stream) => <article className="vote-agent-stream" data-card="true" key={stream.id}><Inline gap="md" wrap className="justify-content-between align-items-center"><Stack gap="xs"><strong>{stream.name}</strong><small>{stream.location} · {stream.date} · {stream.candidates.length} candidatos</small></Stack>{status === 'activa' ? <PrimaryButton icon="plus" onClick={() => onSelect(stream)}>Cargar resultados</PrimaryButton> : <span className="vote-status">{status}</span>}</Inline></article>)}</Stack> : <EmptyState icon="target" title={`No hay Streams ${title.toLowerCase()}`} description="Las asignaciones aparecerán aquí." />}</ContentPanel>; })}</Stack>; }

export default function VoteStreamAgentPanel() {
  const { user } = useAuth(); const { organizationId, activeCampaignId, enabledAddons } = useActiveCampaign();
  const base = organizationId && activeCampaignId ? `/api/organizations/${organizationId}/campaigns/${activeCampaignId}/vote-stream` : null;
  const streamsQ = useAuthenticatedQuery<Stream[]>(user, enabledAddons.voteStream && base ? `${base}/mine` : null, [base, enabledAddons.voteStream]);
  const [streamId, setStreamId] = useState<string | null>(null); const stream = useMemo(() => streamsQ.data?.find((item) => item.id === streamId) ?? null, [streamsQ.data, streamId]);
  const [candidate, setCandidate] = useState<Candidate | null>(null); const [votes, setVotes] = useState(''); const [subLocationId, setSubLocationId] = useState(''); const [genderId, setGenderId] = useState(''); const [ageRangeId, setAgeRangeId] = useState(''); const [confirm, setConfirm] = useState(false); const [sending, setSending] = useState(false); const [notice, setNotice] = useState<Notice | null>(null); const [totals, setTotals] = useState<Record<string, number>>({});
  const submissionsQ = useAuthenticatedQuery<Entry[]>(user, stream && base ? `${base}/${stream.id}/my-submissions` : null, [base, stream?.id]);
  useEffect(() => { if (!stream || !base || !user) { setCandidate(null); return; } void authenticatedFetch<{ candidate: Candidate | null }>(user, `${base}/${stream.id}/next-candidate`).then((result) => setCandidate(result.candidate)).catch((error) => setNotice({ message: error.message, variant: 'error' })); }, [stream?.id, base, user]);
  useEffect(() => { if (!organizationId || !activeCampaignId || !stream) return; return onSnapshot(doc(firestore, 'organizations', organizationId, 'campaigns', activeCampaignId, 'voteStreams', stream.id), (snapshot) => setTotals((snapshot.data()?.liveResults?.totals as Record<string, number>) ?? {})); }, [organizationId, activeCampaignId, stream?.id]);
  const send = async () => { if (!user || !base || !stream || !candidate) return; setSending(true); try { await authenticatedFetch(user, `${base}/${stream.id}/submissions`, { method: 'POST', body: JSON.stringify({ candidateId: candidate.id, votes: Number(votes), subLocationId: subLocationId || undefined, genderId: genderId || undefined, ageRangeId: ageRangeId || undefined }) }); setConfirm(false); setNotice({ message: `Resultado de ${candidate.name} enviado.`, variant: 'success' }); setVotes(''); await submissionsQ.reload(); const next = await authenticatedFetch<{ candidate: Candidate | null }>(user, `${base}/${stream.id}/next-candidate?afterCandidateId=${encodeURIComponent(candidate.id)}`); setCandidate(next.candidate); } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'No pudimos enviar el resultado.', variant: 'error' }); } finally { setSending(false); } };
  if (!enabledAddons.voteStream) return <PageContainer><EmptyState icon="target" title="Vote Stream no está habilitado" description="Pedile a un administrador global que habilite este add-on." /></PageContainer>;
  return <PageContainer><Stack gap="lg"><HeroBanner icon="target" eyebrow="AGENTE DE SONDEO" title="Mi panel de Sondeo" subtitle="Carga guiada, rápida y segura para resultados electorales." />
    {!stream ? <StreamGroups streams={streamsQ.data ?? []} onSelect={(selected) => setStreamId(selected.id)} /> : <Stack gap="lg"><ContentPanel icon="edit-3" title={`Carga de datos · ${stream.name}`} subtitle={stream.status === 'activa' ? 'Completá un candidato a la vez y confirmá antes de enviar.' : 'Esta Stream no está activa.'}>{stream.status !== 'activa' ? <EmptyState icon="lock" title="Carga no disponible" description="La Stream debe estar activa para registrar resultados." /> : candidate ? <Stack gap="lg"><Inline gap="md" className="vote-data-entry__candidate"><Avatar candidate={candidate} /><Stack gap="xs"><strong>{candidate.name}</strong><small>{candidate.party || 'Partido no informado'}</small></Stack></Inline><Stack gap="xs"><label className="form-label">Votos registrados</label><input aria-label={`Votos para ${candidate.name}`} type="number" min="0" inputMode="numeric" className="form-control vote-data-entry__votes" value={votes} onChange={(event) => setVotes(event.target.value)} placeholder="0" autoFocus /></Stack><Inline gap="md" wrap>{stream.subLocations.length > 0 && <SelectControl ariaLabel="Sub ubicación" label="Sub ubicación" value={subLocationId} onChange={setSubLocationId} options={selectOptions(stream.subLocations)} />}{stream.genderOptions.length > 0 && <SelectControl ariaLabel="Género" label="Género" value={genderId} onChange={setGenderId} options={selectOptions(stream.genderOptions)} />}{stream.ageRanges.length > 0 && <SelectControl ariaLabel="Rango de edad" label="Rango de edad" value={ageRangeId} onChange={setAgeRangeId} options={selectOptions(stream.ageRanges)} />}</Inline><Inline gap="sm" wrap><PrimaryButton icon="check" disabled={!Number.isInteger(Number(votes)) || Number(votes) < 0} onClick={() => setConfirm(true)}>Enviar resultado</PrimaryButton><button className="btn btn-outline-secondary" type="button" onClick={() => setStreamId(null)}>Cancelar</button></Inline></Stack> : <EmptyState icon="check-circle" title="Carga completada" description="Ya recorriste todos los candidatos." />}</ContentPanel><Ranking stream={stream} totals={totals} /><ContentPanel icon="calendar" title="Mis envíos" subtitle="Historial personal de solo lectura.">{submissionsQ.data?.length ? <Stack gap="sm">{submissionsQ.data.map((entry) => <article className="vote-agent-submission" data-card="true" key={entry.id}><Inline gap="sm"><strong>{stream.candidates.find((item) => item.id === entry.candidateId)?.name ?? 'Candidato'}</strong><span>{entry.votes} votos</span><small>{entry.submittedAt ? new Date(entry.submittedAt).toLocaleString('es-AR') : ''}</small></Inline></article>)}</Stack> : <EmptyState icon="calendar" title="Todavía no enviaste resultados" description="Tu historial aparecerá aquí después del primer envío." />}</ContentPanel></Stack>}
    <Modal show={confirm} onHide={() => !sending && setConfirm(false)} centered><Modal.Header closeButton><Modal.Title>Confirmar envío</Modal.Title></Modal.Header><Modal.Body>Vas a enviar <strong>{votes || 0}</strong> votos para <strong>{candidate?.name}</strong>.</Modal.Body><Modal.Footer><button className="btn btn-light" onClick={() => setConfirm(false)} disabled={sending}>Cancelar</button><PrimaryButton icon="check" onClick={() => void send()} disabled={sending}>{sending ? 'Enviando…' : 'Confirmar y enviar'}</PrimaryButton></Modal.Footer></Modal>{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </Stack></PageContainer>;
}
