import { useState } from 'react';
import { Button } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner';
import KpiCard from '../../../components/Shared/KpiCard';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import PageContainer from '../../../components/Shared/PageContainer';
import Inline from '../../../components/Shared/Inline';
import Stack from '../../../components/Shared/Stack';
import { Toast } from '../../../components/Toast';

type Summary = { date:string; summary:string|null; generatedAt?:string|null; stats:{visits:number;yes:number;no:number;undecided:number;tasks:number;incidents:number} };
function download(name:string, type:string, value:string) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([value],{type})); link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function asPdf(text:string) { const escaped = text.replace(/[()\\]/g,'\\$&').replace(/[^\x20-\x7E\n]/g,''); const lines = escaped.split(/\n+/).flatMap((line) => line.match(/.{1,82}/g) ?? ['']); const content = ['BT','/F1 12 Tf','50 790 Td',...lines.flatMap((line,index) => [index ? '0 -18 Td' : '', `(${line}) Tj`].filter(Boolean)),'ET'].join('\n'); const objects = [`1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj`,`2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj`,`3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj`,`4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj`,`5 0 obj<</Length ${content.length}>>stream\n${content}\nendstream\nendobj`]; let output='%PDF-1.4\n'; const offsets=[0]; for (const object of objects) { offsets.push(output.length); output+=`${object}\n`; } const xref=output.length; output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer<</Size ${objects.length+1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF`; return output; }

export default function DailySummary() {
  const { user,campaign } = useCampaign(); const [generating,setGenerating] = useState(false); const [notice,setNotice] = useState<{message:string;variant:'success'|'danger'}|null>(null);
  const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/execution/daily-summary` : null; const summaryQ = useAuthenticatedQuery<Summary>(user,path,[path]); const result = summaryQ.data;
  const generate = async () => { if (!user || !path || generating || result?.summary) return; setGenerating(true); try { await authenticatedFetch(user,path,{method:'POST'}); await summaryQ.reload(); setNotice({message:'Resumen de jornada generado.',variant:'success'}); } catch (caught) { setNotice({message:caught instanceof Error ? caught.message : 'No pudimos generar el resumen.',variant:'danger'}); } finally { setGenerating(false); } };
  const exportExcel = () => { if (!result?.summary) return; download(`resumen-jornada-${result.date}.xls`,'text/csv;charset=utf-8',[['Fecha',result.date],['Resumen',result.summary],['Visitas',String(result.stats.visits)],['SI',String(result.stats.yes)],['NO',String(result.stats.no)],['Indecisos',String(result.stats.undecided)],['Tareas completadas',String(result.stats.tasks)],['Incidencias',String(result.stats.incidents)]].map((row) => row.map((cell) => `"${cell.replace(/"/g,'""')}"`).join(';')).join('\n')); };
  const exportPdf = () => { if (!result?.summary) return; download(`resumen-jornada-${result.date}.pdf`,'application/pdf',asPdf(`CloudSuite — Resumen de jornada (${result.date})\n\n${result.summary}\n\nVisitas: ${result.stats.visits} | SI: ${result.stats.yes} | NO: ${result.stats.no} | Indecisos: ${result.stats.undecided}\nTareas completadas: ${result.stats.tasks} | Incidencias: ${result.stats.incidents}`)); };
  return <PageContainer><HeroBanner icon="bars" title="Resumen de Jornada" subtitle="Convertí la actividad del día en una lectura clara para tomar decisiones." tags={[{icon:'clock',label:'Cierre diario'},{icon:'target',label:'Datos de campaña'}]} ctaLabel={result?.summary ? 'Resumen generado' : 'Generar resumen de hoy'} ctaDisabled={Boolean(result?.summary) || generating} onCtaClick={() => void generate()} />
    <div className="cd-dashboard__kpis"><KpiCard icon="bars" value={result?.stats.visits ?? 0} label="Visitas hoy" caption="Actividad registrada" /><KpiCard icon="check" iconColor="green" value={result?.stats.tasks ?? 0} label="Tareas completadas" caption="Cerradas hoy" /><KpiCard icon="help" iconColor="red" value={result?.stats.incidents ?? 0} label="Incidencias reportadas" caption="Durante la jornada" /></div>
    <ContentPanel icon="bars" title="Resumen del día" subtitle={result?.generatedAt ? `Generado el ${new Date(result.generatedAt).toLocaleString('es-AR')}` : 'Generalo una vez para conservar la lectura de esta jornada.'} headerAction={result?.summary ? <Inline gap="sm" wrap><Button size="sm" variant="outline-secondary" onClick={exportPdf}>Exportar a PDF</Button><Button size="sm" variant="primary" onClick={exportExcel}>Exportar a Excel</Button></Inline> : undefined}>
      {summaryQ.loading ? <EmptyState icon="bars" title="Cargando resumen" description="Estamos consultando la jornada actual." /> : summaryQ.error ? <EmptyState icon="bars" title="No pudimos cargar el resumen" description={summaryQ.error.message} ctaLabel="Reintentar" onCtaClick={() => void summaryQ.reload()} /> : result?.summary ? <Stack gap="md"><div className="p-2" style={{whiteSpace:'pre-wrap',lineHeight:1.75}}>{result.summary}</div><small className="text-muted">Este resumen queda guardado para evitar una nueva llamada a Gemini durante el mismo día.</small></Stack> : <EmptyState icon="bars" title="Todavía no hay resumen de jornada" description="Generá el resumen para obtener una lectura profesional de la actividad del día." ctaLabel={generating ? 'Generando…' : 'Generar resumen de hoy'} onCtaClick={() => void generate()} />}
    </ContentPanel>
    {generating && <p className="text-center text-muted mt-3">Analizando datos reales de la jornada…</p>}{notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </PageContainer>;
}
