import { useEffect, useMemo, useState } from 'react';
import Chart from 'react-apexcharts';
import { Button, Card } from 'react-bootstrap';
import { useCampaign } from '../Organization/useCampaign';
import { authenticatedFetch } from '../../../lib/api';
import { Toast } from '../../../components/Toast';

type Summary = { totalVoters: number; visitedCount: number; convertedYes: number; convertedNo: number; undecidedCount: number; conversionRate: number; coverageRate: number; teamStats: Array<{ teamName: string; conversionsCount: number }>; topMilitants: Array<{ uid: string; name: string; visitsCount: number; conversionsCount: number; conversionRate: number }> };
type Timeline = { daily: Array<{ date: string; accumulated_yes: number }> };
const empty: Summary = { totalVoters: 0, visitedCount: 0, convertedYes: 0, convertedNo: 0, undecidedCount: 0, conversionRate: 0, coverageRate: 0, teamStats: [], topMilitants: [] };
const palette = { primary: 'var(--bs-primary)', success: 'var(--bs-success)', danger: 'var(--bs-danger)', warning: 'var(--bs-warning)' };

export default function CampaignDashboard() {
  const { user, campaign, error: campaignError } = useCampaign();
  const [summary, setSummary] = useState<Summary>(empty); const [timeline, setTimeline] = useState<Timeline>({ daily: [] }); const [toast, setToast] = useState('');
  const [from, setFrom] = useState(() => new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10)); const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10));
  useEffect(() => { if (!user || !campaign) return; const base = `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/analytics`; const range = `?start=${encodeURIComponent(from)}&end=${encodeURIComponent(to)}`; void Promise.all([authenticatedFetch(user, `${base}/summary${range}`), authenticatedFetch(user, `${base}/timeline${range}`)]).then(([nextSummary, nextTimeline]) => { setSummary(nextSummary as Summary); setTimeline(nextTimeline as Timeline); }).catch(error => setToast(error instanceof Error ? error.message : 'No pudimos cargar las estadísticas.')); }, [user, campaign, from, to]);
  const exportReport = () => { const rows = [['Métrica', 'Valor'], ['Total de electores', String(summary.totalVoters)], ['Visitados', String(summary.visitedCount)], ['Conversiones SI', String(summary.convertedYes)], ['Conversiones NO', String(summary.convertedNo)], ['Indecisos', String(summary.undecidedCount)], ['Cobertura', `${summary.coverageRate}%`], ['Tasa de conversión', `${summary.conversionRate}%`]]; const blob = new Blob([`\ufeff${rows.map(row => row.join(';')).join('\n')}`], { type: 'application/vnd.ms-excel;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'reporte-cloudsuite.xls'; link.click(); URL.revokeObjectURL(link.href); setToast('Reporte Excel descargado.'); };
  const cards = [{ label: 'Total de electores', value: summary.totalVoters, text: `${summary.coverageRate}% visitados`, color: 'primary' }, { label: 'Conversiones SI', value: summary.convertedYes, text: `${summary.conversionRate}% de conversión`, color: 'success' }, { label: 'Conversiones NO', value: summary.convertedNo, text: 'registradas', color: 'danger' }, { label: 'Indecisos', value: summary.undecidedCount, text: 'a re-visitar', color: 'warning' }];
  const line = useMemo(() => ({ options: { chart: { toolbar: { show: false } }, xaxis: { categories: timeline.daily.map(day => day.date.slice(5)) }, stroke: { curve: 'smooth' as const }, colors: [palette.success] }, series: [{ name: 'SI acumulados', data: timeline.daily.map(day => day.accumulated_yes) }] }), [timeline]);
  const bars = useMemo(() => ({ options: { chart: { toolbar: { show: false } }, xaxis: { categories: summary.teamStats.map(team => team.teamName) }, colors: [palette.success] }, series: [{ name: 'Conversiones SI', data: summary.teamStats.map(team => team.conversionsCount) }] }), [summary]);
  return <section><div className="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><h1 className="h3 mb-1">Dashboard de campaña</h1><p className="text-muted mb-0">Indicadores actualizados cada cinco minutos.</p></div><div className="d-flex flex-wrap gap-2 align-items-end"><label className="small">Desde<input className="form-control" type="date" value={from} max={to} onChange={event => setFrom(event.target.value)} /></label><label className="small">Hasta<input className="form-control" type="date" value={to} min={from} onChange={event => setTo(event.target.value)} /></label><Button onClick={exportReport}><i className="ph-duotone ph-file-xls me-2" />Exportar reporte</Button></div></div>{campaignError && <div className="alert alert-danger">{campaignError}</div>}<div className="row g-3 mb-4">{cards.map(card => <div className="col-sm-6 col-xl-3" key={card.label}><Card className={`h-100 border-start border-4 border-${card.color}`}><Card.Body><p className="text-muted mb-2">{card.label}</p><h2 className="mb-1">{card.value}</h2><small className={`text-${card.color}`}>{card.text}</small></Card.Body></Card></div>)}</div><div className="row g-4"><div className="col-xl-8"><Card className="h-100"><Card.Header><h2 className="h5 mb-0">Evolución de Conversiones</h2></Card.Header><Card.Body><Chart type="line" height={300} options={line.options} series={line.series} /></Card.Body></Card></div><div className="col-xl-4"><Card className="h-100"><Card.Header><h2 className="h5 mb-0">Estado de Conversión</h2></Card.Header><Card.Body><Chart type="donut" height={300} options={{ labels: ['SI', 'NO', 'Indeciso'], colors: [palette.success, palette.danger, palette.warning], legend: { position: 'bottom' } }} series={[summary.convertedYes, summary.convertedNo, summary.undecidedCount]} /></Card.Body></Card></div><div className="col-xl-6"><Card><Card.Header><h2 className="h5 mb-0">Conversiones por Equipo</h2></Card.Header><Card.Body>{summary.teamStats.length ? <Chart type="bar" height={280} options={bars.options} series={bars.series} /> : <p className="text-muted mb-0">Asigná miembros a equipos para ver comparativas.</p>}</Card.Body></Card></div><div className="col-xl-6"><Card><Card.Header><h2 className="h5 mb-0">Top 10 militantes por visitas</h2></Card.Header><Card.Body><div className="table-responsive"><table className="table table-striped table-hover table-sm align-middle mb-0"><thead><tr><th>Militante</th><th>Visitas</th><th>SI</th><th>Tasa</th></tr></thead><tbody>{summary.topMilitants.map(item => <tr key={item.uid}><td>{item.name}</td><td>{item.visitsCount}</td><td>{item.conversionsCount}</td><td>{item.conversionRate}%</td></tr>)}{summary.topMilitants.length === 0 && <tr><td colSpan={4} className="text-muted">Todavía no hay visitas registradas.</td></tr>}</tbody></table></div></Card.Body></Card></div></div>{toast && <Toast message={toast} onClose={() => setToast('')} />}</section>;
}
