import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner'; import ContentPanel from '../../../components/Shared/ContentPanel'; import EmptyState from '../../../components/Shared/EmptyState'; import PageContainer from '../../../components/Shared/PageContainer'; import SelectControl from '../../../components/Shared/SelectControl'; import MapContainer from '../../../components/Planning/MapContainer';
type Point = { id:string; lat:number; lng:number; state:string; name:string };
const target: Record<string,string> = { support:'converted_yes', rejection:'converted_no', undecided:'undecided' };
const color: Record<string,string> = { support:'#10b981', rejection:'#ef4444', undecided:'#f59e0b' };
export default function Heatmap() { const { user, campaign } = useCampaign(); const navigate = useNavigate(); const [mode, setMode] = useState('support'); const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/execution/heatmap-points` : null; const { data, loading, error } = useAuthenticatedQuery<Point[]>(user, path, [path]); const points = useMemo(() => (data ?? []).filter(point => point.state === target[mode]), [data, mode]); const mapsConfigured = Boolean(import.meta.env.VITE_GOOGLE_MAPS_API_KEY); return <PageContainer><HeroBanner icon="map" title="Mapa de Calor de Campaña" subtitle="Identificá dónde concentrar el trabajo territorial." tags={[{icon:'map-pin',label:'Datos geolocalizados'}]} />
<ContentPanel icon="map" title="Intensidad territorial" subtitle="Seleccioná el indicador que querés visualizar" headerAction={<SelectControl label="Apoyo" value={mode} onChange={setMode} options={[{value:'support',label:'Apoyo'},{value:'rejection',label:'Rechazo'},{value:'undecided',label:'Indecisos'}]} />}>{!mapsConfigured ? <EmptyState icon="map" title="Configurá Google Maps" description="Para visualizar el mapa de calor necesitás configurar GOOGLE_MAPS_API_KEY en la plataforma." ctaLabel="Ir a configuración" onCtaClick={() => navigate('/settings')} /> : error ? <EmptyState icon="map" title="No pudimos cargar el mapa" description={error.message} /> : <MapContainer sidebar={<><h2 className="h6">Leyenda</h2><p className="small text-muted">{points.length} puntos en {mode === 'support' ? 'apoyo' : mode === 'rejection' ? 'rechazo' : 'indecisión'}.</p><p className="small mb-0">Cada punto representa un elector con ubicación registrada.</p></>}><div className="execution-heatmap" aria-label="Mapa de calor"><div className="execution-heatmap__label">Mapa de calor</div>{loading ? <EmptyState icon="map" title="Cargando puntos" description="Estamos preparando la capa de calor." /> : points.length ? points.map((point, index) => <span key={point.id} title={point.name} className="execution-heatmap__point" style={{ left:`${12 + index * 19 % 75}%`, top:`${15 + index * 29 % 68}%`, background:color[mode] }} />) : <EmptyState icon="map" title="Sin puntos para este indicador" description="Necesitás electores geolocalizados con ese estado de conversión." />}</div></MapContainer>}</ContentPanel></PageContainer>; }
