import { useMemo, useState } from 'react';
import { useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner'; import ContentPanel from '../../../components/Shared/ContentPanel'; import EmptyState from '../../../components/Shared/EmptyState'; import PageContainer from '../../../components/Shared/PageContainer'; import SelectControl from '../../../components/Shared/SelectControl'; import MapContainer from '../../../components/Planning/MapContainer'; import GoogleMapCanvas from '../../../components/Shared/GoogleMapCanvas'; import Stack from '../../../components/Shared/Stack';
type Point = { id:string; lat:number; lng:number; state:string; name:string };
const target: Record<string,string> = { support:'converted_yes', rejection:'converted_no', undecided:'undecided' };
const color: Record<string,string> = { support:'#10b981', rejection:'#ef4444', undecided:'#f59e0b' };
export default function Heatmap() { const { user, campaign } = useCampaign(); const [mode, setMode] = useState('support'); const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/execution/heatmap-points` : null; const { data, loading, error } = useAuthenticatedQuery<Point[]>(user, path, [path]); const points = useMemo(() => (data ?? []).filter(point => point.state === target[mode]), [data, mode]); return <PageContainer><HeroBanner icon="map" title="Mapa de Calor de Campaña" subtitle="Identificá dónde concentrar el trabajo territorial." tags={[{icon:'map-pin',label:'Datos geolocalizados'}]} />
<ContentPanel icon="map" title="Intensidad territorial" subtitle="Seleccioná el indicador que querés visualizar" headerAction={<SelectControl label="Apoyo" value={mode} onChange={setMode} options={[{value:'support',label:'Apoyo'},{value:'rejection',label:'Rechazo'},{value:'undecided',label:'Indecisos'}]} />}>{error ? <EmptyState icon="map" title="No pudimos cargar el mapa" description={error.message} /> : <MapContainer sidebar={<Stack gap="sm"><h2 className="h6">Leyenda</h2><p className="small text-muted mb-0">{points.length} puntos en {mode === 'support' ? 'apoyo' : mode === 'rejection' ? 'rechazo' : 'indecisión'}.</p><p className="small mb-0">La intensidad aumenta donde se concentran los electores geolocalizados.</p><span className="badge" style={{ background: color[mode], color: '#fff' }}>{mode === 'support' ? 'Apoyo' : mode === 'rejection' ? 'Rechazo' : 'Indecisos'}</span></Stack>}>{loading ? <EmptyState icon="map" title="Cargando puntos" description="Estamos preparando la capa de calor." /> : points.length ? <GoogleMapCanvas points={points} mode="heatmap" ariaLabel="Mapa de calor de campaña" /> : <EmptyState icon="map" title="Sin puntos para este indicador" description="Necesitás electores geolocalizados con ese estado de conversión." />}</MapContainer>}</ContentPanel></PageContainer>; }
