import { FormEvent, useMemo, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner';
import KpiCard from '../../../components/Shared/KpiCard';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import PageContainer from '../../../components/Shared/PageContainer';
import SelectControl from '../../../components/Shared/SelectControl';
import Card from '../../../components/Shared/Card';
import Stack from '../../../components/Shared/Stack';
import Inline from '../../../components/Shared/Inline';
import { Toast } from '../../../components/Toast';

type Incident = { id:string; title:string; description:string; severity:'baja'|'media'|'alta'; status:'abierta'|'resuelta'; address?:string; lat?:number|null; lng?:number|null; photoUrl?:string|null; createdAt?:string|null; resolvedAt?:string|null };
const severityLabels: Record<Incident['severity'],string> = { baja:'Baja', media:'Media', alta:'Alta' }; const statusLabels: Record<Incident['status'],string> = { abierta:'Abierta', resuelta:'Resuelta' };
const blank = () => ({ title:'', description:'', severity:'media' as Incident['severity'], address:'', lat:'', lng:'' });

export default function Incidents() {
  const { user, campaign } = useCampaign(); const [show,setShow] = useState(false); const [form,setForm] = useState(blank); const [photo,setPhoto] = useState<File|null>(null); const [saving,setSaving] = useState(false); const [locating,setLocating] = useState(false); const [status,setStatus] = useState('all'); const [severity,setSeverity] = useState('all'); const [notice,setNotice] = useState<{message:string;variant:'success'|'danger'}|null>(null);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}` : null; const incidentsQ = useAuthenticatedQuery<Incident[]>(user, base ? `${base}/incidents` : null, [base]); const incidents = incidentsQ.data ?? [];
  const filtered = useMemo(() => incidents.filter((incident) => (status === 'all' || incident.status === status) && (severity === 'all' || incident.severity === severity)), [incidents,status,severity]);
  const today = new Date().toISOString().slice(0,10); const open = incidents.filter((incident) => incident.status === 'abierta'); const resolvedToday = incidents.filter((incident) => incident.status === 'resuelta' && incident.resolvedAt?.slice(0,10) === today).length; const critical = open.filter((incident) => incident.severity === 'alta').length;
  const openModal = () => { setForm(blank()); setPhoto(null); setShow(true); };
  const locate = () => { if (!navigator.geolocation) { setNotice({message:'Tu navegador no permite obtener ubicación.',variant:'danger'}); return; } setLocating(true); navigator.geolocation.getCurrentPosition((position) => { setForm({...form,lat:String(position.coords.latitude),lng:String(position.coords.longitude)}); setLocating(false); }, () => { setNotice({message:'No pudimos obtener tu ubicación. Revisá los permisos del navegador.',variant:'danger'}); setLocating(false); }, {enableHighAccuracy:true,timeout:10000}); };
  const submit = async (event:FormEvent) => { event.preventDefault(); if (!user || !base || saving) return; setSaving(true); try { const data = new FormData(); Object.entries(form).forEach(([key,value]) => data.append(key,value)); if (photo) data.append('photo',photo); await authenticatedFetch(user, `${base}/incidents`, {method:'POST',body:data}); await incidentsQ.reload(); setShow(false); setNotice({message:'Incidencia reportada correctamente.',variant:'success'}); } catch (caught) { setNotice({message:caught instanceof Error ? caught.message : 'No pudimos reportar la incidencia.',variant:'danger'}); } finally { setSaving(false); } };
  const resolve = async (incident:Incident) => { if (!user || !base) return; try { await authenticatedFetch(user, `${base}/incidents/${incident.id}`, {method:'PUT',body:JSON.stringify({status:'resuelta'})}); await incidentsQ.reload(); setNotice({message:'Incidencia marcada como resuelta.',variant:'success'}); } catch (caught) { setNotice({message:caught instanceof Error ? caught.message : 'No pudimos actualizar la incidencia.',variant:'danger'}); } };
  return <PageContainer><HeroBanner icon="help-circle" title="Incidencias de Campo" subtitle="Registrá obstáculos y resolvelos con trazabilidad territorial." tags={[{icon:'map-pin',label:'Ubicación en campo'},{icon:'check-circle',label:'Seguimiento de resolución'}]} ctaLabel="Reportar incidencia" onCtaClick={openModal} />
    <div className="cd-dashboard__kpis"><KpiCard icon="help" iconColor="red" value={open.length} label="Abiertas" caption="Pendientes de resolución" /><KpiCard icon="check" iconColor="green" value={resolvedToday} label="Resueltas hoy" caption="Cerradas en la jornada" /><KpiCard icon="target" iconColor="orange" value={critical} label="Alta prioridad sin resolver" caption="Requieren intervención" /></div>
    <ContentPanel icon="help" title="Registro de incidencias" subtitle="Documentá problemas operativos y mantené informado al equipo." headerAction={<Inline gap="sm" wrap><SelectControl ariaLabel="Filtrar incidencias por estado" label={status === 'all' ? 'Todos los estados' : statusLabels[status as Incident['status']]} value={status} onChange={setStatus} options={[{value:'all',label:'Todos los estados'},...Object.entries(statusLabels).map(([value,label]) => ({value,label}))]} /><SelectControl ariaLabel="Filtrar incidencias por severidad" label={severity === 'all' ? 'Todas las severidades' : severityLabels[severity as Incident['severity']]} value={severity} onChange={setSeverity} options={[{value:'all',label:'Todas las severidades'},...Object.entries(severityLabels).map(([value,label]) => ({value,label}))]} /></Inline>}>
      {incidentsQ.loading ? <EmptyState icon="help" title="Cargando incidencias" description="Estamos preparando el registro de campo." /> : incidentsQ.error ? <EmptyState icon="help" title="No pudimos cargar las incidencias" description={incidentsQ.error.message} ctaLabel="Reintentar" onCtaClick={() => void incidentsQ.reload()} /> : filtered.length ? <div className="row g-3">{filtered.map((incident) => <div className="col-md-6" key={incident.id}><Card className="h-100"><Stack gap="md">{incident.photoUrl && <img src={incident.photoUrl} alt={`Foto de ${incident.title}`} className="img-fluid rounded" style={{maxHeight:220,objectFit:'cover',width:'100%'}} />}<Stack gap="xs"><Inline gap="sm" className="justify-content-between"><h3 className="h5 mb-0">{incident.title}</h3><span className={`badge text-bg-${incident.severity === 'alta' ? 'danger' : incident.severity === 'media' ? 'warning' : 'secondary'}`}>{severityLabels[incident.severity]}</span></Inline><p className="mb-0 text-muted">{incident.description || 'Sin descripción'}</p><small>{incident.address || (incident.lat !== null && incident.lat !== undefined ? `${incident.lat}, ${incident.lng}` : 'Ubicación no informada')}</small></Stack><Inline gap="sm" wrap className="justify-content-between"><span className={`badge text-bg-${incident.status === 'resuelta' ? 'success' : 'primary'}`}>{statusLabels[incident.status]}</span>{incident.status === 'abierta' && <Button size="sm" variant="outline-success" onClick={() => void resolve(incident)}>Marcar como resuelta</Button>}</Inline></Stack></Card></div>)}</div> : <EmptyState icon="help" title="No hay incidencias para mostrar" description="Reportá la primera incidencia de campo para darle seguimiento." ctaLabel="Reportar incidencia" onCtaClick={openModal} />}
    </ContentPanel>
    <Modal show={show} onHide={() => !saving && setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>Reportar incidencia</Modal.Title></Modal.Header><Modal.Body><label className="form-label" htmlFor="incident-title">Título</label><input id="incident-title" className="form-control mb-3" value={form.title} onChange={(event) => setForm({...form,title:event.target.value})} required /><label className="form-label" htmlFor="incident-description">Descripción</label><textarea id="incident-description" className="form-control mb-3" value={form.description} onChange={(event) => setForm({...form,description:event.target.value})} /><label className="form-label">Severidad</label><div className="mb-3"><SelectControl ariaLabel="Severidad" label={severityLabels[form.severity]} value={form.severity} onChange={(next) => setForm({...form,severity:next as Incident['severity']})} options={Object.entries(severityLabels).map(([value,label]) => ({value,label}))} /></div><label className="form-label" htmlFor="incident-photo">Foto (opcional)</label><input id="incident-photo" className="form-control mb-3" type="file" accept="image/*" onChange={(event) => setPhoto(event.target.files?.[0] ?? null)} /><label className="form-label" htmlFor="incident-address">Dirección</label><input id="incident-address" className="form-control mb-3" value={form.address} onChange={(event) => setForm({...form,address:event.target.value})} placeholder="Dirección o referencia" /><Inline gap="sm" wrap className="mb-3"><Button type="button" variant="outline-primary" onClick={locate} disabled={locating}>{locating ? 'Obteniendo ubicación…' : 'Usar mi ubicación actual'}</Button>{form.lat && <small className="text-muted align-self-center">Ubicación registrada: {Number(form.lat).toFixed(5)}, {Number(form.lng).toFixed(5)}</small>}</Inline></Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Reportando…' : 'Reportar incidencia'}</Button></Modal.Footer></form></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </PageContainer>;
}
