import { FormEvent, useMemo, useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import { authenticatedFetch, useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner';
import KpiCard from '../../../components/Shared/KpiCard';
import ContentPanel from '../../../components/Shared/ContentPanel';
import EmptyState from '../../../components/Shared/EmptyState';
import PageContainer from '../../../components/Shared/PageContainer';
import SelectControl from '../../../components/Shared/SelectControl';
import Inline from '../../../components/Shared/Inline';
import { Toast } from '../../../components/Toast';

type Member = { uid: string; displayName?: string; email: string; teamId?: string | null };
type Team = { id: string; name: string };
type Task = { id: string; title: string; description: string; assignedTo: string; teamId?: string | null; dueDate: string; priority: 'baja'|'media'|'alta'; status: 'pendiente'|'en_progreso'|'completada'; completedAt?: string | null };
const statusLabels: Record<Task['status'], string> = { pendiente: 'Pendiente', en_progreso: 'En progreso', completada: 'Completada' };
const priorityLabels: Record<Task['priority'], string> = { baja: 'Baja', media: 'Media', alta: 'Alta' };
const today = () => new Date().toISOString().slice(0, 10);
const blank = () => ({ title: '', description: '', assignedTo: '', teamId: '', dueDate: today(), priority: 'media' as Task['priority'], status: 'pendiente' as Task['status'] });

export default function Tasks() {
  const { user, campaign } = useCampaign();
  const [filterStatus, setFilterStatus] = useState('all'); const [filterTeam, setFilterTeam] = useState('all');
  const [show, setShow] = useState(false); const [editing, setEditing] = useState<Task | null>(null); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<{message:string;variant:'success'|'danger'}|null>(null);
  const base = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}` : null;
  const tasksQ = useAuthenticatedQuery<Task[]>(user, base ? `${base}/tasks` : null, [base]);
  const membersQ = useAuthenticatedQuery<Member[]>(user, base ? `${base}/members` : null, [base]);
  const teamsQ = useAuthenticatedQuery<Team[]>(user, base ? `${base}/teams` : null, [base]);
  const tasks = tasksQ.data ?? []; const members = membersQ.data ?? []; const teams = teamsQ.data ?? [];
  const visible = useMemo(() => tasks.filter((task) => (filterStatus === 'all' || task.status === filterStatus) && (filterTeam === 'all' || task.teamId === filterTeam)), [tasks, filterStatus, filterTeam]);
  const pending = tasks.filter((task) => task.status === 'pendiente').length; const progressing = tasks.filter((task) => task.status === 'en_progreso').length;
  const completedToday = tasks.filter((task) => task.status === 'completada' && task.completedAt?.slice(0, 10) === today()).length;
  const overdue = tasks.filter((task) => task.status !== 'completada' && task.dueDate < today()).length;
  const memberName = (uid: string) => members.find((member) => member.uid === uid)?.displayName || members.find((member) => member.uid === uid)?.email || 'Sin asignar';
  const teamName = (id?: string | null) => teams.find((team) => team.id === id)?.name || 'Sin equipo';
  const open = (task?: Task) => { setEditing(task ?? null); setForm(task ? { title: task.title, description: task.description ?? '', assignedTo: task.assignedTo, teamId: task.teamId ?? '', dueDate: task.dueDate, priority: task.priority, status: task.status } : blank()); setShow(true); };
  const reload = () => Promise.all([tasksQ.reload(), membersQ.reload(), teamsQ.reload()]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!user || !base || saving) return; setSaving(true); try { await authenticatedFetch(user, editing ? `${base}/tasks/${editing.id}` : `${base}/tasks`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, teamId: form.teamId || null }) }); await reload(); setShow(false); setNotice({ message: editing ? 'Tarea actualizada.' : 'Tarea creada y asignada.', variant: 'success' }); } catch (caught) { setNotice({ message: caught instanceof Error ? caught.message : 'No pudimos guardar la tarea.', variant: 'danger' }); } finally { setSaving(false); } };
  const complete = async (task: Task) => { if (!user || !base) return; try { await authenticatedFetch(user, `${base}/tasks/${task.id}`, { method: 'PUT', body: JSON.stringify({ ...task, status: 'completada' }) }); await tasksQ.reload(); setNotice({ message: 'Tarea marcada como completada.', variant: 'success' }); } catch (caught) { setNotice({ message: caught instanceof Error ? caught.message : 'No pudimos completar la tarea.', variant: 'danger' }); } };
  const remove = async (task: Task) => { if (!user || !base || !window.confirm(`¿Borrar la tarea "${task.title}"?`)) return; try { await authenticatedFetch(user, `${base}/tasks/${task.id}`, { method: 'DELETE' }); await tasksQ.reload(); setNotice({ message: 'Tarea eliminada.', variant: 'success' }); } catch (caught) { setNotice({ message: caught instanceof Error ? caught.message : 'No pudimos borrar la tarea.', variant: 'danger' }); } };
  const loadError = tasksQ.error?.message || membersQ.error?.message || teamsQ.error?.message;
  return <PageContainer><HeroBanner icon="clipboard" title="Tareas y Asignaciones" subtitle="Coordiná el trabajo de campo y mantené a cada persona enfocada." tags={[{icon:'users', label:'Responsables claros'}, {icon:'check-circle', label:'Seguimiento diario'}]} ctaLabel="Crear tarea" onCtaClick={() => open()} />
    <div className="cd-dashboard__kpis"><KpiCard icon="clock" value={pending} label="Pendientes" caption="Por iniciar" /><KpiCard icon="bars" iconColor="purple" value={progressing} label="En progreso" caption="En ejecución" /><KpiCard icon="check" iconColor="green" value={completedToday} label="Completadas hoy" caption="Cerradas hoy" /><KpiCard icon="help" iconColor="red" value={overdue} label="Vencidas" caption="Requieren atención" /></div>
    <ContentPanel icon="clipboard" title="Tareas de campaña" subtitle="Asigná responsables, prioridades y fechas límite." headerAction={<Inline gap="sm" wrap><SelectControl ariaLabel="Filtrar por estado" label={filterStatus === 'all' ? 'Todos los estados' : statusLabels[filterStatus as Task['status']]} value={filterStatus} onChange={setFilterStatus} options={[{value:'all',label:'Todos los estados'}, ...Object.entries(statusLabels).map(([value,label]) => ({value,label}))]} /><SelectControl ariaLabel="Filtrar por equipo" label={filterTeam === 'all' ? 'Todos los equipos' : teamName(filterTeam)} value={filterTeam} onChange={setFilterTeam} options={[{value:'all',label:'Todos los equipos'}, ...teams.map((team) => ({value:team.id,label:team.name}))]} /></Inline>}>
      {loadError ? <EmptyState icon="clipboard" title="No pudimos cargar las tareas" description={loadError} ctaLabel="Reintentar" onCtaClick={() => void reload()} /> : tasksQ.loading ? <EmptyState icon="clipboard" title="Cargando tareas" description="Estamos preparando las asignaciones de campaña." /> : visible.length ? <div className="cd-table-scroll"><table className="cd-data-table"><thead><tr><th>TAREA</th><th>ASIGNADO A</th><th>EQUIPO</th><th>FECHA LÍMITE</th><th>PRIORIDAD</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{visible.map((task) => <tr key={task.id}><td><strong>{task.title}</strong><small className="d-block text-muted">{task.description || 'Sin descripción'}</small></td><td>{memberName(task.assignedTo)}</td><td>{teamName(task.teamId)}</td><td>{new Date(`${task.dueDate}T00:00:00`).toLocaleDateString('es-AR')}</td><td><span className={`badge text-bg-${task.priority === 'alta' ? 'danger' : task.priority === 'media' ? 'warning' : 'secondary'}`}>{priorityLabels[task.priority]}</span></td><td><span className={`badge text-bg-${task.status === 'completada' ? 'success' : task.status === 'en_progreso' ? 'primary' : 'secondary'}`}>{statusLabels[task.status]}</span></td><td><Inline gap="xs" wrap><Button size="sm" variant="outline-primary" onClick={() => open(task)}>Editar</Button>{task.status !== 'completada' && <Button size="sm" variant="outline-success" onClick={() => void complete(task)}>Completar</Button>}<Button size="sm" variant="outline-danger" onClick={() => void remove(task)}>Borrar</Button></Inline></td></tr>)}</tbody></table></div> : <EmptyState icon="clipboard" title="No hay tareas para mostrar" description="Creá la primera tarea y asignala a una persona de tu campaña." ctaLabel="Crear tarea" onCtaClick={() => open()} />}
    </ContentPanel>
    <Modal show={show} onHide={() => !saving && setShow(false)}><form onSubmit={submit}><Modal.Header closeButton><Modal.Title>{editing ? 'Editar tarea' : 'Crear tarea'}</Modal.Title></Modal.Header><Modal.Body><label className="form-label" htmlFor="task-title">Título</label><input id="task-title" className="form-control mb-3" value={form.title} onChange={(event) => setForm({...form,title:event.target.value})} required /><label className="form-label" htmlFor="task-description">Descripción</label><textarea id="task-description" className="form-control mb-3" value={form.description} onChange={(event) => setForm({...form,description:event.target.value})} /><label className="form-label">Asignar a</label><div className="mb-3"><SelectControl ariaLabel="Asignar a" label={memberName(form.assignedTo)} value={form.assignedTo} onChange={(assignedTo) => setForm({...form,assignedTo})} options={[{value:'',label:'Elegí un miembro'},...members.map((member) => ({value:member.uid,label:member.displayName || member.email}))]} /></div><label className="form-label">Equipo (opcional)</label><div className="mb-3"><SelectControl ariaLabel="Equipo" label={teamName(form.teamId)} value={form.teamId} onChange={(teamId) => setForm({...form,teamId})} options={[{value:'',label:'Sin equipo'},...teams.map((team) => ({value:team.id,label:team.name}))]} /></div><label className="form-label" htmlFor="task-date">Fecha límite</label><input id="task-date" type="date" className="form-control mb-3" value={form.dueDate} onChange={(event) => setForm({...form,dueDate:event.target.value})} required /><label className="form-label">Prioridad</label><div className="mb-3"><SelectControl ariaLabel="Prioridad" label={priorityLabels[form.priority]} value={form.priority} onChange={(priority) => setForm({...form,priority:priority as Task['priority']})} options={Object.entries(priorityLabels).map(([value,label]) => ({value,label}))} /></div>{editing && <><label className="form-label">Estado</label><SelectControl ariaLabel="Estado" label={statusLabels[form.status]} value={form.status} onChange={(status) => setForm({...form,status:status as Task['status']})} options={Object.entries(statusLabels).map(([value,label]) => ({value,label}))} /></>}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)} disabled={saving}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar tarea'}</Button></Modal.Footer></form></Modal>
    {notice && <Toast message={notice.message} variant={notice.variant} onClose={() => setNotice(null)} />}
  </PageContainer>;
}
