import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthenticatedQuery } from '../../../lib/api';
import { useCampaign } from '../Organization/useCampaign';
import HeroBanner from '../../../components/Shared/HeroBanner'; import KpiCard from '../../../components/Shared/KpiCard'; import ContentPanel from '../../../components/Shared/ContentPanel'; import EmptyState from '../../../components/Shared/EmptyState'; import PageContainer from '../../../components/Shared/PageContainer'; import SelectControl from '../../../components/Shared/SelectControl'; import Inline from '../../../components/Shared/Inline';
type Item = { id:string; name:string; address:string; visitCount:number; lastVisitAt:string|null; teamName:string|null; functionName:string|null };
export default function Undecided() { const { user, campaign } = useCampaign(); const navigate = useNavigate(); const [team, setTeam] = useState('all'); const [visits, setVisits] = useState('all'); const path = campaign ? `/api/organizations/${campaign.orgId}/campaigns/${campaign.campId}/execution/undecided` : null; const { data, loading, error } = useAuthenticatedQuery<Item[]>(user, path, [path]); const items = data ?? []; const teams = [...new Set(items.map(i => i.teamName).filter(Boolean))] as string[]; const filtered = useMemo(() => items.filter(i => (team === 'all' || i.teamName === team) && (visits === 'all' || i.visitCount >= Number(visits))).sort((a,b) => new Date(a.lastVisitAt ?? 0).getTime() - new Date(b.lastVisitAt ?? 0).getTime()), [items, team, visits]); const old = items.filter(i => i.lastVisitAt && Date.now() - new Date(i.lastVisitAt).getTime() > 7 * 86400000).length; const average = items.length ? (items.reduce((n,i) => n + i.visitCount, 0) / items.length).toFixed(1) : '0'; return <PageContainer><HeroBanner icon="target" title="Seguimiento de Indecisos" subtitle="Priorizá a quienes necesitan una nueva conversación." tags={[{icon:'users',label:'Re-visitas prioritarias'}]} />
<div className="cd-dashboard__kpis"><KpiCard icon="help" iconColor="orange" value={items.length} label="Total indecisos" caption="Pendientes de definición" /><KpiCard icon="bars" value={average} label="Promedio de visitas" caption="Antes de definir" /><KpiCard icon="clock" iconColor="red" value={old} label="Indecisos +7 días" caption="Requieren seguimiento" /></div>
<ContentPanel icon="users" title="Personas indecisas" subtitle="Ordenadas por antigüedad de la última visita" headerAction={<Inline gap="sm"><SelectControl label="Todos los equipos" value={team} onChange={setTeam} options={[{value:'all',label:'Todos los equipos'},...teams.map(value=>({value,label:value}))]} /><SelectControl label="Todas las visitas" value={visits} onChange={setVisits} options={[{value:'all',label:'Todas las visitas'},{value:'1',label:'1+ visitas'},{value:'2',label:'2+ visitas'}]} /></Inline>}>{loading ? <EmptyState icon="bar-chart-2" title="Cargando indecisos" description="Estamos preparando el seguimiento." /> : error ? <EmptyState icon="bar-chart-2" title="No pudimos cargar los indecisos" description={error.message} /> : filtered.length ? <div className="table-responsive"><table className="table planning-table mb-0"><thead><tr><th>NOMBRE</th><th>DIRECCIÓN</th><th>VISITAS</th><th>ÚLTIMA VISITA</th><th>ÚLTIMO EQUIPO</th><th /></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.address || 'Sin dirección'}</td><td>{item.visitCount}</td><td>{item.lastVisitAt ? new Date(item.lastVisitAt).toLocaleDateString('es-AR') : 'Sin visitas'}</td><td>{item.teamName || item.functionName || 'Sin asignación'}</td><td><button className="btn btn-sm btn-primary" onClick={() => navigate(`/visit/${item.id}`)}>Re-visitar</button></td></tr>)}</tbody></table></div> : <EmptyState icon="users" title="No hay indecisos" description="Cuando una visita se marque como indecisa aparecerá en esta lista." />}</ContentPanel></PageContainer>; }
